### ISSUE TITLE
trailingSlash does not work in next-auth@v5

### ISSUE THREAD

**Issue by ablackoff** [nextauthjs/next-auth#10127]
### Environment

**System:**
  OS: macOS 14.4
  CPU: (10) arm64 Apple M1 Max
  Memory: 256.14 MB / 32.00 GB
  Shell: 5.9 - /bin/zsh
**Binaries:**
  Node: 20.8.0 - /usr/local/bin/node
  Yarn: 1.22.19 - /usr/local/bin/yarn
  npm: 10.2.5 - /usr/local/bin/npm
  pnpm: 8.15.4 - /usr/local/bin/pnpm
  bun: 1.0.0 - ~/.bun/bin/bun
**Browsers:**
  Chrome: 122.0.6261.69
  Safari: 17.4
**npmPackages:**
  next: latest => 14.1.0
  next-auth: beta => 5.0.0-beta.13
  react: ^18.2.0 => 18.2.0

### Reproduction URL

https://github.com/ablackoff/next-auth-example

### Describe the issue

When adding `trailingSlash: true` to the `next.config.js` file, the following error occurs:
In the browser:
```
"Error: This action with HTTP POST is not supported."
```
In the console:
```
[auth][error] UnknownAction: Cannot parse action at /api/auth/signin/github/ .Read more at https://errors.authjs.dev#unknownaction
    at parseActionAndProviderId (webpack-internal:///(rsc)/./node_modules/@auth/core/lib/utils/web.js:90:49)
    at toInternalRequest (webpack-internal:///(rsc)/./node_modules/@auth/core/lib/utils/web.js:32:40)
    at Auth (webpack-internal:///(rsc)/./node_modules/@auth/core/index.js:82:103)
    at httpHandler (webpack-internal:///(rsc)/./node_modules/next-auth/index.js:139:80)
    at /Users/a.blackoff/Projects/my/next-auth-example-v2/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:63815
    at /Users/a.blackoff/Projects/my/next-auth-example-v2/node_modules/next/dist/server/lib/trace/tracer.js:133:36
    at NoopContextManager.with (/Users/a.blackoff/Projects/my/next-auth-example-v2/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:7062)
    at ContextAPI.with (/Users/a.blackoff/Projects/my/next-auth-example-v2/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:518)
    at NoopTracer.startActiveSpan (/Users/a.blackoff/Projects/my/next-auth-example-v2/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:18093)
    at ProxyTracer.startActiveSpan (/Users/a.blackoff/Projects/my/next-auth-example-v2/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:18854)
    at /Users/a.blackoff/Projects/my/next-auth-example-v2/node_modules/next/dist/server/lib/trace/tracer.js:122:103
    at NoopContextManager.with (/Users/a.blackoff/Projects/my/next-auth-example-v2/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:7062)
    at ContextAPI.with (/Users/a.blackoff/Projects/my/next-auth-example-v2/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:518)
    at NextTracerImpl.trace (/Users/a.blackoff/Projects/my/next-auth-example-v2/node_modules/next/dist/server/lib/trace/tracer.js:122:28)
    at /Users/a.blackoff/Projects/my/next-auth-example-v2/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:56866
    at AsyncLocalStorage.run (node:async_hooks:346:14)
    at Object.wrap (/Users/a.blackoff/Projects/my/next-auth-example-v2/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:37102)
    at /Users/a.blackoff/Projects/my/next-auth-example-v2/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:54639
    at AsyncLocalStorage.run (node:async_hooks:346:14)
    at Object.wrap (/Users/a.blackoff/Projects/my/next-auth-example-v2/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:36351)
    at /Users/a.blackoff/Projects/my/next-auth-example-v2/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:54601
    at AsyncLocalStorage.run (node:async_hooks:346:14)
    at eU.execute (/Users/a.blackoff/Projects/my/next-auth-example-v2/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:53994)
    at eU.handle (/Users/a.blackoff/Projects/my/next-auth-example-v2/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:65073)
    at doRender (/Users/a.blackoff/Projects/my/next-auth-example-v2/node_modules/next/dist/server/base-server.js:1333:60)
    at cacheEntry.responseCache.get.routeKind (/Users/a.blackoff/Projects/my/next-auth-example-v2/node_modules/next/dist/server/base-server.js:1543:46)
    at ResponseCache.get (/Users/a.blackoff/Projects/my/next-auth-example-v2/node_modules/next/dist/server/response-cache/index.js:49:26)
    at DevServer.renderToResponseWithComponentsImpl (/Users/a.blackoff/Projects/my/next-auth-example-v2/node_modules/next/dist/server/base-server.js:1463:53)
```

Exactly the same behavior with the **Credentials** provider.

This problem started with version _"next-auth": "5.0.0-beta.6"_ and higher

### How to reproduce

Go to the "Sign in" button, then "Sign in with GitHub", then you will immediately go to the error

### Expected behavior

Must go to Github authorization. Don't get the error "Error: This action with HTTP POST is not supported."

**Comment by stefanullinger** [comment]
I was having the same issue. Needed to turn off `trailingSlash` for now.

**Comment by ablackoff** [comment]
@stefanullinger Yes, I realized that I need to disable it for it to work.
I'm trying to highlight here that this feature would be good to fix

**Comment by lurepheonix** [comment]
The error in question was introduced in commit https://github.com/nextauthjs/next-auth/commit/fc358dfa19deb697489a767eef53ee00da51f84f.

So, what we've got here:

```
export function parseActionAndProviderId(
  pathname: string,
  base: string
): {
  action: AuthAction
  providerId?: string
} {
  const a = pathname.match(new RegExp(`^${base}(.+)`))

  if (a === null)
    throw new UnknownAction(`Cannot parse action at ${pathname}`)

  const [_, actionAndProviderId] = a

  const b = actionAndProviderId.replace(/^\//, "").split("/")

  if (b.length !== 1 && b.length !== 2)
    throw new UnknownAction(`Cannot parse action at ${pathname}`)

  ...etc
}
```

The actual error happens at `if (b.length !== 1 && b.length !== 2)`. 
When we are using trailing slashes, our `pathname` argument becomes `/api/auth/callback/credentials/` (in case of using Credentials provider). 
In this case, `a` will contain `["/api/auth/callback/credentials/","/callback/credentials/"]`.  
So:
- `actionAndProviderId.replace(/^\//, "")` will be `callback/credentials/`
- `b` will be `["callback","credentials",""]` because `callback/credentials/` is split by `/` and thus `b.length` will be 3, thus leading to failure.

Two of the easiest ways to solve:
1. Trim the last slash.
2. Remove empty strings from `b` array with Array.filter.
Or use some other approach.

@chrislambe @balazsorban44 it's your call :) I can save you some time by creating a PR with changes once we settle on the approach.

**Comment by chrislambe** [comment]
I think you'll find that this behavior was _not_ introduced in https://github.com/nextauthjs/next-auth/commit/fc358dfa19deb697489a767eef53ee00da51f84f since the previous implementation:

```ts
const [_, actionAndProviderId] = "/api/auth/callback/credentials/".split("/api/auth")
const b = actionAndProviderId.replace(/^\//, "").split("/")
```

...and the current implementation:

```ts
const [_, actionAndProviderId] = "/api/auth/callback/credentials/".match(new RegExp(`^/api/auth(.+)`))
const b = actionAndProviderId.replace(/^\//, "").split("/")
```

...produce the same value for `b`.

But since I'm here, I'll cast my vote for the third suggested option:

```ts
const b = actionAndProviderId.replace(/\/$/, '').replace(/^\//, '').split("/")
```

...or, if a case like `/api/auth/callback/credentials////` is supported for some reason:

```ts
const b = actionAndProviderId.replace(/\/+$/, '').replace(/^\//, '').split("/")
```

Might be able to take both slashes out in a single method call but it might be better to just keep it simple.

**Comment by ndom91** [comment]
@lurepheonix @chrislambe thanks for diving into this and suggesting some solutions!

I've opened a PR basically following suggestion `1`, by adding the `.filter(Boolean)` to get rid of the empty parsed array members.
