### ISSUE TITLE
Vercel/SvelteKit Authentication Template runs into error on basic launch (Error 500)

### ISSUE THREAD

**Issue by JordanBettridge** [nextauthjs/next-auth#10139]
### Environment

System:
OS: macOS 14.2.1
CPU: (8) arm64 Apple M1
Memory: 66.58 MB / 8.00 GB
Shell: 5.9 - /bin/zsh
Binaries:
Node: 20.11.1 - ~/.nvm/versions/node/v20.11.1/bin/node
npm: 10.2.4 - ~/.nvm/versions/node/v20.11.1/bin/npm
bun: 1.0.1 - /opt/homebrew/bin/bun
Browsers:
Chrome: 121.0.6167.184
Safari: 17.2.1
npmPackages:
@auth/sveltekit: latest => 0.13.0

### Reproduction URL

https://github.com/JordanBettridge/sveltekit-sandbox

### Describe the issue

```
TypeError: options.hooks.handle is not a function
    at Module.respond (/Users/jordanbettridge/Personal/sveltekit-sandbox/node_modules/@sveltejs/kit/src/runtime/server/respond.js:313:40)
    at async file:///Users/jordanbettridge/Personal/sveltekit-sandbox/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:523:22
```

### How to reproduce

Upon Deploying the template via vercel, I clone the repo to my local, and I create the .env file from the sample, I leave all fields blank, except for `AUTH_SECRET`, `AUTH_GITHUB_SECRET`, and `AUTH_GITHUB_ID`. I then use `npm i` to install the node_modules and then `npm run dev`. After this, I visit localhost where vite has launched and Im met with an error 500 page, I go back to VSCode and I see an error.

```
TypeError: options.hooks.handle is not a function
    at Module.respond (/Users/jordanbettridge/Personal/sveltekit-sandbox/node_modules/@sveltejs/kit/src/runtime/server/respond.js:313:40)
    at async file:///Users/jordanbettridge/Personal/sveltekit-sandbox/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:523:22
```

### Expected behavior

The app should launch and be useable

**Comment by Siiggyy** [comment]
I ran into the same error for a quick workaround set the @auth/sveltekit to version 0.11.0 until it gets fixed or a solution is presented.

**Comment by geordiscott** [comment]
Going back to 0.11.1 did work for me as well

**Comment by Michielvk** [comment]
The API was changed.

The updated guide can be found here: https://authjs.dev/reference/sveltekit

`SvelteKitAuth()` previously returned a `Handle` directly. Now it returns `{handle: Handle, signIn: Action, signOut: Action}`.

You can create a separate `src/auth.ts` file as described in the new guide above and re-export it in `server.handle.ts`, or you can rename the `handle` returned by the new `SvelteKitAuth()` function directly:

src/hooks.server.ts
```ts
const {handle: authInitHandle, signIn, signOut} = SvelteKitAuth({
	providers: [/* ... */],
});

export const handle = authInitHandle;
```

Or you can destruct the object directly:

src/hooks.server.ts
```ts
export const { handle } = SvelteKitAuth({
	providers: [/* ... */],
});
```

**Comment by geordiscott** [comment]
Thank you very much, I really missed this. Now it's working with the recent version!
