### ISSUE TITLE
sveltekit error: `Cannot read values from $env/dynamic/private while prerendering (attempted to read env.AUTH_URL)`

### ISSUE THREAD

**Issue by 0x416e746f6e** [nextauthjs/next-auth#10169]
### Environment

```
  System:
    OS: macOS 14.3
    CPU: (10) arm64 Apple M1 Max
    Memory: 1.47 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.1 - /opt/homebrew/opt/node@20/bin/node
    Yarn: 1.22.21 - /opt/homebrew/bin/yarn
    npm: 10.2.4 - /opt/homebrew/opt/node@20/bin/npm
  Browsers:
    Brave Browser: 119.1.60.118
    Chrome: 122.0.6261.94
    Safari: 17.3
  npmPackages:
    @auth/sveltekit: ^0.13.0 => 0.13.0 
```

### Reproduction URL

https://github.com/0x416e746f6e/sveltekit-authjs-twitter

### Describe the issue

The build with `@sveltejs/adapter-node` fails due to error:

> Cannot read values from $env/dynamic/private while prerendering (attempted to read env.AUTH_URL). Use $env/static/private instead`

```shell
yarn build
```

```
yarn run v1.22.21
$ vite build
vite v5.1.4 building SSR bundle for production...
✓ 88 modules transformed.
vite v5.1.4 building for production...
✓ 63 modules transformed.
.svelte-kit/output/client/_app/version.json                             0.03 kB │ gzip:  0.05 kB
.svelte-kit/output/client/.vite/manifest.json                           2.26 kB │ gzip:  0.43 kB
.svelte-kit/output/client/_app/immutable/entry/start.DjbilpSH.js        0.07 kB │ gzip:  0.08 kB
.svelte-kit/output/client/_app/immutable/chunks/stores.D6V8evZ9.js      0.23 kB │ gzip:  0.17 kB
.svelte-kit/output/client/_app/immutable/nodes/0.UmyDgAYB.js            0.60 kB │ gzip:  0.39 kB
.svelte-kit/output/client/_app/immutable/nodes/1.Bn1GM8LT.js            0.84 kB │ gzip:  0.53 kB
.svelte-kit/output/client/_app/immutable/chunks/scheduler.BvLojk_z.js   2.16 kB │ gzip:  1.02 kB
.svelte-kit/output/client/_app/immutable/nodes/2.DtlwLwd4.js            3.13 kB │ gzip:  1.40 kB
.svelte-kit/output/client/_app/immutable/chunks/index.B9OgsaRF.js       5.54 kB │ gzip:  2.34 kB
.svelte-kit/output/client/_app/immutable/entry/app.Dx8_Q9Kt.js          6.00 kB │ gzip:  2.43 kB
.svelte-kit/output/client/_app/immutable/chunks/entry.CQM_HWnJ.js      26.91 kB │ gzip: 10.66 kB
✓ built in 182ms
Error: Cannot read values from $env/dynamic/private while prerendering (attempted to read env.AUTH_URL). Use $env/static/private instead
    at Object.get (file:///Users/anton/Projects/northernforest/sveltekit-authjs-twitter/.svelte-kit/output/server/index.js:2855:11)
    at createActionURL (file:///Users/anton/Projects/northernforest/sveltekit-authjs-twitter/.svelte-kit/output/server/chunks/hooks.server.js:94:25)
    at auth (file:///Users/anton/Projects/northernforest/sveltekit-authjs-twitter/.svelte-kit/output/server/chunks/hooks.server.js:75:22)
    at event.locals.auth (file:///Users/anton/Projects/northernforest/sveltekit-authjs-twitter/.svelte-kit/output/server/chunks/hooks.server.js:132:35)
    at load (file:///Users/anton/Projects/northernforest/sveltekit-authjs-twitter/.svelte-kit/output/server/entries/pages/_layout.server.ts.js:4:33)
    at load_server_data (file:///Users/anton/Projects/northernforest/sveltekit-authjs-twitter/.svelte-kit/output/server/index.js:476:42)
    at file:///Users/anton/Projects/northernforest/sveltekit-authjs-twitter/.svelte-kit/output/server/index.js:2006:24

node:internal/event_target:1100
  process.nextTick(() => { throw err; });
                           ^
Error: 500 /
To suppress or handle this error, implement `handleHttpError` in https://kit.svelte.dev/docs/configuration#prerender
    at file:///Users/anton/Projects/northernforest/sveltekit-authjs-twitter/node_modules/@sveltejs/kit/src/core/config/options.js:202:13
    at file:///Users/anton/Projects/northernforest/sveltekit-authjs-twitter/node_modules/@sveltejs/kit/src/core/postbuild/prerender.js:65:25
    at save (file:///Users/anton/Projects/northernforest/sveltekit-authjs-twitter/node_modules/@sveltejs/kit/src/core/postbuild/prerender.js:403:4)
    at visit (file:///Users/anton/Projects/northernforest/sveltekit-authjs-twitter/node_modules/@sveltejs/kit/src/core/postbuild/prerender.js:236:3)
Emitted 'error' event on Worker instance at:
    at [kOnErrorMessage] (node:internal/worker:326:10)
    at [kOnMessage] (node:internal/worker:337:37)
    at MessagePort.<anonymous> (node:internal/worker:232:57)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:826:20)
    at exports.emitMessage (node:internal/per_context/messageport:23:28)

Node.js v20.11.1
error Command failed with exit code 1.
```

### How to reproduce

```shell
git clone https://github.com/0x416e746f6e/sveltekit-authjs-twitter
cd sveltekit-authjs-twitter
yarn install
yarn build
```

### Expected behavior

Should build without errors.

**Comment by 0x416e746f6e** [comment]
also:  https://github.com/nextauthjs/next-auth/discussions/10177
