### ISSUE TITLE
Google Authorization Error

### ISSUE THREAD

**Issue by ats1999** [nextauthjs/next-auth#1020]
I getting this error, which doing Google Oauth
```js
Error 400: redirect_uri_mismatch
The redirect URI in the request, https://bdevg.com/api/auth/callback/google, does not match the ones authorized for the OAuth client. To update the authorized redirect URIs, visit: https://console.developers.google.com/APIs/credentials/oauthclient/${your_client_id}?project=${your_project_number}
```

**Reproduction**
Visit https://bdevg.com/api/auth/signin then choose sign in with google 

**Authorized JavaScript origin**
https://bdevg.com

**Authorized redirect URIs**
https://bdevg.com

## vercel function logs
```js
[GET] /api/auth/callback/github?code=248bb9c03e85a89c3070&state=6d154f358c1546618487d1cd81bb4c1686b91a60d135507093fcbbb4930ec29b
15:20:25:95
Status:
-1
Duration:
10010.81ms
Memory Used:
74 MB
ID:
dc4x6-1609474825954-f73eb9e7144f
User Agent:
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36
2021-01-01T04:20:36.092Z 02b5d489-c291-43b5-a9d3-6deff015db6a Task timed out after 10.01 seconds
[POST] /api/auth/signin/github
15:20:24:95
Status:
302
Duration:
82.08ms
Memory Used:
66 MB
ID:
dc4x6-1609474824954-55d2910131f0
User Agent:
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36
[GET] /api/auth/error?error=oAuthCallback
15:19:15:43
Status:
200
Duration:
3.68ms
Memory Used:
62 MB
ID:
dc4x6-1609474755430-c761c6296b2a
User Agent:
Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36
[GET] /api/auth/error?error=oAuthCallback
15:19:15:07
Status:
200
Duration:
3.63ms
Memory Used:
62 MB
ID:
dc4x6-1609474755070-1bd8ee28d530
User Agent:
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36 Edg/85.0.564.41
[GET] /api/auth/callback/google
15:19:14:02
Status:
302
Duration:
5.69ms
Memory Used:
62 MB
ID:
dc4x6-1609474754021-902653bead5f
User Agent:
Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36
2021-01-01T04:19:14.153Z	e1ad9526-d2f5-4a48-8f2c-8c98fd8a7f87	ERROR	[next-auth][error][callback_oauth_error] Error: Invalid state returned from oAuth provider
    at /var/task/bdevg/node_modules/next-auth/dist/server/lib/oauth/callback.js:46:27
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/var/task/bdevg/node_modules/next-auth/dist/server/lib/oauth/callback.js:26:103)
    at _next (/var/task/bdevg/node_modules/next-auth/dist/server/lib/oauth/callback.js:28:194)
    at /var/task/bdevg/node_modules/next-auth/dist/server/lib/oauth/callback.js:28:364
    at new Promise (<anonymous>)
    at /var/task/bdevg/node_modules/next-auth/dist/server/lib/oauth/callback.js:28:97
    at /var/task/bdevg/node_modules/next-auth/dist/server/lib/oauth/callback.js:143:17
    at /var/task/bdevg/node_modules/next-auth/dist/server/routes/callback.js:58:31
    at Generator.next (<anonymous>) 
https://next-auth.js.org/errors#callback_oauth_error
[GET] /api/auth/error?error=oAuthCallback
15:19:13:81
Status:
200
Duration:
3.83ms
Memory Used:
62 MB
ID:
46tlr-1609474753656-842d690ca3e2
User Agent:
Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36
[GET] /api/auth/error?error=oAuthCallback
15:19:13:44
Status:
200
Duration:
46.42ms
Memory Used:
62 MB
ID:
p6rrr-1609474753295-3caf0ab0a8c3
User Agent:
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 Safari/537.36
[GET] /api/auth/callback/google
15:19:12:60
Status:
302
Duration:
47.13ms
Memory Used:
120 MB
ID:
p6rrr-1609474752350-528a3121442e
User Agent:
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 Safari/537.36
2021-01-01T04:19:12.731Z	f5774683-208d-49fb-b8d7-46a852e6fdda	ERROR	[next-auth][error][callback_oauth_error] Error: Invalid state returned from oAuth provider
    at /var/task/bdevg/node_modules/next-auth/dist/server/lib/oauth/callback.js:46:27
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/var/task/bdevg/node_modules/next-auth/dist/server/lib/oauth/callback.js:26:103)
    at _next (/var/task/bdevg/node_modules/next-auth/dist/server/lib/oauth/callback.js:28:194)
    at /var/task/bdevg/node_modules/next-auth/dist/server/lib/oauth/callback.js:28:364
    at new Promise (<anonymous>)
    at /var/task/bdevg/node_modules/next-auth/dist/server/lib/oauth/callback.js:28:97
    at /var/task/bdevg/node_modules/next-auth/dist/server/lib/oauth/callback.js:143:17
    at /var/task/bdevg/node_modules/next-auth/dist/server/routes/callback.js:58:31
    at Generator.next (<anonymous>) 
https://next-auth.js.org/errors#callback_oauth_error
[POST] /api/auth/signin/google
15:15:27:33
Status:
302
Duration:
1440.54ms
Memory Used:
119 MB
ID:
dc4x6-1609474527333-0021bfe4f74f
User Agent:
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36
Loaded env from .env.production
[POST] /api/auth/signin/google
15:15:26:82
Status:
302
Duration:
1458.67ms
Memory Used:
118 MB
ID:
dc4x6-1609474526822-bef9b75a6e5c
User Agent:
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36
Loaded env from .env.production
```

**Comment by jaaneh** [comment]
Make sure both the callback URL in your project and on Google Dev Console are the same. You might have used localhost in a place where you're meant to use your prod URL, e.g the project .env file.

**Comment by balazsorban44** [comment]
Could you please provide some source code? (Ideally a link to a reproduction repository)

**Comment by ats1999** [comment]
## Code 
same as in this Github issue https://github.com/nextauthjs/next-auth/issues/1021 created by me

## Google URI's
![Screenshot (514)](https://user-images.githubusercontent.com/54087826/103449923-28390c00-4d03-11eb-92b1-9b58c326ea52.png)

##  Vercel NEXTAUTH_URL
![Screenshot (516)](https://user-images.githubusercontent.com/54087826/103449931-3edf6300-4d03-11eb-87c1-e7fe9a8bc9c6.png)

**Comment by ats1999** [comment]
To see this live, visit https://bdevg.com/api/auth/signin?callbackUrl=https%3A%2F%2Fbdevg.com%2F

or, go to bdevg.com then click on a link, in the footer named **oauth**

**Comment by balazsorban44** [comment]
The authorized redirect URI should be

https://bdvg.com/api/auth/callback/google

See: https://next-auth.js.org/getting-started/rest-api#get-apiauthcallbackprovider

**Comment by ats1999** [comment]
> The authorized redirect URI should be
> 
> https://bdevg.com/api/auth/callback/google
> 
> See: https://next-auth.js.org/getting-started/rest-api#get-apiauthcallbackprovider

Do i need to update it in google console dashboard?

**Comment by balazsorban44** [comment]
Yes
