### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by ryangittings** [nextauthjs/next-auth#1026]
Using 3.2.0-canary.10, and just getting the folllowing error:

**Describe the bug**
RangeError: Maximum call stack size exceeded

Do not report bugs with your own project here, ask from help by raising a question instead - this helps us a lot with administration overhead.

**Steps to reproduce**
Run npm run dev, and load page with auth provider.

**Expected behavior**
No callstack error!

**Screenshots or error logs**
API resolved without sending a response for /api/auth/session, this may result in stalled requests.
/node_modules/next-auth/dist/server/index.js:71
          resolve();
          ^

RangeError: Maximum call stack size exceeded
    at <anonymous>
    at ServerResponse.res.end (/node_modules/next-auth/dist/server/index.js:71:11)
    at ServerResponse.res.end (/node_modules/next-auth/dist/server/index.js:72:15)
    at ServerResponse.res.end (/node_modules/next-auth/dist/server/index.js:72:15)
    at ServerResponse.res.end (/node_modules/next-auth/dist/server/index.js:72:15)
    at ServerResponse.res.end (/node_modules/next-auth/dist/server/index.js:72:15)
    at ServerResponse.res.end (/node_modules/next-auth/dist/server/index.js:72:15)
    at ServerResponse.res.end (/node_modules/next-auth/dist/server/index.js:72:15)
    at ServerResponse.res.end (/node_modules/next-auth/dist/server/index.js:72:15)
    at ServerResponse.res.end (/node_modules/next-auth/dist/server/index.js:72:15)
    at ServerResponse.res.end (/node_modules/next-auth/dist/server/index.js:72:15)
    at ServerResponse.res.end (/node_modules/next-auth/dist/server/index.js:72:15)
    at ServerResponse.res.end (/node_modules/next-auth/dist/server/index.js:72:15)
    at ServerResponse.res.end (/node_modules/next-auth/dist/server/index.js:72:15)
    at ServerResponse.res.end (/node_modules/next-auth/dist/server/index.js:72:15)
    at ServerResponse.res.end (/node_modules/next-auth/dist/server/index.js:72:15)

**Comment by balazsorban44** [comment]
Thanks for reporting! I quickly managed to find the cause and fixed some other bugs along the way. `canary` is a bit brittle at the moment, so feedback is extremely helpful!

**Comment by ryangittings** [comment]
Just tried this! Getting another error, did you want me to create a new issue?

/node_modules/next-auth/dist/server/routes/session.js:48
      return res.setHeader('Content-Type', 'application/json').json({}).end();
                                                                       ^

TypeError: Cannot read property 'end' of undefined

**Comment by balazsorban44** [comment]
Sorry for the inconvenience! Try `next-auth@3.2.0-canary.12`

**Comment by ryangittings** [comment]
No problem - I'm here to help! Great stuff, thanks for sorting so quickly.

**Comment by ryangittings** [comment]
Working locally, though deploying with Next on Netlify and just getting console error. Not sure if this is environment related though...  `/api/auth/session` is just a blank page with no source, but is JSON locally. Hm...

["/api/auth/session", SyntaxError: Unexpected end of JSON input
    at /_next/static/chunks/0…]0: "/api/auth/session"1: SyntaxError: Unexpected end of JSON input
    at /_next/static/chunks/0557186d9f439fb0430cdc93057e1a56c86d23a1.c7cc4ffd86991a5c6ff0.js:1:8356
    at Generator.next (<anonymous>)
    at l (/_next/static/chunks/0557186d9f439fb0430cdc93057e1a56c86d23a1.c7cc4ffd86991a5c6ff0.js:1:3628)
    at c (/_next/static/chunks/0557186d9f439fb0430cdc93057e1a56c86d23a1.c7cc4ffd86991a5c6ff0.js:1:3831)length: 2__proto__: Array(0)

**Comment by ryangittings** [comment]
Just trying the sign in with apple on Vercel, and getting:

`[POST] /api/auth/callback/apple - Task timed out after 10.01 seconds`. Any ideas as to why that might be? Once again, might not be canary related...

**Comment by ryangittings** [comment]
I'm testing Sign in with Apple, and just getting a task timeout on Vercel. Not sure why that is, though!

[POST] /api/auth/callback/apple - Task timed out after 10.01 second

**Comment by balazsorban44** [comment]
Can you check if it works on canary version 8?

**Comment by ryangittings** [comment]
Yep, works perfectly!

**Comment by balazsorban44** [comment]
Will have to look at it again, later. Might have to revert some of the refactorings.

**Comment by marciodiasdeveloper** [comment]
solve updated 3.15.10
