### ISSUE TITLE
UnknownAction: Cannot parse action at /session (Breaking change going from next-auth": "5.0.0-beta.4 to next-auth": "5.0.0-beta.15)

### ISSUE THREAD

**Issue by tomatac** [nextauthjs/next-auth#10309]
### Environment

System:
    OS: Linux 6.5 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
    CPU: (4) x64 AMD Ryzen 9 3900X 12-Core Processor
    Memory: 3.22 GB / 7.75 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.19.1 - /usr/bin/node
    npm: 10.2.4 - /usr/bin/npm
    pnpm: 8.14.3 - /usr/local/bin/pnpm
  Browsers:
    Chrome: 122.0.6261.94
  npmPackages:
    next: 14.1.0 => 14.1.0 
    next-auth: 5.0.0-beta.15 => 5.0.0-beta.15 
    react: ^18.2.0 => 18.2.0 

### Reproduction URL

https://github.com/vercel/ai-chatbot

### Describe the issue

Trying to upgrade from next-auth": "5.0.0-beta.4 to next-auth": "5.0.0-beta.15 to use email based authentication alongside with OAuth (GitHub) authentication.
Going from "5.0.0-beta.4 to next-auth": "5.0.0-beta.15 results in errors:
UnknownAction: Cannot parse action at /session

### How to reproduce

clone: https://github.com/vercel/ai-chatbot
in package.json change "next-auth": "5.0.0-beta.4" to "next-auth": "5.0.0-beta.15"
errors:
[auth][error] UnknownAction: Cannot parse action at /session .Read more at https://errors.authjs.dev#unknownaction
    at parseActionAndProviderId (/home/toma/repos/test/vercel/ai-chatbot-v/.next/server/edge/chunks/43de1_@auth_core_402597._.js:914:27)
    at Module.toInternalRequest (/home/toma/repos/test/vercel/ai-chatbot-v/.next/server/edge/chunks/43de1_@auth_core_402597._.js:858:40)
    at Module.Auth (/home/toma/repos/test/vercel/ai-chatbot-v/.next/server/edge/chunks/43de1_@auth_core_402597._.js:4896:265)
    at getSession (/home/toma/repos/test/vercel/ai-chatbot-v/.next/server/edge/chunks/node_modules__pnpm_8c8a9c._.js:2964:231)
    at handleAuth (/home/toma/repos/test/vercel/ai-chatbot-v/.next/server/edge/chunks/node_modules__pnpm_8c8a9c._.js:3078:35)
    at Object.handler (/home/toma/repos/test/vercel/ai-chatbot-v/.next/server/edge/chunks/node_modules__pnpm_8c8a9c._.js:3048:20)
    at /home/toma/repos/test/vercel/ai-chatbot-v/.next/server/edge/chunks/_399159._.js:6716:27
    at AsyncLocalStorage.run (node:async_hooks:338:14)
    at Object.wrap (/home/toma/repos/test/vercel/ai-chatbot-v/.next/server/edge/chunks/_399159._.js:2903:24)
    at /home/toma/repos/test/vercel/ai-chatbot-v/.next/server/edge/chunks/_399159._.js:6703:355
[auth][error] UnknownAction: Cannot parse action at /session .Read more at https://errors.authjs.dev#unknownaction
    at parseActionAndProviderId (/home/toma/repos/test/vercel/ai-chatbot-v/.next/server/edge/chunks/43de1_@auth_core_402597._.js:914:27)
    at Module.toInternalRequest (/home/toma/repos/test/vercel/ai-chatbot-v/.next/server/edge/chunks/43de1_@auth_core_402597._.js:858:40)
    at Module.Auth (/home/toma/repos/test/vercel/ai-chatbot-v/.next/server/edge/chunks/43de1_@auth_core_402597._.js:4896:265)
    at getSession (/home/toma/repos/test/vercel/ai-chatbot-v/.next/server/edge/chunks/node_modules__pnpm_8c8a9c._.js:2964:231)
    at handleAuth (/home/toma/repos/test/vercel/ai-chatbot-v/.next/server/edge/chunks/node_modules__pnpm_8c8a9c._.js:3078:35)
    at Object.handler (/home/toma/repos/test/vercel/ai-chatbot-v/.next/server/edge/chunks/node_modules__pnpm_8c8a9c._.js:3048:20)
    at /home/toma/repos/test/vercel/ai-chatbot-v/.next/server/edge/chunks/_399159._.js:6716:27
    at AsyncLocalStorage.run (node:async_hooks:338:14)
    at Object.wrap (/home/toma/repos/test/vercel/ai-chatbot-v/.next/server/edge/chunks/_399159._.js:2903:24)
    at /home/toma/repos/test/vercel/ai-chatbot-v/.next/server/edge/chunks/_399159._.js:6703:355
 ○ Compiling /sign-in ...
 ✓ Compiled /sign-in in 4.6s
[auth][error] UnknownAction: Cannot parse action at /session .Read more at https://errors.authjs.dev#unknownaction
    at parseActionAndProviderId (/home/toma/repos/test/vercel/ai-chatbot-v/.next/server/chunks/43de1_@auth_core_75c142._.js:914:27)
    at Module.toInternalRequest (/home/toma/repos/test/vercel/ai-chatbot-v/.next/server/chunks/43de1_@auth_core_75c142._.js:858:40)
    at Module.Auth (/home/toma/repos/test/vercel/ai-chatbot-v/.next/server/chunks/43de1_@auth_core_75c142._.js:4895:265)
    at getSession (/home/toma/repos/test/vercel/ai-chatbot-v/.next/server/chunks/node_modules__pnpm_b1fd4c._.js:3273:231)
    at Module.<anonymous> (/home/toma/repos/test/vercel/ai-chatbot-v/.next/server/chunks/node_modules__pnpm_b1fd4c._.js:3350:20)
    at SignInPage (/home/toma/repos/test/vercel/ai-chatbot-v/.next/server/chunks/_9f3714._.js:1230:135)
    at eR (/home/toma/repos/test/vercel/ai-chatbot-v/node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:200664)
    at /home/toma/repos/test/vercel/ai-chatbot-v/node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:213115
    at Array.toJSON (/home/toma/repos/test/vercel/ai-chatbot-v/node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:217885)
    at stringify (<anonymous>)
    at /home/toma/repos/test/vercel/ai-chatbot-v/node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:204592
    at eW (/home/toma/repos/test/vercel/ai-chatbot-v/node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:204671)
    at ez (/home/toma/repos/test/vercel/ai-chatbot-v/node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:205071)
    at Timeout._onTimeout (/home/toma/repos/test/vercel/ai-chatbot-v/node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:201570)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
[auth][error] UnknownAction: Cannot parse action at /session .Read more at https://errors.authjs.dev#unknownaction
    at parseActionAndProviderId (/home/toma/repos/test/vercel/ai-chatbot-v/.next/server/chunks/43de1_@auth_core_75c142._.js:914:27)
    at Module.toInternalRequest (/home/toma/repos/test/vercel/ai-chatbot-v/.next/server/chunks/43de1_@auth_core_75c142._.js:858:40)
    at Module.Auth (/home/toma/repos/test/vercel/ai-chatbot-v/.next/server/chunks/43de1_@auth_core_75c142._.js:4895:265)
    at getSession (/home/toma/repos/test/vercel/ai-chatbot-v/.next/server/chunks/node_modules__pnpm_b1fd4c._.js:3273:231)
    at Module.<anonymous> (/home/toma/repos/test/vercel/ai-chatbot-v/.next/server/chunks/node_modules__pnpm_b1fd4c._.js:3350:20)
    at UserOrLogin (/home/toma/repos/test/vercel/ai-chatbot-v/.next/server/chunks/_9f3714._.js:865:135)
    at eR (/home/toma/repos/test/vercel/ai-chatbot-v/node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:200664)
    at /home/toma/repos/test/vercel/ai-chatbot-v/node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:213115
    at Object.toJSON (/home/toma/repos/test/vercel/ai-chatbot-v/node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:217885)
    at stringify (<anonymous>)
    at /home/toma/repos/test/vercel/ai-chatbot-v/node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:204592
    at eW (/home/toma/repos/test/vercel/ai-chatbot-v/node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:204671)
    at ez (/home/toma/repos/test/vercel/ai-chatbot-v/node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:205071)
    at Timeout._onTimeout (/home/toma/repos/test/vercel/ai-chatbot-v/node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:201570)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)

### Expected behavior

no errors

**Comment by ItaiZeilig** [comment]
Same here.

**Comment by tomatac** [comment]
I also tried earlier beta versions (next-auth@5.0.0-beta.12) and I get similar errors.

**Comment by armandodlvr** [comment]
+1

**Comment by tomatac** [comment]
Last version that still works is next-auth@5.0.0-beta.5 (Pre-release)

next-auth@5.0.0-beta.6 has other issues: 
./node_modules/.pnpm/@auth+core@0.26.0/node_modules/@auth/core/lib/utils/webauthn-utils.js:3:0
Module not found: Can't resolve '@simplewebauthn/server'

next-auth": "5.0.0-beta.7, 8, 9 issues:
[auth][error] UnknownAction: Cannot parse action at /api/auth/providers
[auth][error] UnknownAction: Cannot parse action at /api/auth/error
[auth][error] UnknownAction: Cannot parse action at /api/auth/csrf
[auth][error] UnknownAction: Cannot parse action at /api/auth/signout

This error happened while installing the dependencies of next-auth@5.0.0-beta.10
ERR_PNPM_WORKSPACE_PKG_NOT_FOUND  In : "@auth/core@workspace:*" is in the dependencies but no package named "@auth/core" is present in the workspace

next-auth": "5.0.0-beta.11 ... an later
[auth][error] UnknownAction: Cannot parse action at /session

**Comment by 42tte** [comment]
I got the same when I added `NEXTAUTH_URL` to my app, this need to end with `/api/auth` (or your custom path to auth)

**Comment by tomatac** [comment]
@42tte, thank you!
For running locally I added 
NEXTAUTH_URL=http://localhost:3000/api/auth
to .env.development.local and I do not get the errors anymore when running next-auth: 5.0.0-beta.15
Documentation could be better!

**Comment by ThangHuuVu** [comment]
duplicated of https://github.com/nextauthjs/next-auth/issues/10081
