### ISSUE TITLE
@auth/express - Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client

### ISSUE THREAD

**Issue by noam-honig** [nextauthjs/next-auth#10505]
### Environment

  System:
    OS: Windows 10 10.0.19045
    CPU: (16) x64 Intel(R) Core(TM) i7-7820X CPU @ 3.60GHz
    Memory: 13.47 GB / 31.68 GB
  Binaries:
    Node: 18.18.2 - C:\Program Files\nodejs\node.EXE
    npm: 10.5.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.15.4 - C:\ProgramData\npm\npm\pnpm.CMD
  Browsers:
    Chrome: 123.0.6312.106
    Edge: Chromium (123.0.2420.81)
    Internet Explorer: 11.0.19041.3636
  npmPackages:
    @auth/express: ^0.5.1 => 0.5.1
    react: ^18.2.0 => 18.2.0

### Reproduction URL

https://github.com/noam-honig/t18/tree/main

### Describe the issue

When using express auth, and a catch all route  - routes that are handled by ExpressAuth fire the Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client

I believe that this is because the ExpressAuth middleware calls `next` also for requests that are handled and don't need any further handling

### How to reproduce

`npm run start`
goto url: `http://localhost:3000/api/auth/signin`
see error in terminal:
```
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at __node_internal_captureLargerStackTrace (node:internal/errors:496:5)
    at new NodeError (node:internal/errors:405:5)
    at ServerResponse.setHeader (node:_http_outgoing:648:11)
    at ServerResponse.header (C:\try\t18\node_modules\express\lib\response.js:795:10)
    at ServerResponse.send (C:\try\t18\node_modules\express\lib\response.js:175:12)
    at <anonymous> (c:\try\t18\index.ts:27:7)
    at Layer.handle [as handle_request] (C:\try\t18\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\try\t18\node_modules\express\lib\router\route.js:149:13)
    at Route.dispatch (C:\try\t18\node_modules\express\lib\router\route.js:119:3)
    at Layer.handle [as handle_request] (C:\try\t18\node_modules\express\lib\router\layer.js:95:5)
    at C:\try\t18\node_modules\express\lib\router\index.js:284:15
    at param (C:\try\t18\node_modules\express\lib\router\index.js:365:14)
    at param (C:\try\t18\node_modules\express\lib\router\index.js:376:14)
    at Function.process_params (C:\try\t18\node_modules\express\lib\router\index.js:421:3)
    at next (C:\try\t18\node_modules\express\lib\router\index.js:280:10)
    at file:///C:/try/t18/node_modules/@auth/express/index.js:140:17
```

### Expected behavior

Not to get the error

**Comment by noam-honig** [comment]
But there are cases where you want to block the next (sign in ) and other
cases where you do not want to block the next

**Comment by noam-honig** [comment]
I'm not trying to protect it - I'm trying for it to be aware of the current user, something like , hi hillac, 

Which I would implement as:
```ts
app.get("/*", (req, res) => {
    const session = res.locals.session ?? (await getSession(req, authConfig))

  res.send("Hello !"+session?.name)
})
```

But I think I understand you better now - the auth route is only to handle sign in, sign out etc... it's not a general middleware that adds the auth info to the request.

For that I need:
```ts
  const session = res.locals.session ?? (await getSession(req, authConfig))
```

Sounds about right?

**Comment by noam-honig** [comment]
Thanks
