### ISSUE TITLE
Error getting user session: Error: Invariant: headers() expects to have requestAsyncStorage, none available.

### ISSUE THREAD

**Issue by SH20RAJ** [nextauthjs/next-auth#10550]
### Environment

  System:
    OS: macOS 14.4.1
    CPU: (8) arm64 Apple M2
    Memory: 233.08 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.12.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.5.0 - /usr/local/bin/npm
    bun: 1.1.2 - ~/.bun/bin/bun
  Browsers:
    Chrome: 123.0.6312.122
    Safari: 17.4.1
  npmPackages:
    next: 14.1.4 => 14.1.4 
    next-auth: ^4.24.7 => 4.24.7 
    react: ^18 => 18.2.0 

### Reproduction URL

https://github.com/SH20RAJ/ShadeV3/tree/2da943dc6b9e8d1a59354e9953ecba07f8f866ce

### Describe the issue

I'm getting errors while the build process very similar to [this](https://stackoverflow.com/questions/77853840/exception-when-using-getserversession-in-server-actions-during-next-js-build-pha) I tried to search the solution use chatgpt (not updated) but I got no solution.

I got the codes and how to setup from a [YouTube Tutorial](https://www.youtube.com/watch?v=ot9yuKg15iA&t=654s&ab_channel=BuildSaaSwithEthan) and it's [blog](https://ethanmick.com/how-to-set-up-google-oauth-with-next-js-using-next-auth/) -> [GitHub Repo](https://github.com/a-bit-of-saas/examples/blob/main/next/oauth-google/lib/session.ts)

> ** And one more request is there to create proper documentation for the app router in nextjs also....**

```bash
info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
   Collecting page data ...
Error getting user session: Error: Invariant: headers() expects to have requestAsyncStorage, none available.
    at u (/vercel/path0/.next/server/chunks/355.js:30:6407)
    at s (/vercel/path0/.next/server/chunks/355.js:25:20302)
    at o (/vercel/path0/.next/server/app/api/auth/[...nextauth]/route.js:1:4019)
    at /vercel/path0/.next/server/app/_not-found.js:1:5355
    at t.a (/vercel/path0/.next/server/webpack-runtime.js:1:889)
    at 26087 (/vercel/path0/.next/server/app/_not-found.js:1:5261)
    at t (/vercel/path0/.next/server/webpack-runtime.js:1:128)
    at /vercel/path0/.next/server/app/_not-found.js:1:8232
    at t.a (/vercel/path0/.next/server/webpack-runtime.js:1:889)
    at 51965 (/vercel/path0/.next/server/app/_not-found.js:1:8137)
Error getting user session: Error: Invariant: headers() expects to have requestAsyncStorage, none available.
    at u (/vercel/path0/.next/server/chunks/355.js:30:6407)
    at s (/vercel/path0/.next/server/chunks/355.js:25:20302)
    at n (/vercel/path0/.next/server/chunks/51.js:1:10424)
    at /vercel/path0/.next/server/chunks/51.js:1:6850
    at t.a (/vercel/path0/.next/server/webpack-runtime.js:1:889)
    at 26087 (/vercel/path0/.next/server/chunks/51.js:1:6756)
    at t (/vercel/path0/.next/server/webpack-runtime.js:1:128)
    at /vercel/path0/.next/server/chunks/51.js:1:9727
    at t.a (/vercel/path0/.next/server/webpack-runtime.js:1:889)
    at 51965 (/vercel/path0/.next/server/chunks/51.js:1:9632)
Error getting user session: Error: Invariant: headers() expects to have requestAsyncStorage, none available.
    at u (/vercel/path0/.next/server/chunks/355.js:30:6407)
    at s (/vercel/path0/.next/server/chunks/355.js:25:20302)
    at o (/vercel/path0/.next/server/app/api/post/route.js:1:2179)
    at /vercel/path0/.next/server/app/log/page.js:1:6211
    at t.a (/vercel/path0/.next/server/webpack-runtime.js:1:889)
    at 26087 (/vercel/path0/.next/server/app/log/page.js:1:6117)
    at t (/vercel/path0/.next/server/webpack-runtime.js:1:128)
    at /vercel/path0/.next/server/app/log/page.js:1:9088
    at t.a (/vercel/path0/.next/server/webpack-runtime.js:1:889)
    at 51965 (/vercel/path0/.next/server/app/log/page.js:1:8993)
   Generating static pages (0/10) ...

   Generating static pages (2/10) 

   Generating static pages (4/10) 
TypeError: Cannot read properties of null (reading 'image')
    at o (/vercel/path0/.next/server/app/log/page.js:1:8173)
    at em (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:131205)
    at /vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:142906
    at Array.toJSON (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:146484)
    at stringify (<anonymous>)
    at eR (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:134868)
    at eP (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:135311)
    at AsyncLocalStorage.run (node:async_hooks:346:14)
    at Timeout._onTimeout (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:146936)
    at listOnTimeout (node:internal/timers:573:17)
TypeError: Cannot read properties of null (reading 'image')
    at o (/vercel/path0/.next/server/app/log/page.js:1:8173)
    at em (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:131205)
    at /vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:142906
    at Array.toJSON (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:146484)
    at stringify (<anonymous>)
    at eR (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:134868)
    at eP (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:135311)
    at Timeout._onTimeout (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:132091)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
TypeError: Cannot read properties of null (reading 'image')
    at o (/vercel/path0/.next/server/app/_not-found.js:1:7317)
    at em (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:131205)
    at /vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:142906
    at Array.toJSON (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:146484)
    at stringify (<anonymous>)
    at eR (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:134868)
    at eP (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:135311)
    at AsyncLocalStorage.run (node:async_hooks:346:14)
    at Timeout._onTimeout (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:146936)
    at listOnTimeout (node:internal/timers:573:17)
TypeError: Cannot read properties of null (reading 'image')
    at o (/vercel/path0/.next/server/app/_not-found.js:1:7317)
    at em (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:131205)
    at /vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:142906
    at Array.toJSON (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:146484)
    at stringify (<anonymous>)
    at eR (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:134868)
    at eP (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:135311)
    at Timeout._onTimeout (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:132091)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
Error occurred prerendering page "/_not-found". Read more: https://nextjs.org/docs/messages/prerender-error
TypeError: Cannot read properties of null (reading 'image')
    at o (/vercel/path0/.next/server/app/_not-found.js:1:7317)
    at em (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:131205)
    at /vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:142906
    at Array.toJSON (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:146484)
    at stringify (<anonymous>)
    at eR (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:134868)
    at eP (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:135311)
    at AsyncLocalStorage.run (node:async_hooks:346:14)
    at Timeout._onTimeout (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:146936)
    at listOnTimeout (node:internal/timers:573:17)
TypeError: Cannot read properties of null (reading 'image')
    at o (/vercel/path0/.next/server/app/_not-found.js:1:7317)
    at em (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:131205)
    at /vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:142906
    at Array.toJSON (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:146484)
    at stringify (<anonymous>)
    at eR (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:134868)
    at eP (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:135311)
    at AsyncLocalStorage.run (node:async_hooks:346:14)
    at Timeout._onTimeout (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:146936)
    at listOnTimeout (node:internal/timers:573:17)
TypeError: Cannot read properties of null (reading 'image')
    at o (/vercel/path0/.next/server/app/_not-found.js:1:7317)
    at em (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:131205)
    at /vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:142906
    at Array.toJSON (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:146484)
    at stringify (<anonymous>)
    at eR (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:134868)
    at eP (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:135311)
    at Timeout._onTimeout (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:132091)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
TypeError: Cannot read properties of null (reading 'image')
    at l (/vercel/path0/.next/server/chunks/51.js:1:8812)
    at em (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:131205)
    at /vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:142906
    at Array.toJSON (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:146484)
    at stringify (<anonymous>)
    at eR (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:134868)
    at eP (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:135311)
    at AsyncLocalStorage.run (node:async_hooks:346:14)
    at Timeout._onTimeout (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:146936)
    at listOnTimeout (node:internal/timers:573:17)
TypeError: Cannot read properties of null (reading 'image')
    at l (/vercel/path0/.next/server/chunks/51.js:1:8812)
    at em (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:131205)
    at /vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:142906
    at Array.toJSON (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:146484)
    at stringify (<anonymous>)
    at eR (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:134868)
    at eP (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:135311)
    at Timeout._onTimeout (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:132091)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
Error occurred prerendering page "/log". Read more: https://nextjs.org/docs/messages/prerender-error
TypeError: Cannot read properties of null (reading 'image')
    at o (/vercel/path0/.next/server/app/_not-found.js:1:7317)
    at em (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:131205)
    at /vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:142906
    at Array.toJSON (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:146484)
    at stringify (<anonymous>)
    at eR (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:134868)
    at eP (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:135311)
    at AsyncLocalStorage.run (node:async_hooks:346:14)
    at Timeout._onTimeout (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:146936)
    at listOnTimeout (node:internal/timers:573:17)

   Generating static pages (7/10) 
Error occurred prerendering page "/". Read more: https://nextjs.org/docs/messages/prerender-error
TypeError: Cannot read properties of null (reading 'image')
    at l (/vercel/path0/.next/server/chunks/51.js:1:8812)
    at em (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:131205)
    at /vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:142906
    at Array.toJSON (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:146484)
    at stringify (<anonymous>)
    at eR (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:134868)
    at eP (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:135311)
    at AsyncLocalStorage.run (node:async_hooks:346:14)
    at Timeout._onTimeout (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:146936)
    at listOnTimeout (node:internal/timers:573:17)
Error occurred prerendering page "/login". Read more: https://nextjs.org/docs/messages/prerender-error
TypeError: Cannot read properties of null (reading 'image')
    at o (/vercel/path0/.next/server/app/log/page.js:1:8173)
    at em (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:131205)
    at /vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:142906
    at Array.toJSON (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:146484)
    at stringify (<anonymous>)
    at eR (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:134868)
    at eP (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:135311)
    at AsyncLocalStorage.run (node:async_hooks:346:14)
    at Timeout._onTimeout (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:146936)
    at listOnTimeout (node:internal/timers:573:17)
Error: Command "npm run build" exited with 1
```

### How to reproduce

I want the login to work properly, Please reply asap with the solution

### Expected behavior

I want the login signup to work properly

**Comment by robliou** [comment]
i'm getting this same error.
