### ISSUE TITLE
Error on missing `profileUrl` and/or `profile`

### ISSUE THREAD

**Issue by jackHedaya** [nextauthjs/next-auth#1065]
**Describe the bug**
In the documentation, `profileUrl` and `profile` for custom providers are said to be not required in documentation but the application will crash if they are not given. This error is also the root of issue #209 as discovered by @ospira.

**Steps to reproduce**
Steps to reproduce the behavior.
+ Create custom provider
+ Omit `profileUrl` and/or `profile`

**Expected behavior**
Authentication to succeed and `profile` to be set to undefined.

**Screenshots or error logs**
```
[next-auth][error][oauth_get_access_token_error] [
  TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received undefined
      at new NodeError (node:internal/errors:278:15)
      at validateString (node:internal/validators:123:11)
      at Url.parse (node:url:160:3)
      at Object.urlParse [as parse] (node:url:155:13)
      at exports.OAuth2._request (/Users/jackhedaya/Desktop/thoughtful-fish/node_modules/oauth/lib/oauth2.js:72:22)
      at /Users/jackhedaya/Desktop/thoughtful-fish/node_modules/next-auth/dist/server/lib/oauth/client.js:240:12
      at new Promise (<anonymous>)
      at exports.OAuth2.<anonymous> (/Users/jackhedaya/Desktop/thoughtful-fish/node_modules/next-auth/dist/server/lib/oauth/client.js:239:12)
     ...
```

**Additional context**
Original custom Provider:
```ts
NextAuth(req, res, {
    providers: [
      {
        id: '[redacted]',
        name: '[redacted]',
        type: 'oauth',
        version: '2.0',
        accessTokenUrl: '[redacted]',
        requestTokenUrl: '[redacted]',
        authorizationUrl: `[redacted]`,
        clientId: process.env.CONSUMER_KEY,
        params: {
          grant_type: 'authorization_code',
        },
      },
    ],
    debug: true,
  })
```

Working custom provider:

```ts
NextAuth(req, res, {
    providers: [
      {
        id: '[redacted]',
        name: '[redacted]',
        type: 'oauth',
        version: '2.0',
        accessTokenUrl: '[redacted]',
        requestTokenUrl: '[redacted]',
        authorizationUrl: `[redacted]`,
        clientId: process.env.CONSUMER_KEY,
        params: {
          grant_type: 'authorization_code',
        },
        profileUrl: '[redacted]',
        profile: (p) => {
          return {
            id: p.userId
          }
        },
      },
    ],
    debug: true,
  })
```

* [ ] Found the documentation helpful
* [x] Found documentation but was incomplete
* [ ] Could not find relevant documentation
* [ ] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by balazsorban44** [comment]
Hi there, I don't think this is a big, but rather wrong documentation. I think we should change the docs to say these are not optional values.

Could you tell me a usecase for logging into a provider and not getting user info is useful? I might be missing something but would like to hear.

**Comment by jackHedaya** [comment]
Hmm I'm not sure if it's fair to assume everyone is using a profile. Personally, I'm using a provider primarily for authentication rather than needing their actual user data. I use the user data as well, but I'm not sure it should be enforced by NextAuth.

**Comment by balazsorban44** [comment]
Thanks for the additional information, I will take this up with @iaincollins!

**Comment by StefanSelfTaught** [comment]
I have the exact same issue. If I pass the `profileURL` I have to send a custom header so I can access the URL. Can I send a header somehow?

**Comment by unframework** [comment]
Related issue from ealier: https://github.com/nextauthjs/next-auth/issues/573.

In my case, for example, I am trying to implement Shopify admin login using their OAuth scheme. There is actually an endpoint that returns some information but it expects a custom X-Shopify-Access-Token header, and there is no way to customize profile GET request to send that.

It would be great to make profileUrl be actually optional, and/or allow per-provider customization of the request headers (and other details too).

**Comment by balazsorban44** [comment]
Hi @unframework, you CAN actually provide custom headers when fetching the profile:

https://github.com/nextauthjs/next-auth/blob/dc5f3f481d11841731b18e12d5ed3a1bf941b745/src/server/lib/oauth/client.js#L197

Docs: https://next-auth.js.org/configuration/providers#oauth-provider-options

**Comment by unframework** [comment]
Thanks for the prompt response! If I understand correctly, those headers are only static values, right? Because in my case I'd need to put the dynamic access token value under a custom header name... And then it would also not be formatted as `Bearer xyz123` but just `xyz123`.

Anywho, I am sure provider configurability is a complicated topic in general so good luck! :)

**Comment by balazsorban44** [comment]
Thanks for understanding! We are constantly thinking about how to provide a robust enough solution that is easy-to-use and covers enough use cases to be a worthy provider option addition.

I think some kind of a callback could work for getting tokens (`id_token`, `refresh_token`, `access_token`) and profile data:
```js
...
async getProfile ({ url, headers, params, tokens }) {
  return { url, headers, params }
},
async getTokens ({ url, headers, params }) {
  return { url, headers, params }
},
...
```

Returning `null` for `getProfile` could mean that the user doesn't want to get any data (that I think would cover a solution for this original issue) about the user.

**Comment by damianesteban** [comment]
I'm having a similar issue with Yext OAuth. The documentation is scarce and the only example I can find is here: https://github.com/yext/twitter-reference-app

This is the example code in Python:

```
def exchange_yext_auth_code(auth_code):
    """Exchanges Yext authorization code for Yext access token
    Returns an identifier and access token for the account that authorized with
    the app.
    """
    request_body = {
        'grant_type': 'authorization_code',
        'code': auth_code,
        'redirect_uri': get_yext_redirect_uri(),
        'client_id': app.config['YEXT_CLIENT_ID'],
        'client_secret': app.config['YEXT_API_KEY']
    }
    response = requests.post('https://api.yext.com/oauth2/accesstoken',
        data=request_body)
    
    response_json = response.json()
    yext_account_id = response_json['appSpecificAccountId']
    yext_access_token = response_json['access_token']
    return yext_account_id, yext_access_token
```

**Comment by bhaskarmurthy** [comment]
I'm running into the same issue as well. Setting up a custom provider - and we don't need the profile as we're only using it for authorization. Is there any workaround or setting to bypass this?

**Comment by balazsorban44** [comment]
I guess a very silly workaround for now could be to just create a dummy api route that you point the profileUrl to that returns a dummy profile. 🤔

It is not ideal, and I will come back to this issue later on to try to find a better solution.

**Comment by balazsorban44** [comment]
Please have a look at this RFC for a new way of configuring a provider, with an optional profile!
#1846

**Comment by mcintyre94** [comment]
One example where a profile doesn't work is the new Notion API, which doesn't have a profile URL available. They don't seem to plan to either:

> Store all of the information your integration receives with the access token. You never know when your UI requirements or product requirements might change, and you find some use of this data. It's really hard (or impossible) to send users to authorize again to get this information.

https://developers.notion.com/docs/authorization#authorizing-public-integrations

**Comment by balazsorban44** [comment]
Think @pbteja1998 dealt with Notion recently, maybe he has a good advice.

**Comment by pbteja1998** [comment]
@mcintyre94 yeah, I used `https://api.notion.com/v1/users` as the endpoint for profile Url, and then filter out the user we want from the response.

My workflow looks something like this
1. Login with email
2. Connect Notion (this executes the same flow as Login with Notion)
3. I get all users of the workspace in the profile instead of a single url. Since I know the email of logged in user, I manually filter that user from these list of users, and update the user properties in my database.

**Comment by cmnstmntmn** [comment]
@unframework how did you manage to make Shopify work?

**Comment by MarcelMalik** [comment]
Hi!
I'm also trying to implement a custom provider for Hubspot. But these don't seem to have a UserInfo endpoint, so it would be useful if this wasn't necessary.
https://legacydocs.hubspot.com/docs/methods/oauth2/oauth2-overview

In the OAuth Specs (https://oauth.net/2/) I also don't find an requirement for a profile / userinfo endpoint.

**Comment by balazsorban44** [comment]
Closing in favor of #1846

**Comment by balazsorban44** [comment]
Sorry, I reopen this to track it differently from #1846 after all. :slightly_smiling_face:. I will have a look at this as well, but the PR to implement #1846 was getting huge.

**Comment by prabureddy** [comment]
Added Shopify Provider:- https://github.com/nextauthjs/next-auth/pull/3964
