### ISSUE TITLE
Try signing with a different account. - Callback error

### ISSUE THREAD

**Issue by ChGGse** [nextauthjs/next-auth#1106]
**Describe the bug**
When trying to sign in to GitHub it says "Try signing with a different account."

**Steps to reproduce**
- Clone orangopus/libby
- click "Login" 
- Click "Sign in with GitHub"

Make sure to include the client ID and secret in .env as `GITHUB_ID` and `GITHUB_SECRET`

**Expected behavior**
I expected it to login and return to the app.

**Screenshots or error logs**
The error is
![browser_7MIk0bI7BK](https://user-images.githubusercontent.com/45247477/104529167-fc6e2e00-5600-11eb-8127-f78be5dd7ca9.png)

**Feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [x] Found the documentation helpful
* [x] Found documentation but was incomplete
* [x] Could not find relevant documentation
* [x] Found the example project helpful
* [x] Did not find the example project helpful

**Comment by balazsorban44** [comment]
Please provide more context, (preferably a full reproduction repository with a link) otherwise we cannot help you.

**Comment by balazsorban44** [comment]
Could you maybe set `debug: true` in your `NextAuth ` options, and see if anything useful comes up in your console then? Also, what's the url of the page you are seeing the "Sign in with a different account" warning on?

**Comment by ChGGse** [comment]
> Could you maybe set `debug: true` in your `NextAuth ` options, and see if anything useful comes up in your console then? Also, what's the url of the page you are seeing the "Sign in with a different account" warning on?

Found the issue! User was already created so it was throwing an error.

```
[next-auth][error][oauth_callback_handler_error] PrismaClientKnownRequestError2 [PrismaClientKnownRequestError]: 
Invalid `prisma.user.create()` invocation:


  Unique constraint failed on the fields: (`name`)
    at PrismaClientFetcher.request (E:\libby\libby-web\node_modules\@prisma\client\runtime\index.js:78130:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  code: 'P2002',
  clientVersion: '2.14.0',
  meta: { target: [ 'name' ] }
}
```

**Comment by ChGGse** [comment]
Getting a new error now...

```
[next-auth][error][session_error] TypeError: Cannot read property 'name' of null
    at E:\libby\libby-web\node_modules\next-auth\dist\server\routes\session.js:99:26
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (E:\libby\libby-web\node_modules\next-auth\dist\server\routes\session.js:22:103)
    at _next (E:\libby\libby-web\node_modules\next-auth\dist\server\routes\session.js:24:194)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
https://next-auth.js.org/errors#session_error
```

**Comment by ChGGse** [comment]
Still getting the session error. Any updates?

**Comment by ovo** [comment]
Experiencing this as well. Ref: #1119

**Comment by awey95** [comment]
I went to bed, woke up, booted up my app and I started getting this error. It was working last night so not sure what happened.

```
[next-auth][error][oauth_callback_handler_error] PrismaClientKnownRequestError2 [PrismaClientKnownRequestError]: 
Invalid `prisma.user.create()` invocation:

Unique constraint failed on the fields: (`name`)
    at PrismaClientFetcher.request (/Users/adam/Development/nextjs/hackernews/node_modules/@prisma/client/runtime/index.js:78130:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  code: 'P2002',
  clientVersion: '2.14.0',
  meta: { target: [ 'name' ] }
} 
https://next-auth.js.org/errors#oauth_callback_handler_error
```

**Comment by balazsorban44** [comment]
@williamluke4 this seems to be Prisma related. Any ideas?

**Comment by mmiszy** [comment]
I'm experiencing the same problem now for no apparent reason.
I'm using the Prisma client :)

**Comment by williamluke4** [comment]
Could someone who is experiencing this issue please post your Schema and indicate whether you are using the stock `nextauthjs/next-auth` prisma adapter or the adapter from `nextauthjs/adapters`

**Comment by kailoon** [comment]
I am facing by the same problem. I am using the Prisma Adapter.

`adapter: Adapters.Prisma.Adapter({ prisma }) `

Prisma Schema

```

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "sqlite"
  url      = "file:./dev.db"
}

model Account {
  id                 Int       @default(autoincrement()) @id
  compoundId         String    @unique @map(name: "compound_id")
  userId             Int       @map(name: "user_id")
  providerType       String    @map(name: "provider_type")
  providerId         String    @map(name: "provider_id")
  providerAccountId  String    @map(name: "provider_account_id")
  refreshToken       String?   @map(name: "refresh_token")
  accessToken        String?   @map(name: "access_token")
  accessTokenExpires DateTime? @map(name: "access_token_expires")
  createdAt          DateTime  @default(now()) @map(name: "created_at")
  updatedAt          DateTime  @default(now()) @map(name: "updated_at")

  @@index([providerAccountId], name: "providerAccountId")
  @@index([providerId], name: "providerId")
  @@index([userId], name: "userId")

  @@map(name: "accounts")
}

model Session {
  id           Int      @default(autoincrement()) @id
  userId       Int      @map(name: "user_id")
  expires      DateTime
  sessionToken String   @unique @map(name: "session_token")
  accessToken  String   @unique @map(name: "access_token")
  createdAt    DateTime @default(now()) @map(name: "created_at")
  updatedAt    DateTime @default(now()) @map(name: "updated_at")

  @@map(name: "sessions")
}

model User {
  id            Int       @default(autoincrement()) @id
  name          String?
  email         String?   @unique
  emailVerified DateTime? @map(name: "email_verified")
  image         String?
  createdAt     DateTime  @default(now()) @map(name: "created_at")
  updatedAt     DateTime  @default(now()) @map(name: "updated_at")

  @@map(name: "users")
}

model VerificationRequest {
  id         Int      @default(autoincrement()) @id
  identifier String
  token      String   @unique
  expires    DateTime
  createdAt  DateTime  @default(now()) @map(name: "created_at")
  updatedAt  DateTime  @default(now()) @map(name: "updated_at")

  @@map(name: "verification_requests")
}
```

**Comment by talentlessguy** [comment]
Same issue

```ts
import Providers from 'next-auth/providers'
import Adapters from 'next-auth/adapters'
import { prisma } from './prisma'
import type { Session as DefaultSession } from 'next-auth'
import { User } from '@prisma/client'
import slug from 'slug'

export type Session = DefaultSession & { id: number; accessToken: string }

const options = {
  adapter: Adapters.Prisma.Adapter({ prisma }),
  site: process.env.BASE_URL,
  callbacks: {
    session: async (sess: Session, user: User) => {
      sess.id = user.id

      // Create user with characteristics
      await prisma.user.update({
        where: {
          id: user.id
        },
        data: {
          slug: slug(user.name)
        }
      })

      return Promise.resolve(sess)
    }
  },
  // Configure one or more authentication providers
  providers: [
    Providers.GitHub({
      clientId: process.env.GITHUB_ID,
      clientSecret: process.env.GITHUB_SECRET
    }),
    Providers.Email({
      server: {
        host: processs.env.MAIL_HOST,
        port: 587,
        auth: {
          user: 'noreply@example.com',
          pass: process.env.MAIL_PWD
        }
      },
      from: 'noreply@example.com'
    })
  ]
```

**Comment by talentlessguy** [comment]
Guys, I found out a simple solution for those who struggle with email auth. Just add a callback for signin and assign a user name there. Prisma will consume that name and user will be registered.

```js
const options = {
  callback: {
    signIn(user, account, profile) {
        user.name = slug(user.email.slice(0, user.email.indexOf('@'))) // or whatever else
  
        return true
      }
  }
}
```
