### ISSUE TITLE
Custom Provider w/ wellKnown Failure (v5)

### ISSUE THREAD

**Issue by Rikaelus** [nextauthjs/next-auth#11192]
### Provider type

Custom provider

### Environment

```
  System:
    OS: Linux 5.15 Ubuntu 24.04 LTS 24.04 LTS (Noble Numbat)
    CPU: (4) x64 AMD Ryzen 7 3700X 8-Core Processor
    Memory: 14.34 GB / 15.62 GB
    Container: Yes
    Shell: 5.2.21 - /bin/bash
  Binaries:
    Node: 18.19.1 - /usr/bin/node
    npm: 9.2.0 - /usr/bin/npm
  npmPackages:
    @auth/unstorage-adapter: ^2.0.0 => 2.2.0
    next: latest => 14.2.4
    next-auth: beta => 5.0.0-beta.19
    react: ^18.2.0 => 18.3.1

Also experienced in: 
   node:20-alpine Docker environment w/
    "react": "18.3.0",
    "next": "^14.2.3",
    "next-auth": "^5.0.0-beta.19",
```

### Reproduction URL

https://github.com/Rikaelus/nextauth-bug

### Describe the issue

What works in v4 with this configuration..
```
            {
                id: 'idcs',
                name: 'IDCS Authentication Scheme',
                type: 'oauth',
                authorization: { params: { scope: 'openid profile email groups' } },
                wellKnown: 'https://idcs-01023b3d6830473585f63c240c0da80f.identity.oraclecloud.com/.well-known/openid-configuration',
                clientId: '5cbb9089e4e54ab69658940964faa9ab',
                clientSecret: '######',
                profile(profile) {
                    return {
                        id: profile?.sub,
                        name: profile?.name,
                        email: profile?.email,
                        image: profile?.picture,
                    }
                },
            },
```
fails in v5 with this configuration...
```
    {
      id: 'idcs',
      name: 'IDCS Authentication Scheme',
      type: 'oauth',
      issuer: 'https://identity.oraclecloud.com',
      authorization: { params: { scope: 'openid profile email groups' } },
      wellKnown: 'https://idcs-01023b3d6830473585f63c240c0da80f.identity.oraclecloud.com/.well-known/openid-configuration',
      clientId: '5cbb9089e4e54ab69658940964faa9ab',
      clientSecret: '######',
      async profile(profile){
        return {
          id: profile?.sub,
          name: profile?.name,
          email: profile?.email,
          image: profile?.picture,
        };
      },
    }
```

The error occurs immediately before the user is redirected to the SSO provider and thus `clientSecret` isn't yet relevant and can be blanked out. My suspicion is that it's improperly reading or using the data provided by the `wellKnown`. These issues can be circumvented (to some extent) by manually specifying URLs instead of relying on the `wellKnown`.

Logs show a somewhat unhelpful:
```
[auth][error] TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11360:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getAuthorizationUrl (webpack-internal:///(rsc)/./node_modules/@auth/core/lib/actions/signin/authorization-url.js:24:35)
    at async Module.signIn (webpack-internal:///(rsc)/./node_modules/@auth/core/lib/actions/signin/index.js:16:56)
    at async AuthInternal (webpack-internal:///(rsc)/./node_modules/@auth/core/lib/index.js:72:24)
    at async Auth (webpack-internal:///(rsc)/./node_modules/@auth/core/index.js:126:34)
    at async /home/****/nextauth-bug/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:55038
    at async ek.execute (/home/****/nextauth-bug/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:45808)   
    at async ek.handle (/home/****/nextauth-bug/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:56292)    
    at async doRender (/home/****/nextauth-bug/node_modules/next/dist/server/base-server.js:1377:42)
    at async cacheEntry.responseCache.get.routeKind (/home/****/nextauth-bug/node_modules/next/dist/server/base-server.js:1587:40)
    at async DevServer.renderToResponseWithComponentsImpl (/home/****/nextauth-bug/node_modules/next/dist/server/base-server.js:1507:28)
    at async DevServer.renderPageComponent (/home/****/nextauth-bug/node_modules/next/dist/server/base-server.js:1931:24)        
    at async DevServer.renderToResponseImpl (/home/****/nextauth-bug/node_modules/next/dist/server/base-server.js:1969:32)       
    at async DevServer.pipeImpl (/home/****/nextauth-bug/node_modules/next/dist/server/base-server.js:920:25)
    at async NextNodeServer.handleCatchallRenderRequest (/home/****/nextauth-bug/node_modules/next/dist/server/next-server.js:272:17)
    at async DevServer.handleRequestImpl (/home/****/nextauth-bug/node_modules/next/dist/server/base-server.js:816:17)
    at async /home/****/nextauth-bug/node_modules/next/dist/server/dev/next-dev-server.js:339:20
    at async Span.traceAsyncFn (/home/****/nextauth-bug/node_modules/next/dist/trace/trace.js:154:20)
    at async DevServer.handleRequest (/home/****/nextauth-bug/node_modules/next/dist/server/dev/next-dev-server.js:336:24)       
    at async invokeRender (/home/****/nextauth-bug/node_modules/next/dist/server/lib/router-server.js:174:21)
    at async handleRequest (/home/****/nextauth-bug/node_modules/next/dist/server/lib/router-server.js:353:24)
    at async requestHandlerImpl (/home/****/nextauth-bug/node_modules/next/dist/server/lib/router-server.js:377:13)
    at async Server.requestListener (/home/****/nextauth-bug/node_modules/next/dist/server/lib/start-server.js:141:13)
```
### How to reproduce

Reproduceable w/ sign-in attempt on provided example repo.

### Expected behavior

As with v4, the user is redirected to a URL resembling:
```
https://idcs-01023b3d6830473585f63c240c0da80f.identity.oraclecloud.com/oauth2/v1/authorize
?client_id=5cbb9089e4e54ab69658940964faa9ab
&scope=openid%20profile%20email%20groups
&response_type=code
&redirect_uri=http%3A%2F%2Flocalhost%3A7000%2Fapi%2Fauth%2Fcallback%2Fidcs
&state=CXLyPApyex2b15hJbBhoSFLwA95os5CN3onRG5m8qWo
```
(and subsequent operations validate and function as expected, though this won't be provable without a functioning secret)

**Comment by Renkas** [comment]
I don't see any use of the `wellKnown` URL in the source of this library.

**Comment by balazsorban44** [comment]
Since v5, the discovery (well-known) URL is inferred from the `issuer`.

It looks like you are trying to use a non-spec compliant provider here, as the issuer on `https://idcs-01023b3d6830473585f63c240c0da80f.identity.oraclecloud.com/.well-known/openid-configuration` does not match `https://identity.oraclecloud.com/`).

Per spec, these should match. See: https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderConfigurationValidation

Currently, we provide no workaround for these non-compliant providers.
