### ISSUE TITLE
Nextjs middleware edge runtime problem (with Mysql database with Knex package)

### ISSUE THREAD

**Issue by Jasermon** [nextauthjs/next-auth#11595]
### Environment

```
  System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
    Memory: 19.24 GB / 31.96 GB
  Binaries:
    Node: 21.1.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.22 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 10.2.5 - ~\AppData\Roaming\npm\npm.CMD
  Browsers:
    Chrome: 127.0.6533.100
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.19041.4355
  npmPackages:
    next: 14.2.5 => 14.2.5
    next-auth: ^5.0.0-beta.20 => 5.0.0-beta.20
    react: ^18 => 18.3.1
```

### Reproduction URL

https://github.com/Jasermon/next-app-router-authjs-v5

### Describe the issue

When I create the middleware file I get the following error:

```
Error: The edge runtime does not support Node.js 'tty' module.
Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime
    at <unknown> (webpack-internal:///(middleware)/./node_modules/next/dist/esm/server/web/globals.js:43)
    at Object.apply (webpack-internal:///(middleware)/./node_modules/next/dist/esm/server/web/globals.js:43:19)
    at eval (webpack-internal:///(middleware)/./node_modules/colorette/index.cjs:39:61)
    at (middleware)/./node_modules/colorette/index.cjs (file://...\.next\server\middleware.js:4920:1)
    at __webpack_require__ (file://...\.next\server\edge-runtime-webpack.js:37:33)
    at fn (file://...\.next\server\edge-runtime-webpack.js:285:21)
    at eval (webpack-internal:///(middleware)/./node_modules/knex/lib/logger.js:1:15)
    at (middleware)/./node_modules/knex/lib/logger.js (file://...\.next\server\middleware.js:1252:1)
    at __webpack_require__ (file://...\.next\server\edge-runtime-webpack.js:37:33)
    at fn (file://...\.next\server\edge-runtime-webpack.js:285:21)
    at eval (webpack-internal:///(middleware)/./node_modules/knex/lib/client.js:29:16)
```

I think this problem is caused by the Knex module. I'm not sure how to solve this.

middleware.js

```
import { auth } from "auth";

export default auth((req) => {
	if (!req.auth && req.nextUrl.pathname !== "/login") {
		const newUrl = new URL("/login", req.nextUrl.origin);
		return Response.redirect(newUrl);
	}
});

// Optionally, don't invoke Middleware on some paths
export const config = {
	matcher: ["/((?!api|_next/static|_next/image|favicon.ico).*)"],
};

```

auth.js

```
import NextAuth from "next-auth";
import Credentials from "next-auth/providers/credentials";
import { UserLoginAuth } from "src/_helpers/auth-repo";

export const { handlers, signIn, signOut, auth } = NextAuth({
	session: {
		strategy: "jwt",
		// maxAge: 60 * 60 * 27,
		maxAge: 5,
	},
	pages: {
		signIn: "/login",
	},
	providers: [
		Credentials({
			name: "credentials",
			authorize: async (crt) => {
				if (crt === null) return null;
				try {
					const user = await UserLoginAuth(crt);
					return user;
				} catch (error) {
					console.log(error);
				}
			},
		}),
	],
	secret: "SK9MiaHNr276ZvX1xQ8WOtCpNbiQU7Quenio5bAqGiU=",
	callbacks: {
		async jwt({ token, user }) {
			if (user) {
				return { ...token, ...user };
			}
			return token;
		},
		async session({ session, token }) {
			if (token) {
				session.user = token;
			}
			return session;
		},
		authorized: async ({ auth }) => {
			return !!auth;
		},
	},
});

```

auth-repo.js

```
import { pool } from "src/lib/db";
import bcrypt from "bcryptjs";

export async function UserLoginAuth(crt) {
	const db = await pool.transaction();
	...
}
```

### How to reproduce

1. Run `yarn dev`
2. You will see the error.

### Expected behavior

I am not sure.

**Comment by lapa182** [comment]
Having the same issue and seems related to `5.0.0-beta.20` async change.

**Comment by Jasermon** [comment]
> Having the same issue, but not using Knex, and seems related to `5.0.0-beta.20` as downgrading to `.19` works fine.

I tried but it doesn't work.

When I remove the `import { UserLoginAuth } from "src/_helpers/auth-repo";` code from the auth.js file, the problem is gone.
If I keep code `import { UserLoginAuth } from "src/_helpers/auth-repo";` in auth.js and remove `import { pool } from "src/lib/db";` from auth-repo.js, the problem is solved again.

I think the problem is that the Knex module is indirectly imported into the middleware via auth. I wonder if there is another way to set up the middleware with next-auth

**Comment by Jasermon** [comment]
I found a tricky solution as below. Is this a good practice? I am not sure. If this is a bad practice, please tell me.

auth.config.js
```
import { NextResponse } from "next/server";

export const authConfig = {
	session: {
		strategy: "jwt",
		maxAge: 60 * 60 * 27,
	},
	pages: {
		signIn: "/login",
		signOut: "/dashboard/logout",
	},
	secret: "...",
	callbacks: {
		async jwt({ token, user }) {
			if (user) {
				return { ...token, items: user };
			}
			return token;
		},
		async session({ session, token }) {
			session.user = token;
			return session;
		},
		authorized({ auth, request: { nextUrl } }) {
			const isLoggedIn = !!auth?.user;
			const isOnDashboard = nextUrl.pathname.startsWith("/dashboard");
			if (isOnDashboard) {
				if (isLoggedIn) return true;
				return NextResponse.redirect(new URL("/login", nextUrl)); // Redirect unauthenticated users to login page
			} else if (isLoggedIn) {
				return NextResponse.redirect(new URL("/dashboard", nextUrl));
			}
			return true;
		},
	},
	providers: [], // Add providers with an empty array for now
};
```

auth.js

```
import { authConfig } from "auth.config";
import NextAuth from "next-auth";
import Credentials from "next-auth/providers/credentials";
import { UserLoginAuth } from "src/_helpers/auth-repo";

export const { handlers, signIn, signOut, auth } = NextAuth({
	...authConfig,
	providers: [
		Credentials({
			name: "credentials",
			authorize: async (crt) => {
				if (crt === null) return null;
				try {
					const user = await UserLoginAuth(crt);
					return user;
				} catch (error) {
					console.log(error);
				}
			},
		}),
	],
});
```

middleware.js

```
import { authConfig } from "auth.config";
import NextAuth from "next-auth";
import { NextResponse } from "next/server";

const { auth } = NextAuth(authConfig);

export default auth(async function middleware(request) {
	const { url, nextUrl, auth } = request;
	if (nextUrl.pathname === "/" && !auth) {
		return NextResponse.redirect(new URL("/login", url));
	} else if (nextUrl.pathname === "/" && auth) {
		return NextResponse.redirect(new URL("/dashboard", url));
	}
});

export const config = {
	matcher: ["/((?!api|_next/static|_next/image|favicon.ico).*)"],
};
```

**Comment by balazsorban44** [comment]
Please see https://authjs.dev/guides/edge-compatibility

**Comment by antonlvovych** [comment]
Next.js added support for setting up runtime for middleware.
Example here: https://github.com/vercel/next.js/discussions/71727#discussioncomment-12063767

**Comment by Kepron** [comment]
> Next.js added support for setting up runtime for middleware. Example here: [vercel/next.js#71727 (comment)](https://github.com/vercel/next.js/discussions/71727#discussioncomment-12063767)

Thanks for the info. But I wrote my own auth system. I'm sure it will help those who encounter a similar problem.
