### ISSUE TITLE
Firestore adapter doesn't work when adding middleware.ts

### ISSUE THREAD

**Issue by KareemMAX** [nextauthjs/next-auth#11787]
### Adapter type

@auth/firebase-adapter

### Environment

```
  System:
    OS: Linux 5.15 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
    CPU: (12) x64 AMD Ryzen 5 5600X 6-Core Processor
    Memory: 11.28 GB / 15.59 GB
    Container: Yes
    Shell: 5.2.15 - /bin/bash
  Binaries:
    Node: 22.6.0 - /usr/local/bin/node
    Yarn: 1.22.22 - /usr/local/bin/yarn
    npm: 10.8.2 - /usr/local/bin/npm
    pnpm: 9.7.1 - /usr/local/share/npm-global/bin/pnpm
  npmPackages:
    @auth/firebase-adapter: ^2.4.2 => 2.4.2 
    next: 14.2.8 => 14.2.8 
    next-auth: ^5.0.0-beta.20 => 5.0.0-beta.20 
    react: ^18 => 18.3.1 
    firebase-admin: ^11.11.1
```

### Reproduction URL

https://github.com/KareemMAX/firestore-adapter-reproduction

### Describe the issue

When importing `Firebase adapter` while having the optional middleware as described in the [installation guide](https://authjs.dev/getting-started/installation#configure), the app refuses to work. Throwing the following error:
```
 ⨯ Error: The edge runtime does not support Node.js 'os' module.
Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime
    at <unknown> (webpack-internal:///(middleware)/./node_modules/next/dist/esm/server/web/globals.js:43)
    at Object.apply (webpack-internal:///(middleware)/./node_modules/next/dist/esm/server/web/globals.js:43:19)
    at eval (webpack-internal:///(middleware)/./node_modules/firebase-admin/lib/app/credential-internal.js:38:20)
    at eval (webpack-internal:///(middleware)/./node_modules/firebase-admin/lib/app/credential-internal.js:44:3)
    at (middleware)/./node_modules/firebase-admin/lib/app/credential-internal.js (file:///workspaces/firestore-adapter-reproduction/firestore-adapter-reproduction/.next/server/middleware.js:1044:1)
    at __webpack_require__ (file:///workspaces/firestore-adapter-reproduction/firestore-adapter-reproduction/.next/server/edge-runtime-webpack.js:37:33)
    at fn (file:///workspaces/firestore-adapter-reproduction/firestore-adapter-reproduction/.next/server/edge-runtime-webpack.js:285:21)
    at eval (webpack-internal:///(middleware)/./node_modules/firebase-admin/lib/utils/index.js:21:31)
    at (middleware)/./node_modules/firebase-admin/lib/utils/index.js (file:///workspaces/firestore-adapter-reproduction/firestore-adapter-reproduction/.next/server/middleware.js:1143:1)
    at __webpack_require__ (file:///workspaces/firestore-adapter-reproduction/firestore-adapter-reproduction/.next/server/edge-runtime-webpack.js:37:33)
    at fn (file:///workspaces/firestore-adapter-reproduction/firestore-adapter-reproduction/.next/server/edge-runtime-webpack.js:285:21)
```

Keep in mind that I tried `firebase-admin@12.4.0` the following error was produced:
```
Module build failed: UnhandledSchemeError: Reading from "node:stream" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "node:" URIs.
Import trace for requested module:
node:stream
./node_modules/@fastify/busboy/lib/main.js
./node_modules/firebase-admin/lib/utils/api-request.js
./node_modules/firebase-admin/lib/app/credential-internal.js
./node_modules/firebase-admin/lib/app/credential-factory.js
./node_modules/firebase-admin/lib/app/index.js
./node_modules/firebase-admin/lib/esm/app/index.js
./node_modules/@auth/firebase-adapter/index.js
./auth.ts
```

### How to reproduce

1. Create a simple next.js app, I used `create-next-app`
2. Follow [auth.js installation guide](https://authjs.dev/getting-started/installation#configure), including adding the middleware
3. Follow [Firebase adapter installation guide](https://authjs.dev/getting-started/adapters/firebase)

### Expected behavior

The adapter shouldn't use any functionality that is not allowed within nextjs middleware (next.js middleware runs on only on the [edge runtime](https://nextjs.org/docs/app/building-your-application/routing/middleware#runtime)).

**Comment by masoudmanson** [comment]
Any updates on this? I’m running into the exact same issue! The `Firestore` adapter works perfectly until I try adding even the simplest middleware. Just adding this line of middleware:

```
export { auth as middleware } from "@/auth";
```

gives me the following error:

```
⨯ node:stream
Module build failed: UnhandledSchemeError: Reading from "node:stream" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "node:" URIs.
Import trace for requested module:
node:stream
./node_modules/@fastify/busboy/lib/main.js
./node_modules/firebase-admin/lib/utils/api-request.js
./node_modules/firebase-admin/lib/app/credential-internal.js
./node_modules/firebase-admin/lib/utils/index.js
./node_modules/firebase-admin/lib/app/index.js
./node_modules/firebase-admin/lib/esm/app/index.js
./src/auth.ts
```

Any tips or workarounds?

**Comment by masoudmanson** [comment]
## UPDATE

Take a look at this documentation. This workaround fixes the adaptor errors!
https://authjs.dev/guides/edge-compatibility#middleware

```
"next": "^14.2.11",
"next-auth": "^5.0.0-beta.20",
```

**Comment by balazsorban44** [comment]
This is unrelated to Auth.js, it's a Next.js limitation. See https://authjs.dev/guides/edge-compatibility
