### ISSUE TITLE
"response" is not a conform Authorization Server Metadata response

### ISSUE THREAD

**Issue by lbenevento** [nextauthjs/next-auth#12041]
### Provider type

Azure Active Directory

### Environment

Docker container built with the Dockerfile present in the repo.

### Reproduction URL

https://github.com/lbenevento/authjs-response-not-conform

### Describe the issue

When I try to login AuthJS throw the following error: 
```
[auth][error] e2: "response" is not a conform Authorization Server Metadata response
    at tn (/app/.next/server/chunks/633.js:379:7136)
    at rP (/app/.next/server/chunks/633.js:379:43662)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async rC (/app/.next/server/chunks/633.js:379:46272)
    at async rj (/app/.next/server/chunks/633.js:379:48912)
    at async rL (/app/.next/server/chunks/633.js:379:53178)
    at async /app/node_modules/.pnpm/next@14.2.15_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:36957
    at async eC.execute (/app/node_modules/.pnpm/next@14.2.15_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:27552)
    at async eC.handle (/app/node_modules/.pnpm/next@14.2.15_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:38291)
    at async doRender (/app/node_modules/.pnpm/next@14.2.15_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/server/base-server.js:1352:42)
```

The only notable thing I can share about it is the fact that the Next build runs fine on my local machine. The error only occurs when it is run from the docker container.

### How to reproduce

Rename .env.local.example to .env.local (this one is in .gitignore) and fill the environment variables.
Then run the docker container with the following commands:

`docker build -t authjs-response-not-conform`
`docker run --rm -p 3000:3000 --env-file .env.local authjs-response-not-conform`

### Expected behavior

No error I guess?

**Comment by balazsorban44** [comment]
Related to https://github.com/nextauthjs/next-auth/pull/11980

Azure does not follow the specification they claim to. Will make sure to address this for Azure AD as well as Entra in the PR

**Comment by conklin20** [comment]
> Related to [#11980](https://github.com/nextauthjs/next-auth/pull/11980)
> 
> In short, Azure does not follow the specification they claim to, so our library needs to add hacks around it. Will make sure to address this for Azure AD as well as Entra in the PR

What about in long? I'm still not able to find the right configuration for my Azure AD B2B provider. Same error as OP.
