### ISSUE TITLE
Error on Next.js 15 about synchronous usage of `headers()`

### ISSUE THREAD

**Issue by IncognitoTGT** [nextauthjs/next-auth#12136]
### Environment

```
  System:
    OS: macOS 15.1
    CPU: (8) arm64 Apple M2
    Memory: 92.91 MB / 24.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.10.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 10.9.0 - /opt/homebrew/bin/npm
    pnpm: 9.4.0 - /opt/homebrew/bin/pnpm
    bun: 1.1.12 - /usr/local/bin/bun
  Browsers:
    Chrome Canary: 132.0.6803.0
    Safari: 18.1
  npmPackages:
    next: 15.0.2-canary.9 => 15.0.2-canary.9 
    next-auth: 5.0.0-beta.18 => 5.0.0-beta.18 
    react: 19.0.0-rc-69d4b800-20241021 => 19.0.0-rc-69d4b800-20241021 
```

### Reproduction URL

https://github.com/spaceness/stardust

### Describe the issue

Next.js 15 introduced breaking changes to some dynamic APIs, such as headers().[ That API must now be accessed asynchronously.](https://nextjs.org/blog/next-15#async-request-apis-breaking-change) Auth.js still accesses them synchronously, which throws multiple warnings when you go to run your app. For example, when you try to access the log in page in the aforementioned application, this is logged:
```
Error: Route "/auth/login" used `headers().get('x-forwarded-proto')`. `headers()` should be awaited before using its value. Learn more: https://nextjs.org/docs/messages/sync-dynamic-apis
    at createHeadersAccessError (webpack://stardust/node_modules/.pnpm/next@15.0.2-canary.9_babel-plugin-react-compiler@0.0.0-experimental-696af53-20240625_react-do_xjqegx5hikrboysqw4mgu6qmje/node_modules/next/dist/server/request/headers.js?f897:311:0)
    at logDedupedError (webpack://stardust/node_modules/.pnpm/next@15.0.2-canary.9_babel-plugin-react-compiler@0.0.0-experimental-696af53-20240625_react-do_xjqegx5hikrboysqw4mgu6qmje/node_modules/next/dist/server/create-deduped-by-callsite-server-error-logger.js?8f8b:74:0)
    at syncIODev (webpack://stardust/node_modules/.pnpm/next@15.0.2-canary.9_babel-plugin-react-compiler@0.0.0-experimental-696af53-20240625_react-do_xjqegx5hikrboysqw4mgu6qmje/node_modules/next/dist/server/request/headers.js?f897:305:0)
    at Promise.get (webpack://stardust/node_modules/.pnpm/next@15.0.2-canary.9_babel-plugin-react-compiler@0.0.0-experimental-696af53-20240625_react-do_xjqegx5hikrboysqw4mgu6qmje/node_modules/next/dist/server/request/headers.js?f897:230:0)
    at getSession (webpack://stardust/node_modules/.pnpm/next-auth@5.0.0-beta.18_next@15.0.2-canary.9_babel-plugin-react-compiler@0.0.0-experimental-6_gqluejmixuq2sejsxgkdkxzlwe/node_modules/next-auth/lib/index.js?85e5:8:0)
    at eval (webpack://stardust/node_modules/.pnpm/next-auth@5.0.0-beta.18_next@15.0.2-canary.9_babel-plugin-react-compiler@0.0.0-experimental-6_gqluejmixuq2sejsxgkdkxzlwe/node_modules/next-auth/lib/index.js?85e5:88:0)
    at auth (webpack://stardust/src/app/auth/login/page.tsx?f6f3:20:27)
   6 |     const url = createActionURL("session", 
   7 |     // @ts-expect-error `x-forwarded-proto` is not nullable, next.js sets it by default
>  8 |     headers.get("x-forwarded-proto"), headers, process.env, config.basePath);
   9 |     const request = new Request(url, {
  10 |         headers: { cookie: headers.get("cookie") ?? "" },
  11 |     });
Error: Route "/auth/login" used `headers().get('x-forwarded-host')`. `headers()` should be awaited before using its value. Learn more: https://nextjs.org/docs/messages/sync-dynamic-apis
    at createHeadersAccessError (webpack://stardust/node_modules/.pnpm/next@15.0.2-canary.9_babel-plugin-react-compiler@0.0.0-experimental-696af53-20240625_react-do_xjqegx5hikrboysqw4mgu6qmje/node_modules/next/dist/server/request/headers.js?f897:311:0)
    at logDedupedError (webpack://stardust/node_modules/.pnpm/next@15.0.2-canary.9_babel-plugin-react-compiler@0.0.0-experimental-696af53-20240625_react-do_xjqegx5hikrboysqw4mgu6qmje/node_modules/next/dist/server/create-deduped-by-callsite-server-error-logger.js?8f8b:74:0)
    at syncIODev (webpack://stardust/node_modules/.pnpm/next@15.0.2-canary.9_babel-plugin-react-compiler@0.0.0-experimental-696af53-20240625_react-do_xjqegx5hikrboysqw4mgu6qmje/node_modules/next/dist/server/request/headers.js?f897:305:0)
    at Promise.get (webpack://stardust/node_modules/.pnpm/next@15.0.2-canary.9_babel-plugin-react-compiler@0.0.0-experimental-696af53-20240625_react-do_xjqegx5hikrboysqw4mgu6qmje/node_modules/next/dist/server/request/headers.js?f897:230:0)
    at createActionURL (webpack://stardust/node_modules/.pnpm/@auth+core@0.31.0/node_modules/@auth/core/lib/utils/env.js?207c:60:0)
    at getSession (webpack://stardust/node_modules/.pnpm/next-auth@5.0.0-beta.18_next@15.0.2-canary.9_babel-plugin-react-compiler@0.0.0-experimental-6_gqluejmixuq2sejsxgkdkxzlwe/node_modules/next-auth/lib/index.js?85e5:6:31)
    at eval (webpack://stardust/node_modules/.pnpm/next-auth@5.0.0-beta.18_next@15.0.2-canary.9_babel-plugin-react-compiler@0.0.0-experimental-6_gqluejmixuq2sejsxgkdkxzlwe/node_modules/next-auth/lib/index.js?85e5:88:0)
    at auth (webpack://stardust/src/app/auth/login/page.tsx?f6f3:20:27)
  58 |     }
  59 |     else {
> 60 |         const detectedHost = headers.get("x-forwarded-host") ?? headers.get("host");
  61 |         const detectedProtocol = headers.get("x-forwarded-proto") ?? protocol ?? "https";
  62 |         const _protocol = detectedProtocol.endsWith(":")
  63 |             ? detectedProtocol
Error: Route "/auth/login" used `headers().get('x-forwarded-proto')`. `headers()` should be awaited before using its value. Learn more: https://nextjs.org/docs/messages/sync-dynamic-apis
    at createHeadersAccessError (webpack://stardust/node_modules/.pnpm/next@15.0.2-canary.9_babel-plugin-react-compiler@0.0.0-experimental-696af53-20240625_react-do_xjqegx5hikrboysqw4mgu6qmje/node_modules/next/dist/server/request/headers.js?f897:311:0)
    at logDedupedError (webpack://stardust/node_modules/.pnpm/next@15.0.2-canary.9_babel-plugin-react-compiler@0.0.0-experimental-696af53-20240625_react-do_xjqegx5hikrboysqw4mgu6qmje/node_modules/next/dist/server/create-deduped-by-callsite-server-error-logger.js?8f8b:74:0)
    at syncIODev (webpack://stardust/node_modules/.pnpm/next@15.0.2-canary.9_babel-plugin-react-compiler@0.0.0-experimental-696af53-20240625_react-do_xjqegx5hikrboysqw4mgu6qmje/node_modules/next/dist/server/request/headers.js?f897:305:0)
    at Promise.get (webpack://stardust/node_modules/.pnpm/next@15.0.2-canary.9_babel-plugin-react-compiler@0.0.0-experimental-696af53-20240625_react-do_xjqegx5hikrboysqw4mgu6qmje/node_modules/next/dist/server/request/headers.js?f897:230:0)
    at createActionURL (webpack://stardust/node_modules/.pnpm/@auth+core@0.31.0/node_modules/@auth/core/lib/utils/env.js?207c:61:0)
    at getSession (webpack://stardust/node_modules/.pnpm/next-auth@5.0.0-beta.18_next@15.0.2-canary.9_babel-plugin-react-compiler@0.0.0-experimental-6_gqluejmixuq2sejsxgkdkxzlwe/node_modules/next-auth/lib/index.js?85e5:6:31)
    at eval (webpack://stardust/node_modules/.pnpm/next-auth@5.0.0-beta.18_next@15.0.2-canary.9_babel-plugin-react-compiler@0.0.0-experimental-6_gqluejmixuq2sejsxgkdkxzlwe/node_modules/next-auth/lib/index.js?85e5:88:0)
    at auth (webpack://stardust/src/app/auth/login/page.tsx?f6f3:20:27)
  59 |     else {
  60 |         const detectedHost = headers.get("x-forwarded-host") ?? headers.get("host");
> 61 |         const detectedProtocol = headers.get("x-forwarded-proto") ?? protocol ?? "https";
  62 |         const _protocol = detectedProtocol.endsWith(":")
  63 |             ? detectedProtocol
  64 |             : detectedProtocol + ":";
Error: Route "/auth/login" used `headers().get('cookie')`. `headers()` should be awaited before using its value. Learn more: https://nextjs.org/docs/messages/sync-dynamic-apis
    at createHeadersAccessError (webpack://stardust/node_modules/.pnpm/next@15.0.2-canary.9_babel-plugin-react-compiler@0.0.0-experimental-696af53-20240625_react-do_xjqegx5hikrboysqw4mgu6qmje/node_modules/next/dist/server/request/headers.js?f897:311:0)
    at logDedupedError (webpack://stardust/node_modules/.pnpm/next@15.0.2-canary.9_babel-plugin-react-compiler@0.0.0-experimental-696af53-20240625_react-do_xjqegx5hikrboysqw4mgu6qmje/node_modules/next/dist/server/create-deduped-by-callsite-server-error-logger.js?8f8b:74:0)
    at syncIODev (webpack://stardust/node_modules/.pnpm/next@15.0.2-canary.9_babel-plugin-react-compiler@0.0.0-experimental-696af53-20240625_react-do_xjqegx5hikrboysqw4mgu6qmje/node_modules/next/dist/server/request/headers.js?f897:305:0)
    at Promise.get (webpack://stardust/node_modules/.pnpm/next@15.0.2-canary.9_babel-plugin-react-compiler@0.0.0-experimental-696af53-20240625_react-do_xjqegx5hikrboysqw4mgu6qmje/node_modules/next/dist/server/request/headers.js?f897:230:0)
    at getSession (webpack://stardust/node_modules/.pnpm/next-auth@5.0.0-beta.18_next@15.0.2-canary.9_babel-plugin-react-compiler@0.0.0-experimental-6_gqluejmixuq2sejsxgkdkxzlwe/node_modules/next-auth/lib/index.js?85e5:10:19)
    at eval (webpack://stardust/node_modules/.pnpm/next-auth@5.0.0-beta.18_next@15.0.2-canary.9_babel-plugin-react-compiler@0.0.0-experimental-6_gqluejmixuq2sejsxgkdkxzlwe/node_modules/next-auth/lib/index.js?85e5:88:0)
    at auth (webpack://stardust/src/app/auth/login/page.tsx?f6f3:20:27)
   8 |     headers.get("x-forwarded-proto"), headers, process.env, config.basePath);
   9 |     const request = new Request(url, {
> 10 |         headers: { cookie: headers.get("cookie") ?? "" },
     |                   ^
  11 |     });
  12 |     return Auth(request, {
  13 |         ...config,
```

### How to reproduce

Setup Auth.js in a Next.js 15 application and use a function such as `auth()`

### Expected behavior

These headers should be accessed with `await` to reflect the changes, and no errors should be logged in the console.

**Comment by sinorrman** [comment]
For me this was resolved when updating to: next-auth@5.0.0-beta.**25**

**Comment by balazsorban44** [comment]
see https://github.com/nextauthjs/next-auth/issues/12136#issuecomment-2444728065

please upgrade

**Comment by ajmalshahabudeen** [comment]
> For me this was resolved when updating to: [next-auth@5.0.0-beta](mailto:next-auth@5.0.0-beta).**25**

Thanks, it worked

**Comment by SarfrazAlame** [comment]
same error i'm getting

**Comment by DieHardd** [comment]
> same error i'm getting

go to package,json change "next-auth": "5.0.0-beta.**23**" to "next-auth": "5.0.0-beta.**25**" then > _npm i_

**Comment by Billmike** [comment]
@balazsorban44 I have this same issue, but I am also utilizing `getServerSession` in my codebase. When I install the `5.0.0-beta.25`, I get the error saying `Module '"next-auth"' has no exported member 'getServerSession'.`. I took a look at the exported modules in the current beta version and `getServerSession` is not included. Is there a replacement for this module in the beta version?

**Comment by balazsorban44** [comment]
yes https://authjs.dev/getting-started/migrating-to-v5#authenticating-server-side

**Comment by tomitrescak** [comment]
I'm stil seeing this with beta.25:

```
auth.ts:326  Server   Error: Route "/course/[name]/[section]" used `headers().get('x-forwarded-proto')`. `headers()` should be awaited before using its value. Learn more: https://nextjs.org/docs/messages/sync-dynamic-apis
    at getServerAuthSession (auth.ts:326:16)
    at Page (page.tsx:40:45)
    at resolveErrorDev (react-server-dom-webpack-client.browser.development.js:1792:1)
    at getOutlinedModel (react-server-dom-webpack-client.browser.development.js:1283:1)
    at parseModelString (react-server-dom-webpack-client.browser.development.js:1423:1)
    at Array.eval (react-server-dom-webpack-client.browser.development.js:2119:1)
    at JSON.parse (<anonymous>)
    at resolveConsoleEntry (react-server-dom-webpack-client.browser.development.js:1955:1)
    at processFullStringRow (react-server-dom-webpack-client.browser.development.js:2095:1)
    at processFullBinaryRow (react-server-dom-webpack-client.browser.development.js:2059:1)
    at progress (react-server-dom-webpack-client.browser.development.js:2262:1)
overrideMethod @ hook.js:608
getServerAuthSession @ auth.ts:326
Page @ page.tsx:40
react-stack-bottom-frame @ react-server-dom-webpack-client.browser.development.js:2446
resolveConsoleEntry @ react-server-dom-webpack-client.browser.development.js:1961
processFullStringRow @ react-server-dom-webpack-client.browser.development.js:2095
processFullBinaryRow @ react-server-dom-webpack-client.browser.development.js:2059
progress @ react-server-dom-webpack-client.browser.development.js:2262
Promise.then
progress @ react-server-dom-webpack-client.browser.development.js:2282
Promise.then
progress @ react-server-dom-webpack-client.browser.development.js:2282
Promise.then
progress @ react-server-dom-webpack-client.browser.development.js:2282
Promise.then
progress @ react-server-dom-webpack-client.browser.development.js:2282
Promise.then
progress @ react-server-dom-webpack-client.browser.development.js:2282
Promise.then
progress @ react-server-dom-webpack-client.browser.development.js:2282
Promise.then
startReadingFromStream @ react-server-dom-webpack-client.browser.development.js:2289
exports.createFromReadableStream @ react-server-dom-webpack-client.browser.development.js:2490
eval @ app-index.tsx:147
(app-pages-browser)/../../node_modules/.pnpm/next@15.1.4_@playwright+test@1.48.1_react-dom@19.0.0_react@19.0.0__react@19.0.0_sass@1.79.4/node_modules/next/dist/client/app-index.js @ main-app.js?v=1736744619139:354
options.factory @ webpack.js?v=1736744619139:717
__webpack_require__ @ webpack.js?v=1736744619139:37
fn @ webpack.js?v=1736744619139:374
eval @ app-next-dev.ts:7
eval @ app-bootstrap.ts:61
loadScriptsInSequence @ app-bootstrap.ts:20
appBootstrap @ app-bootstrap.ts:60
eval @ app-next-dev.ts:6
(app-pages-browser)/../../node_modules/.pnpm/next@15.1.4_@playwright+test@1.48.1_react-dom@19.0.0_react@19.0.0__react@19.0.0_sass@1.79.4/node_modules/next/dist/client/app-next-dev.js @ main-app.js?v=1736744619139:376
options.factory @ webpack.js?v=1736744619139:717
__webpack_require__ @ webpack.js?v=1736744619139:37
__webpack_exec__ @ main-app.js?v=1736744619139:2482
(anonymous) @ main-app.js?v=1736744619139:2483
webpackJsonpCallback @ webpack.js?v=1736744619139:1409
(anonymous) @ main-app.js?v=1736744619139:9Understand this warningAI
auth.ts:326  

Server   Error: Route "/course/[name]/[section]" used `headers().get('cookie')`. `headers()` should be awaited before using its value. Learn more: https://nextjs.org/docs/messages/sync-dynamic-apis
    at getServerAuthSession (auth.ts:326:16)
    at Page (page.tsx:40:45)
    at resolveErrorDev (react-server-dom-webpack-client.browser.development.js:1792:1)
    at getOutlinedModel (react-server-dom-webpack-client.browser.development.js:1283:1)
    at parseModelString (react-server-dom-webpack-client.browser.development.js:1423:1)
    at Array.eval (react-server-dom-webpack-client.browser.development.js:2119:1)
    at JSON.parse (<anonymous>)
```

Any idea where this is blowing up ? This is the code where it blows up:

```ts
export const { auth, handlers, signIn, signOut } = NextAuth({
...
});

export const getServerAuthSession = async (): Promise<Session> => {
  return await auth(); // <- HERE
};
```

**Comment by Arvin7** [comment]
Upgrading to version `5.0.0-beta.25` breaks Reddit login.

**Comment by YoSoyPhil** [comment]
I am using `5.0.0-beta.25` and I am also asked to await headers()

```
Error: Route "/platform/performance" used `headers().get('cookie')`. `headers()` should be awaited before using its value. Learn more: https://nextjs.org/docs/messages/sync-dynamic-apis
    at auth (src/app/platform/performance/page.js:15:28)
  13 |
  14 | export default async function BudgetPage() {
> 15 |   const session = await auth()
```

**Comment by rafael-marques** [comment]
> For me this was resolved when updating to: [next-auth@5.0.0-beta](mailto:next-auth@5.0.0-beta).**25**

Worked for me too. 

Is it safe to use next-auth in beta version for prod ?

**Comment by Nithur-M** [comment]
I am getting this error on nextjs@15

**Comment by thiagonsiq** [comment]
Had this issue, upgrading next-auth to `"next-auth": "5.0.0-beta.25"` solved it.

**Comment by LKL2017** [comment]
I use `auth` function in `middleware.ts` file (next-auth@5.0.0-beta.4), and found:
- when using auth as wrapper, such as `export default auth(req => {...})`,  it throw errors like **Failed to collect page data  for [some path]** in `next build` phase
- when using auth as a helper function, such as `const session = await auth()`, it throw errors like **`headers()` should be awaited before using its value** in `next dev` phase

These problems **SOLVED** after upgrading next-auth to `"next-auth": "5.0.0-beta.25"`, I have always ignored the version issue, consulted a lot of information, and tried many solutions. I think the next-auth documentation needs to clarify more version compatibility issues or precautions. Although they are both v5 versions, I didn't expect the difference to be so big.

Fortunately, the problem was solved in the end, thanks to the community.

**Comment by resulyrt93** [comment]
As I understand next-auth@v4 is not compatible with next.js 15, right? If we want to upgrade our next.js version we need to bump next-auth package to v5 beta version? Is it possible that fix it without upgrade it?

I'm trying to migrate v4 -> v5 for hours and still have some typescript issues about authOptions and middleware :)
