### ISSUE TITLE
Adding Next-Auth with ADB2C Fails

### ISSUE THREAD

**Issue by anandlingaraj** [nextauthjs/next-auth#12341]
### Environment

```

  System:
    OS: macOS 14.6.1
    CPU: (16) arm64 Apple M3 Max
    Memory: 82.34 GB / 128.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.9.0 - /opt/homebrew/bin/node
    Yarn: 1.22.22 - /opt/homebrew/bin/yarn
    npm: 10.8.3 - /opt/homebrew/bin/npm
    pnpm: 9.9.0 - /opt/homebrew/bin/pnpm
    Watchman: 2024.10.28.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 131.0.6778.87
    Edge: 131.0.2903.70
    Safari: 17.6
  npmPackages:
    next: ^15.0.3 => 15.0.3 
    next-auth: ^4.24.10 => 4.24.10 
    react: ^18.3.1 => 18.3.1 

```

### Reproduction URL

https://github.com/anandlingaraj/nexty

### Describe the issue

Unable to add NextAuth with ADB2C. > rev@0.1.0 dev
> next dev

   ▲ Next.js 15.0.3
   - Local:        http://localhost:3000
   - Environments: .env

 ✓ Starting...
 ✓ Ready in 909ms
 ✓ Compiled /middleware in 58ms
 ✓ Compiled (307 modules)
 ⨯ Error [TypeError]: Cannot read properties of undefined (reading 'substring')
    at <unknown> (node_modules/oidc-token-hash/lib/shake256.js:3)
    at (middleware)/./node_modules/oidc-token-hash/lib/shake256.js (.next/server/middleware.js:1500:1)
    at __webpack_require__ (.next/server/edge-runtime-webpack.js:37:33)
    at fn (.next/server/edge-runtime-webpack.js:273:21)
    at (middleware)/./node_modules/oidc-token-hash/lib/index.js (.next/server/middleware.js:1490:1)
    at __webpack_require__ (.next/server/edge-runtime-webpack.js:37:33)
    at fn (.next/server/edge-runtime-webpack.js:273:21)
    at (middleware)/./node_modules/openid-client/lib/client.js (.next/server/middleware.js:1511:1)
 ⨯ Error [TypeError]: Cannot read properties of undefined (reading 'substring')
    at <unknown> (node_modules/oidc-token-hash/lib/shake256.js:3)
    at (middleware)/./node_modules/oidc-token-hash/lib/shake256.js (.next/server/middleware.js:1500:1)
    at __webpack_require__ (.next/server/edge-runtime-webpack.js:37:33)
    at fn (.next/server/edge-runtime-webpack.js:273:21)
    at (middleware)/./node_modules/oidc-token-hash/lib/index.js (.next/server/middleware.js:1490:1)
    at __webpack_require__ (.next/server/edge-runtime-webpack.js:37:33)
    at fn (.next/server/edge-runtime-webpack.js:273:21)
    at (middleware)/./node_modules/openid-client/lib/client.js (.next/server/middleware.js:1511:1)
 ⨯ Error [TypeError]: Cannot read properties of undefined (reading 'substring')
    at <unknown> (node_modules/oidc-token-hash/lib/shake256.js:3)
    at (middleware)/./node_modules/oidc-token-hash/lib/shake256.js (.next/server/middleware.js:1500:1)
    at __webpack_require__ (.next/server/edge-runtime-webpack.js:37:33)
    at fn (.next/server/edge-runtime-webpack.js:273:21)
    at (middleware)/./node_modules/oidc-token-hash/lib/index.js (.next/server/middleware.js:1490:1)
    at __webpack_require__ (.next/server/edge-runtime-webpack.js:37:33)
    at fn (.next/server/edge-runtime-webpack.js:273:21)
    at (middleware)/./node_modules/openid-client/lib/client.js (.next/server/middleware.js:1511:1)
 ○ Compiling /_not-found ...
 ✓ Compiled /_not-found in 1714ms (877 modules)
 GET /login 404 in 3ms
 GET / 404 in 3ms
 GET /_next/static/webpack/a480f6292504d7ae.webpack.hot-update.json 404 in 1539ms
 ⨯ Error [TypeError]: Cannot read properties of undefined (reading 'substring')
    at <unknown> (node_modules/oidc-token-hash/lib/shake256.js:3)
    at (middleware)/./node_modules/oidc-token-hash/lib/shake256.js (.next/server/middleware.js:1500:1)
    at __webpack_require__ (.next/server/edge-runtime-webpack.js:37:33)
    at fn (.next/server/edge-runtime-webpack.js:273:21)
    at (middleware)/./node_modules/oidc-token-hash/lib/index.js (.next/server/middleware.js:1490:1)
    at __webpack_require__ (.next/server/edge-runtime-webpack.js:37:33)
    at fn (.next/server/edge-runtime-webpack.js:273:21)
    at (middleware)/./node_modules/openid-client/lib/client.js (.next/server/middleware.js:1511:1)
 ✓ Compiled in 199ms (845 modules)
 GET / 404 in 1ms
 ⚠ Fast Refresh had to perform a full reload. Read more: https://nextjs.org/docs/messages/fast-refresh-reload
 GET /_next/static/webpack/a480f6292504d7ae.webpack.hot-update.json 404 in 225ms
 ⨯ Error [TypeError]: Cannot read properties of undefined (reading 'substring')
    at <unknown> (node_modules/oidc-token-hash/lib/shake256.js:3)
    at (middleware)/./node_modules/oidc-token-hash/lib/shake256.js (.next/server/middleware.js:1500:1)
    at __webpack_require__ (.next/server/edge-runtime-webpack.js:37:33)
    at fn (.next/server/edge-runtime-webpack.js:273:21)
    at (middleware)/./node_modules/oidc-token-hash/lib/index.js (.next/server/middleware.js:1490:1)
    at __webpack_require__ (.next/server/edge-runtime-webpack.js:37:33)
    at fn (.next/server/edge-runtime-webpack.js:273:21)
    at (middleware)/./node_modules/openid-client/lib/client.js (.next/server/middleware.js:1511:1)
 GET /login 404 in 1ms
 ⨯ Error [TypeError]: Cannot read properties of undefined (reading 'substring')
    at <unknown> (node_modules/oidc-token-hash/lib/shake256.js:3)
    at (middleware)/./node_modules/oidc-token-hash/lib/shake256.js (.next/server/middleware.js:1500:1)
    at __webpack_require__ (.next/server/edge-runtime-webpack.js:37:33)
    at fn (.next/server/edge-runtime-webpack.js:273:21)
    at (middleware)/./node_modules/oidc-token-hash/lib/index.js (.next/server/middleware.js:1490:1)
    at __webpack_require__ (.next/server/edge-runtime-webpack.js:37:33)
    at fn (.next/server/edge-runtime-webpack.js:273:21)
    at (middleware)/./node_modules/openid-client/lib/client.js (.next/server/middleware.js:1511:1)
 GET /login 404 in 6ms
 ⨯ Error [TypeError]: Cannot read properties of undefined (reading 'substring')
    at <unknown> (node_modules/oidc-token-hash/lib/shake256.js:3)
    at (middleware)/./node_modules/oidc-token-hash/lib/shake256.js (.next/server/middleware.js:1500:1)
    at __webpack_require__ (.next/server/edge-runtime-webpack.js:37:33)
    at fn (.next/server/edge-runtime-webpack.js:273:21)
    at (middleware)/./node_modules/oidc-token-hash/lib/index.js (.next/server/middleware.js:1490:1)
    at __webpack_require__ (.next/server/edge-runtime-webpack.js:37:33)
    at fn (.next/server/edge-runtime-webpack.js:273:21)
    at (middleware)/./node_modules/openid-client/lib/client.js (.next/server/middleware.js:1511:1)
 GET /login 404 in 0ms
 ⨯ Error [TypeError]: Cannot read properties of undefined (reading 'substring')
    at <unknown> (node_modules/oidc-token-hash/lib/shake256.js:3)
    at (middleware)/./node_modules/oidc-token-hash/lib/shake256.js (.next/server/middleware.js:1500:1)
    at __webpack_require__ (.next/server/edge-runtime-webpack.js:37:33)
    at fn (.next/server/edge-runtime-webpack.js:273:21)
    at (middleware)/./node_modules/oidc-token-hash/lib/index.js (.next/server/middleware.js:1490:1)
    at __webpack_require__ (.next/server/edge-runtime-webpack.js:37:33)
    at fn (.next/server/edge-runtime-webpack.js:273:21)
    at (middleware)/./node_modules/openid-client/lib/client.js (.next/server/middleware.js:1511:1)
 GET /login 404 in 0ms
 ⨯ Error [TypeError]: Cannot read properties of undefined (reading 'substring')
    at <unknown> (node_modules/oidc-token-hash/lib/shake256.js:3)
    at (middleware)/./node_modules/oidc-token-hash/lib/shake256.js (.next/server/middleware.js:1500:1)
    at __webpack_require__ (.next/server/edge-runtime-webpack.js:37:33)
    at fn (.next/server/edge-runtime-webpack.js:273:21)
    at (middleware)/./node_modules/oidc-token-hash/lib/index.js (.next/server/middleware.js:1490:1)
    at __webpack_require__ (.next/server/edge-runtime-webpack.js:37:33)
    at fn (.next/server/edge-runtime-webpack.js:273:21)
    at (middleware)/./node_modules/openid-client/lib/client.js (.next/server/middleware.js:1511:1)
 GET /login 404 in 0ms
 ⨯ Error [TypeError]: Cannot read properties of undefined (reading 'substring')
    at <unknown> (node_modules/oidc-token-hash/lib/shake256.js:3)
    at (middleware)/./node_modules/oidc-token-hash/lib/shake256.js (.next/server/middleware.js:1500:1)
    at __webpack_require__ (.next/server/edge-runtime-webpack.js:37:33)
    at fn (.next/server/edge-runtime-webpack.js:273:21)
    at (middleware)/./node_modules/oidc-token-hash/lib/index.js (.next/server/middleware.js:1490:1)
    at __webpack_require__ (.next/server/edge-runtime-webpack.js:37:33)
    at fn (.next/server/edge-runtime-webpack.js:273:21)
    at (middleware)/./node_modules/openid-client/lib/client.js (.next/server/middleware.js:1511:1)
 GET /login 404 in 1ms
 ⨯ Error [TypeError]: Cannot read properties of undefined (reading 'substring')
    at <unknown> (node_modules/oidc-token-hash/lib/shake256.js:3)
    at (middleware)/./node_modules/oidc-token-hash/lib/shake256.js (.next/server/middleware.js:1500:1)
    at __webpack_require__ (.next/server/edge-runtime-webpack.js:37:33)
    at fn (.next/server/edge-runtime-webpack.js:273:21)
    at (middleware)/./node_modules/oidc-token-hash/lib/index.js (.next/server/middleware.js:1490:1)
    at __webpack_require__ (.next/server/edge-runtime-webpack.js:37:33)
    at fn (.next/server/edge-runtime-webpack.js:273:21)
    at (middleware)/./node_modules/openid-client/lib/client.js (.next/server/middleware.js:1511:1)
 GET /login 404 in 1ms
 ⨯ Error [TypeError]: Cannot read properties of undefined (reading 'substring')
    at <unknown> (node_modules/oidc-token-hash/lib/shake256.js:3)
    at (middleware)/./node_modules/oidc-token-hash/lib/shake256.js (.next/server/middleware.js:1500:1)
    at __webpack_require__ (.next/server/edge-runtime-webpack.js:37:33)
    at fn (.next/server/edge-runtime-webpack.js:273:21)
    at (middleware)/./node_modules/oidc-token-hash/lib/index.js (.next/server/middleware.js:1490:1)
    at __webpack_require__ (.next/server/edge-runtime-webpack.js:37:33)
    at fn (.next/server/edge-runtime-webpack.js:273:21)
    at (middleware)/./node_modules/openid-client/lib/client.js (.next/server/middleware.js:1511:1)
 GET /login 404 in 1ms
 ⨯ Error [TypeError]: Cannot read properties of undefined (reading 'substring')
    at <unknown> (node_modules/oidc-token-hash/lib/shake256.js:3)
    at (middleware)/./node_modules/oidc-token-hash/lib/shake256.js (.next/server/middleware.js:1500:1)
    at __webpack_require__ (.next/server/edge-runtime-webpack.js:37:33)
    at fn (.next/server/edge-runtime-webpack.js:273:21)
    at (middleware)/./node_modules/oidc-token-hash/lib/index.js (.next/server/middleware.js:1490:1)
    at __webpack_require__ (.next/server/edge-runtime-webpack.js:37:33)
    at fn (.next/server/edge-runtime-webpack.js:273:21)
    at (middleware)/./node_modules/openid-client/lib/client.js (.next/server/middleware.js:1511:1)
 GET /login 404 in 0ms

### How to reproduce

Just Cant start the app at all after adding authentication.

### Expected behavior

Expected to redirect to login page.

**Comment by anandlingaraj** [comment]
I get TypeError: Cannot read properties of undefined (reading 'substring')
    at <unknown> (file:///Users/anandl/projects/chatty/rev/node_modules/oidc-token-hash/lib/shake256.js:3)
    at eval (webpack-internal:///(middleware)/./node_modules/oidc-token-hash/lib/shake256.js:3:40)
    at (middleware)/./node_modules/oidc-token-hash/lib/shake256.js (file:///Users/anandl/projects/chatty/rev/.next/server/middleware.js:1500:1)
    at __webpack_require__ (file:///Users/anandl/projects/chatty/rev/.next/server/edge-runtime-webpack.js:37:33)
    at fn (file:///Users/anandl/projects/chatty/rev/.next/server/edge-runtime-webpack.js:273:21)
    at eval (webpack-internal:///(middleware)/./node_modules/oidc-token-hash/lib/index.js:6:18)
    at (middleware)/./node_modules/oidc-token-hash/lib/index.js (file:///Users/anandl/projects/chatty/rev/.next/server/middleware.js:1490:1)
    at __webpack_require__ (file:///Users/anandl/projects/chatty/rev/.next/server/edge-runtime-webpack.js:37:33)
    at fn (file:///Users/anandl/projects/chatty/rev/.next/server/edge-runtime-webpack.js:273:21)
    at eval (webpack-internal:///(middleware)/./node_modules/openid-client/lib/client.js:11:19)
    at (middleware)/./node_modules/openid-client/lib/client.js (file:///Users/anandl/projects/chatty/rev/.next/server/middleware.js:1511:1)

**Comment by vikanirav** [comment]
I am also getting same error

**Comment by anandlingaraj** [comment]
I solved it. by
// components/providers/SessionProvider.tsx
'use client';

import { SessionProvider as NextAuthSessionProvider } from "next-auth/react";

export function SessionProvider({ children }: { children: React.ReactNode }) {
    return <NextAuthSessionProvider>{children}</NextAuthSessionProvider>;
}
----------------------------------------------------
// app/api/auth/[...nextauth]/route.ts
import NextAuth from "next-auth"
import { authOptions } from "@/lib/auth/auth-options"


// @ts-ignore
const handler = NextAuth(authOptions)
export { handler as GET, handler as POST }
----------------------------------------------------

// app/lib/auth-options.ts

import { jwtDecode } from "jwt-decode";
import { DefaultSession } from "next-auth";
import AzureADB2C from "next-auth/providers/azure-ad-b2c"
import CredentialsProvider from "next-auth/providers/credentials"
import { createLog } from "../logger";
import { prisma } from "../prisma";

const B2C_TENANT = process.env.AZURE_AD_B2C_TENANT!;
const CLIENT_ID = process.env.AZURE_AD_B2C_CLIENT_ID!;
const POLICY_NAME = process.env.AZURE_AD_B2C_POLICY_NAME!;

declare module "next-auth" {
    interface Session {
        accessToken?: string;
        idToken?: string;
        user: {
            id: string;
            name?: string | null;
            email?: string | null;
            image?: string | null;
            roles?: string[];
        } & DefaultSession["user"];
    }

    interface User {
        accessToken?: string;
        idToken?: string;
        roles?: string[];
    }
}
export const authOptions = {
    providers: [
        CredentialsProvider({
            id: "azure-ad-b2c-ropc",
            name: "Credentials",
            credentials: {
                email: { label: "Email", type: "text" },
                password: { label: "Password", type: "password" }
            },
            async authorize(credentials) {
                try {
                    console.log("Starting ROPC authorization...");
                    const tokenEndpoint = `https://${B2C_TENANT}.b2clogin.com/${B2C_TENANT}.onmicrosoft.com/${POLICY_NAME}/oauth2/v2.0/token`;
                    console.log("Token endpoint:", tokenEndpoint);

                    const bodyParams = {
                        grant_type: 'password',
                        client_id: CLIENT_ID,
                        scope: `${CLIENT_ID} offline_access openid`,
                        username: credentials?.email || '',
                        password: credentials?.password || '',
                        response_type: 'token id_token',
                    };
                    console.log("Request body params:", bodyParams);


                    const response = await fetch(tokenEndpoint, {
                        method: 'POST',
                        headers: {
                            'Content-Type': 'application/x-www-form-urlencoded',
                        },
                        body: new URLSearchParams(bodyParams).toString(),
                    });

                    // Log the raw response for debugging
                    const responseText = await response.text();
                    console.log('Raw response:', responseText);
                    console.log("Raw response headers:", Object.fromEntries(response.headers.entries()));
                    console.log("Raw response body:", responseText);

                    let data;
                    try {
                        data = JSON.parse(responseText);
                    } catch (e) {
                        console.error('Failed to parse response:', e);
                        throw new Error(`Authentication failed: ${responseText}`);
                    }

                    if (!response.ok) {
                        console.error('Auth error:', data);
                        throw new Error(data.error_description || 'Authentication failed');
                    }
                    const decodedIDToken = jwtDecode(data.id_token) as any;
                    const decodedAccessToken = jwtDecode(data.access_token) as any;
                
                    return {
                        id: decodedIDToken.oid || decodedAccessToken.oid,
                        email: credentials?.email,
                        name: decodedIDToken.name,
                        accessToken: data.access_token,
                        firstName: decodedIDToken.given_name,
                        lastName: decodedIDToken.family_name,
                        idToken: data.id_token,
                        roles: decodedIDToken.roles || [],
                    };
                } catch (error) {
                    console.error('ROPC authentication error:', error);
                    return null;
                }
            }
        }),
        AzureADB2C({
            clientId: process.env.AZURE_AD_B2C_CLIENT_ID!,
            clientSecret: process.env.AZURE_AD_B2C_CLIENT_SECRET!,
            tenantId: process.env.AZURE_AD_B2C_TENANT!,
        })
    ],
    callbacks: {
        async jwt({ token, user, profile }) {
            if (user) {
                token.accessToken = user.accessToken;
                token.idToken = user.idToken;
                token.roles = user.roles;
                token.name = user.name;
                token.id = user.id;
                console.log('Token ID:>>>>>>>>>>>>>>>>>>>', token.id);
                try {
                    const dbUser = await prisma.user.upsert({
                        where: { id: user.id },
                        update: {
                            email: user.email || "",
                            name: user.name || ""
                        },
                        create: {
                            id: user.id,
                            email: user.email || "",
                            name: user.name || ""
                        }
                    });

                    // Then create log
                    await createLog({
                        level: 'info',
                        action: 'USER_LOGIN',
                        details: 'User logged in successfully',
                        userId: dbUser.id,
                        resource: 'auth',
                        metadata: { email: user.email || "" }
                    });

                } catch (error) {
                    console.error('Error creating user/log:', error);
                }
            }
            return token;
        },
        async session({ session, token }) {
            session.accessToken = token.accessToken;
            session.idToken = token.idToken;
            session.user.roles = token.roles as string[]
            if (session.user && token.id) {
                session.user.id = token.id as string;
            }
            console.log('session user ID:', session.user.id);
            return session;
        }
    },
    events: {
        async signOut({session, token}) {
            session.accessToken = "";
            session.idToken = "";
            session.user.roles = "";
            return session;
        },
    }
}
