### ISSUE TITLE
InvalidCheck: pkceCodeVerifier value could not be parsed. (Oath Provider Error)

### ISSUE THREAD

**Issue by Lucifer472** [nextauthjs/next-auth#12345]
### Provider type

GitHub, Google

### Environment

  System:
    OS: macOS 15.1.1
    CPU: (8) arm64 Apple M2
    Memory: 305.41 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.1.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 10.8.3 - /opt/homebrew/bin/npm
    bun: 1.1.38 - /opt/homebrew/bin/bun
  Browsers:
    Chrome: 131.0.6778.108
    Safari: 18.1.1
  npmPackages:
    @auth/prisma-adapter: ^2.7.4 => 2.7.4 
    next: 15.0.3 => 15.0.3 
    next-auth: ^5.0.0-beta.25 => 5.0.0-beta.25 
    react: 19.0.0-rc-66855b96-20241106 => 19.0.0-rc-66855b96-20241106 

### Reproduction URL

https://github.com/Lucifer472/slack-clone

### Describe the issue

[auth][error] InvalidCheck: pkceCodeVerifier value could not be parsed. Read more at https://errors.authjs.dev#invalidcheck
    at parseCookie (/Users/truepubmedia/Desktop/sites/slack-clone/.next/server/chunks/e044d_@auth_core_d1f52f._.js:3030:15)
    at Object.use (/Users/truepubmedia/Desktop/sites/slack-clone/.next/server/chunks/e044d_@auth_core_d1f52f._.js:3058:30)
    at handleOAuth (/Users/truepubmedia/Desktop/sites/slack-clone/.next/server/chunks/e044d_@auth_core_d1f52f._.js:3288:247)
    at async Module.callback (/Users/truepubmedia/Desktop/sites/slack-clone/.next/server/chunks/e044d_@auth_core_d1f52f._.js:3782:41)
    at async AuthInternal (/Users/truepubmedia/Desktop/sites/slack-clone/.next/server/chunks/e044d_@auth_core_d1f52f._.js:4859:24)
    at async Auth (/Users/truepubmedia/Desktop/sites/slack-clone/.next/server/chunks/e044d_@auth_core_d1f52f._.js:5120:34)
    at async AppRouteRouteModule.do (/Users/truepubmedia/Desktop/sites/slack-clone/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:10:33313)
    at async AppRouteRouteModule.handle (/Users/truepubmedia/Desktop/sites/slack-clone/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:10:40382)
    at async doRender (/Users/truepubmedia/Desktop/sites/slack-clone/node_modules/next/dist/server/base-server.js:1455:42)
    at async responseGenerator (/Users/truepubmedia/Desktop/sites/slack-clone/node_modules/next/dist/server/base-server.js:1814:28)
    at async DevServer.renderToResponseWithComponentsImpl (/Users/truepubmedia/Desktop/sites/slack-clone/node_modules/next/dist/server/base-server.js:1824:28)
    at async DevServer.renderPageComponent (/Users/truepubmedia/Desktop/sites/slack-clone/node_modules/next/dist/server/base-server.js:2240:24)
    at async DevServer.renderToResponseImpl (/Users/truepubmedia/Desktop/sites/slack-clone/node_modules/next/dist/server/base-server.js:2278:32)
    at async DevServer.pipeImpl (/Users/truepubmedia/Desktop/sites/slack-clone/node_modules/next/dist/server/base-server.js:960:25)
    at async NextNodeServer.handleCatchallRenderRequest (/Users/truepubmedia/Desktop/sites/slack-clone/node_modules/next/dist/server/next-server.js:281:17)
    at async DevServer.handleRequestImpl (/Users/truepubmedia/Desktop/sites/slack-clone/node_modules/next/dist/server/base-server.js:853:17)
    at async /Users/truepubmedia/Desktop/sites/slack-clone/node_modules/next/dist/server/dev/next-dev-server.js:373:20
    at async Span.traceAsyncFn (/Users/truepubmedia/Desktop/sites/slack-clone/node_modules/next/dist/trace/trace.js:153:20)
    at async DevServer.handleRequest (/Users/truepubmedia/Desktop/sites/slack-clone/node_modules/next/dist/server/dev/next-dev-server.js:370:24)
    at async invokeRender (/Users/truepubmedia/Desktop/sites/slack-clone/node_modules/next/dist/server/lib/router-server.js:183:21)
    at async handleRequest (/Users/truepubmedia/Desktop/sites/slack-clone/node_modules/next/dist/server/lib/router-server.js:360:24)
    at async requestHandlerImpl (/Users/truepubmedia/Desktop/sites/slack-clone/node_modules/next/dist/server/lib/router-server.js:384:13)
    at async Server.requestListener (/Users/truepubmedia/Desktop/sites/slack-clone/node_modules/next/dist/server/lib/start-server.js:142:13)
    
Credentials Provider works like charm without any issues but Oath Providers are not working all the give the same error i tried different ways to sort it out but nothing works. i think the issue is with latest version on next js and prisma because i tried going to past version but same issue also the same config works perfectly fine in next js 14 i tried that 

### How to reproduce

Just clone the repo and added github client id and secret in env file also connect a database

### Expected behavior

Github provider should redirect to authorized page then logged in to App.

**Comment by OtisTemler** [comment]
Same issue here, using Next.js 15.1.0 & React 19.

Sometimes works, sometimes doesn't with the above stated error.

**Comment by junheeLee96** [comment]
I also encountered the same error. In my case, I used Chrome's incognito mode to log in and found that the error disappeared.

**Comment by rubinpaudel** [comment]
I have the same issue with Notion, using these versions:
```
"next": "15.1.2",
"next-auth": "5.0.0-beta.25",
"react": "^19.0.0",
```

**Comment by Harisene** [comment]
I have the same issue. I get this error when I try to log in using google provider. 

```
[31m[auth][error][0m InvalidCheck: pkceCodeVerifier value could not be parsed. Read more at https://errors.authjs.dev#invalidcheck

20:24:42.971
at i8 (/var/task/.next/server/chunks/555.js:368:26741)
    at Object.use (/var/task/.next/server/chunks/555.js:368:27149)
    at os (/var/task/.next/server/chunks/555.js:368:33213)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async ob (/var/task/.next/server/chunks/555.js:368:40282)
    at async oR (/var/task/.next/server/chunks/555.js:368:51845)
    at async oC (/var/task/.next/server/chunks/555.js:368:56536)
    at async te.do (/var/task/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:18:17826)
    at async te.handle (/var/task/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:18:22492)
    at async eB (/var/task/node_modules/next/dist/compiled/next-server/server.runtime.prod.js:2871:21083)

```

I use,
```
"react": "19.0.0-rc-66855b96-20241106",
"next": "15.0.3",
"next-auth": "^5.0.0-beta.25"
```

**Comment by suitux** [comment]
Same here

**Comment by Lucifer472** [comment]
well downgraded to next 14.2.20 and next auth beta to 5.0.0-beta.20 and everything if fixed and also clear your cookies as well.

**Comment by Ferdinand737** [comment]
> well downgraded to next 14.2.20 and next auth beta to 5.0.0-beta.20 and everything if fixed and also clear your cookies as well.

Doing this did not solve the issue for me.

**Comment by Harisene** [comment]
> > well downgraded to next 14.2.20 and next auth beta to 5.0.0-beta.20 and everything if fixed and also clear your cookies as well.
> 
> Doing this did not solve the issue for me.

Same here. Issue still exists

**Comment by wouteth** [comment]
Also experiencing the same issue. It occurs randomly on sign in. Some sign-ins work, some throw this exact error.

**Comment by stephan-noel** [comment]
Same happening for me using the Cognito provider.  Works most of the time but getting these errors in the logs and some users saying they can't log in.  Please let me know if there's any other info I can provide to help out.

```
"next-auth": "5.0.0-beta.20"
"next": "14.2.22",
"react": "18.3.1"
```

**Comment by lucassalicanorc** [comment]
I got this error today, and I don't know if it helps, but for me, the reason was that I was subscribing to the pkceCodeVerifier cookie, and the SameSite attribute was set to None. So, I followed the documentation and set it to Lax, and it worked for me.

**Comment by arxkdev** [comment]
This error is happening to me, React 19 & Next.js 15.. Can we get an update on this?

**Comment by pauleway** [comment]
Also happening to me, also on Next.js 15.

**Comment by sameerxanand** [comment]
Just happened to me as well. React 19, Next.js 15.2.0-canary.19 and next-auth 5.0.0-beta.25.

**Comment by mutgarth** [comment]
It's the same to me. I was using next-auth 5.0.0-beta-25 and even after downgrading to next-aht 5.0.0-beta-20 the issues still exist.

**Comment by franceschiniandrea** [comment]
The issue still exists - as a temporary fix, clearing your cookies usually does the trick. In our case it is sporadic but still happens for some users. But this issue should be reopened

**Comment by Chetan-KK** [comment]
why is this issue closed, it's still not get solved i'm also facing this issue.

**Comment by crazytweeks** [comment]
Am having same issue with latest version. Github auth works, Google auth doesnt

**Comment by mutgarth** [comment]
Hi all,

I fixed it, at least for my use case.

My system uses auth.js only to handle stuff like JWT, callbacks, etc. I am using Google provider to get the access_token and then send it to my backend auth service (where JWT is generated and sent back to the front end).

The callback URL in my backend is configured to send the Google info (after a successful login) to a "www" subdomain. It is important to note here that the callback URL must be the same on Google API console. 

The problem arises when user tries to login using the non-www subdomain, which is not configured as callback in my backend.

To fix the error I routed all non-www traffic to a www subdomain in my Nginx web server.

**Comment by koyo-snow** [comment]
I met this error in the Auth.js turorial.
https://authjs.dev/getting-started/authentication/oauth?framework=next-js

This is my solution.

I set clientId and clientSecret like this.
https://authjs.dev/guides/environment-variables?framework=next-js

---------------
import NextAuth from "next-auth"
import Google from "next-auth/providers/google"
 
export const { handlers, auth } = NextAuth({
  providers: [
    Google({
      clientId: process.env.AUTH_WEBAPP_GOOGLE_CLIENT_ID,
      clientSecret: process.env.AUTH_WEBAPP_GOOGLE_CLIENT_SECRET,
    }),
  ],
})
---------------

And add localhost in OAuth 2.0 in Google Console,
・Authorized JavaScript origins
→http://localhost:3000
・Authorized redirect URIs
→http://localhost:3000/api/auth/callback/google

**Comment by koyo-snow** [comment]
I didn't know the difference between latest version and next.auth.
Sorry.

**Comment by wasimsandhu** [comment]
I was running into this error with the Google provider after setting `AUTH_REDIRECT_PROXY_URL` to my staging deployment URL (e.g. `https://vercel-staging-deployment.app/api/auth`).

Long story short, I had set `AUTH_REDIRECT_PROXY_URL` in my preview and production environments, but NOT in the staging environment (e.g. my stable deployment).

This was my fault; the docs for ["Securing a preview deployment"](https://authjs.dev/getting-started/deployment#securing-a-preview-deployment) clearly state:

> **In both the preview and stable environment,** set AUTH_REDIRECT_PROXY_URL to that stable deployment URL...

**Comment by zuluaica18** [comment]
In my case, it happened because:
1. The user would open several tabs to log in.
2. 15 minutes would pass without entering credentials.
3. The browser would block cookies.

For cases 1 and 2, I did the following to resolve it with a retry.

1. In config
```
pages: {
    signIn: "/api/custom/auth/signin",
    error: "/api/custom/auth/error",
  }
```

2. In /api/custom/auth/signin/route.ts
```
import { signIn } from "...";
import { NextRequest } from "next/server";

export async function GET(request: NextRequest) {
  const callbackUrl = request.nextUrl.searchParams.get('callbackUrl') ?? request.nextUrl.origin;
  return signIn("keycloak", { redirectTo: callbackUrl });
}
```

3. In /api/custom/auth/error/route.ts
```
import { NextRequest, NextResponse } from "next/server";

function setCookie(response: NextResponse, cookiePrefix: string, maxAge: number) {
  response.cookies.set(
    `${cookiePrefix}authjs.signin-attempt`,
    `true`,
    {
      httpOnly: true,
      sameSite: "lax",
      path: "/",
      secure: cookiePrefix === "__Secure-",
      maxAge: maxAge,
    }
  );
}
export async function GET(request: NextRequest) {
  const cookiePrefix = request.nextUrl.protocol === "https:" ? "__Secure-" : "";
  const callbackUrlCookie = request.cookies.get(`${cookiePrefix}authjs.callback-url`)?.value ?? "";
  const signinAttemptCookie = request.cookies.get(`${cookiePrefix}authjs.signin-attempt`)?.value ?? "";
  const error = request.nextUrl.searchParams.get('error') ?? "Configuration";
  if (error === "Configuration" && signinAttemptCookie !== "true") {
    const signInUrl = new URL("/api/custom/auth/signin", request.nextUrl.origin);
    signInUrl.searchParams.set("callbackUrl", callbackUrlCookie);
    const response = NextResponse.redirect(signInUrl);
    setCookie(response, cookiePrefix, 5 * 60); // 5 minutes
    return response;
  }
  const errorUrl = new URL("/auth/error", request.nextUrl.origin);
  errorUrl.searchParams.set("error", error);
  const response = NextResponse.redirect(errorUrl);
  setCookie(response, cookiePrefix, 0); // 0 minutes
  return response;
}
```

Keep in mind that you'll need to create your own error handling page: /auth/error/page.tsx

**Comment by Lucifer472** [comment]
This Error still happens in google Oauth client i have no idea what to do i tried pretty much everything

**Comment by AmazingTurtle** [comment]
I did some research. It looks like:

1. ` ["pkce"]` is the default default `checks` as part of `normalizeOAuth`
https://github.com/nextauthjs/next-auth/blob/12665208ff57bd9be061e7c770c04e476f7ca059/packages/core/src/lib/utils/providers.ts#L92

2. oauth providers try to invoke the pkce verifier
https://github.com/nextauthjs/next-auth/blob/262db2561e83548961aa2de009f7cb0f85acad4b/packages/core/src/lib/actions/callback/oauth/callback.ts#L152

3. the verifier returns, if the `check` (pkce) was not defined in the `checks` array
https://github.com/nextauthjs/next-auth/blob/12665208ff57bd9be061e7c770c04e476f7ca059/packages/core/src/lib/actions/callback/oauth/checks.ts#L99

4. a variety of oauth providers does _not_ explicitly define an `checks` array - the default as per 1.) will be used

see the [KeycloakProvider](https://github.com/nextauthjs/next-auth/blob/next-auth%405.0.0-beta.27/packages/core/src/providers/keycloak.ts#L104-L110) or the [GoogleProvider](https://github.com/nextauthjs/next-auth/blob/12665208ff57bd9be061e7c770c04e476f7ca059/packages/core/src/providers/google.ts#L142-L151) for example

To me, the solution is simple:

![Image](https://github.com/user-attachments/assets/41a06f52-d570-4ba7-970a-41f537d34970)

I explicitly define `checks` in my provider. I am experimenting with `state` and `nonce`. That works for keycloak in my situation. I haven't observed any issue yet. I hope this helps fellows who faced the same issue :)

**Comment by ds5105119** [comment]
I’m using Keycloak as a provider and encountered the same issue. This might not help those who aren’t using Keycloak, but if you are, go to the Keycloak client’s Advanced Settings and change the Proof Key for Code Exchange Code Challenge Method to `S256` (recommended)

![Image](https://github.com/user-attachments/assets/d5eb8a8b-b406-4d14-bfe7-c5553c9035b9)

**Comment by devperson12345** [comment]
I am getting this exact same issue, but only when I change the host I'm running under. Using localhost, everything works perfectly with a Keycloak identity provider. Whenever I configure my dev environment to use tenant.myapp.local, this is when the pkceCodeVerifier hits.

I can see the appropriate cookie being set and passed back.

**Comment by soko-xyz** [comment]
I did experience the same problem with "next-auth": "5.0.0-beta.29". I could fix it by using cy.session wrapping cy.origin(keycloakUrl like https://docs.cypress.io/api/commands/origin#SSO-login-custom-command suggested!

**Comment by paaax** [comment]
Ensure there are no cross-origin issues by setting NEXTAUTH_URL in your environment variables to exactly match the domain you're using in the browser (including protocol and subdomain). Mismatches can break authentication flows like PKCE.

If your NEXTAUTH_URL is https://staging.your-domain.com then calling from...
https://staging.your-domain.com -> successful
https://www.your-domain.com -> unsuccessful

**Comment by khuezy** [comment]
Good advice @paaax . I have my callbacks to the correct domains but I was still getting this error only on MacOS Brave (no issues on Windows.) What worked for me was adding the "." prefix to the pkce cookie domain, eg

```
cookies: {
	pkceCodeVerifier: {
	name: useSecureCookies ? '__Secure-authjs.pkce.code_verifier': 'authjs.pkce.code_verifier',
	options: {
		httpOnly: useSecureCookies,
		sameSite: 'lax',
		path: '/',
		domain: useSecureCookies ? '.example.com': undefined,
		secure: useSecureCookies,
	},
}
```
Hope that helps anyone w/ this issue.

**Comment by jonas-is-coding** [comment]
This looks like a type boundary problem rather than a runtime logic issue. The most reliable fix is to make the input/output contract explicit at the entry point, validate unknown data before it reaches typed code, and avoid widening to `any` in shared paths. If the failure appeared after an upgrade, pinning to the previous known-good version while narrowing the contract usually removes the regression without introducing hidden behavior changes.
