### ISSUE TITLE
yarn2: Can't resolve 'process' 

### ISSUE THREAD

**Issue by JakubKoralewski** [nextauthjs/next-auth#1306]
**Describe the bug**
Can't build the project with yarn version 2 (2.4.0-git.20210210.hash-cb8c8d68) Windows

**Steps to reproduce**
You can try on the example repo or [my open-source wip project](https://github.com/JakubKoralewski/lets-watch-it-together-private)
1. `npm i -g yarn`
2. `yarn set version from sources`
3. `yarn install`
4. `yarn next`

**Screenshots or error logs**
```
$ yarn next
Loaded env from D:\projects\2020-2021uam\se\lets-watch-it-together-regular\.env
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
warn  - React 17.0.1 or newer will be required to leverage all of the upcoming features in Next.js 11. Read more: https://err.sh/next.js/react-version
> [PWA] PWA support is disabled
error - .yarn/$$virtual/next-auth-virtual-c1f7f2724b/0/cache/next-auth-npm-3.4.1-20f5d78bcb-3f4ce0728e.zip/node_modules/next-auth/dist/client/index.js:34:0
Module not found: Can't resolve 'process'
null
error - .yarn/$$virtual/next-auth-virtual-c1f7f2724b/0/cache/next-auth-npm-3.4.1-20f5d78bcb-3f4ce0728e.zip/node_modules/next-auth/dist/client/index.js:34:0
Module not found: Can't resolve 'process'
null
```

Same on WSL:
```
$ yarn next
Loaded env from /mnt/d/projects/2020-2021uam/se/lets-watch-it-together-regular/.env
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
warn  - React 17.0.1 or newer will be required to leverage all of the upcoming features in Next.js 11. Read more: https://err.sh/next.js/react-version
> [PWA] PWA support is disabled
info  - Using external babel configuration from /mnt/d/projects/2020-2021uam/se/lets-watch-it-together-regular/.babelrc
error - .yarn/$$virtual/next-auth-virtual-c1f7f2724b/0/cache/next-auth-npm-3.4.1-20f5d78bcb-3f4ce0728e.zip/node_modules/next-auth/dist/client/index.js:34:0
Module not found: Can't resolve 'process'
null
error - .yarn/$$virtual/next-auth-virtual-c1f7f2724b/0/cache/next-auth-npm-3.4.1-20f5d78bcb-3f4ce0728e.zip/node_modules/next-auth/dist/client/index.js:34:0
Module not found: Can't resolve 'process'
null
error - .yarn/$$virtual/next-auth-virtual-c1f7f2724b/0/cache/next-auth-npm-3.4.1-20f5d78bcb-3f4ce0728e.zip/node_modules/next-auth/dist/client/index.js:34:0
Module not found: Can't resolve 'process'
null
```

**Additional context**
Second line is the 34th line in `dist/client/index.js`
```js
var __NEXTAUTH = {
  baseUrl: (0, _parseUrl.default)(process.env.NEXTAUTH_URL || process.env.VERCEL_URL).baseUrl,
  basePath: (0, _parseUrl.default)(process.env.NEXTAUTH_URL).basePath,
  keepAlive: 0,
  clientMaxAge: 0,
  _clientLastSync: 0,
  _clientSyncTimer: null,
  _eventListenersAdded: false,
  _clientSession: undefined,
  _clientId: Math.random().toString(36).substring(2) + Date.now().toString(36),
  _getSession: () => {}
};
```

**Feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [ ] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [x] Could not find relevant documentation
* [ ] Found the example project helpful
* [x] Did not find the example project helpful

I tried to test yarn2 plug and play on the example project but I didn't get very
<details>
<summary>
far (even with just yarn1)
</summary>

```
$ git clone https://github.com/nextauthjs/next-auth-example.git
$ cd next-auth-example/
$ yarn install
yarn install v1.22.10
info No lockfile found.
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
warning sqlite3 > node-pre-gyp@0.11.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
warning sqlite3 > node-gyp > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning sqlite3 > node-gyp > request > har-validator@5.1.5: this library is no longer supported
[2/4] Fetching packages...
info fsevents@2.3.2: The platform "win32" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[1/3] ⠈ @ampproject/toolbox-optimizer
[-/3] ⠁ waiting...
error D:\projects\2020-2021uam\se\next-auth-example\node_modules\sqlite3: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build
Arguments:
Directory: D:\projects\2020-2021uam\se\next-auth-example\node_modules\sqlite3
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.11.0
node-pre-gyp info using node@12.19.0 | win32 | x64
node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp info check checked for "D:\projects\2020-2021uam\se\next-auth-example\node_modules\sqlite3\lib\binding\napi-v6-win32-x64\node_sqlite3.node" (not found)
node-pre-gyp http GET https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.1/napi-v6-win32-x64.tar.gz
node-pre-gyp http 403 https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.1/napi-v6-win32-x64.tar.gz
node-pre-gyp WARN Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.1/napi-v6-win32-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for sqlite3@5.0.1 and node@12.19.0 (node-v72 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp http 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.1/napi-v6-win32-x64.tar.gz
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@12.19.0 | win32 | x64
gyp info ok
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@12.19.0 | win32 | x64
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Users\jakkor8\Miniconda3\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                       ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:308:12)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
gyp ERR! System Windows_NT 10.0.19041
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\projects\\2020-2021uam\\se\\next-auth-example\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=D:\\projects\\2020-2021uam\\se\\next-auth-example\\node_modules\\sqlite3\\lib\\binding\\napi-v6-win32-x64\\node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=D:\\projects\\2020-2021uam\\se\\next-auth-example\\node_modules\\sqlite3\\lib\\binding\\napi-v6-win32-x64" "--napi_version=7" "--node_abi_napi=napi" "--napi_build_version=6" "--node_napi_label=napi-v6"
gyp ERR! cwd D:\projects\2020-2021uam\se\next-auth-example\node_modules\sqlite3
gyp ERR! node -v v12.19.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe D:\projects\2020-2021uam\se\next-auth-example\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=D:\projects\2020-2021uam\se\next-auth-example\node_modules\sqlite3\lib\binding\napi-v6-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=D:\projects\2020-2021uam\se\next-auth-example\node_modules\sqlite3\lib\binding\napi-v6-win32-x64 --napi_version=7 --node_abi_napi=napi --napi_build_version=6 --node_napi_label=napi-v6' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (D:\projects\2020-2021uam\se\next-auth-example\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
node-pre-gyp ERR! System Windows_NT 10.0.19041
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\projects\\2020-2021uam\\se\\next-auth-example\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd D:\projects\2020-2021uam\se\next-auth-example\node_modules\sqlite3
node-pre-gyp ERR! node -v v12.19.0
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe D:\projects\2020-2021uam\se\next-auth-example\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=D:\projects\2020-2021uam\se\next-auth-example\node_modules\sqlite3\lib\binding\napi-v6-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=D:\projects\2020-2021uam\se\next-auth-example\node_modules\sqlite3\lib\binding\napi-v6-win32-x64 --napi_version=7 --node_abi_napi=napi --napi_build_v
```

</details>

<details>

<summary>I tried to run the same commands as above (in the details dropdown) on WSL </summary>

and same issue

```
$ yarn install
yarn install v1.22.10
info No lockfile found.
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
warning sqlite3 > node-pre-gyp@0.11.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
warning sqlite3 > node-gyp > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning sqlite3 > node-gyp > request > har-validator@5.1.5: this library is no longer supported
[2/4] Fetching packages...
info fsevents@2.3.2: The platform "linux" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[-/3] ⠠ waiting...
[2/3] ⠐ sharp
error /mnt/d/projects/2020-2021uam/se/debugging/next-auth-example/node_modules/sqlite3: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build
Arguments:
Directory: /mnt/d/projects/2020-2021uam/se/debugging/next-auth-example/node_modules/sqlite3
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.11.0
node-pre-gyp info using node@15.8.0 | linux | x64
node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp info check checked for "/mnt/d/projects/2020-2021uam/se/debugging/next-auth-example/node_modules/sqlite3/lib/binding/napi-v6-linux-x64/node_sqlite3.node" (not found)
node-pre-gyp http GET https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.1/napi-v6-linux-x64.tar.gz
node-pre-gyp http 403 https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.1/napi-v6-linux-x64.tar.gz
node-pre-gyp WARN Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.1/napi-v6-linux-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for sqlite3@5.0.1 and node@15.8.0 (node-v88 ABI, glibc) (falling back to source compile with node-gyp)
node-pre-gyp http 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.1/napi-v6-linux-x64.tar.gz
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@15.8.0 | linux | x64
gyp info ok
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@15.8.0 | linux | x64
gyp http GET https://nodejs.org/download/release/v15.8.0/node-v15.8.0-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v15.8.0/node-v15.8.0-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v15.8.0/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v15.8.0/SHASUMS256.txt
gyp info spawn /usr/bin/python2
gyp info spawn args [
gyp info spawn args   '/mnt/d/projects/2020-2021uam/se/debugging/next-auth-example/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/mnt/d/projects/2020-2021uam/se/debugging/next-auth-example/node_modules/sqlite3/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/mnt/d/projects/2020-2021uam/se/debugging/next-auth-example/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/jcubed/.node-gyp/15.8.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/jcubed/.node-gyp/15.8.0',
gyp info spawn args   '-Dnode_gyp_dir=/mnt/d/projects/2020-2021uam/se/debugging/next-auth-example/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/jcubed/.node-gyp/15.8.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/mnt/d/projects/2020-2021uam/se/debugging/next-auth-example/node_modules/sqlite3',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info ok
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@15.8.0 | linux | x64
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/mnt/d/projects/2020-2021uam/se/debugging/next-auth-example/node_modules/sqlite3/build'
  CC(target) Release/obj.target/nothing/../node-addon-api/nothing.o
  AR(target) Release/obj.target/../node-addon-api/nothing.a
  COPY Release/nothing.a
  ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c
/bin/sh: 1: python: not found
make: *** [deps/action_before_build.target.mk:13: Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c] Error 127
make: Leaving directory '/mnt/d/projects/2020-2021uam/se/debugging/next-auth-example/node_modules/sqlite3/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/mnt/d/projects/2020-2021uam/se/debugging/next-auth-example/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (node:events:378:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
gyp ERR! System Linux 4.19.128-microsoft-standard
gyp ERR! command "/home/jcubed/.nvm/versions/node/v15.8.0/bin/node" "/mnt/d/projects/2020-2021uam/se/debugging/next-auth-example/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/mnt/d/projects/2020-2021uam/se/debugging/next-auth-example/node_modules/sqlite3/lib/binding/napi-v6-linux-x64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/mnt/d/projects/2020-2021uam/se/debugging/next-auth-example/node_modules/sqlite3/lib/binding/napi-v6-linux-x64" "--napi_version=7" "--node_abi_napi=napi" "--napi_build_version=6" "--node_napi_label=napi-v6"
gyp ERR! cwd /mnt/d/projects/2020-2021uam/se/debugging/next-auth-example/node_modules/sqlite3
gyp ERR! node -v v15.8.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/home/jcubed/.nvm/versions/node/v15.8.0/bin/node /mnt/d/projects/2020-2021uam/se/debugging/next-auth-example/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/mnt/d/projects/2020-2021uam/se/debugging/next-auth-example/node_modules/sqlite3/lib/binding/napi-v6-linux-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/mnt/d/projects/2020-2021uam/se/debugging/next-auth-example/node_modules/sqlite3/lib/binding/napi-v6-linux-x64 --napi_version=7 --node_abi_napi=napi --napi_build_version=6 --node_napi_label=napi-v6' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/mnt/d/projects/2020-2021uam/se/debugging/next-auth-example/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:378:20)
node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1067:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
node-pre-gyp ERR! System Linux 4.19.128-microsoft-standard
node-pre-gyp ERR! command "/home/jcubed/.nvm/versions/node/v15.8.0/bin/node" "/mnt/d/projects/2020-2021uam/se/debugging/next-auth-example/node_modules/sqlite3/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /mnt/d/projects/2020-2021uam/se/debugging/next-auth-example/node_modules/sqlite3
node-pre-gyp ERR! node -v v15.8.0
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok
Failed to execute '/home/jcubed/.nvm/versions/node/v15.8.0/bin/node /mnt/d/projects/2020-2021uam/se/debugging/next-auth-example/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/mnt/d/projects/2020-2021uam/se/debugging/next-auth-example/node_modules/sqlite3/lib/binding/napi-v6-linux-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/mnt/d/projects/2020-2021uam/se/debugging/next-auth-example/node_modules/sqlite3/lib/binding/napi-v6-linux-x6
```

</details>

I have similar issue with building just the template next.js app https://github.com/vercel/next.js/issues/22113 but the issue there is only on windows

**Comment by balazsorban44** [comment]
#1034 has been raised and tried to deal with this.
We also opened an issue/PR on Next.js:

https://github.com/vercel/next.js/issues/20955
https://github.com/vercel/next.js/pull/20971

Other than that, I think you can try to turn to Yarn folks, because as discussed before, this error does not originate from our end.

**Comment by JakubKoralewski** [comment]
Sorry, I don't know how I missed the duplicate. Thanks!

**Comment by 0xDing** [comment]
The same is encountered under macOS 11.2 and Apple Silicon
