### ISSUE TITLE
Error: Missing or invalid provider account

### ISSUE THREAD

**Issue by robertsamarji** [nextauthjs/next-auth#1362]
Hello, I've been integrating SSO from a private company into my NextJs app and using NextAuth custom provider to do it (great library btw).

However, I'm getting the following error:

```
[next-auth][error][oauth_callback_handler_error] 
https://next-auth.js.org/errors#oauth_callback_handler_error Error: Missing or invalid provider account
    at .../node_modules/next-auth/dist/server/lib/callback-handler.js:31:121
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (.../node_modules/next-auth/dist/server/lib/callback-handler.js:20:103)
    at _next (.../node_modules/next-auth/dist/server/lib/callback-handler.js:22:194)
    at .../node_modules/next-auth/dist/server/lib/callback-handler.js:22:364
    at new Promise (<anonymous>)
    at .../node_modules/next-auth/dist/server/lib/callback-handler.js:22:97
    at callbackHandler (.../node_modules/next-auth/dist/server/lib/callback-handler.js:25:27)
    at Object.<anonymous> (.../node_modules/next-auth/dist/server/routes/callback.js:115:50)
    at Generator.next (<anonymous>)
```

I had a look at the similar threads on here, but I'm still not sure how to tackle this, so any help would be greatly appreciated. Config below:

```js
// [...nextauth].js

export default NextAuth({
  session: {
    jwt: true
  },
  providers: [
    {
      id: 'company',
      name: 'Company',
      type: 'oauth',
      version: '2.0',
      scope: 'openid',
      params: {
        grant_type: 'authorization_code',
      },
      accessTokenUrl: 'https://oauth-server.company.com/oauth2/token',
      authorizationUrl: 'https://oauth-server.company.com/oauth2/authorize?response_type=code&response_mode=form_post',
      idToken: true,
      async profile(profile, tokens) {
        console.log('profile', profile)
        console.log('tokens', tokens)
        return {
          aud: profile.aud,
          iss: profile.iss,
          iat: profile.iat,
          exp: profile.exp,
          sub: profile.sub
        }
      },
      clientId: process.env.CLIENTID
      clientSecret: process.env.CLIENTSECRET
    }
  ],
  callbacks: {
    async session(session, token) {
      console.log('session', session)
      console.log('sessiontoken', token)
      return session
    }
  },
  async jwt(token, user, account, profile, isNewUser) {
    console.log('token', token)
    console.log('user', user)
    console.log('account', account)
    console.log('profile', profile)
    console.log('isNewUser', isNewUser)
    return token
  }
})
```

```js
// Output from console.log('profile', profile)

profile {
  aud: '54f422b9150863ad792e2099v8832e43',
  iss: 'https://oauth-server.company.com',
  iat: 1614085785,
  exp: 1614089384,
  sub: ''
}
```

```js
// Output from console.log('tokens', tokens)

undefined
```

```js
// Output from localhost:3000/api/auth/providers

{"company":{"id":"company","name":"Company","type":"oauth","signinUrl":"http://localhost:3000/api/auth/signin/company","callbackUrl":"http://localhost:3000/api/auth/callback/company"}}
```

**Feedback**
* [ ] Found the documentation helpful
* [x] Found documentation but was incomplete
* [x] Could not find relevant documentation
* [ ] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by balazsorban44** [comment]
So a few things. Don't know if it is just a copy+paste error, but your `jwt` callback is outside of `callbacks`, so that is one error.

Also, you could try adding `debug: true` to the options for more info: https://next-auth.js.org/configuration/options#debug

Could you maybe also share some information how do you invoke the `signIn` method?

**Comment by robertsamarji** [comment]
Hi @balazsorban44, thank you for the spot, my mistake. I've moved the `jwt` callback into `callbacks`.

This is how I'm invoking the signIn method:

```
import { signIn, signOut, useSession } from 'next-auth/client'

export default function Test() {
  const [ session, loading ] = useSession()
  console.log('session', session)

  return <>
    {!session && <>
      Not signed in <br/>
      <button onClick={() => signIn()}>Sign in</button>
    </>}
    {session && <>
      Signed in as {session.user.email} <br/>
      <button onClick={() => signOut()}>Sign out</button>
    </>}
  </>
}
```

Thanks for the tip on adding `debug: true`.  Interestingly, I can now see the `accessToken`, `refreshToken` and `IdToken` that I'm after, although I'm still seeing the same error:

```
[next-auth][debug][oauth_callback_protection] Added state to authorization params {
  state: '057efc6e213834aa61318cb72a3af55a538ecf30a5bcd1de47c3cd35fba7a1cd'
}
[next-auth][debug][get_authorization_url] https://oauth-server.company.com/oauth2/authorize?response_type=code&response_mode=form_post&state=057efc6e213834aa61318cb72a3af55a538ecf30a5bcd1de47c3cd35fba7a1cd&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Fapi%2Fauth%2Fcallback%2Fcompany&scope=openid&client_id=61f425d9150866ad792e2086b8832e63
[next-auth][debug][oauth_callback_protection] Comparing received and expected state {
  state: '057efc6e213834aa61318cb72a3af55a538ecf30a5bcd1de47c3cd35fba7a1cd',
  expectedState: '057efc6e213834aa61318cb72a3af55a538ecf30a5bcd1de47c3cd35fba7a1cd'
}
[next-auth][debug][profile_data] {
  aud: '61f425d9150866ad792e2086b8832e63',
  iss: 'https://oauth-server.company.com',
  iat: 1614118115,
  exp: 1614121715,
  sub: ''
}
profile {
  aud: '61f425d9150866ad792e2086b8832e63',
  iss: 'https://oauth-server.company.com',
  iat: 1614118115,
  exp: 1614121715,
  sub: ''
}
tokens undefined
[next-auth][debug][oauth_callback_response] {
  profile: {
    aud: '61f425d9150866ad792e2086b8832e63',
    iss: 'https://oauth-server.company.com',
    iat: 1614118115,
    exp: 1614121715,
    sub: '',
    email: null
  },
  account: {
    provider: 'company',
    type: 'oauth',
    id: undefined,
    accessToken: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiI2MWY0MjVkOTE1MDg2NmFkNzkyZTIwODZiODgzMmU2MyIsImp0aSI6IjJhZGNiMzEzNTU3ZTY4NzE5ODZkYTQxM2M5M2MzNDMzYjVlNTI2YmE2MDNkYzlhMDFjMTUyMTdhMzYxYTZhMjI5ZWRjZWMyZTFlMDQ2YmJmIiwiaWF0IjoxNjE0MTE4MTE1LCJuYmYiOjE2MTQxMTgxMTUsImV4cCI6MTYxNDEyMTcxNSwic3ViIjoiMTA0NzEyMzUiLCJzY29wZXMiOlsib3BlbmlkIl19.V-yicQ-UOYcx_NlVszHkvt48nX0z87oem8auz7FO6pGhIJRlkL6MXyrFAVYJU1WRvJKha9W5UjDvPZiZFG1kudMeOOGCNYKF5UK4RkpgryFe1zE26hf4tQBNN5yQbTZ1W2-5j8sAJgIXPueFh2bbKfTR1lc-1f_t522BKhdXQU5S5ilqBLSzihRem7PohsUt8931fc4INhIhBzujIWW3dkuT2m9AqjnIjRDL8FVY3GF_Z2w5w3F2qwc4wl3qZBVHuLk-4xp7fw1HUAg9L4_05xVVDJ8ESpBrCY2-Hs47Rkqmsiha17poIRDKgOoXS7cp2DV4JqWZjMXytLuNaP3WZQ',
    accessTokenExpires: null,
    refreshToken: 'def502006631cf638ddcd4be7b85fdda72b39a6cfad6d61a8de13c842c9c869f10651d80a9bc8ff1f20a177cf296f355c9a0a02349553611d6dbff2f7e0030b0ece60a6d258f41bc625355d2d69bb222e7cf4caaa4e5fc9670facf6f4aeea689d879bdf8a1effc92dfa36e1a06772ccf4872daeb30a425d6386c21b2d84810dd20f77e0f41e7842ce6d77d7da9258c90f23556a6bca56a3e8fd8bf2932284c6baa749ce86ff8e828c0a739dc7fd8b30ac42bca2831246960b643c416a3d8fe4932d5f69790657845be746608dc3490f60f50d0857f8f13517a08ba3a26d8373e55628dbb59be31a974406b5550fee956a38e75bd1073517424be12256c2c0e3fbbbe0ec8c0ec8b3232b9e065e0e14852c11213b431af08002fb32107fd7143349eae6b9ea55d771f3ed9fa18660968b6c071028e3dba81ac7a7119627eee95178b41fdff781be5afdab89e742696983be2fd1646964d9be818b911c5385a794397fd4ff72011d3ad5cf35659fb0ded8211365e8de2cc944863197b47c65b645b097750e8af91768a311fc797aba0637966',
    idToken: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiI2MWY0MjVkOTE1MDg2NmFkNzkyZTIwODZiODgzMmU2MyIsImlzcyI6Imh0dHBzOlwvXC9vYXV0aC1zZXJ2ZXIuYWNjZXB0eS5zYW5kYm94LnN5cnVwbWUubmV0IiwiaWF0IjoxNjE0MTE4MTE1LCJleHAiOjE2MTQxMjE3MTUsInN1YiI6IiJ9.5MrNW14I1hGiFDZ-aakL35O1P6j1i87eirDfSjqfn5WvAvyuVWFlGiihy7QEoLQskBIRLlXs57HZKkfEjHUePKc9UmriWR2vbnjVYlga1OUxKN9QOxEOqPYR7tdqahGcpK6fO6POIuUU8M2nsuqgDSfdW7p7k1nO9Y9EhKOahDzvH1QbL1MB0zl7P9PR7tgvdAxxFUiglW4oHn8IYnnJDKushpgPM_bb_DlDZ_GI2-9CfTiFU8j9-05s7sA6Ixdua59Mm7m1Rv73ZWRUgQVxDfv9nUvv5_QpCzBN3FzGpIrcGtwbv3qejP5v6GgDgYPnOmk0Urjdw13L4XMi0boOtQ',
    id_token: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiI2MWY0MjVkOTE1MDg2NmFkNzkyZTIwODZiODgzMmU2MyIsImlzcyI6Imh0dHBzOlwvXC9vYXV0aC1zZXJ2ZXIuYWNjZXB0eS5zYW5kYm94LnN5cnVwbWUubmV0IiwiaWF0IjoxNjE0MTE4MTE1LCJleHAiOjE2MTQxMjE3MTUsInN1YiI6IiJ9.5MrNW14I1hGiFDZ-aakL35O1P6j1i87eirDfSjqfn5WvAvyuVWFlGiihy7QEoLQskBIRLlXs57HZKkfEjHUePKc9UmriWR2vbnjVYlga1OUxKN9QOxEOqPYR7tdqahGcpK6fO6POIuUU8M2nsuqgDSfdW7p7k1nO9Y9EhKOahDzvH1QbL1MB0zl7P9PR7tgvdAxxFUiglW4oHn8IYnnJDKushpgPM_bb_DlDZ_GI2-9CfTiFU8j9-05s7sA6Ixdua59Mm7m1Rv73ZWRUgQVxDfv9nUvv5_QpCzBN3FzGpIrcGtwbv3qejP5v6GgDgYPnOmk0Urjdw13L4XMi0boOtQ',
    token_type: 'Bearer',
    expires_in: 3600,
    access_token: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiI2MWY0MjVkOTE1MDg2NmFkNzkyZTIwODZiODgzMmU2MyIsImp0aSI6IjJhZGNiMzEzNTU3ZTY4NzE5ODZkYTQxM2M5M2MzNDMzYjVlNTI2YmE2MDNkYzlhMDFjMTUyMTdhMzYxYTZhMjI5ZWRjZWMyZTFlMDQ2YmJmIiwiaWF0IjoxNjE0MTE4MTE1LCJuYmYiOjE2MTQxMTgxMTUsImV4cCI6MTYxNDEyMTcxNSwic3ViIjoiMTA0NzEyMzUiLCJzY29wZXMiOlsib3BlbmlkIl19.V-yicQ-UOYcx_NlVszHkvt48nX0z87oem8auz7FO6pGhIJRlkL6MXyrFAVYJU1WRvJKha9W5UjDvPZiZFG1kudMeOOGCNYKF5UK4RkpgryFe1zE26hf4tQBNN5yQbTZ1W2-5j8sAJgIXPueFh2bbKfTR1lc-1f_t522BKhdXQU5S5ilqBLSzihRem7PohsUt8931fc4INhIhBzujIWW3dkuT2m9AqjnIjRDL8FVY3GF_Z2w5w3F2qwc4wl3qZBVHuLk-4xp7fw1HUAg9L4_05xVVDJ8ESpBrCY2-Hs47Rkqmsiha17poIRDKgOoXS7cp2DV4JqWZjMXytLuNaP3WZQ',
    refresh_token: 'def502006631cf638ddcd4be7b85fdda72b39a6cfad6d61a8de13c842c9c869f10651d80a9bc8ff1f20a177cf296f355c9a0a02349553611d6dbff2f7e0030b0ece60a6d258f41bc625355d2d69bb222e7cf4caaa4e5fc9670facf6f4aeea689d879bdf8a1effc92dfa36e1a06772ccf4872daeb30a425d6386c21b2d84810dd20f77e0f41e7842ce6d77d7da9258c90f23556a6bca56a3e8fd8bf2932284c6baa749ce86ff8e828c0a739dc7fd8b30ac42bca2831246960b643c416a3d8fe4932d5f69790657845be746608dc3490f60f50d0857f8f13517a08ba3a26d8373e55628dbb59be31a974406b5550fee956a38e75bd1073517424be12256c2c0e3fbbbe0ec8c0ec8b3232b9e065e0e14852c11213b431af08002fb32107fd7143349eae6b9ea55d771f3ed9fa18660968b6c071028e3dba81ac7a7119627eee95178b41fdff781be5afdab89e742696983be2fd1646964d9be818b911c5385a794397fd4ff72011d3ad5cf35659fb0ded8211365e8de2cc944863197b47c65b645b097750e8af91768a311fc797aba0637966'
  },
  OAuthProfile: {
    aud: '61f425d9150866ad792e2086b8832e63',
    iss: 'https://oauth-server.company.com',
    iat: 1614118115,
    exp: 1614121715,
    sub: ''
  }
}
[next-auth][error][oauth_callback_handler_error] 
https://next-auth.js.org/errors#oauth_callback_handler_error Error: Missing or invalid provider account
    at .../node_modules/next-auth/dist/server/lib/callback-handler.js:31:121
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (.../node_modules/next-auth/dist/server/lib/callback-handler.js:20:103)
    at _next (...node_modules/next-auth/dist/server/lib/callback-handler.js:22:194)
    at .../node_modules/next-auth/dist/server/lib/callback-handler.js:22:364
    at new Promise (<anonymous>)
    at .../node_modules/next-auth/dist/server/lib/callback-handler.js:22:97
    at callbackHandler (.../node_modules/next-auth/dist/server/lib/callback-handler.js:25:27)
    at Object.<anonymous> (.../node_modules/next-auth/dist/server/routes/callback.js:115:50)
    at Generator.next (<anonymous>)
```

**Comment by balazsorban44** [comment]
I can also see that you don't get an id called `sub`, and therefore id is `undefined` in account. It looks to be the problem. Your `profile` callback should return a valid `id`.


We check for its existence on this line:
https://github.com/nextauthjs/next-auth/blob/96ff048b594ab2f42f62be8c773a6de7819eafc5/src/server/lib/callback-handler.js#L19

ALthough maybe we shouldn't require it, if you don't use a database.

**Comment by robertsamarji** [comment]
Ah, thank you so much.

Entering a dummy value in `profile.id` has fixed my issue.

Really appreciate your help, thanks again Balázs.
