### ISSUE TITLE
JWT signingKey is incorrectly parsed as JSON

### ISSUE THREAD

**Issue by Baterka** [nextauthjs/next-auth#1425]
**Describe the bug**
If you set `JWT_SIGNING_PRIVATE_KEY="example"` into `.env` file then you get this error while jwt is generating internally:
```
(node:30216) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token Y in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.<anonymous> (C:\Users\David\IdeaProjects\varmi-ticket-system\node_modules\next-auth\dist\lib\jwt.js:54:65)
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (C:\Users\David\IdeaProjects\varmi-ticket-system\node_modules\next-auth\dist\lib\jwt.js:22:103)
    at _next (C:\Users\David\IdeaProjects\varmi-ticket-system\node_modules\next-auth\dist\lib\jwt.js:24:194)
    at C:\Users\David\IdeaProjects\varmi-ticket-system\node_modules\next-auth\dist\lib\jwt.js:24:364
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\David\IdeaProjects\varmi-ticket-system\node_modules\next-auth\dist\lib\jwt.js:24:97)
    at Object._encode (C:\Users\David\IdeaProjects\varmi-ticket-system\node_modules\next-auth\dist\lib\jwt.js:66:18)
    at Object.encode (C:\Users\David\IdeaProjects\varmi-ticket-system\node_modules\next-auth\dist\lib\jwt.js:32:18)
    at Object.<anonymous> (C:\Users\David\IdeaProjects\varmi-ticket-system\node_modules\next-auth\dist\server\routes\callback.js:340:39)
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (C:\Users\David\IdeaProjects\varmi-ticket-system\node_modules\next-auth\dist\server\routes\callback.js:30:103)
    at _next (C:\Users\David\IdeaProjects\varmi-ticket-system\node_modules\next-auth\dist\server\routes\callback.js:32:194)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

```

https://github.com/nextauthjs/next-auth/blob/f960cc0f6fc232a00f5e8288b5f6a2ad53b03f5d/src/lib/jwt.js#L34
At this line we are parsing signingKey as JSON which is incorrect.

**Steps to reproduce**
Enable JWT in config:
```
session: {
    jwt: true,
    maxAge: 30 * 24 * 60 * 60, // 30 days
    updateAge: 24 * 60 * 60, // 24 hours
  },
  jwt: {
    signingKey: process.env.JWT_SIGNING_PRIVATE_KEY,
  },
```

And try to do some signIn action.

**Expected behavior**
signingKey should be used as is and not parsed as JSON...

**Additional context**
This is easily fixable by adding quotes in `.env` file like so: `JWT_SIGNING_PRIVATE_KEY=""example""`, but this is really stupid and not very beginner friendly :D

**Feedback**

* [ ] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [X] Could not find relevant documentation
* [ ] Found the example project helpful
* [X] Did not find the example project helpful

**Comment by Baterka** [comment]
Sorry. It seems like just bad documentation.

Here is described how to generate proper key: https://next-auth.js.org/warnings#server

It needs to be generated by `jose newkey -s 256 -t oct -a HS512` (node-jose-tools) and then it is JSON what can be parsed.
