### ISSUE TITLE
Try running on local for contributing leads to error

### ISSUE THREAD

**Issue by martinratinaud** [nextauthjs/next-auth#1711]
**Describe the bug**
I want to contribute and thus tried to launch the app on my local but I end up with

```
(node:56122) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/Users/martin/Workspace/ambanum/next-auth/dist/css/index.css'
    at Object.openSync (fs.js:476:3)
    at Object.readFileSync (fs.js:377:35)
    at css (webpack-internal:///./src/css/index.js:14:52)
    at send (webpack-internal:///./src/server/pages/index.js:39:258)
    at Object.signin (webpack-internal:///./src/server/pages/index.js:44:7)
    at eval (webpack-internal:///./src/server/index.js:194:25)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Steps to reproduce**

```
git clone git@github.com:nextauthjs/next-auth.git
cd next-auth
npm i 
cp .env.local.example .env.local
```

Then go to `pages/api/auth/[...nextauth].js` and comment out all providers except Credentials to keep it simple

And finally launch `npm run dev`

**Expected behavior**
The website loads correctly and when I click on "Sign In", I should arrive on the signing page

**Screenshots or error logs**
In the console

**Comment by balazsorban44** [comment]
currently you have to build the css file once when starting dev.

Just run `npm run build:css` and after that `npm run dev` should work. Feel free to clarify this jn the CONTRIBUTING.MD
