### ISSUE TITLE
getToken throws an error

### ISSUE THREAD

**Issue by mtt87** [nextauthjs/next-auth#1798]
**Describe the bug**
After updating to `3.15.5` the following code throws an error
```ts
export default async function TruAPIHandler(
  req: NextApiRequest,
  res: NextApiResponse,
) {
  // getToken will throw
  const token = await getToken({
    req,
    secret: process.env.NEXTAUTH_SECRET,
    encryption: true,
    signingKey: process.env.NEXTAUTH_SIGNIN_KEY,
    encryptionKey: process.env.NEXTAUTH_ENCRYPTION_KEY,
  })

```

**Steps to reproduce**
I'm using an encrypted JWT in my configuration
```js
  secret: process.env.NEXTAUTH_SECRET,
  session: {
    jwt: true,
  },
  jwt: {
    encryption: true,
    secret: process.env.NEXTAUTH_SECRET,
    signingKey: process.env.NEXTAUTH_SIGNIN_KEY,
    encryptionKey: process.env.NEXTAUTH_ENCRYPTION_KEY,
  },
```

Simple repo to reproduce https://github.com/mtt87/next-auth-bug

**Expected behavior**
It should not throw an error and return the token as it happens correctly on `3.14.8`

**Screenshots or error logs**
```
TypeError: Object(...) is not a function
    at TruAPIHandler (webpack-internal:///./pages/api/tru/[...params].ts:9:85)
    at apiResolver (/Users/mattia/node_modules/next/dist/next-server/server/api-utils.js:8:7)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async DevServer.handleApiRequest (/Users/mattia/node_modules/next/dist/next-server/server/next-server.js:67:462)
    at async Object.fn (/Users/mattia/node_modules/next/dist/next-server/server/next-server.js:59:492)
    at async Router.execute (/Users/mattia/node_modules/next/dist/next-server/server/router.js:25:67)
    at async DevServer.run (/Users/mattia/node_modules/next/dist/next-server/server/next-server.js:69:1042)
    at async DevServer.handleRequest (/Users/mattia/node_modules/next/dist/next-server/server/next-server.js:34:504)
```

**Comment by balazsorban44** [comment]
will wait for the reproduction! as far as I know we didn't touch that part of the code, so very curious what happens here. 🤔

**Comment by mtt87** [comment]
Just created the repo
https://github.com/mtt87/next-auth-bug

Make sure to copy `.env.example` to `.env.local` and populate the variables, it's using GitHub as IDP but you can change it to whatever you want.

To generate the keys you can use https://8gwifi.org/jwkfunctions.jsp
`NEXTAUTH_ENCRYPTION_KEY` uses A256GCM
`NEXTAUTH_SIGNIN_KEY` uses HS512

**Comment by balazsorban44** [comment]
so looking at your reproduction (which I highly appreciate, thanks) just for a few seconds, it reminded me of this recent PR : https://github.com/nextauthjs/next-auth/pull/1751

I'll check it out better, but that seems relevant

**Comment by balazsorban44** [comment]
The problem was something else, but I now verified locally that the new release fixed the problem!
