### ISSUE TITLE
`[GET] /api/auth/session` error on Vercel server-less Runtime Log.

### ISSUE THREAD

**Issue by typedashutosh** [nextauthjs/next-auth#1799]
**Your question**
On local server, I'm getting this error:
![image](https://user-images.githubusercontent.com/68853189/115607764-fcb64d80-a302-11eb-8fdc-042065a4135a.png)
Since I couldn't figure out to solve this, I uploaded the same to GitHub, which when deployed with Vercel, Server-less function on Vercel throws this error:
```
[GET] /api/auth/session
00:28:20:21
2021-04-21T18:58:22.460Z	0dc4af44-c956-482d-a03e-34d56b51c4b6	ERROR	Error: Cannot find module '/var/task/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node'
Require stack:
- /var/task/node_modules/bcrypt/bcrypt.js
- /var/task/.next/server/pages/api/auth/[...nextauth].js
- /var/task/node_modules/next/dist/next-server/server/next-server.js
- /var/task/___next_launcher.js
- /var/runtime/UserFunction.js
- /var/runtime/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/var/task/node_modules/bcrypt/bcrypt.js:6:16)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.jeq0 (/var/task/.next/server/pages/api/auth/[...nextauth].js:215:18)
    at __webpack_require__ (/var/task/.next/server/pages/api/auth/[...nextauth].js:23:31)
    at Object.vsCM (/var/task/.next/server/pages/api/auth/[...nextauth].js:258:64)
    at __webpack_require__ (/var/task/.next/server/pages/api/auth/[...nextauth].js:23:31)
    at Module.KMLI (/var/task/.next/server/pages/api/auth/[...nextauth].js:127:76) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/var/task/node_modules/bcrypt/bcrypt.js',
    '/var/task/.next/server/pages/api/auth/[...nextauth].js',
    '/var/task/node_modules/next/dist/next-server/server/next-server.js',
    '/var/task/___next_launcher.js',
    '/var/runtime/UserFunction.js',
    '/var/runtime/index.js'
  ]
}
RequestId: 0dc4af44-c956-482d-a03e-34d56b51c4b6 Error: Runtime exited with error: exit status 1
Runtime.ExitError
```

**What are you trying to do**
On Local, 
whenever i makes a little change in my page, and refresh, it throws `RangeError`,
On preview,
whenever I login to my webpage, it throws an error on Vercel server-less function Runtime Log

**Reproduction**
Clone [this](https://github.com/typedashutosh/blog-app-nextjs/tree/03184df95dd82addf59e05dea59640b9e436b23a) repository
Add `.env.local`

Just for instance, my **[...nextauth].ts** looks this:
```
import { NextApiRequest, NextApiResponse } from 'next'
import NextAuth, { Account, Profile, Session, User } from 'next-auth'
import { JWT } from 'next-auth/jwt'
import Providers from 'next-auth/providers'
import UserModel from '../../../models/User.model'
import dbConnect from '../../../utils/dbConnect'
import bcrypt from 'bcrypt'

export default (req: NextApiRequest, res: NextApiResponse) => {
  return new Promise((resolve) =>
    NextAuth(req, res, {
      providers: [
        Providers.Credentials({
          name: 'Credentials',
          credentials: {
            username: {
              label: 'Username',
              type: 'text',
              placeholder: 'Username'
            },
            password: {
              label: 'Password',
              type: 'text',
              placeholder: 'Password'
            }
          },
          authorize: async ({
            csrfToken,
            username,
            password
          }: Record<string, string>): Promise<User | null> => {
            if (!csrfToken) return null
            dbConnect()

            const user: { password: string } & User = await UserModel.findOne(
              { username },
              ['id', 'firstname', 'lastname', 'username', 'password']
            )
            return (await bcrypt.compare(password, user.password)) ? user : null
          }
        })
      ],
      session: {
        jwt: true,
        maxAge: 30 * 24 * 60 * 60,
        updateAge: 24 * 60 * 60
      },
      jwt: {
        maxAge: 24 * 60 * 60,
        encryption: true,
        secret: process.env.JWT_SECRET,
        signingKey: process.env.JWT_SIGNING_KEY,
        encryptionKey: process.env.JWT_ENCRYPTION_KEY
      },
      callbacks: {
        signIn: async (
          user: User,
          account: Account,
          profile: Profile
        ): Promise<string | boolean> => {
          return true
        },
        redirect: async (url: string, baseUrl: string): Promise<string> => {
          return url
        },
        session: async (
          session: Session,
          userOrToken: User | JWT
        ): Promise<Session> => {
          const returnSession = {
            expires: session.expires,
            user: {
              _id: userOrToken._id,
              firstname: userOrToken.firstname,
              lastname: userOrToken.lastname,
              username: userOrToken.username
            },
            accessToken: session.accessToken
          }
          return returnSession
        },
        jwt: async (
          token: JWT,
          user: User,
          account: Account,
          profile: Profile,
          isNewUser: boolean
        ): Promise<JWT> => {
          user &&
            (token = {
              _id: user._id,
              firstname: user.firstname,
              lastname: user.lastname,
              username: user.username
            })
          return token
        }
      }
    })
  )
}

```
How do I know what is wrong I'm doing?

**Feedback**
Documentations are Good, thanks for adding native Typescript support. Cheers 👍

**Comment by balazsorban44** [comment]
Please upgrade to at least `3.15.5` See #1783

**Comment by typedashutosh** [comment]
Updated to `v3.15.9` and replaced `bcrypt` with `bcryptjs` and its working fine. 
Thanks!!!
👍
