### ISSUE TITLE
Error: ENOENT: no such file or directory, open '7HOL'

### ISSUE THREAD

**Issue by meotimdihia** [nextauthjs/next-auth#1842]
**Describe the bug**
```
Error: ENOENT: no such file or directory, open '7HOL'
    at Object.openSync (fs.js:462:3)
    at Object.readFileSync (fs.js:364:35)
    at C:\sources\b\.next\serverless\pages\api\auth\[...nextauth].js:291331:19
    at Array.map (<anonymous>)
    at C:\sources\b\.next\serverless\pages\api\auth\[...nextauth].js:291330:30
    at Object.w19Z (C:\sources\b\.next\serverless\pages\api\auth\[...nextauth].js:291335:2)
    at __webpack_require__ (C:\sources\b\.next\serverless\pages\api\auth\[...nextauth].js:23:31)
    at Object.HI7s (C:\sources\b\.next\serverless\pages\api\auth\[...nextauth].js:117813:16)
    at __webpack_require__ (C:\sources\b\.next\serverless\pages\api\auth\[...nextauth].js:23:31)
    at Object.3Qgs (C:\sources\b\.next\serverless\pages\api\auth\[...nextauth].js:29767:21) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: '7HOL'
}
```

**Steps to reproduce**
Run the command `yarn build && yarn start` at localhost

**Screenshots or error logs**
![QqCNj3X 1](https://user-images.githubusercontent.com/300961/115963032-30ce8000-a548-11eb-9a2e-b7d3bcbef020.png)

**Additional context**
The problem always happens on Ubuntu or Windows when the browser request to `/auth/session` on my project. 
But If I deploy the project to Vercel, the problem is disappeared.
Windows, Node.js 12
Ubuntu, Node.js 12
next-auth: ^3.17.0

**Comment by balazsorban44** [comment]
please provide a reproduction!
