### ISSUE TITLE
[next-auth][error][oauth_get_access_token_error] TypeError: Cannot read property 'includes' of undefined

### ISSUE THREAD

**Issue by parantha97** [nextauthjs/next-auth#1941]
## Description 🐜

Please provide a clear and concise description of the bug in NextAuth.js.
I am trying to connect next-auth with Azure AD B2C. with the latest version but I am getting an error "TypeError: Cannot read property 'includes' of undefined". but after reverting to 3.13.3 it works. Any higher version above 3.13.3 throws this error below 

## How to reproduce ☕️

this is my code

import NextAuth from 'next-auth';
import Providers from "next-auth/providers";
import getConfig from 'next/config';
const { publicRuntimeConfig } = getConfig();
const tokenUrl = https://${tenantName}.b2clogin.com/${tenantName}.onmicrosoft.com/${userFlow}/oauth2/v2.0/token

const options:any = {
session: {
jwt: true,
},
secret : 'sdfsdfsdfsfg',
providers: [
{
id: 'azureb2c',
name: 'Azure B2C',
type: 'oauth',
version: '2.0',
debug: true,
scope: 'https://torsoai.onmicrosoft.com/api/54433534-12b2-46a4-a8f9-324d05a718f0/demo.read offline_access openid',
params: {
grant_type: 'authorization_code',
},
accessTokenUrl: tokenUrl,
requestTokenUrl: tokenUrl,
authorizationUrl:
https://${tenantName}.b2clogin.com/${tenantName}.onmicrosoft.com/${userFlow}/oauth2/v2.0/authorize? response_type=code+id_token+token&response_mode=form_post,
profileUrl: 'https://graph.microsoft.com/oidc/userinfo',
profile: (profile) => {
console.log('THE PROFILE', profile)
return {
id: profile.oid,
email: profile.emails.length ? profile.emails[0] : null,
}
},
clientId: clientId,
clientSecret: clientSecret,
idToken: true,
state:false
}
],
pages:{
signIn: '/auth/signin',
signOut: '/auth/signout',
},
};

export default (req, res) => NextAuth(req, res, options);

but I am getting an error like this

[next-auth][error][oauth_get_access_token_error]
https://next-auth.js.org/errors#oauth_get_access_token_error TypeError: Cannot read property 'includes' of undefined
at exports.OAuth2. (C:\Torso\master_7\UI\Prod_UI\node_modules\next-auth\dist\server\lib\oauth\client.js:171:29)
at Generator.next ()
at asyncGeneratorStep (C:\Torso\master_7\UI\Prod_UI\node_modules\next-auth\dist\server\lib\oauth\client.js:24:103)
at _next (C:\Torso\master_7\UI\Prod_UI\node_modules\next-auth\dist\server\lib\oauth\client.js:26:194)
at C:\Torso\master_7\UI\Prod_UI\node_modules\next-auth\dist\server\lib\oauth\client.js:26:364
at new Promise ()
at exports.OAuth2. (C:\Torso\master_7\UI\Prod_UI\node_modules\next-auth\dist\server\lib\oauth\client.js:26:97)
at exports.OAuth2._getOAuth2AccessToken (C:\Torso\master_7\UI\Prod_UI\node_modules\next-auth\dist\server\lib\oauth\client.js:219:32)
at exports.OAuth2.getOAuth2AccessToken [as getOAuthAccessToken] (C:\Torso\master_7\UI\Prod_UI\node_modules\next-auth\dist\server\lib\oauth\client.js:109:32)
at C:\Torso\master_7\UI\Prod_UI\node_modules\next-auth\dist\server\lib\oauth\callback.js:72:35
at Generator.next ()
at asyncGeneratorStep (C:\Torso\master_7\UI\Prod_UI\node_modules\next-auth\dist\server\lib\oauth\callback.js:24:103)
at _next (C:\Torso\master_7\UI\Prod_UI\node_modules\next-auth\dist\server\lib\oauth\callback.js:26:194)
at C:\Torso\master_7\UI\Prod_UI\node_modules\next-auth\dist\server\lib\oauth\callback.js:26:364
at new Promise ()
at C:\Torso\master_7\UI\Prod_UI\node_modules\next-auth\dist\server\lib\oauth\callback.js:26:97 azureb2c eyJraWQiOiJjcGltY29yZV8wOTI1MjAxNSIsInZlciI6IjEuMCIsInppcCI6IkRlZmxhdGUiLCJzZXIiOiIxLjAifQ..ca6T6qoF7fIfqPJ9.eSld8kcvBHARAhmVzIt196GSv7tB-ch4-SuLYOvtRZvb0-shcqL4hTE7YJXRK_OjKx_cqbmKxoV_cJ2We9zbMYKpZbyHWvie34ljJD-i5CkY55qybkNpbPD-7gCtaguvFf2Csw5jTblWbxKB76KHoDaLaha0ub6BThKT4qMR-WjoWTwoZ17Ddh0RyC1vJcZ1gfGRnrrGEWdSDmQSA5LrQQp2dp0kF0_a1sND9PLTgqVbvnSOXkzYAiOlErvfvyvvk0SIA4ccF3P8dK89rdAERspr5gU2kcs5nvcFkgHti8Qqx-W3b-UvduVTRy4YxNRIzInGjUoamnD-s2eeilJoyrpdB0GYc2h0nTyCz9pKtgK_hBAwRs3y1WuSNhwlTVcuqG4RUppZWnQE-J2dU5pM9SZVG3gBMxBdiIcpCcKxTGvDEbWH_99o0Cg54W796qJrKubJGxq9d3871KenNDbnNzN3txHsuU-OdgvOA0NlR3e_YNUSGWS1T_ppM_p7ScLBza4iEi_O5TxjlWniSKDE6mrEnjuFonlE9P1FFpTNqrCDqnbY6J2yPhl2kAaPi40wE-DT8LqvgwE1mr63yES6pLQQCDwgoqOpm9Zp5rdzY7mdjf5OzXMhvHE5_LCV5hD5LoviD_0ExDTTK_k.KPa2kwO_A8qluW8t8hXxbQ
[next-auth][error][oauth_callback_error]
https://next-auth.js.org/errors#oauth_callback_error TypeError: Cannot read property 'includes' of undefined
at exports.OAuth2. (C:\Torso\master_7\UI\Prod_UI\node_modules\next-auth\dist\server\lib\oauth\client.js:171:29)
at Generator.next ()
at asyncGeneratorStep (C:\Torso\master_7\UI\Prod_UI\node_modules\next-auth\dist\server\lib\oauth\client.js:24:103)
at _next (C:\Torso\master_7\UI\Prod_UI\node_modules\next-auth\dist\server\lib\oauth\client.js:26:194)
at C:\Torso\master_7\UI\Prod_UI\node_modules\next-auth\dist\server\lib\oauth\client.js:26:364
at new Promise ()
at exports.OAuth2. (C:\Torso\master_7\UI\Prod_UI\node_modules\next-auth\dist\server\lib\oauth\client.js:26:97)
at exports.OAuth2._getOAuth2AccessToken (C:\Torso\master_7\UI\Prod_UI\node_modules\next-auth\dist\server\lib\oauth\client.js:219:32)
at exports.OAuth2.getOAuth2AccessToken [as getOAuthAccessToken] (C:\Torso\master_7\UI\Prod_UI\node_modules\next-auth\dist\server\lib\oauth\client.js:109:32)
at C:\Torso\master_7\UI\Prod_UI\node_modules\next-auth\dist\server\lib\oauth\callback.js:72:35
at Generator.next ()
at asyncGeneratorStep (C:\Torso\master_7\UI\Prod_UI\node_modules\next-auth\dist\server\lib\oauth\callback.js:24:103)
at _next (C:\Torso\master_7\UI\Prod_UI\node_modules\next-auth\dist\server\lib\oauth\callback.js:26:194)
at C:\Torso\master_7\UI\Prod_UI\node_modules\next-auth\dist\server\lib\oauth\callback.js:26:364
at new Promise ()
at C:\Torso\master_7\UI\Prod_UI\node_modules\next-auth\dist\server\lib\oauth\callback.js:26:97

**Comment by balazsorban44** [comment]
Could you please provide your client-side code as well? 

Preferably, please use the provided CodeSandbox template! https://codesandbox.io/s/next-auth-example-1kktb

Does it occur locally, or only when deployed?

**Comment by emrysal** [comment]
@balazsorban44 I have come across this issue yesterday, this is caused by `if (provider.protection.includes('pkce')) {` and it happens when you don't add the protection: [] setting to your provider. `state` is deprecated, so OP can use protection: [ "none" ] to resolve.

**Comment by balazsorban44** [comment]
This is what https://github.com/nextauthjs/next-auth/blob/ffd0601ab0a786438d126d18ae44466495784ac0/src/server/index.js#L74-#82 tries to address. Objectively not elegant, but it is to support the `state` option to be backwards compatible.

I'll revisit it and see if it doesn't handle some cases.

**Comment by emrysal** [comment]
@balazsorban44 Looking at that line:

`if (!provider.protection && provider.state !== false) {`

If ! isset provider.protection and provider.state === true - set provider.protection to provider.protection = ["state"]

This misses this exact scenario, when provider.protection is not set and provider.state = false. I suggest rewriting to:
```javascript
if (!provider.protection && provider.state !== undefined) {
  provider.protection = provider.state ? [ "state" ] : [ "none" ];
}
```

What do you think?

**Comment by parantha97** [comment]
@balazsorban44 @emrysal yup adding protection resolves this issue. 

Thanks...

**Comment by balazsorban44** [comment]
thanks, I'll fix this tomorrow then!

**Comment by balazsorban44** [comment]
Sorry for the delay, but this should now be fixed in `3.21.0`. Please tell me if there are any further problems!
