### ISSUE TITLE
Error while authenticating with GitHub & the new Prisma adapter

### ISSUE THREAD

**Issue by icflorescu** [nextauthjs/next-auth#2144]
## Description 🐜

While trying to authenticate with GitHub provider on the new (**non**-legacy) Prisma adapter configuration, I'm getting this error:

```
[next-auth][error][prisma__get_user_by_provider_account_id_error]
https://next-auth.js.org/errors#prisma__get_user_by_provider_account_id_error PrismaClientValidationError:
Invalid `prisma.account.findUnique()` invocation:

{
  where: {
    providerId_providerAccountId: {
      providerId: 'github',
      providerAccountId: 123456
                         ~~~~~~
    }
  },
  select: {
    user: true
  }
}

Argument providerAccountId: Got invalid value 123456 on prisma.findUniqueAccount. Provided Int, expected String.

    at Document.validate (/[...]/node_modules/@prisma/client/runtime/index.js:32898:19)
    at NewPrismaClient._executeRequest (/[...]/node_modules/@prisma/client/runtime/index.js:34840:17)
    at /[...]/node_modules/@prisma/client/runtime/index.js:34775:52
    at AsyncResource.runInAsyncScope (node:async_hooks:199:9)
    at NewPrismaClient._request (/[...]/node_modules/@prisma/client/runtime/index.js:34775:25)
    at Object.then (/[...]/node_modules/@prisma/client/runtime/index.js:34895:39)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  clientVersion: '2.24.1'
```

The `providerAccountId` integer in the above snapshot was changed for obvious privacy reasons.

## How to reproduce ☕️

1. Fork this sandbox: https://codesandbox.io/s/next-auth-test-2o3s1?file=/.env
2. Set the appropriate variables in the `.env` file:
  - `NEXTAUTH_URL` to your forked sandbox browser URL (i.e. https://2o3s1.sse.codesandbox.io/)
  - `GITHUB_CLIENT_ID` and `GITHUB_CLIENT_SECRET` you'll need to create a GitHub app for that
3. Make sure the sandbox server is running and open the browser output in a new window (otherwise GitHub auth flow will not trigger), like this:
![image](https://user-images.githubusercontent.com/581999/121186062-5d77f600-c86f-11eb-88cc-477973e7d066.png)
4. Try to authenticate with GitHub - it won't work
5. Inspect the error in the sandbox console

## Screenshots / Logs 📽

Upon the unsuccessful login attempt, the browser will redirect to `/api/auth/signin?error=Callback`, showing this:
![image](https://user-images.githubusercontent.com/581999/121186756-16d6cb80-c870-11eb-8852-6d547ae7768a.png)

...but the above error message is visible in the server console.

## Environment 🖥

```
  System:
    OS: Linux 5.4 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (16) x64 AMD Ryzen 7 4800U with Radeon Graphics
    Memory: 5.52 GB / 11.99 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 16.3.0 - ~/.nvm/versions/node/v16.3.0/bin/node
    Yarn: 1.22.10 - /mnt/c/Users/ionut/AppData/Roaming/npm/yarn
    npm: 7.16.0 - ~/.nvm/versions/node/v16.3.0/bin/npm
```

## Contributing 🙌🏽

Not sure, but I'm guessing this has something to do with the refactoring involved in the transition from `prisma-legacy` to `prisma`. Maybe `NewPrismaClient` would be a good starting point?!... In which case, I wonder whether this bug doesn't affect other providers as well. My initial testcase included Google and GitHub. Google is working fine, GitHub is not.

**Comment by icflorescu** [comment]
Apologies, I should probably have raised this in `nextauthjs/adapters` in the first place.
