### ISSUE TITLE
Cannot run the project locally after cloning the repository

### ISSUE THREAD

**Issue by mahieyin-rahmun** [nextauthjs/next-auth#2277]
## Description 🐜

I am trying to setup a local development environment after cloning the NextAuth repository. I have followed all the steps mentioned in [CONTRIBUTING.md](https://github.com/nextauthjs/next-auth/blob/main/CONTRIBUTING.md#setting-up-local-environment). However, when I run the project using `npm run dev`, I get an error about React Hooks being called outside functional components, which makes no sense :(

## How to reproduce ☕️

1. Clone the repo. I forked the repo and then cloned it from the fork, but it should not have any difference.
2. Run `npm i && npm run dev:setup` in the root folder.
3. Create a `.env.local` file inside the `app` folder and populate it with any secrets that you may need.
4. Run `npm run dev` in the root folder.

## Screenshots / Logs 📽

Error log
```sh
npm run dev               

> next-auth@0.0.0-semantically-released dev
> cd app && npm run dev


> next-auth-app@1.0.0 dev /home/phantomhive/Documents/Code/open-source/mahieyin-next-auth-raw/app
> npm-run-all --parallel copy:app dev:css dev:next


> next-auth-app@1.0.0 copy:app /home/phantomhive/Documents/Code/open-source/mahieyin-next-auth-raw/app
> cpx "../src/**/*" next-auth --watch


> next-auth-app@1.0.0 dev:css /home/phantomhive/Documents/Code/open-source/mahieyin-next-auth-raw/app
> npm-run-all --parallel watch:css copy:css


> next-auth-app@1.0.0 dev:next /home/phantomhive/Documents/Code/open-source/mahieyin-next-auth-raw/app
> next dev

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Loaded env from /home/phantomhive/Documents/Code/open-source/mahieyin-next-auth-raw/app/.env.local

> next-auth-app@1.0.0 watch:css /home/phantomhive/Documents/Code/open-source/mahieyin-next-auth-raw/app
> cd .. && npm run watch:css


> next-auth-app@1.0.0 copy:css /home/phantomhive/Documents/Code/open-source/mahieyin-next-auth-raw/app
> cpx "../dist/css/**/*" dist/css --watch

info  - Using webpack 4. Reason: custom webpack configuration in next.config.js https://nextjs.org/docs/messages/webpack5

> next-auth@0.0.0-semantically-released watch:css /home/phantomhive/Documents/Code/open-source/mahieyin-next-auth-raw
> postcss --config config/postcss.config.js --watch src/**/*.css --base src --dir dist

event - compiled successfully
event - build page: /next/dist/pages/_error
wait  - compiling...
event - compiled successfully
Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
    at resolveDispatcher (/home/phantomhive/Documents/Code/open-source/mahieyin-next-auth-raw/node_modules/react/cjs/react.development.js:1476:13)
    at useContext (/home/phantomhive/Documents/Code/open-source/mahieyin-next-auth-raw/node_modules/react/cjs/react.development.js:1484:20)
    at useSession (/home/phantomhive/Documents/Code/open-source/mahieyin-next-auth-raw/node_modules/next-auth/dist/client/index.js:75:39)
    at Provider (/home/phantomhive/Documents/Code/open-source/mahieyin-next-auth-raw/node_modules/next-auth/dist/client/index.js:587:12)
    at processChild (/home/phantomhive/Documents/Code/open-source/mahieyin-next-auth-raw/app/node_modules/react-dom/cjs/react-dom-server.node.development.js:3353:14)
    at resolve (/home/phantomhive/Documents/Code/open-source/mahieyin-next-auth-raw/app/node_modules/react-dom/cjs/react-dom-server.node.development.js:3270:5)
    at ReactDOMServerRenderer.render (/home/phantomhive/Documents/Code/open-source/mahieyin-next-auth-raw/app/node_modules/react-dom/cjs/react-dom-server.node.development.js:3753:22)
    at ReactDOMServerRenderer.read (/home/phantomhive/Documents/Code/open-source/mahieyin-next-auth-raw/app/node_modules/react-dom/cjs/react-dom-server.node.development.js:3690:29)
    at renderToString (/home/phantomhive/Documents/Code/open-source/mahieyin-next-auth-raw/app/node_modules/react-dom/cjs/react-dom-server.node.development.js:4298:27)
    at Object.renderPage (/home/phantomhive/Documents/Code/open-source/mahieyin-next-auth-raw/app/node_modules/next/dist/next-server/server/render.js:54:854)
    at Function.getInitialProps (webpack-internal:///./node_modules/next/dist/pages/_document.js:211:19)
    at loadGetInitialProps (/home/phantomhive/Documents/Code/open-source/mahieyin-next-auth-raw/app/node_modules/next/dist/next-server/lib/utils.js:5:101)
    at renderToHTML (/home/phantomhive/Documents/Code/open-source/mahieyin-next-auth-raw/app/node_modules/next/dist/next-server/server/render.js:54:1145)
    at async /home/phantomhive/Documents/Code/open-source/mahieyin-next-auth-raw/app/node_modules/next/dist/next-server/server/next-server.js:112:97
    at async /home/phantomhive/Documents/Code/open-source/mahieyin-next-auth-raw/app/node_modules/next/dist/next-server/server/next-server.js:105:142
    at async DevServer.renderToHTMLWithComponents (/home/phantomhive/Documents/Code/open-source/mahieyin-next-auth-raw/app/node_modules/next/dist/next-server/server/next-server.js:137:387)

```

## Environment 🖥

```sh
System:
    OS: Linux 5.8 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (6) x64 AMD Ryzen 5 4500U with Radeon Graphics
    Memory: 1.38 GB / 15.11 GB
    Container: Yes
    Shell: 5.8 - /bin/zsh
Binaries:
  Node: 14.15.1 - ~/.nvm/versions/node/v14.15.1/bin/node
  Yarn: 1.22.10 - ~/.nvm/versions/node/v14.15.1/bin/yarn
  npm: 6.14.13 - ~/Documents/Code/open-source/mahieyin-next-auth-raw/node_modules/.bin/npm
Browsers:
  Chrome: 90.0.4430.212
  Firefox: 89.0.2
npmPackages:
  next: ^10.0.5 => 10.2.3 
  react: ^17.0.1 => 17.0.2 
```

## Contributing 🙌🏽

I am currently trying to figure out a cause, but I can't find any instance where there has been a hook call outside a functional component. I also haven't made any changes to any of the files. However, if this is indeed some sort of legitimate issue and I can find out a cause, I will open a PR.

**Comment by mahieyin-rahmun** [comment]
I was able to get it working locally after doing the following:

- Run `npm link` in `node_modules/react/` under project root folder.
- Run `cd app/`
- Run `npm link react` inside the app folder.

Should this be included in the documentation?

On a side note, it does seem like there are two different versions of `react` and `next` being referenced. Could that be the issue as well?

[root/package.json](https://github.com/nextauthjs/next-auth/blob/main/package.json#L125)
```json
    "next": "^10.0.5",
    "postcss-cli": "^7.1.1",
    "postcss-nested": "^4.2.1",
    "prettier": "^2.2.1",
    "pretty-quick": "^3.1.0",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
```

[root/app/package.json](https://github.com/nextauthjs/next-auth/blob/main/app/package.json#L17)
```json
    "next": "^10.1.3",
    "react": "^17.0.2",
    "react-dom": "^17.0.2"
```

**Comment by balazsorban44** [comment]
So glad if you managed to fix it so easily! But I think there might be an easier fix. I think it is because we have a mismatch of `react` versions in the `root/package.json` and `root/app/package.json`. I'll try to verify if bumping the root version would be enough and report back here.

**Comment by balazsorban44** [comment]
Thanks again for reporting @mahieyin-rahmun! With the provided information, I could pinpoint the issue and I can gladly say that #2280 fixes it!
