### ISSUE TITLE
GitHub or GitLab providers + Prisma (+ PostgreSQL?) results in PrismaClientValidationError

### ISSUE THREAD

**Issue by ivanmaeder** [nextauthjs/next-auth#2317]
### Description 🐜

Logging in with the GitHub or GitLab providers results in a `PrismaClientValidationError`.

```
Argument providerAccountId: Got invalid value 2310208 on prisma.findUniqueAccount. Provided Int, expected String.
```

### Is this a bug in your own project?

Yes

### How to reproduce ☕️

Trigger the GitHub sign in action:

```
signIn('github', { callbackUrl }, { scope: 'user.email' })
```

Or GitLab:

```
signIn('gitlab', { callbackUrl })
```

I was able to provide a quick fix by converting the values to strings in my `./node_modules/@next-auth/prisma-adapter/dist/index.js`,

```
                        data: {
                            name: profile.name,
                            email: profile.email,
                            image: profile.image,
                            emailVerified: (_b = (_a = profile.emailVerified) === null || _a === void 0 ? void 0 : _a.toISOString()) !== null && _b !== void 0 ? _b : null,
                            ...profile,
                            id: `${ profile.id }` // ADDED THIS LINE (LINE 26)
                        },

//...

                            providerId_providerAccountId: { providerId, providerAccountId: `${ providerAccountId }` }, // MODIFIED LINE 44 (PREVIOUSLY LINE 43)

//...

                        data: {
                            userId,
                            providerId,
                            providerType,
                            providerAccountId: `${ providerAccountId }`, //MODIFIED LINE 73 (PREVIOUSLY LINE 72)
                            refreshToken,
                            accessToken,
                            accessTokenExpires,
                        },
```

### Screenshots / Logs 📽

GitHub is the same but with a different `providerId` and `providerAccountId`.

```
[next-auth][error][prisma__get_user_by_provider_account_id_error] 
https://next-auth.js.org/errors#prisma__get_user_by_provider_account_id_error PrismaClientValidationError: 
Invalid `prisma.account.findUnique()` invocation:

{
  where: {
    providerId_providerAccountId: {
      providerId: 'gitlab',
      providerAccountId: 2310208
                         ~~~~~~~
    }
  },
  select: {
    user: true
  }
}

Argument providerAccountId: Got invalid value 2310208 on prisma.findUniqueAccount. Provided Int, expected String.


    at Document.validate (/srv/node_modules/@prisma/client/runtime/index.js:32626:19)
    at NewPrismaClient._executeRequest (/srv/node_modules/@prisma/client/runtime/index.js:34733:17)
    at consumer (/srv/node_modules/@prisma/client/runtime/index.js:34678:23)
    at /srv/node_modules/@prisma/client/runtime/index.js:34680:47
    at AsyncResource.runInAsyncScope (node:async_hooks:199:9)
    at NewPrismaClient._request (/srv/node_modules/@prisma/client/runtime/index.js:34680:25)
    at Object.then (/srv/node_modules/@prisma/client/runtime/index.js:34788:39)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  clientVersion: '2.26.0'
}
[next-auth][error][oauth_callback_handler_error] 
https://next-auth.js.org/errors#oauth_callback_handler_error Error: 
Invalid `prisma.account.findUnique()` invocation:

{
  where: {
    providerId_providerAccountId: {
      providerId: 'gitlab',
      providerAccountId: 2310208
                         ~~~~~~~
    }
  },
  select: {
    user: true
  }
}

Argument providerAccountId: Got invalid value 2310208 on prisma.findUniqueAccount. Provided Int, expected String.


    at Document.validate (/srv/node_modules/@prisma/client/runtime/index.js:32626:19)
    at NewPrismaClient._executeRequest (/srv/node_modules/@prisma/client/runtime/index.js:34733:17)
    at consumer (/srv/node_modules/@prisma/client/runtime/index.js:34678:23)
    at /srv/node_modules/@prisma/client/runtime/index.js:34680:47
    at AsyncResource.runInAsyncScope (node:async_hooks:199:9)
    at NewPrismaClient._request (/srv/node_modules/@prisma/client/runtime/index.js:34680:25)
    at Object.then (/srv/node_modules/@prisma/client/runtime/index.js:34788:39)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  name: 'GetUserByProviderAccountIdError'
}
```

### Environment 🖥

```
  System:
    OS: Linux 5.10 Alpine Linux
    CPU: (1) x64 Intel(R) Core(TM) i5-3427U CPU @ 1.80GHz
    Memory: 57.58 MB / 1.94 GB
    Container: Yes
    Shell: 1.31.1 - /bin/ash
  Binaries:
    Node: 16.0.0 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 7.10.0 - /usr/local/bin/npm
  npmPackages:
    next: 10.2.3 => 10.2.3 
    next-auth: ^3.27.1 => 3.27.1 
    react: 17.0.2 => 17.0.2 
```

☝️ That's from inside the Docker container running the project (image node:16.0.0-alpine3.11).

**@next-auth/prisma-adapter**: 0.4.4-canary.81
**@prisma/client**: 2.26.0
**next-auth**: 3.27.1
**prisma**: 2.26.0

I was also getting the GitHub error with these versions (didn't try GitLab),

**@next-auth/prisma-adapter**: 0.4.4-canary.64
**@prisma/client**: 2.24.1
**next-auth**: 3.26.1
**prisma**: 2.24.1

This is the first time I try to set up GitHub or GitLab auth (I've never seen them work in my app). I did successfully configure Twitter auth today and I have been running Google auth for a while.

I also have a credentials provider configured with an extra `User.password` field (in the NextAuth.js `User` table).

The Prisma schema `Account.providerAccountId` field is of type `String`. Other Prisma settings:

```
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["orderByAggregateGroup"]
}
```

For the DB I'm using the Docker postgres:9.6.21-alpine image.

### Contributing 🙌🏽

Yes,  I am willing to help solve this bug in a PR

**Comment by ivanmaeder** [comment]
I've just realised that this might be more relevant in the [nextauthjs/adapters](https://github.com/nextauthjs/adapters) repo instead of here. Let me know if I should post it there.

**Comment by balazsorban44** [comment]
It's also a duplicate, already fixed on v4. See the release notes/merged PRs

**Comment by ivanmaeder** [comment]
@balazsorban44 I'm still getting this error with **4.0.0-next.18**:

```
[next-auth][error][oauth_callback_handler_error] 
https://next-auth.js.org/errors#oauth_callback_handler_error PrismaClientValidationError: 
Invalid `prisma.account.findUnique()` invocation:

{
  where: {
    providerId_providerAccountId: {
      providerId: 'github',
      providerAccountId: 1976478
                         ~~~~~~~
    }
  },
  select: {
    user: true
  }
}

Argument providerAccountId: Got invalid value 1976478 on prisma.findUniqueAccount. Provided Int, expected String.


    at Document.validate (/srv/node_modules/@prisma/client/runtime/index.js:32626:19)
    at NewPrismaClient._executeRequest (/srv/node_modules/@prisma/client/runtime/index.js:34733:17)
    at consumer (/srv/node_modules/@prisma/client/runtime/index.js:34678:23)
    at /srv/node_modules/@prisma/client/runtime/index.js:34680:47
    at AsyncResource.runInAsyncScope (node:async_hooks:199:9)
    at NewPrismaClient._request (/srv/node_modules/@prisma/client/runtime/index.js:34680:25)
    at Object.then (/srv/node_modules/@prisma/client/runtime/index.js:34788:39)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  clientVersion: '2.26.0'
}
```

This is the updated environment:

```
  System:
    OS: Linux 5.10 Alpine Linux
    CPU: (1) x64 Intel(R) Core(TM) i5-3427U CPU @ 1.80GHz
    Memory: 79.72 MB / 1.94 GB
    Container: Yes
    Shell: 1.31.1 - /bin/ash
  Binaries:
    Node: 16.0.0 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 7.10.0 - /usr/local/bin/npm
  npmPackages:
    next: 10.2.3 => 10.2.3 
    next-auth: ^4.0.0-next.18 => 4.0.0 
    react: 17.0.2 => 17.0.2 
```

The PR you point to refers to `profile.id` being made a string, not the `providerAccountId`.

Am I missing something? Could it maybe be an adapter issue and not core to NextAuth.js?

Thanks!

**Comment by balazsorban44** [comment]
you can trace it back to this line

https://github.com/nextauthjs/next-auth/blob/0fae0c7a8eb224964e38da409ecb9ba0497e8c50/src/server/lib/oauth/callback.js#L137

**Comment by ivanmaeder** [comment]
I'll do that, thanks.

**Comment by ivanmaeder** [comment]
I just did a proper search in the adapters repo and found some links that you provided [here](https://github.com/nextauthjs/adapters/issues/144). In one of those there's a [workaround](https://github.com/nextauthjs/adapters/issues/130#issuecomment-856995741) that's done the trick.

Thanks @balazsorban44 👍
