### ISSUE TITLE
Unable to build the project with next@11 due to typeorm requirements

### ISSUE THREAD

**Issue by TeosVerdi** [nextauthjs/next-auth#2358]
### Description 🐜

Follow-up to #988, `next`'s move to `webpack 5` disallows building a project using Next-Auth.
On build, Next-Auth asks for every database package to be installed due to typeorm's requirements, although there are none in the configuration file. (as seen in `[...nextauth].ts`)
I'm not using `target: 'serverless'`, as suggested in beforementioned issue.

### Is this a bug in your own project?

No

### How to reproduce ☕️

Run `next build`

### Screenshots / Logs 📽

The error itself:
```
info  - Loaded env from C:\brrrrrrr\.env
(node:12584) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `node --trace-warnings ...` to show where the warning was created)
info  - Checking validity of types  
info  - Creating an optimized production build  
Failed to compile.

ModuleNotFoundError: Module not found: Error: Can't resolve 'mongodb' in 'C:\brrrrrrr\.yarn\cache\typeorm-npm-0.2.34-590a97efd6-1bf2488a19.zip\node_modules\typeorm\platform'     


> Build error occurred
Error: > Build failed because of webpack errors
    at C:\brrrrrrr\.yarn\$$virtual\next-virtual-f70edc9490\0\cache\next-npm-11.0.1-c40bc7f380-823700a2a0.zip\node_modules\next\dist\build\index.js:15:924
    at async Span.traceAsyncFn (C:\brrrrrrr\.yarn\$$virtual\next-virtual-f70edc9490\0\cache\next-npm-11.0.1-c40bc7f380-823700a2a0.zip\node_modules\next\dist\telemetry\trace\trace.js:6:584)
```

This error reproduces even after installing the `mongodb` package, next time asking for a different one.

next.config.js:
```js
/* eslint-disable @typescript-eslint/no-var-requires */
const path = require('path');
const { i18n } = require('./next-i18next.config');
// IEKILL
const withTM = require('next-transpile-modules')(['next-auth']);

module.exports = withTM({
  productionBrowserSourceMaps: true,
  i18n,
  webpack: (config, { isServer }) => {
    config.module.rules.push({
      test: /\.svg$/,
      use: ['@svgr/webpack'],
    });

    if (!isServer) {
      config.resolve.alias['@sentry/node'] = '@sentry/browser';
      // IEKILL
      config.resolve.alias['react-hook-form'] =
        'react-hook-form/dist/index.ie11';
    }
    return config;
  },
  sassOptions: {
    includePaths: [path.join(__dirname, 'src/styles')],
    prependData: `@use "sass:math"; @import "global/variables.scss";`,
  },
});
```
[...nextauth].ts 

```js
const options = {
  pages: {
    signIn: '/auth/signin',
  },
  providers: [
    <List of providers>
  ],
  session: {
    jwt: true,
  },
  callbacks: {
    async redirect(url, baseUrl) {
      return url.startsWith(baseUrl) ? url : baseUrl + url;
    },
    async jwt(token, user, account) {
      if (account && user) {
        return {
          accessToken: account.access_token,
          accessTokenExpires: Date.now() + account.expires_in * 1000,
          refreshToken: account.refresh_token,
          user,
        };
      }

      // Return previous token if the access token has not expired yet
      if (
        typeof token.accessTokenExpires === 'number' &&
        Date.now() < token.accessTokenExpires
      ) {
        return token;
      }

      // Access token has expired, try to update it
      return refreshAccessToken(token);
    },
    async session(session, token) {
      if (token) {
        session.user = token.user;
        session.accessToken = token.accessToken;
        session.error = token.error;
      }

      return session;
    },
  },
};

export default (req, res) => NextAuth(req, res, options);
```

### Environment 🖥

  System:
    OS: Windows 10 10.0.19043
    CPU: (16) x64 AMD Ryzen 7 3700X 8-Core Processor
    Memory: 18.84 GB / 31.91 GB
  Binaries:
    Node: 14.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 2.4.2 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1023.0), Chromium (91.0.864.67)
    Internet Explorer: 11.0.19041.1

**Next.js**: 11.0.1
**Next-Auth**: ^3.27.1

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
Interesting. Could you try to recreate this with the provided CodeSandbox templates?

our example runs smoothly with next 11, see https://github.com/nextauthjs/next-auth-example

**Comment by TeosVerdi** [comment]
@balazsorban44 
Removing `next-transpile-modules` helped, thank you!
I'll close the issue, but in case someone else feels to still consider this a bug, they can reopen it.

**Comment by TeosVerdi** [comment]
@balazsorban44 
Although, i have noticed next-auth doesn't translate well to IE11 without `next-transpile-modules`.

Error: `SCRIPT1006: Expected ')'`
Lines this refers to: 
```
function setLogger(newLogger = {}) {
  if (newLogger.error) _logger.error = newLogger.error;
  if (newLogger.warn) _logger.warn = newLogger.warn;
  if (newLogger.debug) _logger.debug = newLogger.debug;
}

var _default = _logger;
exports.default = _default;

```
