### ISSUE TITLE
Google broken for new sign ups / account links

### ISSUE THREAD

**Issue by bduff9** [nextauthjs/next-auth#2544]
### Description 🐜

Why was this report moved to discussions?  https://github.com/nextauthjs/next-auth/discussions/2243

This seems to be a bug with either this library or something changed with Google.  For some reason, the error logs for this do not show up when running in a non-local env, but in local, the following gets printed:

```
[next-auth][error][oauth_callback_handler_error] 
https://next-auth.js.org/errors#oauth_callback_handler_error QueryFailedError: Column 'AccountAccessTokenExpires' cannot be null
    at new QueryFailedError (/Users/bduffey2/projects/nfl-pool-serverless/nfl-pool-fe/node_modules/typeorm/error/QueryFailedError.js:12:28)
    at Query.onResult (/Users/bduffey2/projects/nfl-pool-serverless/nfl-pool-fe/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:217:45)
    at Query.execute (/Users/bduffey2/projects/nfl-pool-serverless/nfl-pool-fe/node_modules/mysql2/lib/commands/command.js:31:14)
    at PoolConnection.handlePacket (/Users/bduffey2/projects/nfl-pool-serverless/nfl-pool-fe/node_modules/mysql2/lib/connection.js:456:32)
    at PacketParser.onPacket (/Users/bduffey2/projects/nfl-pool-serverless/nfl-pool-fe/node_modules/mysql2/lib/connection.js:85:12)
    at PacketParser.executeStart (/Users/bduffey2/projects/nfl-pool-serverless/nfl-pool-fe/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/Users/bduffey2/projects/nfl-pool-serverless/nfl-pool-fe/node_modules/mysql2/lib/connection.js:92:25)
    at Socket.emit (events.js:310:20)
    at Socket.EventEmitter.emit (domain.js:505:15)
    at addChunk (_stream_readable.js:286:12) {
  message: "Column 'AccountAccessTokenExpires' cannot be null",
  code: 'ER_BAD_NULL_ERROR',
  errno: 1048,
  sqlState: '23000',
  sqlMessage: "Column 'AccountAccessTokenExpires' cannot be null",
  sql: "INSERT INTO `Accounts`(`AccountID`, `AccountCompoundID`, `UserID`, `AccountProviderType`, `AccountProviderID`, `AccountProviderAccountID`, `AccountRefreshToken`, `AccountAccessToken`, `AccountAccessTokenExpires`, `AccountAdded`, `AccountUpdated`, `AccountAddedBy`, `AccountUpdatedBy`) VALUES (DEFAULT, '4...eb', 1, 'oauth', 'google', '107...63', DEFAULT, 'ya..._X', NULL, DEFAULT, DEFAULT, 'NEXT_AUTH', 'NEXT_AUTH')",
  name: 'QueryFailedError',
  query: 'INSERT INTO `Accounts`(`AccountID`, `AccountCompoundID`, `UserID`, `AccountProviderType`, `AccountProviderID`, `AccountProviderAccountID`, `AccountRefreshToken`, `AccountAccessToken`, `AccountAccessTokenExpires`, `AccountAdded`, `AccountUpdated`, `AccountAddedBy`, `AccountUpdatedBy`) VALUES (DEFAULT, ?, ?, ?, ?, ?, DEFAULT, ?, ?, DEFAULT, DEFAULT, ?, ?)',
  parameters: [
    '4d...eb',
    1,
    'oauth',
    'google',
    '10...63',
    'ya..._X',
    null,
    'NEXT_AUTH',
    'NEXT_AUTH'
  ]
}
```

If I manually change my AccountAccessTokenExpires column to allow nulls, it works again.  And if I had an account that was linked before, it can be used to log in even without the null change.  But whatever this change is seems to have broken all new Google logins completely without modifying the Accounts database table.

### Is this a bug in your own project?

No

### How to reproduce ☕️

https://codesandbox.io/s/next-auth-example-1kktb

Go to your codesandbox example, and click log in with Google

### Environment 🖥

  System:
    OS: macOS 11.2.3
    CPU: (8) x64 Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
    Memory: 90.44 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.16.2 - /usr/local/bin/node
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 2021.06.07.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 93.0.4577.42
    Firefox Developer Edition: 89.0
    Safari: 14.0.3
  npmPackages:
    next: 11.1.0 => 11.1.0 
    next-auth: <3.18.0 => 3.17.2 
    react: 17.0.2 => 17.0.2 

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
It was very limited, with no reproduction or a proper explanation, and also labeled as a question:

https://github.com/nextauthjs/next-auth/issues/419

> When you fill out the "Question" template, we are going to convert it to Discussions. 

Unfortunately, GitHub doesn't have a good UI to make this more visible.


This looks like an Adapter issue though, so I will transfer it there.

cc @ndom91 any ideas?
