### ISSUE TITLE
Typeorm OPTIONAL_MODULE_NOT_FOUND

### ISSUE THREAD

**Issue by danhab99** [nextauthjs/next-auth#2638]
### Description 🐜

I'm getting this error whenever `next-auth` tries to do a DB operation, but not with my mongoose connection.

```
[next-auth][error][session_error] 
https://next-auth.js.org/errors#session_error Error: optional dependency [mongodb] found but version [4.1.1] did not satisfy constraint [^3.5.9]
    at require_optional (/home/dan/Documents/node/secret_project1/node_modules/require_optional/index.js:109:19)
    at Object.getAdapter (/home/dan/Documents/node/secret_project1/node_modules/@next-auth/typeorm-legacy-adapter/dist/index.js:104:55)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.session (/home/dan/Documents/node/secret_project1/node_modules/next-auth/dist/server/routes/session.js:81:38) {
  code: 'OPTIONAL_MODULE_NOT_FOUND'
}

```

### Is this a bug in your own project?

Yes

### How to reproduce ☕️

Using:

* mongoose `5.13.5`
* next-auth `^3.28.0`
* MongoDB server `5.0.2`

```typescript
// pages/api/auth/[...nextauth].tsx
import NextAuth from "next-auth";
import Providers from "next-auth/providers";

export default NextAuth({
  providers: [
    Providers.Google({
      clientId: process.env.GOOGLE_ID,
      clientSecret: process.env.GOOGLE_SECRET,
    }),
  ],

  database: process.env.MONGO_SRV,
  secret: process.env.COOKIE_SECRET,
  session: {
    maxAge: 30 * 24 * 60 * 60, // 30 days
    updateAge: 24 * 60 * 60, // 24 hours
  },

  pages: {
    signIn: "/auth/signin",
    signOut: "/auth/signout",
    error: "/auth/error", // Error code passed in query string as ?error=
  },

  callbacks: {
    session: async (session, user) => {
      session.user.id = user.id as any;
      return Promise.resolve(session);
    },
  },
});
```

Observe that warning being spat out at random intervals, or when trying to signin with Google.

### Environment 🖥

```
  System:
    OS: Linux 5.10 Manjaro Linux
    CPU: (20) x64 Intel(R) Core(TM) i9-10850K CPU @ 3.60GHz
    Memory: 19.25 GB / 31.25 GB
    Container: Yes
    Shell: 5.1.8 - /bin/bash
  Binaries:
    Node: 16.6.2 - /usr/bin/node
    Yarn: 1.22.11 - /usr/bin/yarn
    npm: 7.20.6 - /usr/bin/npm
  Browsers:
    Brave Browser: unknown
  npmPackages:
    next: 11.1.0 => 11.1.0 
    next-auth: ^3.28.0 => 3.28.0 
    react: 17.0.2 => 17.0.2 
```

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by danhab99** [comment]
Resolved by adding `mongodb@3.5.9` to my dependencies

```
yarn add mongodb@3.5.9
```
