### ISSUE TITLE
Cannot build with nextjs and typescript due to ModuleNotFoundError

### ISSUE THREAD

**Issue by abnerlee** [nextauthjs/next-auth#2697]
### Description 🐜

When run `yarn build`, webpack prints error

```
Failed to compile.

ModuleNotFoundError: Module not found: Error: Package path ./react is not exported from package ~/my-app/p/node_modules/next-auth (see exports field in ~/my-app/node_modules/next-auth/package.json)
```

### Is this a bug in your own project?

No

### How to reproduce ☕️

1. Follow https://nextjs.org/docs/basic-features/typescript, run
    
   ```
   yarn create next-app --typescript
   ```

2. run `yarn add next-auth` in that newly created project

3. Add a sample page at `page/admin.js` following https://next-auth.js.org/getting-started/example

```
import { useSession, signIn, signOut } from "next-auth/react";

export default function Component() {
  const { data: session } = useSession();
  if (session) {
    return (
      <>
        Signed in as {session.user.email} <br />
        <button onClick={() => signOut()}>Sign out</button>
      </>
    );
  }
  return (
    <>
      Not signed in <br />
      <button onClick={() => signIn()}>Sign in</button>
    </>
  );
}
```

4. run `yarn build`

   Now you got the error message

```
Failed to compile.

ModuleNotFoundError: Module not found: Error: Package path ./react is not exported from package ~/my-app/p/node_modules/next-auth (see exports field in ~/my-app/node_modules/next-auth/package.json)
```

### Screenshots / Logs 📽

```
yarn run v1.22.10
$ next build
info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
info  - Checking validity of types  
info  - Creating an optimized production build  
Failed to compile.

ModuleNotFoundError: Module not found: Error: Package path ./react is not exported from package /home/admin/workspace/my-app/node_modules/next-auth (see exports field in /home/admin/workspace/my-app/node_modules/next-auth/package.json)


> Build error occurred
Error: > Build failed because of webpack errors
    at /home/admin/workspace/my-app/node_modules/next/dist/build/index.js:397:19
    at async Span.traceAsyncFn (/home/admin/workspace/my-app/node_modules/next/dist/telemetry/trace/trace.js:60:20)
    at async Object.build [as default] (/home/admin/workspace/my-app/node_modules/next/dist/build/index.js:77:25)
error Command failed with exit code 1.
```

### Environment 🖥

It happens in Linux, node 14.16.1
And also fail when deploying to vercel

In my linux:

```
npmPackages "next,next-auth,react"
npx: installed 1 in 1.62s

  System:
    OS: Linux 4.14 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Celeron(R) J4125 CPU @ 2.00GHz
    Memory: 1.25 GB / 15.54 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 14.16.1 - ~/.nvs/node/14.16.1/x64/bin/node
    Yarn: 1.22.10 - ~/.nvs/node/14.16.1/x64/bin/yarn
    npm: 6.14.12 - ~/.nvs/node/14.16.1/x64/bin/npm
  Browsers:
    Chrome: 89.0.4389.90
    Firefox: 91.0.2
  npmPackages:
    next: 11.1.2 => 11.1.2 
    next-auth: ^3.29.0 => 3.29.0 
    react: 17.0.2 => 17.0.2 
```

### Contributing 🙌🏽

Yes,  I am willing to help solve this bug in a PR

**Comment by balazsorban44** [comment]
Be aware of the banner at the top of the documentation. You have installed v3, but you were looking at the v4 docs.

Go to https://next-auth.js.org/v3/getting-started/client if you want to use v3 still.

(hint, in your case, the import path is `next-auth/client`, not `next-auth/react`)

**Comment by ninsau** [comment]
Help please. My build keeps failing on production due to this reason. I'm not sure how to fix it

```
2021-12-06T09:35:11.0202372Z Error: > Build failed because of webpack errors

2021-12-06T09:35:11.0203202Z at nextBuildSpan.traceAsyncFn (/var/www/html/node_modules/next/dist/build/index.js:397:19)
```

**Comment by ninsau** [comment]
> 11.1.2

I downgraded to nextjs v11.1.2 and also next-auth v13.29.0 and it's working now. Is this the best fix ?

**Comment by EmmanuelN1** [comment]
I fixed mine by updating my codes to v4 using https://next-auth.js.org/getting-started/upgrade-v4.
Hope it works for you
