### ISSUE TITLE
OAUTH_PARSE_PROFILE_ERROR using AzureAD Provider

### ISSUE THREAD

**Issue by haydenisler** [nextauthjs/next-auth#2772]
### Question 💬

Howdy,

I've been testing the built in AzureAD provider in 4.0.0-beta.2 and have run into an issue that is preventing me from successfully completing the login flow.

After every sign in attempt, I receive an `OAUTH_PARSE_PROFILE_ERROR`. This occurs due to this line:
https://github.com/nextauthjs/next-auth/blob/a2c4046772d77754dffee1254e8321c263096537/src/server/lib/oauth/callback.ts#L149

The OAuthProfile returned on log-in attempt does not contain an id property which causes the `.toString()` to fail in `getProfile()`.

I've seemed to configure my AzureAD app registration + api permissions correctly.

My question: could this possibly be a bug in the beta build? Or is this a problem with my configuration?

Thanks in advance.

### How to reproduce ☕️

**Console Output:**
```
[next-auth][error][OAUTH_PARSE_PROFILE_ERROR]
https://next-auth.js.org/errors#oauth_parse_profile_error Cannot read property 'toString' of undefined {
  error: {
    message: "Cannot read property 'toString' of undefined",
    stack: "TypeError: Cannot read property 'toString' of undefined\n" +
      '    at getProfile (C:\\Users\\hisler\\web\\dynamic-systems\\dist\\apps\\pto-dashboard\\.next\\server\\pages\\api\\auth\\[...nextauth].js:1793:39)\n' +
      '    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n' +
      '    at async oAuthCallback (C:\\Users\\hisler\\web\\dynamic-systems\\dist\\apps\\pto-dashboard\\.next\\server\\pages\\api\\auth\\[...nextauth].js:1759:12)\n' +  
      '    at async Object.callback (C:\\Users\\hisler\\web\\dynamic-systems\\dist\\apps\\pto-dashboard\\.next\\server\\pages\\api\\auth\\[...nextauth].js:2565:11)\n' +
      '    at async NextAuthHandler (C:\\Users\\hisler\\web\\dynamic-systems\\dist\\apps\\pto-dashboard\\.next\\server\\pages\\api\\auth\\[...nextauth].js:835:18)\n' + 
      '    at async Object.apiResolver (C:\\Users\\hisler\\web\\dynamic-systems\\node_modules\\next\\dist\\server\\api-utils.js:101:9)\n' +
      '    at async DevServer.handleApiRequest (C:\\Users\\hisler\\web\\dynamic-systems\\node_modules\\next\\dist\\server\\next-server.js:760:9)\n' +
      '    at async Object.fn (C:\\Users\\hisler\\web\\dynamic-systems\\node_modules\\next\\dist\\server\\next-server.js:651:37)\n' +
      '    at async Router.execute (C:\\Users\\hisler\\web\\dynamic-systems\\node_modules\\next\\dist\\server\\router.js:205:32)\n' +
      '    at async DevServer.run (C:\\Users\\hisler\\web\\dynamic-systems\\node_modules\\next\\dist\\server\\next-server.js:825:29)',
    name: 'TypeError'
  },
  OAuthProfile: {
    sub: <omitted>,
    name: 'Hayden Isler',
    family_name: 'Isler',
    given_name: 'Hayden',
    picture: 'https://graph.microsoft.com/v1.0/me/photo/$value',
    email: <omitted>,
    user: null
  },
  message: "Cannot read property 'toString' of undefined"
}
```

**.../[nextauth].ts:**
```javascript
import { NextApiHandler } from 'next';
import NextAuth from 'next-auth';
import AzureADProvider from 'next-auth/providers/azure-ad';

const authHandler: NextApiHandler = (req, res) => NextAuth(req, res, options);

export default authHandler;

const options = {
  providers: [
    AzureADProvider({
      clientId: process.env.AZURE_AD_CLIENT_ID,
      clientSecret: process.env.AZURE_AD_CLIENT_SECRET,
      tenantId: process.env.AZURE_AD_TENANT_ID,
      wellKnown: process.env.AZURE_AD_OPENID,
      authorization: {
        params: {
          audience: process.env.AZURE_AD_CLIENT_ID,
          response_mode: 'form_post',
          response_type: 'code id_token',
          scope:
            'offline_access openid User.Read User.Read.All User.ReadBasic.All Mail.Send',
        },
      },
    }),
  ],
};

```

**Environment:**
```
System:
    OS: Windows 10 10.0.19043
    CPU: (8) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 18.08 GB / 31.76 GB
  Binaries:
    Node: 14.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.11 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 7.20.6 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 93.0.4577.82
    Edge: Spartan (44.19041.1023.0), Chromium (93.0.961.47)
    Internet Explorer: 11.0.19041.906
  npmPackages:
    next: 11.1.0 => 11.1.0
    next-auth: ^4.0.0-beta.2 => 4.0.0-beta.2
    react: 17.0.2 => 17.0.2
```

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment]
This thread might be useful: https://github.com/nextauthjs/next-auth/discussions/2690

**Comment by haydenisler** [comment]
Thanks for the direction towards fixing the issue, the suggestions in that thread have resolved my problem. I did have to move away from the built-in AzureAD configuration. My `auth/[...nextauth].ts` file now looks like the following:

```javascript
import { NextApiHandler } from 'next';
import NextAuth from 'next-auth';

const authHandler: NextApiHandler = (req, res) =>
  NextAuth(req, res, {
    providers: [
      {
        id: 'azure-ad',
        name: 'Azure Active Directory',
        type: 'oauth',
        authorization: {
          url: `https://login.microsoftonline.com/${process.env.AZURE_AD_TENANT_ID}/oauth2/v2.0/authorize?response_mode=query`,
          params: {
            audience: process.env.AZURE_AD_CLIENT_ID,
            scope:
              'offline_access openid User.Read User.Read.All User.ReadBasic.All Mail.Send',
          },
        },
        token: `https://login.microsoftonline.com/${process.env.AZURE_AD_TENANT_ID}/oauth2/v2.0/token`,
        wellKnown: process.env.AZURE_AD_OPENID,
        profile(profile) {
          return {
            id: profile.sub,
            ...profile,
          };
        },
        options: {
          clientId: process.env.AZURE_AD_CLIENT_ID,
          clientSecret: process.env.AZURE_AD_CLIENT_SECRET,
        },
      },
    ],
  });

export default authHandler;
```

Thanks again for the help.
