### ISSUE TITLE
Azure Active Directory XboxLive.signin scope not working

### ISSUE THREAD

**Issue by taep96** [nextauthjs/next-auth#2779]
### Description 🐜

I used this custom provider and it works but I am getting errors when I add XboxLive.signin scope

### Is this a bug in your own project?

Yes

### How to reproduce ☕️

```js
    providers: [
        {
            id: 'azure-ad',
            name: 'Microsoft Account',
            type: 'oauth',
            authorization: {
                url: `https://login.microsoftonline.com/consumers/oauth2/v2.0/authorize?response_mode=query`,
                params: {
                    scope: 'openid email profile offline_access User.Read', // XboxLive.signin
                },
            },
            token: `https://login.microsoftonline.com/consumers/oauth2/v2.0/token`,
            userinfo: 'https://graph.microsoft.com/oidc/userinfo',
            clientId: process.env.AZURE_AD_CLIENT_ID,
            clientSecret: process.env.AZURE_AD_CLIENT_SECRET,
            profile(profile) {
                return {
                    id: profile.sub,
                    name: profile.name,
                    email: profile.email,
                    image: profile.picture,
                };
            },
        },
    ],
```

### Screenshots / Logs 📽

```[next-auth][error][OAUTH_CALLBACK_ERROR] 
https://next-auth.js.org/errors#oauth_callback_error invalid_scope (AADSTS70011: The provided request must include a 'scope' input parameter.
Trace ID: ca99cfc2-61a8-47eb-822a-2e5fa7caa700
Correlation ID: 7b45c2b3-a6b4-4636-890a-1ec3ed77a61c
Timestamp: 2021-09-17 14:59:54Z) {
  error: {
    message: "invalid_scope (AADSTS70011: The provided request must include a 'scope' input parameter.\r\n" +
      'Trace ID: ca99cfc2-61a8-47eb-822a-2e5fa7caa700\r\n' +
      'Correlation ID: 7b45c2b3-a6b4-4636-890a-1ec3ed77a61c\r\n' +
      'Timestamp: 2021-09-17 14:59:54Z)',
    stack: "OPError: invalid_scope (AADSTS70011: The provided request must include a 'scope' input parameter.\r\n" +
      'Trace ID: ca99cfc2-61a8-47eb-822a-2e5fa7caa700\r\n' +
      'Correlation ID: 7b45c2b3-a6b4-4636-890a-1ec3ed77a61c\r\n' +
      'Timestamp: 2021-09-17 14:59:54Z)\n' +
      '    at processResponse (C:\\Users\\Nizomidin\\Documents\\GitHub\\lemonjuicer96\\node_modules\\openid-client\\lib\\helpers\\process_response.js:45:13)\n' +
      '    at Client.grant (C:\\Users\\Nizomidin\\Documents\\GitHub\\lemonjuicer96\\node_modules\\openid-client\\lib\\client.js:1237:26)\n' +
      '    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n' +
      '    at async oAuthCallback (C:\\Users\\Nizomidin\\Documents\\GitHub\\lemonjuicer96\\.next\\server\\pages\\api\\auth\\[...nextauth].js:1692:16)\n' +
      '    at async Object.callback (C:\\Users\\Nizomidin\\Documents\\GitHub\\lemonjuicer96\\.next\\server\\pages\\api\\auth\\[...nextauth].js:2524:11)\n' +
      '    at async NextAuthHandler (C:\\Users\\Nizomidin\\Documents\\GitHub\\lemonjuicer96\\.next\\server\\pages\\api\\auth\\[...nextauth].js:794:18)\n' +
      '    at async C:\\Users\\Nizomidin\\Documents\\GitHub\\lemonjuicer96\\.next\\server\\pages\\api\\auth\\[...nextauth].js:874:32\n' +
      '    at async Object.apiResolver (C:\\Users\\Nizomidin\\Documents\\GitHub\\lemonjuicer96\\node_modules\\next\\dist\\server\\api-utils.js:101:9)\n' +
      '    at async DevServer.handleApiRequest (C:\\Users\\Nizomidin\\Documents\\GitHub\\lemonjuicer96\\node_modules\\next\\dist\\server\\next-server.js:770:9)\n' +
      '    at async Object.fn (C:\\Users\\Nizomidin\\Documents\\GitHub\\lemonjuicer96\\node_modules\\next\\dist\\server\\next-server.js:661:37)',
    name: 'OPError'
  },
  providerId: 'azure-ad',
  message: "invalid_scope (AADSTS70011: The provided request must include a 'scope' input parameter.\r\n" +
    'Trace ID: ca99cfc2-61a8-47eb-822a-2e5fa7caa700\r\n' +
    'Correlation ID: 7b45c2b3-a6b4-4636-890a-1ec3ed77a61c\r\n' +
    'Timestamp: 2021-09-17 14:59:54Z)'
}
[next-auth][error][CALLBACK_OAUTH_ERROR] 
https://next-auth.js.org/errors#callback_oauth_error invalid_scope (AADSTS70011: The provided request must include a 'scope' input parameter.
Trace ID: ca99cfc2-61a8-47eb-822a-2e5fa7caa700
Correlation ID: 7b45c2b3-a6b4-4636-890a-1ec3ed77a61c
Timestamp: 2021-09-17 14:59:54Z) OPError: invalid_scope (AADSTS70011: The provided request must include a 'scope' input parameter.
Trace ID: ca99cfc2-61a8-47eb-822a-2e5fa7caa700
Correlation ID: 7b45c2b3-a6b4-4636-890a-1ec3ed77a61c
Timestamp: 2021-09-17 14:59:54Z)
    at processResponse (C:\Users\Nizomidin\Documents\GitHub\lemonjuicer96\node_modules\openid-client\lib\helpers\process_response.js:45:13)
    at Client.grant (C:\Users\Nizomidin\Documents\GitHub\lemonjuicer96\node_modules\openid-client\lib\client.js:1237:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async oAuthCallback (C:\Users\Nizomidin\Documents\GitHub\lemonjuicer96\.next\server\pages\api\auth\[...nextauth].js:1692:16)
    at async Object.callback (C:\Users\Nizomidin\Documents\GitHub\lemonjuicer96\.next\server\pages\api\auth\[...nextauth].js:2524:11)
    at async NextAuthHandler (C:\Users\Nizomidin\Documents\GitHub\lemonjuicer96\.next\server\pages\api\auth\[...nextauth].js:794:18)
    at async C:\Users\Nizomidin\Documents\GitHub\lemonjuicer96\.next\server\pages\api\auth\[...nextauth].js:874:32
    at async Object.apiResolver (C:\Users\Nizomidin\Documents\GitHub\lemonjuicer96\node_modules\next\dist\server\api-utils.js:101:9)
    at async DevServer.handleApiRequest (C:\Users\Nizomidin\Documents\GitHub\lemonjuicer96\node_modules\next\dist\server\next-server.js:770:9)
    at async Object.fn (C:\Users\Nizomidin\Documents\GitHub\lemonjuicer96\node_modules\next\dist\server\next-server.js:661:37) {
  name: 'OAuthCallbackError'
}
```

### Environment 🖥

  ```System:
    OS: Windows 10 10.0.19043
    CPU: (4) x64 AMD Ryzen 3 2200G with Radeon Vega Graphics    
    Memory: 1.03 GB / 5.93 GB
  Binaries:
    Node: 16.9.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.11 - C:\Program Files\nodejs\yarn.CMD
    npm: 7.21.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1023.0), Chromium (93.0.961.47)
    Internet Explorer: 11.0.19041.906
  npmPackages:
    next: 11.1.2 => 11.1.2 
    next-auth: 4.0.0-beta.2 => 4.0.0-beta.2 
    react: 17.0.2 => 17.0.2 
```

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by iaincollins** [comment]
Thanks for the detailed bug report! I wonder if this actually weird behaviour from Microsoft.

From https://stackoverflow.com/a/51789899  

> You are using the client credential flow here, which means that you cannot dynamically request scopes. You must configure your required permission scopes on your app registration in apps.dev.microsoft.com, then you set the value of scope in your code to https://graph.microsoft.com/.default.
> 
> See https://developer.microsoft.com/en-us/graph/docs/concepts/auth_v2_service for more details.

I'm not 100% certain of that is is correct in this instance but it might be helpful in investigating.

**Comment by TruRooms** [comment]
I was able to correct this in my app registrations.

Under 'API Access' the 'offline_access' permission needs to be added in order for the scope to be allowed.

**Comment by ekofi** [comment]
Same issue.

**Comment by balazsorban44** [comment]
Closing as this issue is kinda old. Let's open a new one with a fresh, minimal reproduction, if it still exists.
