### ISSUE TITLE
invalid_grant with Google Provider

### ISSUE THREAD

**Issue by ramiel** [nextauthjs/next-auth#2871]
### Description 🐜

I keep receiving `invalid_grant (Missing code verifier.)` error when trying to login with google. I have this issue only with version `4.0.0-beta.2` while version 3, with the same google id, is working fine.

Also, this was working yesterday, same code. The only difference is I reinstalled deps. This is the entry in my yarn.lock

```
next-auth@4.0.0-beta.2:
  version "4.0.0-beta.2"
  resolved "https://registry.yarnpkg.com/next-auth/-/next-auth-4.0.0-beta.2.tgz#b4a84c70f7a77a20447352748fa395647441047c"
  integrity sha512-WuY3T+9NhwZMKlq4y/YOLa1PUl+IgIfIcmhLLCxP7mSsB9b7VrlN5x4AwrY7oymUEFiCjNaLBQ2DU8/Rhhat/Q==
  dependencies:
    "@babel/runtime" "^7.14.6"
    futoin-hkdf "^1.3.3"
    jose "^1.27.2"
    oauth "^0.9.15"
    openid-client "^4.7.4"
    preact "^10.5.13"
    preact-render-to-string "^5.1.19"
```

What can it be?

### Is this a bug in your own project?

Yes

### How to reproduce ☕️

There's nothing special, just install a fresh veesion of next-auth and try a google provider

### Screenshots / Logs 📽

This is the log I get

```
https://next-auth.js.org/errors#oauth_callback_error invalid_grant (Missing code verifier.) {
  error: {
    message: 'invalid_grant (Missing code verifier.)',
    stack: 'OPError: invalid_grant (Missing code verifier.)\n' +
      '    at processResponse (/home/fabrizio/Modelli/Projects/hse/hypersay-events/sites/control-panel/node_modules/openid-client/lib/helpers/process_response.js:45:13)\n' +
      '    at Client.grant (/home/fabrizio/Modelli/Projects/hse/hypersay-events/sites/control-panel/node_modules/openid-client/lib/client.js:1238:26)\n' +
      '    at runMicrotasks (<anonymous>)\n' +
      '    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n' +
      '    at async Client.callback (/home/fabrizio/Modelli/Projects/hse/hypersay-events/sites/control-panel/node_modules/openid-client/lib/client.js:460:24)\n' +
      '    at async oAuthCallback (webpack-internal:///./node_modules/next-auth/server/lib/oauth/callback.js:87:16)\n' +
      '    at async Object.callback (webpack-internal:///./node_modules/next-auth/server/routes/callback.js:50:11)\n' +
      '    at async NextAuthHandler (webpack-internal:///./node_modules/next-auth/server/index.js:171:18)\n' +
      '    at async eval (webpack-internal:///./node_modules/next-auth/server/index.js:251:32)\n' +
      '    at async Object.apiResolver (/home/fabrizio/Modelli/Projects/hse/hypersay-events/sites/control-panel/node_modules/next/dist/server/api-utils.js:101:9)',
    name: 'OPError'
  },
  providerId: 'google',
  message: 'invalid_grant (Missing code verifier.)'
}

```

### Environment 🖥

```
  System:
    OS: Linux 5.11 KDE neon 5.22
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 1.53 GB / 15.50 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 14.18.0 - /usr/bin/node
    Yarn: 1.22.11 - ~/.npm-global/bin/yarn
    npm: 6.14.15 - /usr/bin/npm
  Browsers:
    Brave Browser: 94.1.30.86
    Chrome: 94.0.4606.71
    Firefox: 92.0
  npmPackages:
    next: ^11.1.2 => 11.1.2 
    next-auth: 4.0.0-beta.2 => 4.0.0-beta.2 
    react: 17.0.2 => 17.0.2
```

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
have reproduction?

**Comment by ramiel** [comment]
My configuration is exactly the same. I have no reproduction atm, let me see if I can provide one

**Comment by ramiel** [comment]
I just found the issue. It was a configuration of mine on cookies, the domain set was wrong. I'm closing this

**Comment by balazsorban44** [comment]
My next suggestion would have been to check cookies. 😅

**Comment by yuklai** [comment]
Sorry, mind sharing what was the cookie configuration that caused this? I followed the migration guide from V3 to V4, and nothing else really changed. But now my app is getting invalid_grant for gmail integration.
