### ISSUE TITLE
[Beta] Server Callback - getProfile() : Error when profile.id is undefined

### ISSUE THREAD

**Issue by Chris-Sytadelle** [nextauthjs/next-auth#2872]
### Description 🐜

Callback fails when profile.id is null or undefined.

Source (beta) : /src/server/lib/oauth/callback.ts#L150

This is new in the beta.

### Is this a bug in your own project?

No

### How to reproduce ☕️

Use a custom Provider with no profile id returned (I have an example with a client).

### Screenshots / Logs 📽

2021-10-01T10:20:41.012960961Z: [ERROR]  [next-auth][error][OAUTH_PARSE_PROFILE_ERROR] 
2021-10-01T10:20:41.012989862Z: [ERROR]  https://next-auth.js.org/errors#oauth_parse_profile_error Cannot read property 'toString' of undefined {
2021-10-01T10:20:41.013003962Z: [ERROR]    error: {
2021-10-01T10:20:41.013008162Z: [ERROR]      message: "Cannot read property 'toString' of undefined",
2021-10-01T10:20:41.013012262Z: [ERROR]      stack: "TypeError: Cannot read property 'toString' of undefined\n" +
2021-10-01T10:20:41.013016362Z: [ERROR]        '    at getProfile (/usr/src/app/.next/server/chunks/1315.js:1446:39)\n' +
2021-10-01T10:20:41.013020362Z: [ERROR]        '    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n' +
2021-10-01T10:20:41.013024262Z: [ERROR]        '    at async oAuthCallback (/usr/src/app/.next/server/chunks/1315.js:1412:12)\n' +
2021-10-01T10:20:41.013028162Z: [ERROR]        '    at async Object.callback (/usr/src/app/.next/server/chunks/1315.js:2182:11)\n' +
2021-10-01T10:20:41.013031962Z: [ERROR]        '    at async NextAuthHandler (/usr/src/app/.next/server/chunks/1315.js:515:18)\n' +
2021-10-01T10:20:41.013035863Z: [ERROR]        '    at async /usr/src/app/.next/server/chunks/1315.js:595:32\n' +
2021-10-01T10:20:41.013040063Z: [ERROR]        '    at async Object.apiResolver (/usr/src/app/node_modules/next/dist/server/api-utils.js:101:9)\n' +
2021-10-01T10:20:41.013044063Z: [ERROR]        '    at async Server.handleApiRequest (/usr/src/app/node_modules/next/dist/server/next-server.js:770:9)\n' +
2021-10-01T10:20:41.013047963Z: [ERROR]        '    at async Object.fn (/usr/src/app/node_modules/next/dist/server/next-server.js:661:37)\n' +
2021-10-01T10:20:41.013051763Z: [ERROR]        '    at async Router.execute (/usr/src/app/node_modules/next/dist/server/router.js:205:32)',
2021-10-01T10:20:41.013055563Z: [ERROR]      name: 'TypeError'
2021-10-01T10:20:41.013059363Z: [ERROR]    },
2021-10-01T10:20:41.013062863Z: [ERROR]    OAuthProfile: {
2021-10-01T10:20:41.013066563Z: [ERROR]      at_hash: '*****',
2021-10-01T10:20:41.013070163Z: [ERROR]      aud: '*****',
2021-10-01T10:20:41.013073863Z: [ERROR]      sub: '*****@*****',
2021-10-01T10:20:41.013077663Z: [ERROR]      nbf: *****,
2021-10-01T10:20:41.013153365Z: [ERROR]      auth_time: 1633083640,
2021-10-01T10:20:41.013159965Z: [ERROR]      amr: [ '1' ],
2021-10-01T10:20:41.013163865Z: [ERROR]      iss: '*****',
2021-10-01T10:20:41.013167665Z: [ERROR]      exp: 1633090840,
2021-10-01T10:20:41.013171265Z: [ERROR]      iat: 1633083640,
2021-10-01T10:20:41.013174765Z: [ERROR]      user: null
2021-10-01T10:20:41.013186365Z: [ERROR]    },
2021-10-01T10:20:41.013190666Z: [ERROR]    message: "Cannot read property 'toString' of undefined"
2021-10-01T10:20:41.013194666Z: [ERROR]  }

### Environment 🖥

Node.js
Beta branch

### Contributing 🙌🏽

Yes,  I am willing to help solve this bug in a PR

**Comment by balazsorban44** [comment]
profile id is a required field in the new version. if you don't care about the value, just return an empty string 😅

the profile id is used to manage different accounts in databases when an adapter is used.
