### ISSUE TITLE
[Azure B2C] JWT not active yet

### ISSUE THREAD

**Issue by Toonshorty** [nextauthjs/next-auth#3032]
### Description 🐜

When trying to authenticate with Azure AD B2C and next-auth 4.0.0-beta4 I get an error saying `JWT not active yet, now 1635241897, nbf 1635241898`. It appears that the token validation is occurring a second ahead of the 'not before' time on the token, causing it to fail.

 

### Is this a bug in your own project?

Yes

### How to reproduce ☕️

Create a project with the 4.0.0-beta4 branch of next-auth and configure the provider as below:

```js
const tenantName = process.env.AZURE_AD_B2C_TENANT_NAME;
const userFlow = process.env.AZURE_AD_B2C_USER_FLOW;

...

AzureADB2CProvider({
    tenantId: tenantName,
    tenantName,
    clientId: process.env.AZURE_AD_B2C_CLIENT_ID,
    clientSecret: process.env.AZURE_AD_B2C_CLIENT_SECRET,
    primaryUserFlow: userFlow,
    authorization: {
        params: {
            scope: process.env.AZURE_AD_B2C_SCOPES
        }
    }
})
```

### Screenshots / Logs 📽

```
[next-auth][error][OAUTH_CALLBACK_ERROR] 
https://next-auth.js.org/errors#oauth_callback_error JWT not active yet, now 1635241857, nbf 1635241858 {
  error: {
    message: 'JWT not active yet, now 1635241857, nbf 1635241858',
    stack: 'RPError: JWT not active yet, now 1635241857, nbf 1635241858\n' +
      '    at Client.validateJWT (C:\\Azure DevOps\\synergiit\\St Oswalds Hospice\\ForgetMeNot\\ForgetMeNot.React\\node_modules\\openid-client\\lib\\client.js:869:15)\n' +
      '    at Client.validateIdToken (C:\\Azure DevOps\\synergiit\\St Oswalds Hospice\\ForgetMeNot\\ForgetMeNot.React\\node_modules\\openid-client\\lib\\client.js:704:60)\n' +
      '    at Client.callback (C:\\Azure DevOps\\synergiit\\St Oswalds Hospice\\ForgetMeNot\\ForgetMeNot.React\\node_modules\\openid-client\\lib\\client.js:480:18)\n' +
      '    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n' +
      '    at async oAuthCallback (C:\\Azure DevOps\\synergiit\\St Oswalds Hospice\\ForgetMeNot\\ForgetMeNot.React\\node_modules\\next-auth\\server\\lib\\oauth\\callback.js:90:16)\n' +
      '    at async Object.callback (C:\\Azure DevOps\\synergiit\\St Oswalds Hospice\\ForgetMeNot\\ForgetMeNot.React\\node_modules\\next-auth\\server\\routes\\callback.js:50:11)\n' +
      '    at async NextAuthHandler (C:\\Azure DevOps\\synergiit\\St Oswalds Hospice\\ForgetMeNot\\ForgetMeNot.React\\node_modules\\next-auth\\server\\index.js:171:18)\n' +
      '    at async C:\\Azure DevOps\\synergiit\\St Oswalds Hospice\\ForgetMeNot\\ForgetMeNot.React\\node_modules\\next-auth\\server\\index.js:251:32\n' +
      '    at async Object.apiResolver (C:\\Azure DevOps\\synergiit\\St Oswalds Hospice\\ForgetMeNot\\ForgetMeNot.React\\node_modules\\next\\dist\\server\\api-utils.js:101:9)\n' +
      '    at async DevServer.handleApiRequest (C:\\Azure DevOps\\synergiit\\St Oswalds Hospice\\ForgetMeNot\\ForgetMeNot.React\\node_modules\\next\\dist\\server\\next-server.js:770:9)',
    name: 'RPError'
  },
  providerId: 'azure-ad-b2c',
  message: 'JWT not active yet, now 1635241857, nbf 1635241858'
}
```

### Environment 🖥

```
System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz  
    Memory: 14.02 GB / 31.59 GB
Binaries:
    Node: 12.21.0 - C:\Program Files\nodejs\node.EXE        
    npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (95.0.1020.30)
    Internet Explorer: 11.0.19041.1202
npmPackages:
    next: ^11.1.2 => 11.1.2 
    next-auth: ^4.0.0-beta.4 => 4.0.0-beta.4 
    react: ^17.0.2 => 17.0.2
```

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
We added a 10 seconds clock tolerance, but you should probably make sure your clock is synced up correctly.

**Comment by devinrhode2** [comment]
Related: https://github.com/XeroAPI/xero-node/issues/327#issuecomment-1028079189
