### ISSUE TITLE
Can't use Bitbucket as a provider

### ISSUE THREAD

**Issue by arthurfalcao** [nextauthjs/next-auth#3075]
### Question 💬

Hey folks,

I was adding Bitbucket as a provider and did not work. Since the bitbucket authorization returns the `token_type` as `bearer`, when passing through `userinfo` it returns 401 as it only accepts the token as `Bearer`.

```sh
[next-auth][error][CALLBACK_OAUTH_ERROR]
https://next-auth.js.org/errors#callback_oauth_error expected 200 OK, got: 401 Unauthorized OPError: expected 200 OK, got: 401 Unauthorized
    at processResponse (webpack-internal:///../next-auth/node_modules/openid-client/lib/helpers/process_response.js:48:11)
    at Client.userinfo (webpack-internal:///../next-auth/node_modules/openid-client/lib/client.js:1123:18)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async oAuthCallback (webpack-internal:///../next-auth/server/lib/oauth/callback.js:112:17)
    at async Object.callback (webpack-internal:///../next-auth/server/routes/callback.js:50:11)
    at async NextAuthHandler (webpack-internal:///../next-auth/server/index.js:171:18)
    at async eval (webpack-internal:///../next-auth/server/index.js:251:32)
    at async Object.apiResolver (/home/arthurfalcao/Development/arthurfalcao/epic-notes-generator/node_modules/next/dist/server/api-utils.js:102:9)
    at async DevServer.handleApiRequest (/home/arthurfalcao/Development/arthurfalcao/epic-notes-generator/node_modules/next/dist/server/next-server.js:1017:9) {
  name: 'OAuthCallbackError'
}
```

Response from bitbucket oauth2:
```json
{
  "provider": "bitbucket",
  "type": "oauth",
  "providerAccountId": "",
  "scopes": "account pullrequest",
  "access_token": "",
  "expires_at": 1635642968,
  "token_type": "bearer",
  "state": "authorization_code",
  "refresh_token": ""
}
```

### How to reproduce ☕️

[CodeSandbox](https://codesandbox.io/s/unruffled-heyrovsky-gt0jp)

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment]
This seems to be an upstream bug. They send one response but then expect something else? :sweat_smile:

**Comment by jayantbh** [comment]
I posted a comment here: https://github.com/nextauthjs/next-auth/pull/3076#issuecomment-1180218158

This is how I managed to use bitbucket as a provider.

**Comment by domharrington** [comment]
I also came across this same issue to do with the token_type inconsistency breaking stuff. NextAuth's OpenID Client was making a request with a lowercase b in the `bearer` header which was causing 401s:

```sh
curl https://api.bitbucket.org/2.0/user --header "authorization: bearer xxxxxxxxx" -i
HTTP/2 401
server: envoy
```

But it works when using uppercase b in `Bearer`:

```sh
curl https://api.bitbucket.org/2.0/user --header "authorization: Bearer xxxxxxxxx" -i
HTTP/2 200
server: envoy
```

I used @jayantbh's example from above, but had to modify it a bit to work with bitbucket's latest API: https://github.com/nextauthjs/next-auth/pull/3076#issuecomment-1523446826
