### ISSUE TITLE
MongoDB adapter crash when upgrading to Next 12

### ISSUE THREAD

**Issue by xTunqki** [nextauthjs/next-auth#3086]
### Description 🐜

So i upgraded the whole thing using `yarn upgrade --latest`

`next ready - started server on 0.0.0.0:3000, url: http://localhost:3000 info - Loaded env from /home/xtunqki/test/project/.env event - compiled successfully in 3.1s (203 modules) wait - compiling /api/auth/[...nextauth] (server only)... event - compiled successfully in 197 ms (215 modules) [next-auth][error][adapter_connection_error] https://next-auth.js.org/errors#adapter_connection_error MongoAPIError: URI must include hostname, domain name, and tld at Object.resolveSRVRecord (/home/xtunqki/test/project/node_modules/mongodb/lib/connection_string.js:51:25) at Object.connect (/home/xtunqki/test/project/node_modules/mongodb/lib/operations/connect.js:41:36) at /home/xtunqki/test/project/node_modules/mongodb/lib/mongo_client.js:127:23 at Object.maybePromise (/home/xtunqki/test/project/node_modules/mongodb/lib/utils.js:518:5) at MongoClient.connect (/home/xtunqki/test/project/node_modules/mongodb/lib/mongo_client.js:126:24) at Function.connect (/home/xtunqki/test/project/node_modules/mongodb/lib/mongo_client.js:187:36) at /home/xtunqki/test/project/node_modules/typeorm/driver/mongodb/MongoDriver.js:172:39 at new Promise (<anonymous>) at MongoDriver.connect (/home/xtunqki/test/project/node_modules/typeorm/driver/mongodb/MongoDriver.js:170:16) at Connection.<anonymous> (/home/xtunqki/test/project/node_modules/typeorm/connection/Connection.js:110:58)`

I don't know if the error is because next-auth or the mongodb library, but when i only upgrade the Next 12 it's works fine

### Is this a bug in your own project?

Yes

### How to reproduce ☕️

`yarn upgrade --latest` using mongodb as the database

### Environment 🖥

  System:
    OS: Linux 5.11 Ubuntu 20.04.3 LTS (Focal Fossa)
    CPU: (2) x64 Intel(R) Xeon(R) CPU E5-2673 v4 @ 2.30GHz
    Memory: 2.56 GB / 3.84 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 17.0.1 - /usr/local/bin/node
    Yarn: 1.22.11 - /usr/local/bin/yarn
    npm: 8.1.0 - /usr/local/bin/npm
  npmPackages:
    next: ^12.0.2 => 12.0.2
    next-auth: ^3.29.0 => 3.29.0
    react: ^17.0.2 => 17.0.2

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by xTunqki** [comment]
nvm i downgrade the mongodb version to "mongodb": "^3.6.6", and it's work
