### ISSUE TITLE
Value is too long for column type - Prisma Adapter + PlanetScale MySQL db 

### ISSUE THREAD

**Issue by vcapretz** [nextauthjs/next-auth#3254]
### Description 🐜

I just configured a new project using Prisma adapter and PlanetScale's MySQL database, when trying to sign in I get the following error:

```
[next-auth][error][adapter_error_linkAccount] 
https://next-auth.js.org/errors#adapter_error_linkaccount 
Invalid `prisma.account.create()` invocation:


  The provided value for the column is too long for the column's type. Column: 22001) {
  message: '\n' +
    'Invalid `prisma.account.create()` invocation:\n' +
    '\n' +
    '\n' +
    "  The provided value for the column is too long for the column's type. Column: 22001)",
  stack: 'Error: \n' +
    'Invalid `prisma.account.create()` invocation:\n' +
    '\n' +
    '\n' +
    "  The provided value for the column is too long for the column's type. Column: 22001)\n" +
    '    at cb (/Users/vcapretz/Developer/organize/node_modules/@prisma/client/runtime/index.js:38675:17)\n' +
    '    at async linkAccount (webpack-internal:///./pages/api/auth/[...nextauth].ts:20:9)',
  name: 'Error'
}
[next-auth][error][OAUTH_CALLBACK_HANDLER_ERROR] 
https://next-auth.js.org/errors#oauth_callback_handler_error 
Invalid `prisma.account.create()` invocation:


  The provided value for the column is too long for the column's type. Column: 22001) Error: 
Invalid `prisma.account.create()` invocation:


  The provided value for the column is too long for the column's type. Column: 22001)
    at cb (/Users/vcapretz/Developer/organize/node_modules/@prisma/client/runtime/index.js:38675:17)
    at async linkAccount (webpack-internal:///./pages/api/auth/[...nextauth].ts:20:9) {
  name: 'LinkAccountError',
  code: 'P2000'
}
```

After debugging it seems like `id_token`'s value is too big to fit in MySQL's default `VARCHAR(199)` column type (it also doesn't fit in `VARCHAR(255)` from the [models page](https://next-auth.js.org/adapters/models) 

So I wonder if I'm doing something wrong or if the value should be mapped to the `TEXT` type instead. 

### Is this a bug in your own project?

No

### How to reproduce ☕️

my auth route:

```
export default NextAuth({
  adapter: PrismaAdapter(prisma),
  session: {
    strategy: "database",
  },
  secret: process.env.AUTH_SECRET,
  providers: [
    GoogleProvider({
      clientId: process.env.GOOGLE_CLIENT_ID,
      clientSecret: process.env.GOOGLE_CLIENT_SECRET,
    }),
  ],
});
```

prisma's schema file:
```
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

generator client {
  provider = "prisma-client-js"
  previewFeatures = ["referentialIntegrity"]
}

datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
  shadowDatabaseUrl = env("SHADOW_DATABASE_URL")
  referentialIntegrity = "prisma"
}

model Account {
  id                 String  @id @default(cuid())
  userId             String
  type               String  @db.VarChar(255)
  provider           String  @db.VarChar(255)
  providerAccountId  String  @db.VarChar(255)
  refresh_token      String? @db.VarChar(255)
  access_token       String? @db.VarChar(255)
  expires_at         Int?
  token_type         String? @db.VarChar(255)
  scope              String? @db.VarChar(255)
  id_token           String? @db.VarChar(255)
  session_state      String? @db.VarChar(255)
  oauth_token_secret String? @db.VarChar(255)
  oauth_token        String? @db.VarChar(255)

  user User @relation(fields: [userId], references: [id], onDelete: Cascade)

  @@unique([provider, providerAccountId])
}

model Session {
  id           String   @id @default(cuid())
  sessionToken String   @unique
  userId       String
  expires      DateTime
  user         User     @relation(fields: [userId], references: [id], onDelete: Cascade)
}

model User {
  id            String    @id @default(cuid())
  name          String?
  email         String?   @unique
  emailVerified DateTime?
  image         String?
  accounts      Account[]
  sessions      Session[]
}

model VerificationToken {
  identifier String
  token      String   @unique
  expires    DateTime

  @@unique([identifier, token])
}
```

### Screenshots / Logs 📽

<img width="855" alt="Screen Shot 2021-11-22 at 11 28 39" src="https://user-images.githubusercontent.com/14620121/142878928-06a2a018-4f35-4cee-afe9-091ed336ad82.png">

### Environment 🖥

```
System:
    OS: macOS 12.0.1
    CPU: (8) x64 Apple M1
    Memory: 36.11 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.6 - ~/.volta/tools/image/node/14.17.6/bin/node
    Yarn: 1.22.11 - ~/.volta/tools/image/yarn/1.22.11/bin/yarn
    npm: 6.14.15 - ~/.volta/tools/image/node/14.17.6/bin/npm
  Browsers:
    Firefox: 94.0.1
    Safari: 15.1
  npmPackages:
    next: 12.0.4 => 12.0.4 
    next-auth: ^4.0.0-beta.7 => 4.0.0-beta.7 
    react: 17.0.2 => 17.0.2 
 ```

### Contributing 🙌🏽

Yes,  I am willing to help solve this bug in a PR

**Comment by balazsorban44** [comment]
please report in the correct repository and check for duplicates first.

**Comment by riccardogiorato** [comment]
Hey @vcapretz were you able to solve the issue with Next-Auth and PlanetScale?
