### ISSUE TITLE
Okta callback error v4

### ISSUE THREAD

**Issue by bogdansoare** [nextauthjs/next-auth#3383]
### Description 🐜

I'm getting an error when trying to use the Okta provider with v4

```
[next-auth][error][OAUTH_CALLBACK_ERROR] 
https://next-auth.js.org/errors#oauth_callback_error id_token detected in the response, you must use client.callback() instead of client.oauthCallback() {
  error: {
    message: 'id_token detected in the response, you must use client.callback() instead of client.oauthCallback()',
    stack: 'RPError: id_token detected in the response, you must use client.callback() instead of client.oauthCallback()\n' +
      '    at Client.oauthCallback (/Users/bogdansoare/Work/planetscale/flux-v2/node_modules/openid-client/lib/client.js:622:15)\n' +
      '    at runMicrotasks (<anonymous>)\n' +
      '    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n' +
      '    at async oAuthCallback (/Users/bogdansoare/Work/planetscale/flux-v2/node_modules/next-auth/core/lib/oauth/callback.js:114:16)\n' +
      '    at async Object.callback (/Users/bogdansoare/Work/planetscale/flux-v2/node_modules/next-auth/core/routes/callback.js:50:11)\n' +
      '    at async NextAuthHandler (/Users/bogdansoare/Work/planetscale/flux-v2/node_modules/next-auth/core/index.js:133:28)\n' +
      '    at async NextAuthNextHandler (/Users/bogdansoare/Work/planetscale/flux-v2/node_modules/next-auth/next/index.js:20:19)\n' +
      '    at async /Users/bogdansoare/Work/planetscale/flux-v2/node_modules/next-auth/next/index.js:56:32\n' +
      '    at async Object.apiResolver (/Users/bogdansoare/Work/planetscale/flux-v2/node_modules/next/dist/server/api-utils.js:102:9)\n' +
      '    at async DevServer.handleApiRequest (/Users/bogdansoare/Work/planetscale/flux-v2/node_modules/next/dist/server/next-server.js:1054:9)',
    name: 'RPError'
  },
  providerId: 'okta',
  message: 'id_token detected in the response, you must use client.callback() instead of client.oauthCallback()'
}
```

### Is this a bug in your own project?

No

### How to reproduce ☕️

Add the Okta provider to v4 and try to sign-in

### Environment 🖥

npmPackages:
    next: 12.0.4 => 12.0.4 
    next-auth: ^4.0.2 => 4.0.2 
    react: 17.0.2 => 17.0.2 

### Contributing 🙌🏽

Yes,  I am willing to help solve this bug in a PR

**Comment by balazsorban44** [comment]
Seemed to work here https://github.com/nextauthjs/next-auth/pull/2856 🤔

**Comment by mattppi** [comment]
I was having the same issue and setting idToken to true resolved it for me as well.

**Comment by balazsorban44** [comment]
feel free to open a PR

**Comment by balazsorban44** [comment]
follow docs. wyi, it won't be necessary in the latest release as the PR addressing this has been merged.

**Comment by jimfilippou** [comment]
When is a new release planned?

**Comment by Donivanes** [comment]
@balazsorban44 There is the same problem with `Amazon Cognito` provider, adding `idToken: true` solves the issue. Should I create a new pull request adding the idToken true by default to Cognito provider?
