### ISSUE TITLE
Vercel deployment gives [CLIENT_FETCH_ERROR] and [NO_SECRET]

### ISSUE THREAD

**Issue by arnoDevSolutions** [nextauthjs/next-auth#3390]
### Question 💬

After successfully deploying a NextAuth application to Vercel, I have found that my landing page (ie. the page containing a button to perform the NextAuth signIn( ) ) immediately logs:
`
Failed to load resource: the server responded with a status of 500 ()
_app-e6f7bc05db6ca90bab0f.js:101 [next-auth][error][CLIENT_FETCH_ERROR] 
https://next-auth.js.org/errors#client_fetch_error Unexpected token < in JSON at position 0 Object
`

After reviewing the vercel server logs, I also notice the following: 
`ERROR	[next-auth][error][NO_SECRET] 
https://next-auth.js.org/errors#no_secret Please define a `secret` in production. MissingSecret [MissingSecretError]: Please define a `secret` in production.
    at assertConfig (/var/task/node_modules/next-auth/core/lib/assert.js:24:14)
    at NextAuthHandler (/var/task/node_modules/next-auth/core/index.js:34:52)
    at NextAuthNextHandler (/var/task/node_modules/next-auth/next/index.js:16:51)
    at NextAuth (/var/task/node_modules/next-auth/next/index.js:55:10)
    at _callee3$ (/var/task/.next/server/pages/api/auth/[...nextauth].js:319:37)
    at tryCatch (/var/task/node_modules/regenerator-runtime/runtime.js:63:40)
    at Generator.invoke [as _invoke] (/var/task/node_modules/regenerator-runtime/runtime.js:294:22)
    at Generator.next (/var/task/node_modules/regenerator-runtime/runtime.js:119:21)
    at asyncGeneratorStep (/var/task/.next/server/pages/api/auth/[...nextauth].js:12:24)
    at _next (/var/task/.next/server/pages/api/auth/[...nextauth].js:34:9) {
  code: 'NO_SECRET'` 

So far I have tried setting the relevant environment variable name to both NEXTAUTH_URL and VERCEL_URL, and I have assigned it as `https://my-app-name.vercel.app` (ie. where Vercel is hosting my deployment), and still no luck so far unfortunately.

Has anyone come across a similar issue and might be able to point me in the right direction?

### How to reproduce ☕️

// package.json

"next-auth": "^4.0.0-beta.7"

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
please upgrade
