### ISSUE TITLE
Cognito + Okta - Nonce Mismatch Error

### ISSUE THREAD

**Issue by saad-karim** [nextauthjs/next-auth#3403]
### Question 💬

Recently moved to version 4.0.2 and hit issues when using Cognito Provider that has a third party IDP integration (okta). I'll start by sharing my provider config as that seems like the most relevant section.

```
  return CognitoProvider({
    id: provider.id,
    name: provider.name,
    clientId: provider.clientId,
    clientSecret: provider.clientSecret,
    issuer: provider.issuerURL,
    idToken: true,
    authorization: {
      url: provider.authorizationURL,
      params: {
        scope: "email openid aws.cognito.signin.user.admin profile",
      },
    },
  });
```

I want to first point out that using Cognito directly with no third party integration everything seems to work fine. But when we use Okta through Cognito, we started to see the follow nonce mismatch error:

```
[next-auth][error][OAUTH_CALLBACK_ERROR]
https://next-auth.js.org/errors#oauth_callback_error nonce mismatch, expected undefined, got: 5ynHXEwhOEluQVAIvVdFs4g8OC7d8XJTu9mmX2cEZlLngAcGpDiv3M-S6FMcIgCx3Aepv-r97oWms1NjOlZuBB6280N7u1aU1qMt-ER6MnEWM30EHM1SsyeD8GOg6Vp2x7C2ByE70tV9baX0wp7CA5SJI0ecqnquw_EWlHR4nWM {
  error: {
    message: 'nonce mismatch, expected undefined, got: 5ynHXEwhOEluQVAIvVdFs4g8OC7d8XJTu9mmX2cEZlLngAcGpDiv3M-S6FMcIgCx3Aepv-r97oWms1NjOlZuBB6280N7u1aU1qMt-ER6MnEWM30EHM1SsyeD8GOg6Vp2x7C2ByE70tV9baX0wp7CA5SJI0ecqnquw_EWlHR4nWM',
    stack: 'RPError: nonce mismatch, expected undefined, got: 5ynHXEwhOEluQVAIvVdFs4g8OC7d8XJTu9mmX2cEZlLngAcGpDiv3M-S6FMcIgCx3Aepv-r97oWms1NjOlZuBB6280N7u1aU1qMt-ER6MnEWM30EHM1SsyeD8GOg6Vp2x7C2ByE70tV9baX0wp7CA5SJI0ecqnquw_EWlHR4nWM\n' +
      '    at Client.validateIdToken (/Users/SaadK/Development/ghe.metrumrg.com/metworx/next-ui/node_modules/openid-client/lib/client.js:802:13)\n' +
      '    at async Client.callback (/Users/SaadK/Development/ghe.metrumrg.com/metworx/next-ui/node_modules/openid-client/lib/client.js:488:7)\n' +
      '    at async oAuthCallback (/Users/SaadK/Development/ghe.metrumrg.com/metworx/next-ui/node_modules/next-auth/core/lib/oauth/callback.js:122:16)\n' +
      '    at async Object.callback (/Users/SaadK/Development/ghe.metrumrg.com/metworx/next-ui/node_modules/next-auth/core/routes/callback.js:50:11)\n' +
      '    at async NextAuthHandler (/Users/SaadK/Development/ghe.metrumrg.com/metworx/next-ui/node_modules/next-auth/core/index.js:133:28)\n' +
      '    at async NextAuthNextHandler (/Users/SaadK/Development/ghe.metrumrg.com/metworx/next-ui/node_modules/next-auth/next/index.js:20:19)\n' +
      '    at async Object.apiResolver (/Users/SaadK/Development/ghe.metrumrg.com/metworx/next-ui/node_modules/next/dist/server/api-utils.js:102:9)\n' +
      '    at async DevServer.handleApiRequest (/Users/SaadK/Development/ghe.metrumrg.com/metworx/next-ui/node_modules/next/dist/server/next-server.js:1017:9)\n' +
      '    at async Object.fn (/Users/SaadK/Development/ghe.metrumrg.com/metworx/next-ui/node_modules/next/dist/server/next-server.js:904:37)\n' +
      '    at async Router.execute (/Users/SaadK/Development/ghe.metrumrg.com/metworx/next-ui/node_modules/next/dist/server/router.js:210:32)',
    name: 'RPError'
  },
  providerId: 'k07khWkH6',
  message: 'nonce mismatch, expected undefined, got: 5ynHXEwhOEluQVAIvVdFs4g8OC7d8XJTu9mmX2cEZlLngAcGpDiv3M-S6FMcIgCx3Aepv-r97oWms1NjOlZuBB6280N7u1aU1qMt-ER6MnEWM30EHM1SsyeD8GOg6Vp2x7C2ByE70tV9baX0wp7CA5SJI0ecqnquw_EWlHR4nWM'
}
```

The interesting part seems to be that I am not initiating the authorization request using a nonce. The nonce seems to be getting injected some where in the flow (possibly by Cognito?), we have a ticket open on AWS to get some answers there. The issue in the end is that OpenID spec requires nonce validation if present in ID token. 

The answer that I am looking for is how can I provide a nonce in next-auth that will then be used for validation as well? For example, if I were to update my provider config to include nonce, such as 

```
  return CognitoProvider({
   ...
    authorization: {
      url: provider.authorizationURL,
      params: {
        scope: "email openid aws.cognito.signin.user.admin profile",
        *nonce: <Generate nonce here...>*
      },
    },
  });
}
```

I don't know how I can then pass the nonce that I generate to be the one used for validation. I  looked into the source, specifically https://github.com/nextauthjs/next-auth/blob/main/src/core/lib/oauth/callback.ts#L112, I don't see any way to set the nonce on the `checks` object, which is the parameter that openid client seems to looking for (see: https://github.com/panva/node-openid-client/blob/main/lib/client.js#L484)

Another interesting note is that this worked fine for me in 4.0.0-beta.4.

### How to reproduce ☕️

1. Setup Cognito
2. Configure to Cognito user pool to use Okta as identity provider
3. Initiate authentication through Okta via Cognito

```
  return CognitoProvider({
    id: provider.id,
    name: provider.name,
    clientId: provider.clientId,
    clientSecret: provider.clientSecret,
    issuer: provider.issuerURL,
    idToken: true,
    authorization: {
      url: provider.authorizationURL,
      params: {
        scope: "email openid aws.cognito.signin.user.admin profile",
      },
    },
  });
```

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment]
I believe we currently don't support nonce. When available, we use PKCE instead.

**Comment by leonp-s** [comment]
I am running into the same issue, is there not currently a way to work with Cognito + 3rd party IDPs?
