### ISSUE TITLE
callbacks.session missing user arg 

### ISSUE THREAD

**Issue by HT-Moh** [nextauthjs/next-auth#3444]
### Description 🐜

Hi I updated the next-auth to v4.0.5, and now I am getting `oauth_callback_error checks.state argument is missing ` 
I am using Prisma adapter with Hasura 

Logs

```
0] prisma:query SELECT "public"."users"."id", "public"."users"."name", "public"."users"."email", "public"."users"."email_verified", "public"."users"."image", "public"."users"."created_at", "public"."users"."updated_at", "public"."users"."is_admin", "public"."users"."twitter", "public"."users"."avatar", "public"."users"."title", "public"."users"."first_name", "public"."users"."last_name", "public"."users"."facebook", "public"."users"."github", "public"."users"."project_id" FROM "public"."users" WHERE 1=1 LIMIT $1 OFFSET $2
[0] [next-auth][debug][CREATE_STATE] { state: 'Q2RCPxwYV44YBOUcdQrBxLlHV-ct_FZLl8AnwiS5TU8', maxAge: 900 }
[0] [next-auth][debug][CREATE_PKCE_CHALLENGE_VERIFIER] {
[0]   code_challenge: '4qVSrPTZ4YdxhToBe9LNsSEI8I6bTEZBQnpexDJIROU',
[0]   code_challenge_method: 'S256',
[0]   code_verifier: 'gBYPKd6akjkMtD_ZvBxRfzvQ3XTZimaE8Z7bxdXUfPY',
[0]   PKCE_MAX_AGE: 900
[0] }
[0] [next-auth][debug][GET_AUTHORIZATION_URL] {
[0]   url: 'https://accounts.google.com/o/oauth2/v2/auth?client_id=1095858922980-35f8o8cg984undoimo5d0nr5jpktcebu.apps.googleusercontent.com&scope=openid%20email%20profile&response_type=code&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Fapi%2Fauth%2Fcallback%2Fgoogle&state=Q2RCPxwYV44YBOUcdQrBxLlHV-ct_FZLl8AnwiS5TU8&code_challenge=4qVSrPTZ4YdxhToBe9LNsSEI8I6bTEZBQnpexDJIROU&code_challenge_method=S256',
[0]   cookies: [
[0]     {
[0]       name: 'next-auth.state',
[0]       value: 'eyJhbGciOiJSUzUxMiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjciLCJpc0FkbWluIjpmYWxzZSwiaHR0cHM6Ly9oYXN1cmEuaW8vand0L2NsYWltcyI6eyJ4LWhhc3VyYS1hbGxvd2VkLXJvbGVzIjpbImFkbWluIiwimFub255bW91cyJdLCJ4LWhhc3VyYS1kZWZhdWx0LXJvbGUiOiJhbm9ueW1vdXMiLCJ4LWhhc3VyYS1yb2xlIjoiYW5vbnltb3VzIiwieC1oYXN1cmE1pZCI6InVuZGVmaW5lZCJ9LCJpDMuMDQ0LCJleHAiOjE2Mzk3NjczODMsInN1YiI6InVuZGVmaW5lZCJ9.pGuIn-MWIFVlbqFdP0G36pqhZmNp7fyizGAso2ZZZpIxTaPslBnYtR3kYVHNY7cEqr4KIURWUx-a6FSwQQHlIBjxa96H5UtTAh1g8Wh05aw9V0cPf_1PGTwxKG3qnUm-9Yw8tc2TpDGtQX3keA23EsLJtR5dik2TWAKxoP5It1wNE3gOZnQtY2iRmXBa8O04bM4ojnVtvc1GsSmwHkDE0w9FfefDzTAN7oLu0XYnpV6NoP6BO6wayZj-WgeQgKZGl9Dd7zgyEspzJhIC6lJO15ZV18e04SFT-O8Tx6pMFBw_G1kO2SHU-XltrQFbhOr7sGeKiqNQJl2e1i_iQq3XcQ',
[0]       options: [Object]
[0]     },
[0]     {
[0]       name: 'next-auth.pkce.code_verifier',
[0]       value: 'eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..y2v1x1cMzzLqSO8t.lZH9pTrhNYJuKy7HrYNFiwj9lu6aqp-XKV3uxr8OzwCE50i-ZbDIpeK-K3hx2en2vP6ka5ltBX1H1b_Edbj7MRMRrBzeV5aapkgb2QyNUFZYzgSaS99PxvoNF_vAHHCOv2BhS52ddMhaypBByb1qmxoSFcYCRyVJ_91ESG7O4TKgf30HPN20zdox8dycUg.Z96JIoGEQYrWPFBL8mIuHQ',
[0]       options: [Object]
[0]     }
[0]   ]
[0] }
[0] cookies
[0] {
[0]   debug: true,
[0]   pages: {},
[0]   theme: { colorScheme: 'auto', logo: '', brandColor: '' },
[0]   providers: [
[0]     {
[0]       id: 'google',
[0]       name: 'Google',
[0]       type: 'oauth',
[0]       wellKnown: 'https://accounts.google.com/.well-known/openid-configuration',
[0]       authorization: [Object],
[0]       idToken: true,
[0]       checks: [Array],
[0]       profile: [Function: profile],
[0]       clientId: '1095858922980-35f8o8cg984undoimo5d0nr5jpktcebu.apps.googleusercontent.com',
[0]       clientSecret: 'vqKv_YF7MNUJKJJOr4HoR1JY',
[0]       signinUrl: 'http://localhost:3000/api/auth/signin/google',
[0]       callbackUrl: 'http://localhost:3000/api/auth/callback/google'
[0]     },
[0]     {
[0]       id: 'github',
[0]       name: 'GitHub',
[0]       type: 'oauth',
[0]       authorization: [Object],
[0]       token: [Object],
[0]       userinfo: [Object],
[0]       profile: [Function: profile],
[0]       checks: [Array],
[0]       clientId: '5977228f20f48f882a97',
[0]       clientSecret: '850d28c45666d6c80ffea7a25703fdfe201c2596',
[0]       signinUrl: 'http://localhost:3000/api/auth/signin/github',
[0]       callbackUrl: 'http://localhost:3000/api/auth/callback/github'
[0]     }
[0]   ],
[0]   secret: '+UeVgY+QNOLN0v9JLmZp8345dC1jZGs7U/+xiM0xDc0=',
[0]   database: 'postgres://postgres:@localhost:5432/postgres',
[0]   adapter: {
[0]     createUser: [Function (anonymous)],
[0]     getUser: [Function (anonymous)],
[0]     getUserByEmail: [Function (anonymous)],
[0]     getUserByAccount: [Function (anonymous)],
[0]     updateUser: [Function (anonymous)],
[0]     deleteUser: [Function (anonymous)],
[0]     linkAccount: [Function (anonymous)],
[0]     unlinkAccount: [Function (anonymous)],
[0]     getSessionAndUser: [Function (anonymous)],
[0]     createSession: [Function (anonymous)],
[0]     updateSession: [Function (anonymous)],
[0]     deleteSession: [Function (anonymous)],
[0]     createVerificationToken: [Function (anonymous)],
[0]     useVerificationToken: [Function (anonymous)]
[0]   },
[0]   session: { strategy: 'jwt', maxAge: 2592000, updateAge: 86400 },
[0]   jwt: {
[0]     secret: '+UeVgY+QNOLN0v9JLmZp8345dC1jZGs7U/+xiM0xDc0=',
[0]     maxAge: 2592000,
[0]     encode: [AsyncFunction: encode],
[0]     decode: [Function: decode]
[0]   },
[0]   callbacks: {
[0]     signIn: [Function: signIn],
[0]     redirect: [Function: redirect],
[0]     session: [AsyncFunction: session],
[0]     jwt: [AsyncFunction: jwt]
[0]   },
[0]   url: {
[0]     origin: 'http://localhost:3000',
[0]     host: 'localhost:3000',
[0]     path: '/api/auth',
[0]     base: 'http://localhost:3000/api/auth',
[0]     toString: [Function: toString]
[0]   },
[0]   action: 'callback',
[0]   provider: {
[0]     id: 'google',
[0]     name: 'Google',
[0]     type: 'oauth',
[0]     wellKnown: 'https://accounts.google.com/.well-known/openid-configuration',
[0]     authorization: { params: [Object] },
[0]     idToken: true,
[0]     checks: [ 'pkce', 'state' ],
[0]     profile: [Function: profile],
[0]     clientId: '1095858922980-35f8o8cg984undoimo5d0nr5jpktcebu.apps.googleusercontent.com',
[0]     clientSecret: 'vqKv_YF7MNUJKJJOr4HoR1JY',
[0]     signinUrl: 'http://localhost:3000/api/auth/signin/google',
[0]     callbackUrl: 'http://localhost:3000/api/auth/callback/google'
[0]   },
[0]   cookies: {
[0]     sessionToken: { name: 'next-auth.session-token', options: [Object] },
[0]     callbackUrl: { name: 'next-auth.callback-url', options: [Object] },
[0]     csrfToken: { name: 'next-auth.csrf-token', options: [Object] },
[0]     pkceCodeVerifier: { name: 'next-auth.pkce.code_verifier', options: [Object] },
[0]     state: { name: 'next-auth.state', options: [Object] }
[0]   },
[0]   events: {},
[0]   logger: {
[0]     error: [Function: error],
[0]     warn: [Function: warn],
[0]     debug: [Function: debug]
[0]   },
[0]   callbackUrl: 'http://localhost:3000/admin',
[0]   csrfToken: 'b79af1cf8a271c3c58e29dd8b24d902bead075af0000bae54384765057da59b3',
[0]   csrfTokenVerified: false
[0] }
[0] {
[0]   csrftoken: 't1WQ1cOXlHu2uORC4Bc8wZVyBtjwTG2uGLK0EKLfqqzgw4VgDFfgzcc8Q0tHdbCC',
[0]   'crypto-catalyst': 'true',
[0]   sessionid: 'atnxzb4gl040z3vq2uhib7yvlu42z7xo',
[0]   djdt: 'show',
[0]   'next-auth.csrf-token': 'b79af1cf8a271c3c58e29dd8b24d902bead075af0000bae54384765057da59b3|6a0d32ea8376e50e688dff8420ee8ea9c02d83d797be34dbf2a0e78585ff65af',
[0]   'next-auth.callback-url': 'http://localhost:3000/admin',
[0]   'next-auth.state': 'eyJhbGciOiJSUzUxMiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjciLCJpc0FkbWluIjpmYWxzZSwiaHR0cHM6Ly9oYXN1cmEuaW8vand0L2NsYWltcyI6eyJ4LWhhc3VyYS1hbGxvd2VkLXJvbGVzIjpbImFkbWluIiwidXNlciIsImFub255bW91cyJdLCJ4LWhhc3VyYS1kZWZhdWx0LXJvbGUiOiJhbm9ueW1vdXMiLCJ4LWhhc3VyYS1yb2xlIjoiYW5vbnltb3VzIiwieC1oYXN1cmEtdXNlci1pZCI6InVuZGVmaW5lZCJ9LCJpYXQiOjE2Mzk1MDgxODMuMDQ0LCJleHAiOjE2Mzk3NjczODMsInN1YiI6InVuZGVmaW5lZCJ9.pGuIn-MWIFVlbqFdP0G36pqhZmNp7fyizGAso2ZZZpIxTaPslBnYtR3kYVHNY7cEqr4KIURWUx-a6FSwQQHlIBjxa96H5UtTAh1g8Wh05aw9V0cPf_1PGTwxKG3qnUm-9Yw8tc2TpDGtQX3keA23EsLJtR5dik2TWAKxoP5It1wNE3gOZnQtY2iRmXBa8O04bM4ojnVtvc1GsSmwHkDE0w9FfefDzTAN7oLu0XYnpV6NoP6BO6wayZj-WgeQgKZGl9Dd7zgyEspzJhIC6lJO15ZV18e04SFT-O8Tx6pMFBw_G1kO2SHU-XltrQFbhOr7sGeKiqNQJl2e1i_iQq3XcQ',
[0]   'next-auth.pkce.code_verifier': 'eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..y2v1x1cMzzLqSO8t.lZH9pTrhNYJuKy7HrYNFiwj9lu6aqp-XKV3uxr8OzwCE50i-ZbDIpeK-K3hx2en2vP6ka5ltBX1H1b_Edbj7MRMRrBzeV5aapkgb2QyNUFZYzgSaS99PxvoNF_vAHHCOv2BhS52ddMhaypBByb1qmxoSFcYCRyVJ_91ESG7O4TKgf30HPN20zdox8dycUg.Z96JIoGEQYrWPFBL8mIuHQ'
[0] }
[0] STATE
[0] {
[0]   value: undefined,
[0]   cookie: {
[0]     name: 'next-auth.state',
[0]     value: '',
[0]     options: {
[0]       httpOnly: true,
[0]       sameSite: 'lax',
[0]       path: '/',
[0]       secure: false,
[0]       maxAge: 0
[0]     }
[0]   }
[0] }
[0] [next-auth][error][OAUTH_CALLBACK_ERROR] 
[0] https://next-auth.js.org/errors#oauth_callback_error checks.state argument is missing {
[0]   error: {
[0]     message: 'checks.state argument is missing',
[0]     stack: 'TypeError: checks.state argument is missing\n' +
[0]       '    at Client.callback (/media/bicatalyst/Pytech/crypto-catalyst-website/NextJS/node_modules/openid-client/lib/client.js:386:13)\n' +
[0]       '    at oAuthCallback (/media/bicatalyst/Pytech/crypto-catalyst-website/NextJS/node_modules/next-auth/core/lib/oauth/callback.js:117:29)\n' +
[0]       '    at async Object.callback (/media/bicatalyst/Pytech/crypto-catalyst-website/NextJS/node_modules/next-auth/core/routes/callback.js:50:11)\n' +
[0]       '    at async NextAuthHandler (/media/bicatalyst/Pytech/crypto-catalyst-website/NextJS/node_modules/next-auth/core/index.js:133:28)\n' +
[0]       '    at async NextAuthNextHandler (/media/bicatalyst/Pytech/crypto-catalyst-website/NextJS/node_modules/next-auth/next/index.js:20:19)\n' +
[0]       '    at async Object.apiResolver (/media/bicatalyst/Pytech/crypto-catalyst-website/NextJS/node_modules/next/dist/server/api-utils.js:102:9)\n' +
[0]       '    at async DevServer.handleApiRequest (/media/bicatalyst/Pytech/crypto-catalyst-website/NextJS/node_modules/next/dist/server/next-server.js:1064:9)\n' +
[0]       '    at async Object.fn (/media/bicatalyst/Pytech/crypto-catalyst-website/NextJS/node_modules/next/dist/server/next-server.js:951:37)\n' +
[0]       '    at async Router.execute (/media/bicatalyst/Pytech/crypto-catalyst-website/NextJS/node_modules/next/dist/server/router.js:222:32)\n' +
[0]       '    at async DevServer.run (/media/bicatalyst/Pytech/crypto-catalyst-website/NextJS/node_modules/next/dist/server/next-server.js:1135:29)',
[0]     name: 'TypeError'
[0]   },
[0]   providerId: 'google',
[0]   message: 'checks.state argument is missing'
[0] }
[0] [next-auth][error][CALLBACK_OAUTH_ERROR] 
[0] https://next-auth.js.org/errors#callback_oauth_error checks.state argument is missing TypeError: checks.state argument is missing
[0]     at Client.callback (/media/bicatalyst/Pytech/crypto-catalyst-website/NextJS/node_modules/openid-client/lib/client.js:386:13)
[0]     at oAuthCallback (/media/bicatalyst/Pytech/crypto-catalyst-website/NextJS/node_modules/next-auth/core/lib/oauth/callback.js:117:29)
[0]     at async Object.callback (/media/bicatalyst/Pytech/crypto-catalyst-website/NextJS/node_modules/next-auth/core/routes/callback.js:50:11)
[0]     at async NextAuthHandler (/media/bicatalyst/Pytech/crypto-catalyst-website/NextJS/node_modules/next-auth/core/index.js:133:28)
[0]     at async NextAuthNextHandler (/media/bicatalyst/Pytech/crypto-catalyst-website/NextJS/node_modules/next-auth/next/index.js:20:19)
[0]     at async Object.apiResolver (/media/bicatalyst/Pytech/crypto-catalyst-website/NextJS/node_modules/next/dist/server/api-utils.js:102:9)
[0]     at async DevServer.handleApiRequest (/media/bicatalyst/Pytech/crypto-catalyst-website/NextJS/node_modules/next/dist/server/next-server.js:1064:9)
[0]     at async Object.fn (/media/bicatalyst/Pytech/crypto-catalyst-website/NextJS/node_modules/next/dist/server/next-server.js:951:37)
[0]     at async Router.execute (/media/bicatalyst/Pytech/crypto-catalyst-website/NextJS/node_modules/next/dist/server/router.js:222:32)
[0]     at async DevServer.run (/media/bicatalyst/Pytech/crypto-catalyst-website/NextJS/node_modules/next/dist/server/next-server.js:1135:29) {
[0]   name: 'OAuthCallbackError',
[0]   code: undefined
[0] }
```
I printed the state and the values is undefined, 
```
    const state = await (0, _stateHandler.useState)(cookies === null || cookies === void 0 ? void 0 : cookies[options.cookies.state.name], options);
    console.log("STATE")
    console.log(state)
```

### Is this a bug in your own project?

No

### How to reproduce ☕️

I am not sure if reproducible.

I am using 
nextjs 12.0.7 
prisma v3.6.0 
@next-auth/prisma-adapter 1.0.1
hasura

```js
import { PrismaAdapter } from '@next-auth/prisma-adapter'
import jwt from 'jsonwebtoken'
import { NextApiRequest, NextApiResponse } from 'next'
import NextAuth, { NextAuthOptions } from 'next-auth'
import GithubProvider from 'next-auth/providers/github'
import GoogleProvider from 'next-auth/providers/google'

import { prisma } from '@/lib/prisma'
import Session from '@/types/session'
import Token from '@/types/token'
import User from '@/types/user'
// https://github.com/nextauthjs/adapters/issues/120#issuecomment-787603137
// https://github.com/hasura/graphql-engine/issues/2849#issuecomment-529802902

const jwtSecret = JSON.parse(process.env.AUTH_PRIVATE_KEY || ``)

const options = {
  providers: [
    GoogleProvider({
      clientId: process.env.GOOGLE_CLIENT_ID || '',
      clientSecret: process.env.GOOGLE_CLIENT_SECRET || ''
      // authorization: {
      //   params: {
      //     prompt: 'consent',
      //     access_type: 'offline',
      //     response_type: 'code'
      //   }
      // }
    }),
    GithubProvider({
      clientId: process.env.GITHUB_ID,
      clientSecret: process.env.GITHUB_SECRET
    })
  ],
  secret: '+UeVgY+QNOLN0v9JLmZp8345dC1jZGs7U/+xiM0xDc0=',
  database: process.env.DATABASE_URL,
  adapter: PrismaAdapter(prisma),
  session: {
    strategy: 'jwt'
  },
  jwt: {
    encode: async ({ token }: { token: Token }) => {
      // fetch user id from database
      const user = await prisma.user.findFirst({
        where: {
          email: token.email
        }
      })
      const tokenContents = {
        id: `${user?.id}`,
        name: token.name,
        email: token.email,
        picture: token.picture,
        isAdmin: user?.is_admin,
        'https://hasura.io/jwt/claims': {
          'x-hasura-allowed-roles': ['admin', 'user', 'anonymous'],
          'x-hasura-default-role': user?.is_admin ? 'admin' : 'anonymous',
          'x-hasura-role': user?.is_admin ? 'admin' : 'anonymous',
          'x-hasura-user-id': `${token.id}`
        },
        iat: Date.now() / 1000,
        exp: Math.floor(Date.now() / 1000) + 72 * 60 * 60,
        sub: `${token.id}`
      }
      return jwt.sign(tokenContents, jwtSecret.key, {
        algorithm: jwtSecret.type
      })
    },
    decode: ({ token }: { token: string }) => {
      return jwt.verify(token, jwtSecret.key, {
        algorithms: jwtSecret.type
      })
    }
  },
  debug: true,
  callbacks: {
    session: async ({
      session,
      token,
      user
    }: {
      session: Session
      token: string
      user: User
    }) => {
      return Promise.resolve({
        ...session,
        id: user.id,
        token: token,
        isAdmin: user.isAdmin
      })
    },
    jwt: async ({ token, user }: { token: Token; user: User }) => {
      const isSignIn = !!user

      if (isSignIn) {
        return Promise.resolve({ ...token, id: token.id })
      }

      return Promise.resolve(token)
    }
  }
}

const Auth = (
  request: NextApiRequest,
  response: NextApiResponse
): void | Promise<void> =>
  NextAuth(request, response, options as unknown as NextAuthOptions)

export default Auth
```

### Environment 🖥

 System:
    OS: Linux 5.11 Ubuntu 20.04.3 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Memory: 5.55 GB / 31.00 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 16.13.1 - /usr/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.1.2 - /usr/local/bin/npm
  Browsers:
    Brave Browser: 96.1.32.115
    Chrome: 96.0.4664.93
    Firefox: 95.0
  npmPackages:
    next: ^12.0.7 => 12.0.7 
    next-auth: ^4.0.5 => 4.0.5 
    react: ^17.0.2 => 17.0.2 

### Contributing 🙌🏽

Yes,  I am willing to help solve this bug in a PR

**Comment by HT-Moh** [comment]
I needed to do some changes on the Account , session , and user table.  mentioned on [doc](https://next-auth.js.org/adapters/prisma) , but not in the [upgrade guide](https://next-auth.js.org/getting-started/upgrade-v4)

Now I end up with another problem 
So before the following code inside `[...nextauth]` was working, I could get back the user with it's ID, but now I don't receive the user on session callback. 

```
    session: async (session: Session, user: User) => {
      return Promise.resolve({
        ...session,
        id: user.id,
        token: jwt.sign(user, jwtSecret.key, {
          algorithm: jwtSecret.type
        }),
        isAdmin: user.isAdmin
      })
    },
``` 
[The line 85](https://github.com/nextauthjs/next-auth/blob/50fe115df6379fffe3f24408a1c8271284af660b/src/core/routes/session.ts#L65) ` const newSession = await callbacks.session({ session, token }) ` on the `session.ts` file, does not send the user back 

![image](https://user-images.githubusercontent.com/34759569/146222758-05303bdb-d7d2-4a29-bb04-4fb654c74d5f.png)

according to the doc it should 

![image](https://user-images.githubusercontent.com/34759569/146222818-191d3ac1-9e7e-4270-9c94-f0114ff4a656.png)

**Comment by balazsorban44** [comment]
https://next-auth.js.org/configuration/callbacks#session-callback
