### ISSUE TITLE
"To confirm your identity, sign in with the same account you used originally."

### ISSUE THREAD

**Issue by adnanfuat** [nextauthjs/next-auth#3488]
### Question 💬

Hi. First of all, thank you for your great service.

***

I am using NextAuth in my project. Login, logout operations are working perfectly. I am connecting to database with Prisma. No problem here either.

Then I send the updates of my project to the production environment with github. Then if necessary
"npx prisma db pull"
I am doing "npx prisma db generate" operations.

And my project starts working with recent updates. Database connection processing is problem free during this time.

***

The problem starts right here. I am a previously logged in gmail user. when i try to login again

**"To confirm your identity, sign in with the same account you used originally."**

I get an error. I wonder if it's about sessions?
I delete sessions, it doesn't work.
It makes no sense, but I'm saying it's about "Verifications" or "Accounts". I'm deleting them as well.

I'm going to Gmail. I am removing the relevant site from the sites that have access to my account. It doesn't happen again.

***

That is, until you remove that user from the "user" table in the database. Then I can login again.

**If that's the case, I have to delete all users from the database after each database update.**

My problem is big. :) Your support is very important.

### How to reproduce ☕️

I have written above

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by fredericoo** [comment]
Facing the same issue with Slack.

Here's my error log:

```
2021-12-21T10:43:45.744Z	793bb020-617c-4c9f-bb41-3434a8de2be6	ERROR	[next-auth][error][adapter_error_linkAccount] https://next-auth.js.org/errors#adapter_error_linkaccount Unknown arg `ok` in data.ok for type AccountUncheckedCreateInput. Did you mean `id`?Unknown arg `state` in data.state for type AccountUncheckedCreateInput. Did you mean `type`? {  message: 'Unknown arg `ok` in data.ok for type AccountUncheckedCreateInput. Did you mean `id`?\n' +    'Unknown arg `state` in data.state for type AccountUncheckedCreateInput. Did you mean `type`?\n',  stack: 'Error: Unknown arg `ok` in data.ok for type AccountUncheckedCreateInput. Did you mean `id`?\n' +    'Unknown arg `state` in data.state for type AccountUncheckedCreateInput. Did you mean `type`?\n' +    '\n' +    '    at Object.validate (/var/task/node_modules/@prisma/client/runtime/index.js:34750:20)\n' +    '    at PrismaClient._executeRequest (/var/task/node_modules/@prisma/client/runtime/index.js:39729:17)\n' +    '    at consumer (/var/task/node_modules/@prisma/client/runtime/index.js:39670:23)\n' +    '    at /var/task/node_modules/@prisma/client/runtime/index.js:39674:49\n' +    '    at AsyncResource.runInAsyncScope (async_hooks.js:197:9)\n' +    '    at PrismaClient._request (/var/task/node_modules/@prisma/client/runtime/index.js:39674:27)\n' +    '    at request (/var/task/node_modules/@prisma/client/runtime/index.js:39779:77)\n' +    '    at _callback (/var/task/node_modules/@prisma/client/runtime/index.js:39987:14)\n' +    '    at PrismaPromise.then (/var/task/node_modules/@prisma/client/runtime/index.js:39994:23)',  name: 'Error'}2021-12-21T10:43:45.745Z	793bb020-617c-4c9f-bb41-3434a8de2be6	ERROR	[next-auth][error][OAUTH_CALLBACK_HANDLER_ERROR] https://next-auth.js.org/errors#oauth_callback_handler_error Unknown arg `ok` in data.ok for type AccountUncheckedCreateInput. Did you mean `id`?Unknown arg `state` in data.state for type AccountUncheckedCreateInput. Did you mean `type`? Error: Unknown arg `ok` in data.ok for type AccountUncheckedCreateInput. Did you mean `id`?Unknown arg `state` in data.state for type AccountUncheckedCreateInput. Did you mean `type`?    at Object.validate (/var/task/node_modules/@prisma/client/runtime/index.js:34750:20)    at PrismaClient._executeRequest (/var/task/node_modules/@prisma/client/runtime/index.js:39729:17)    at consumer (/var/task/node_modules/@prisma/client/runtime/index.js:39670:23)    at /var/task/node_modules/@prisma/client/runtime/index.js:39674:49    at AsyncResource.runInAsyncScope (async_hooks.js:197:9)    at PrismaClient._request (/var/task/node_modules/@prisma/client/runtime/index.js:39674:27)    at request (/var/task/node_modules/@prisma/client/runtime/index.js:39779:77)    at _callback (/var/task/node_modules/@prisma/client/runtime/index.js:39987:14)    at PrismaPromise.then (/var/task/node_modules/@prisma/client/runtime/index.js:39994:23) {  name: 'LinkAccountError',  code: undefined}
```
