### ISSUE TITLE
Facebook provider - Error 400 when creating new users

### ISSUE THREAD

**Issue by lionelrudaz** [nextauthjs/next-auth#3499]
### Question 💬

I'm using Prisma as a client to connect to a Postgres DB hosted on Heroku.

I've got successful configurations for Email and Google providers. For Facebook, existing users can still connect, because there's an account record in DB, but new users can't. 

Here's the error that I get from the logs:

```
302 /api/auth/callback/facebook?codeAQDt-qTVExAOe77AlF5pbrraWctJ3OAWf-N2I576VzUwX2aLzBS0412jUe9KidDbf9mFLF7qwM18KhDi8U2ir1NPmwJZ_XNm9JOq1I3DidUiAmApYfSxvmEhXHvEDNAdvMPvg_f40VDlmpe7kWWHFfx-ufTfylU3dNn4aVkltQkf6CQasUqL_sfj4bfvoXK5gyW79JEJLcOlvqhQ7rmQNeLLaBJk-DQc4qAPnDlKsSg9uX3tRVV4-HWqpfAg-d0uR5lpcjc1tJ2Qj1-v_rNnmaEl0MOh6_E2NxjoucRQBltx3tQRtfYMjtbc1yUhzJ3mtsCm67bRDVWWjO08zwKrnmqY9Y1J9UsJQduWAi6QehgwFwGlhJGzeDYE3P8Sn2wCHi1yZ8lKrkmy8oJu3nj39a2ctoO-WAE3xghgEPZ6YG2KXw&state¶zdETQaPwfogpdH3CaSa0SZP8cU7pQX6E3-_hX_f3Y
2021-12-22T10:43:38.128Z         ERROR    [next-auth][error][OAUTH_CALLBACK_ERROR]
https://next-auth.js.org/errors#oauth_callback_error expected 200 OK, got: 400 Bad Request {
error: {
   message: 'expected 200 OK, got: 400 Bad Request',
   stack: 'OPError: expected 200 OK, got: 400 Bad Request\n' +
     '    at processResponse (/var/task/node_modules/openid-client/lib/helpers/process_response.js:41:11)\n' +
     '    at Client.grant (/var/task/node_modules/openid-client/lib/client.js:1338:22)\n' +
     '    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n' +
     '    at async Client.oauthCallback (/var/task/node_modules/openid-client/lib/client.js:610:24)\n' +
     '    at async oAuthCallback (/var/task/node_modules/next-auth/core/lib/oauth/callback.js:114:16)\n' +
     '    at async Object.callback (/var/task/node_modules/next-auth/core/routes/callback.js:50:11)\n' +
     '    at async NextAuthHandler (/var/task/node_modules/next-auth/core/index.js:133:28)\n' +
     '    at async NextAuthNextHandler (/var/task/node_modules/next-auth/next/index.js:20:19)\n' +
     '    at async Object.apiResolver (/var/task/node_modules/next/dist/server/api-utils.js:102:9)\n' +
     '    at async Server.handleApiRequest (/var/task/node_modules/next/dist/server/next-server.js:1017:9)',
   name: 'OPError'
 },
 providerId: 'facebook',
 message: 'expected 200 OK, got: 400 Bad Request'
}
2021-12-22T10:43:38.129Z                ERROR    [next-auth][error][CALLBACK_OAUTH_ERROR]
https://next-auth.js.org/errors#callback_oauth_error expected 200 OK, got: 400 Bad Request OPError: expected 200 OK, got: 400 Bad Request
   at processResponse (/var/task/node_modules/openid-client/lib/helpers/process_response.js:41:11)
   at Client.grant (/var/task/node_modules/openid-client/lib/client.js:1338:22)
   at processTicksAndRejections (internal/process/task_queues.js:97:5)
   at async Client.oauthCallback (/var/task/node_modules/openid-client/lib/client.js:610:24)
   at async oAuthCallback (/var/task/node_modules/next-auth/core/lib/oauth/callback.js:114:16)
   at async Object.callback (/var/task/node_modules/next-auth/core/routes/callback.js:50:11)
   at async NextAuthHandler (/var/task/node_modules/next-auth/core/index.js:133:28)
   at async NextAuthNextHandler (/var/task/node_modules/next-auth/next/index.js:20:19)
   at async Object.apiResolver (/var/task/node_modules/next/dist/server/api-utils.js:102:9)
   at async Server.handleApiRequest (/var/task/node_modules/next/dist/server/next-server.js:1017:9) {
 name: 'OAuthCallbackError',
 code: undefined
}
```

I've already updated my schema on Prisma based on this: https://github.com/nextauthjs/next-auth/issues/3465

```
model Account {
  id                 Int     @id @default(autoincrement())
  userId             String  @map("user_id")
  type               String  @map("provider_type")
  provider           String
  providerAccountId  String  @map("provider_account_id")
  refresh_token      String? @db.Text
  access_token       String? @db.Text
  expires_at         Int?
  token_type         String?
  scope              String?
  id_token           String? @db.Text
  session_state      String?
  oauth_token_secret String? @db.Text
  oauth_token        String? @db.Text

  user User @relation(fields: [userId], references: [id], onDelete: Cascade)

  @@unique([provider, providerAccountId])
  @@map("accounts")
}
```

I'm assuming there should be something wrong with the data retrieved from Facebook and the way it should be inserted in the DB, but as FB doesn't allow to test locally and that I don't know where to add more logs, I'm requesting for your help.

### How to reproduce ☕️

- Use a test user from Facebook developer dashboard, or use your own Facebook account if you're not registered to my app
- Go to https://www.tasters.ch
- Click on the profile icon
- Click Login with Facebook

=> You get an error OAuthCallback

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by lionelrudaz** [comment]
OK it seems to be fixed! The issue seemed to be that I didn't delete the column compound_id in my table 🤦 Don't know why it was working for Google and not for Facebook though...

**Comment by moritzmyrz** [comment]
Hello, I am experiencing this same issue although I've migrated my Prisma schema to a new database, and they're both in sync.

The following error is received whenever:
- Someone other than me tries logging in to the published production website

This does not apply to local dev instances.

```text
[GET] /api/auth/callback/facebook?code=AQCjDd1WazT8DE8SKsstm0e3iOFW10s68xzDOAwk5UNyd1HG-cwh-H5gHNCWBgoAlGIlznyyeJJR4ge588oP_OD262n9e9u1YuO_qcVYu8sPZYGigXeCL1n2ZlFwfQ8EO8x2dtsID_rDjntWpzDbpmtNUki25X9cgbm19h6AC77_HqXwBj8Ublv_y7Dx0yBaovrYqY5FcTv-AqZ1yHNzvy92ZHgv809E7GLJdpxCTux-hXSA5ZKQ22Ru_2W8wFMFaitfwn-4n607O1Y-OxQFf-J_c1Zb_JXEEEpOUM1TLj1aFgYSLlpcOqqwkKfZDkwgvMObubM2_AJfZAF71UodQ9vVWgx1PA8bFT-6G9I_Yyrzjsu9gTIat-8GaF1UPcCHKtI&state=klppdEl9m8SFEYWjPp7UFUbIy-oWawNDgXL3PKv9I-A
21:24:56:43
2022-02-24T20:24:57.173Z	ea894128-a956-40cd-b023-dc791adc17a9	ERROR	[next-auth][error][OAUTH_CALLBACK_ERROR] 
https://next-auth.js.org/errors#oauth_callback_error expected 200 OK, got: 400 Bad Request {
  error: {
    message: 'expected 200 OK, got: 400 Bad Request',
    stack: 'OPError: expected 200 OK, got: 400 Bad Request\n' +
      '    at processResponse (/var/task/node_modules/openid-client/lib/helpers/process_response.js:41:11)\n' +
      '    at Client.grant (/var/task/node_modules/openid-client/lib/client.js:1340:22)\n' +
      '    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n' +
      '    at async Client.oauthCallback (/var/task/node_modules/openid-client/lib/client.js:612:24)\n' +
      '    at async oAuthCallback (/var/task/node_modules/next-auth/core/lib/oauth/callback.js:114:16)\n' +
      '    at async Object.callback (/var/task/node_modules/next-auth/core/routes/callback.js:50:11)\n' +
      '    at async NextAuthHandler (/var/task/node_modules/next-auth/core/index.js:139:28)\n' +
      '    at async NextAuthNextHandler (/var/task/node_modules/next-auth/next/index.js:21:19)\n' +
      '    at async Object.apiResolver (/var/task/node_modules/next/dist/server/api-utils/node.js:182:9)\n' +
      '    at async NextNodeServer.runApi (/var/task/node_modules/next/dist/server/next-server.js:386:9)',
    name: 'OPError'
  },
  providerId: 'facebook',
  message: 'expected 200 OK, got: 400 Bad Request'
}
2022-02-24T20:24:57.175Z	ea894128-a956-40cd-b023-dc791adc17a9	ERROR	[next-auth][error][CALLBACK_OAUTH_ERROR] 
https://next-auth.js.org/errors#callback_oauth_error expected 200 OK, got: 400 Bad Request OPError: expected 200 OK, got: 400 Bad Request
    at processResponse (/var/task/node_modules/openid-client/lib/helpers/process_response.js:41:11)
    at Client.grant (/var/task/node_modules/openid-client/lib/client.js:1340:22)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Client.oauthCallback (/var/task/node_modules/openid-client/lib/client.js:612:24)
    at async oAuthCallback (/var/task/node_modules/next-auth/core/lib/oauth/callback.js:114:16)
    at async Object.callback (/var/task/node_modules/next-auth/core/routes/callback.js:50:11)
    at async NextAuthHandler (/var/task/node_modules/next-auth/core/index.js:139:28)
    at async NextAuthNextHandler (/var/task/node_modules/next-auth/next/index.js:21:19)
    at async Object.apiResolver (/var/task/node_modules/next/dist/server/api-utils/node.js:182:9)
    at async NextNodeServer.runApi (/var/task/node_modules/next/dist/server/next-server.js:386:9) {
  name: 'OAuthCallbackError',
  code: undefined
}
```

Of course, I've double-checked the Facebook callback URL which is the following: https://www.example.com/api/auth/callback/facebook

These are all my Prisma models and types.

```prisma
model Account {
  id                 String  @id @default(cuid())
  userId             String
  type               String
  provider           String
  providerAccountId  String
  refresh_token      String?  @db.Text
  access_token       String?  @db.Text
  expires_at         Int?
  token_type         String?
  scope              String?
  id_token           String?  @db.Text
  session_state      String?
  oauth_token_secret String?
  oauth_token        String?

  user User @relation(fields: [userId], references: [id], onDelete: Cascade)

  @@unique([provider, providerAccountId])
}


model Session {
  id           String   @id @default(cuid())
  sessionToken String   @unique
  userId       String
  expires      DateTime


  user         User     @relation(fields: [userId], references: [id], onDelete: Cascade)
}

model User {
  id            String    @id @default(cuid())
  name          String?
  email         String?   @unique
  emailVerified DateTime?
  image         String?

  accounts      Account[]
  sessions      Session[]

  Reputation Trade[] @relation("user")
  Reputated  Trade[] @relation("author")

  role Role @default(USER)
}

model VerificationToken {
  identifier String
  token      String   @unique
  expires    DateTime

  @@unique([identifier, token])
}

model Trade {
  id        String    @id @default(cuid())
  author    User      @relation("author", references: [id], fields: [authorId])
  user      User      @relation("user", references: [id], fields: [userId])
  published Boolean   @default(true)
  comment   String
  rating    Float       @default(3.0)
  createdAt DateTime  @default(now()) @map(name: "created_at")
  updatedAt DateTime  @default(now()) @map(name: "updated_at")

  authorId String
  userId   String
}

enum Role {
  USER
  MODERATOR
  ADMINISTRATOR
}
```

**Comment by lionelrudaz** [comment]
Don't know if that's related, but I realized there was a regression when I updated to 4.1.2. Facebook user creation was not working anymore. I've updated to 4.2 and it was working again. I had also to change the API version to v10.0.

Really weird stuff happening from time to time...

**Comment by moritzmyrz** [comment]
> Don't know if that's related, but I realized there was a regression when I updated to 4.1.2. Facebook user creation was not working anymore. I've updated to 4.2 and it was working again. I had also to change the API version to v10.0.
> 
> 
> 
> Really weird stuff happening from time to time...

Well the v10 is deprecated atm, only v13 is available as I can see.
![image](https://user-images.githubusercontent.com/64229413/155734513-32623311-f6f0-4756-b423-dd49519ecb69.png)

**Comment by lionelrudaz** [comment]
<img width="983" alt="CleanShot 2022-02-28 at 15 24 24@2x" src="https://user-images.githubusercontent.com/592678/155999566-742b0e48-10da-4055-b3bf-66315917788c.png">

Well, on my side I was able to go back to v10 for the first dropdown and v11 for the second dropdown.

As soon as I upgrade one of those fields, the new users can't sign up...

**Comment by moritzmyrz** [comment]
> <img alt="CleanShot 2022-02-28 at 15 24 24@2x" width="983" src="https://user-images.githubusercontent.com/592678/155999566-742b0e48-10da-4055-b3bf-66315917788c.png">
> 
> Well, on my side I was able to go back to v10 for the first dropdown and v11 for the second dropdown.
> 
> As soon as I upgrade one of those fields, the new users can't sign up...

Ah alright, as my Facebook app is recently created I was not able to change it back to a version, however, one of my older apps has the possibility to do so after all.

**Comment by lionelrudaz** [comment]
I'm not familiar enough with the different versions of Facebook API to know if there are some breaking changes between them. I seemed to be the only one with issues creating new users, so I don't know. Can you try plugging it to your old app to see if that's working?

**Comment by moritzmyrz** [comment]
> I'm not familiar enough with the different versions of Facebook API to know if there are some breaking changes between them. I seemed to be the only one with issues creating new users, so I don't know. Can you try plugging it to your old app to see if that's working?
Unfortunately, when I restored the older app, the API versions automatically changed themselves back to v13.0 with no possibility to change.
