### ISSUE TITLE
Unable to get session server-side.

### ISSUE THREAD

**Issue by david-de-angelis** [nextauthjs/next-auth#3611]
### Description 🐜

Trying to access the current next-auth session from within an GraphQL API call in my nextJS project, 

using
```
import { getSession } from 'next-auth/react';
import { Session } from 'next-auth';

const session: Session | null = await getSession({ req: context.req });
```

however I am getting the following error:

```
[next-auth][error][CLIENT_FETCH_ERROR] 
https://next-auth.js.org/errors#client_fetch_error Cannot read property 'cookie' of undefined {
  error: {
    message: "Cannot read property 'cookie' of undefined",
    stack: "TypeError: Cannot read property 'cookie' of undefined\n" +
      '    at _callee$ (/Users/davidctolabs/Desktop/Projects/add/node_modules/next-auth/client/_utils.js:44:69)\n' +
      '    at tryCatch (/Users/davidctolabs/Desktop/Projects/add/node_modules/regenerator-runtime/runtime.js:63:40)\n' +
      '    at Generator.invoke [as _invoke] (/Users/davidctolabs/Desktop/Projects/add/node_modules/regenerator-runtime/runtime.js:294:22)\n' +
      '    at Generator.next (/Users/davidctolabs/Desktop/Projects/add/node_modules/regenerator-runtime/runtime.js:119:21)\n' +
      '    at asyncGeneratorStep (/Users/davidctolabs/Desktop/Projects/add/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)\n' +
      '    at _next (/Users/davidctolabs/Desktop/Projects/add/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)\n' +
      '    at /Users/davidctolabs/Desktop/Projects/add/node_modules/@babel/runtime/helpers/asyncToGenerator.js:32:7\n' +
      '    at new Promise (<anonymous>)\n' +
      '    at /Users/davidctolabs/Desktop/Projects/add/node_modules/@babel/runtime/helpers/asyncToGenerator.js:21:12\n' +
      '    at fetchData (/Users/davidctolabs/Desktop/Projects/add/node_modules/next-auth/client/_utils.js:24:21)',
    name: 'TypeError'
  },
  path: 'session',
  header: undefined,
  message: "Cannot read property 'cookie' of undefined"
}
```

and `session.user` is undefined.

The 'NEXTAUTH_URL' environment variable exists in my .env, as per the docs:
`NEXTAUTH_URL=http://localhost:3000`

Not sure if this error is occuring to everyone or if it's just me, I have spent a few hours making sure I did the v4 migration properly, and as far as I can tell, it's all up to scratch... so I thought I'd make this issue.

TIA

### Is this a bug in your own project?

Yes

### How to reproduce ☕️

Trying to access the session from within a graphQL resolver

```
    risks: async (_parent, _args, _context, _info) => {
      const session: Session | null = await getSession({ req: _context.req });
      console.log(session.user):
      return (await _context.dataLoaders.bleh.load(_parent.id)) as Risk[];
    },
```

### Environment 🖥

  System:
    OS: macOS 11.6
    CPU: (4) x64 Intel(R) Core(TM) i5-7287U CPU @ 3.30GHz
    Memory: 1.83 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.6 - /usr/local/bin/node
    npm: 8.1.2 - /usr/local/bin/npm
  Browsers:
    Chrome: 97.0.4692.71
    Safari: 14.1.2
  npmPackages:
    next: ^11.1.3 => 11.1.3 
    next-auth: ^4.0.6 => 4.0.6 
    react: ^17.0.2 => 17.0.2 

### Contributing 🙌🏽

Yes,  I am willing to help solve this bug in a PR

**Comment by david-de-angelis** [comment]
fixed, for some reason, it required me to do the following:
`const session = await getSession({ req: req.req });`
