### ISSUE TITLE
ModuleNotFoundError: Module not found: Error: Can't resolve 'next/server'

### ISSUE THREAD

**Issue by ShahriarKh** [nextauthjs/next-auth#3671]
### Question 💬

I just cloned the [Next Auth Example][1], changed ports in package.json to match my server and added my domain in `.env.local`. Because of WASM middleware in Next 12, I had to downgrade to Next 11.
When I try to `npm run build`, I get this error:
```lang-shellsession
ModuleNotFoundError: Module not found: Error: Can't resolve 'next/server' in 'domain.com/pages'
```
The `npm run dev` works fine.

The page that has the `server` import is:
https://github.com/nextauthjs/next-auth-example/blob/main/pages/_middleware.js
```js
import { getToken } from "next-auth/jwt"
import { NextResponse } from "next/server"

/** @param {import("next/server").NextRequest} req */
export async function middleware(req) {
  if (req.nextUrl.pathname === "/middleware-protected") {
    const session = await getToken({
      req,
      secret: process.env.SECRET,
      secureCookie:
        process.env.NEXTAUTH_URL?.startsWith("https://") ??
        !!process.env.VERCEL_URL,
    })
    // You could also check for any property on the session object,
    // like role === "admin" or name === "John Doe", etc.
    if (!session) return NextResponse.redirect("/api/auth/signin")
    // If user is authenticated, continue.
  }
}
```

### Full Log:
```lang-console
> next-auth-example@0.0.0 build /domain.com
> next build

info  - Loaded env from /domain.com/.env.local
info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
info  - Checking validity of types
warn  - No ESLint configuration detected. Run next lint to begin setup
info  - Creating an optimized production build
Failed to compile.

ModuleNotFoundError: Module not found: Error: Can't resolve 'next/server' in 'domain.com/pages'


> Build error occurred
Error: > Build failed because of webpack errors
    at domain.com/node_modules/next/dist/build/index.js:397:19
    at async Span.traceAsyncFn (domain.com/node_modules/next/dist/telemetry/trace/trace.js:60:20)
    at async Object.build [as default] (domain.com/node_modules/next/dist/build/index.js:77:25)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! next-auth-example@0.0.0 build: `next build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the next-auth-example@0.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     domain.com/.npm/_logs/blahblahblah-debug.log // I edited this line
```

What's causing the problem and how should I solve it?

  [1]: https://github.com/nextauthjs/next-auth-example

### package.json
```json
{
  "name": "authentication",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "author": "damn",
  "license": "ISC",
  "dependencies": {
    "next": "^11.1.2",
    "next-auth": "^4.1.2",
    "react": "^17.0.2",
    "react-dom": "^17.0.2"
  }
}
```
(removed -p since it had no effect in my environment)

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
This is not even NextAuth.js related.

You are using Next.js 11, which does not support Middleware. You have to upgrade to at least 12.

**Comment by ShahriarKh** [comment]
Got it! So:
1. I added info in the readme to state that the example uses Next 12's Middleware & opened a pull request.
2. Is there an example app using Next 11?

**Comment by balazsorban44** [comment]
No. But upgrading from Next 11 to Next 12 should be straightforward, and there is no real breaking change. I highly recommend upgrading https://nextjs.org/docs/upgrading#upgrading-from-11-to-12
