### ISSUE TITLE
GET_AUTHORIZATION_URL_ERROR timeout

### ISSUE THREAD

**Issue by khuezy** [nextauthjs/next-auth#3718]
### Question 💬

Hi, I need some help determining the cause of this error. I've successfully used NextAuth w/ vercel but I'm having trouble with it on AWS Lambda + CloudFront.

I currently have GoogleProvider + Prisma Adapter. When I click on "Sign in with Google", it waits ~3seconds and then it errors.
NOTE: this works when I run locally `ie npm run dev`
```
ERROR	[next-auth][error][GET_AUTHORIZATION_URL_ERROR]
https://next-auth.js.org/errors#get_authorization_url_error outgoing request timed out after 3500ms {
  message: 'outgoing request timed out after 3500ms',
  stack: 'RPError: outgoing request timed out after 3500ms\n' +
    '    at /var/task/node_modules/openid-client/lib/helpers/request.js:136:13\n' +
    '    at async Function.discover (/var/task/node_modules/openid-client/lib/issuer.js:144:24)\n' +
    '    at async openidClient (/var/task/node_modules/next-auth/core/lib/oauth/client.js:16:14)\n' +
    '    at async getAuthorizationUrl (/var/task/node_modules/next-auth/core/lib/oauth/authorization-url.js:67:20)\n' +
    '    at async Object.signin (/var/task/node_modules/next-auth/core/routes/signin.js:37:24)\n' +
    '    at async NextAuthHandler (/var/task/node_modules/next-auth/core/index.js:191:26)\n' +
    '    at async NextAuthNextHandler (/var/task/node_modules/next-auth/next/index.js:20:19)\n' +
    '    at async Object.apiResolver (/var/task/node_modules/next/dist/server/api-utils.js:102:9)\n' +
    '    at async /var/task/.next/serverless/chunks/884.js:38:13',
  name: 'RPError'
}
```

```
[next-auth][error][SIGNIN_OAUTH_ERROR] 
https://next-auth.js.org/errors#signin_oauth_error outgoing request timed out after 3500ms {
  error: {
    message: 'outgoing request timed out after 3500ms',
    stack: 'RPError: outgoing request timed out after 3500ms\n' +
      '    at /var/task/node_modules/openid-client/lib/helpers/request.js:136:13\n' +
      '    at async Function.discover (/var/task/node_modules/openid-client/lib/issuer.js:144:24)\n' +
      '    at async openidClient (/var/task/node_modules/next-auth/core/lib/oauth/client.js:16:14)\n' +
      '    at async getAuthorizationUrl (/var/task/node_modules/next-auth/core/lib/oauth/authorization-url.js:67:20)\n' +
      '    at async Object.signin (/var/task/node_modules/next-auth/core/routes/signin.js:37:24)\n' +
      '    at async NextAuthHandler (/var/task/node_modules/next-auth/core/index.js:191:26)\n' +
      '    at async NextAuthNextHandler (/var/task/node_modules/next-auth/next/index.js:20:19)\n' +
      '    at async Object.apiResolver (/var/task/node_modules/next/dist/server/api-utils.js:102:9)\n' +
      '    at async /var/task/.next/serverless/chunks/884.js:38:13',
    name: 'RPError'
  },
  provider: {
    id: 'google',
    name: 'Google',
    type: 'oauth',
    wellKnown: 'https://accounts.google.com/.well-known/openid-configuration',
    authorization: { params: [Object] },
    idToken: true,
    checks: [ 'pkce', 'state' ],
    profile: [Function: profile],
    clientId: 'c.apps.googleusercontent.com',
    clientSecret: 'secret',
    signinUrl: 'https://dev.example.com/api/auth/signin/google',
    callbackUrl: 'https://dev.example.com/api/auth/callback/google'
  },
  message: 'outgoing request timed out after 3500ms'
}
```

Thanks!

### How to reproduce ☕️

N/A

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by khuezy** [comment]
Sorry, this is addressed in this discussion: https://github.com/nextauthjs/next-auth/discussions/3186
