### ISSUE TITLE
GetUserByEmailError: Requested resource not found

### ISSUE THREAD

**Issue by jaimin-grubbrr** [nextauthjs/next-auth#3759]
### Description 🐜

```[next-auth][error][adapter_error_getUserByEmail] 
https://next-auth.js.org/errors#adapter_error_getuserbyemail Requested resource not found {
  message: 'Requested resource not found',
  stack: 'ResourceNotFoundException: Requested resource not found\n' +
    '    at deserializeAws_json1_0QueryCommandError (/home/mustan/Jaimin/Demos/nextjs-auth-demo/node_modules/@aws-sdk/client-dynamodb/dist-cjs/protocols/Aws_json1_0.js:2984:41)\n' +
    '    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n' +
    '    at async /home/mustan/Jaimin/Demos/nextjs-auth-demo/node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24\n' +
    '    at async /home/mustan/Jaimin/Demos/nextjs-auth-demo/node_modules/@aws-sdk/middleware-signing/dist-cjs/middleware.js:11:20\n' +
    '    at async StandardRetryStrategy.retry (/home/mustan/Jaimin/Demos/nextjs-auth-demo/node_modules/@aws-sdk/middleware-retry/dist-cjs/StandardRetryStrategy.js:51:46)\n' +
    '    at async /home/mustan/Jaimin/Demos/nextjs-auth-demo/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:6:22\n' +
    '    at async /home/mustan/Jaimin/Demos/nextjs-auth-demo/node_modules/@aws-sdk/lib-dynamodb/dist-cjs/commands/QueryCommand.js:34:26\n' +
    '    at async getUserByEmail (/home/mustan/Jaimin/Demos/nextjs-auth-demo/node_modules/@next-auth/dynamodb-adapter/dist/index.js:42:26)',
  name: 'ResourceNotFoundException'
}
error - GetUserByEmailError: Requested resource not found```

### Is this a bug in your own project?

Yes

### How to reproduce ☕️

on page load 

### Screenshots / Logs 📽

![Screenshot from 2022-01-28 16-04-33](https://user-images.githubusercontent.com/85555880/151532063-13c8a3ba-7dc2-4890-ae21-45a8d74d1f81.png)


### Environment 🖥

local environmnet 

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by david-mcqueen** [comment]
@jaimin-grubbrr Did you manage to resolve? I am seeing the same issue today when I deploy to prod, but it is working fine on dev. It would be good to know how you managed to get past this? 😀
