### ISSUE TITLE
OAuthCallbackError on Dropbox integrating

### ISSUE THREAD

**Issue by michaltaberski** [nextauthjs/next-auth#3899]
### Question 💬

Hello,

I am integrating Dropbox just like I do Facebook and Google. However although Facebook and Google works Dropbox does not. I am constantly getting an error `expected 200 OK, got: 404 Not Found`

```
[next-auth][error][OAUTH_CALLBACK_ERROR]
https://next-auth.js.org/errors#oauth_callback_error expected 200 OK, got: 404 Not Found {
  error: {
    message: 'expected 200 OK, got: 404 Not Found',
    stack: 'OPError: expected 200 OK, got: 404 Not Found\n' +
      '    at processResponse (.../node_modules/openid-client/lib/helpers/process_response.js:41:11)\n' +
      '    at Client.userinfo (.../node_modules/openid-client/lib/client.js:1250:18)\n' +
      '    at runMicrotasks (<anonymous>)\n' +
      '    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n' +
      '    at async oAuthCallback (.../node_modules/next-auth/core/lib/oauth/callback.js:134:17)\n' +
      '    at async Object.callback (.../node_modules/next-auth/core/routes/callback.js:50:11)\n' +
      '    at async NextAuthHandler (.../node_modules/next-auth/core/index.js:139:28)\n' +
      '    at async NextAuthNextHandler (.../node_modules/next-auth/next/index.js:21:19)\n' +
      '    at async .../node_modules/next-auth/next/index.js:57:32\n' +
      '    at async Object.apiResolver (.../node_modules/next/dist/server/api-utils.js:101:9)',
    name: 'OPError'
  },
  providerId: 'dropbox',
  message: 'expected 200 OK, got: 404 Not Found'
}
[next-auth][error][CALLBACK_OAUTH_ERROR]
https://next-auth.js.org/errors#callback_oauth_error expected 200 OK, got: 404 Not Found OPError: expected 200 OK, got: 404 Not Found
    at processResponse (.../node_modules/openid-client/lib/helpers/process_response.js:41:11)
    at Client.userinfo (.../node_modules/openid-client/lib/client.js:1250:18)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async oAuthCallback (.../node_modules/next-auth/core/lib/oauth/callback.js:134:17)
    at async Object.callback (.../node_modules/next-auth/core/routes/callback.js:50:11)
```

I have intentionally installed `node v14.19.0`, but the issues is still happening. Not sure how to debug it further. Any ideas?

### How to reproduce ☕️

Just use `DropboxProvider` and try to login with that provider.

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
https://github.com/nextauthjs/next-auth/issues/2524
