### ISSUE TITLE
Signing in with Email magic link second time fails

### ISSUE THREAD

**Issue by goranefbl** [nextauthjs/next-auth#3923]
### Title

Second email magic link signin fails

### How to reproduce ☕️

Package.json:
```

{
    "private": true,
    "scripts": {
        "dev": "next dev -p 3000",
        "build": "next build",
        "start": "next start",
        "vercel-build": "prisma generate && next build",
        "prisma:generate": "prisma generate"
    },
    "dependencies": {
        "@heroicons/react": "^1.0.5",
        "@hookform/resolvers": "^2.8.4",
        "@next-auth/prisma-adapter": "^1.0.1",
        "@sendgrid/client": "^7.6.0",
        "@sendgrid/mail": "^7.6.0",
        "@sentry/nextjs": "^6.17.5",
        "bcryptjs": "^2.4.3",
        "cloudinary": "^1.27.1",
        "draft-js": "^0.11.7",
        "immer": "^9.0.7",
        "joi": "^17.4.2",
        "joi-extract-type": "^15.0.8",
        "multer": "^1.4.4",
        "multer-storage-cloudinary": "^4.0.0",
        "next": "^12.0.7",
        "next-auth": "^4.2.1",
        "next-seo": "^4.29.0",
        "nodemailer": "^6.7.2",
        "nprogress": "^0.2.0",
        "react": "17.0.2",
        "react-dom": "17.0.2",
        "react-draft-wysiwyg": "^1.14.7",
        "react-gtm-module": "^2.0.11",
        "react-hook-form": "^7.20.5",
        "react-select": "^5.2.1",
        "slugify": "^1.6.3",
        "swr": "^1.1.0",
        "yup": "^0.32.11"
    },
    "devDependencies": {
        "@babel/preset-env": "^7.16.4",
        "@babel/preset-typescript": "^7.16.0",
        "@prisma/client": "^3.9.2",
        "@tailwindcss/forms": "^0.3.4",
        "@testing-library/jest-dom": "^5.15.1",
        "@testing-library/react": "^12.1.2",
        "@types/draft-js": "^0.11.7",
        "@types/react": "^17.0.35",
        "@types/react-draft-wysiwyg": "^1.13.3",
        "@types/react-select": "^5.0.1",
        "autoprefixer": "^10.4.0",
        "eslint-config-prettier": "^8.3.0",
        "jest": "^27.4.2",
        "msw": "^0.35.0",
        "node-mocks-http": "^1.11.0",
        "postcss": "^8.4.4",
        "prisma": "^3.9.2",
        "react-test-renderer": "^17.0.2",
        "tailwindcss": "^2.2.19",
        "typescript": "^4.5.2"
    },
    "prisma": {
        "seed": "node prisma/seed.js"
    }
}

```

My prisma scheme:

```

model Account {
  id                 String  @id @default(cuid()) @db.VarChar(255)
  userId             String  @db.VarChar(255)
  type               String  @db.VarChar(255)
  provider           String  @db.VarChar(255)
  providerAccountId  String  @db.VarChar(255)
  refresh_token      String? @db.VarChar(500)
  access_token       String? @db.VarChar(500)
  expires_at         Int?
  token_type         String? @db.VarChar(255)
  scope              String? @db.VarChar(255)
  id_token           String? @db.Text
  session_state      String? @db.VarChar(255)
  oauth_token_secret String? @db.VarChar(255)
  oauth_token        String? @db.VarChar(255)
  user               User    @relation(fields: [userId], references: [id], onDelete: NoAction, onUpdate: NoAction, map: "accounts_userid_foreign")

  @@unique([provider, providerAccountId], map: "accounts_provider_provideraccountid_unique")
  @@index([userId], map: "accounts_userid_index")
  @@map("accounts")
}

model User {
  id                   String         @id @default(cuid()) @db.VarChar(255)
  name                 String?        @db.VarChar(255)
  email                String         @unique(map: "users_email_unique") @db.VarChar(255)
  emailVerified        DateTime?      @db.DateTime(0)
  password             String?        @db.VarChar(255)
  image                String?        @db.VarChar(255)
  role                 Role           @default(USER)
  resetPasswordToken   String?        @db.VarChar(255)
  resetPasswordExpires DateTime?      @db.Timestamp(0)
  created_at           DateTime?      @default(now()) @db.Timestamp(0)
  updated_at           DateTime?      @updatedAt @db.Timestamp(0)
  deleted_at           DateTime?      @db.Timestamp(0)
  accounts             Account[]
  utisci               utisci[]
  companies            companies?     @relation("companiesTousers")
  jobs                 jobs[]         @relation("jobsTousers")
  user_meta            user_meta?     @relation("user_metaTousers")
  utisci_votes         utisci_votes[]

  @@map("users")
}

```

### Your question/bug report 📓

So when creating a user with Magic link everything works well and user gets signed in. But if he tries to sign in again, p.user.update which is run under updateUser Adapter method fails, with below error: 

```
Invalid `p.user.update()` invocation in
/Users/goranjakovljevic/React/it-poslovi/node_modules/@next-auth/prisma-adapter/dist/index.js:19:27

  16 },
  17 updateUser: (data) => {
  18     console.log('d',data);
→ 19     return p.user.update(
  Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Server(ServerError { code: 1105, message: "symbol `it-poslovi`.users.id not found", state: "HY000" })) })
    at cb (/Users/goranjakovljevic/React/it-poslovi/node_modules/@prisma/client/runtime/index.js:38707:17)
    at async PrismaClient._request (/Users/goranjakovljevic/React/it-poslovi/node_modules/@prisma/client/runtime/index.js:40859:18) {
  clientVersion: '3.9.2'
}
CALLBACK_EMAIL_ERROR Error: 
Invalid `p.user.update()` invocation in
/Users/goranjakovljevic/React/it-poslovi/node_modules/@next-auth/prisma-adapter/dist/index.js:19:27

  16 },
  17 updateUser: (data) => {
  18     console.log('d',data);
→ 19     return p.user.update(
  Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Server(ServerError { code: 1105, message: "symbol `it-poslovi`.users.id not found", state: "HY000" })) })
    at cb (/Users/goranjakovljevic/React/it-poslovi/node_modules/@prisma/client/runtime/index.js:38707:17)
    at async PrismaClient._request (/Users/goranjakovljevic/React/it-poslovi/node_modules/@prisma/client/runtime/index.js:40859:18) {
  name: 'UpdateUserError',
  code: undefined
```

### Contributing  🙌🏽

No, I'm afraid I cannot help regarding this

**Comment by goranefbl** [comment]
If I change updateUser Method to:

updateUser: (data) => {
            console.log('d',data);
            return p.user.findUnique({ where: { id: data.id } })
//            return p.user.update({ where: { id: data.id }, data })
        },

its working just fine. So the question is, what does the updateUser do within Email provider? Since email is verified on account creation and only data that is sent is emailVerified?

**Comment by goranefbl** [comment]
This might be issue with Planetscale, per https://github.com/prisma/prisma/issues/10758

**Comment by riccardogiorato** [comment]
how did you solve this @goranefbl ?
