### ISSUE TITLE
Trying to use Callbacks in next-auth but it isn't working!

### ISSUE THREAD

**Issue by AR-Ayush-Kumar-Sahoo** [nextauthjs/next-auth#3961]
### Question 💬

So, While I was trying to customize the session that next-auth gives after the signin using callbacks but I get an error!

Heres my code:
```js
  callbacks: {
    async jwt({ token, user }) {
      if (user) {
        token.id = user.id;
      }
      return token;
    },
    async session({ session, token }) {
      session.id = token.id;
      return session;
    },
  },
```
after all my other code and i get this error:
```
https://next-auth.js.org/errors#session_error Cannot read properties of undefined (reading 'id') {
  message: "Cannot read properties of undefined (reading 'id')",
  stack: "TypeError: Cannot read properties of undefined (reading 'id')\n" +
    '    at Object.session (D:\\Builds\\team-dd05\\.next\\server\\pages\\api\\auth\\[...nextauth].js:54:26)\n' +
    '    at Object.session (D:\\Builds\\team-dd05\\node_modules\\next-auth\\core\\routes\\session.js:111:48)\n' +
    '    at runMicrotasks (<anonymous>)\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n' +
    '    at async NextAuthHandler (D:\\Builds\\team-dd05\\node_modules\\next-auth\\core\\index.js:96:27)\n' +
    '    at async NextAuthNextHandler (D:\\Builds\\team-dd05\\node_modules\\next-auth\\next\\index.js:21:19)\n' +
    '    at async D:\\Builds\\team-dd05\\node_modules\\next-auth\\next\\index.js:57:32\n' +
    '    at async apiResolver (D:\\Builds\\team-dd05\\node_modules\\next\\dist\\next-server\\server\\api-utils.js:8:1)\n' +
    '    at async DevServer.handleApiRequest (D:\\Builds\\team-dd05\\node_modules\\next\\dist\\next-server\\server\\next-server.js:66:462)\n' +
    '    at async Object.fn (D:\\Builds\\team-dd05\\node_modules\\next\\dist\\next-server\\server\\next-server.js:58:580)\n' +
    '    at async Router.execute (D:\\Builds\\team-dd05\\node_modules\\next\\dist\\next-server\\server\\router.js:25:67)\n' +
    '    at async DevServer.run (D:\\Builds\\team-dd05\\node_modules\\next\\dist\\next-server\\server\\next-server.js:68:1042)\n' +
    '    at async DevServer.handleRequest (D:\\Builds\\team-dd05\\node_modules\\next\\dist\\next-server\\server\\next-server.js:32:504)',
 
 name: 'TypeError'
}
```

Plz help me cuz i need to deliver this project today!

### How to reproduce ☕️

Already provided above!

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by AR-Ayush-Kumar-Sahoo** [comment]
I thought it was a bug in next js but no there was a problem in my code!

When you change `session.id = token.id` to `session.id = token?.id`
It suddenly just magically worked!
