### ISSUE TITLE
error:id_token not present in TokenSet when adding scopes for google signin

### ISSUE THREAD

**Issue by ma3ve** [nextauthjs/next-auth#4295]
### Question 💬

When adding scopes to Google Provider, sign in works properly but after signing in I get the below error
```
[next-auth][error][OAUTH_CALLBACK_ERROR] 
https://next-auth.js.org/errors#oauth_callback_error id_token not present in TokenSet {
  error: {
    message: 'id_token not present in TokenSet',
    stack: 'TypeError: id_token not present in TokenSet\n' +
      '    at Client.validateIdToken (C:\\Users\\jo\\Desktop\\epub-reader\\node_modules\\openid-client\\lib\\client.js:757:15)\n' +
      '    at Client.callback (C:\\Users\\jo\\Desktop\\epub-reader\\node_modules\\openid-client\\lib\\client.js:486:18)\n' +
      '    at runMicrotasks (<anonymous>)\n' +
      '    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n' +
      '    at async oAuthCallback (C:\\Users\\jo\\Desktop\\epub-reader\\node_modules\\next-auth\\core\\lib\\oauth\\callback.js:112:16)\n' +
      '    at async Object.callback (C:\\Users\\jo\\Desktop\\epub-reader\\node_modules\\next-auth\\core\\routes\\callback.js:50:11)\n' +
      '    at async NextAuthHandler (C:\\Users\\jo\\Desktop\\epub-reader\\node_modules\\next-auth\\core\\index.js:139:28)\n' +
      '    at async NextAuthNextHandler (C:\\Users\\jo\\Desktop\\epub-reader\\node_modules\\next-auth\\next\\index.js:21:19)\n' +
      '    at async C:\\Users\\jo\\Desktop\\epub-reader\\node_modules\\next-auth\\next\\index.js:57:32\n' +
      '    at async Object.apiResolver (C:\\Users\\jo\\Desktop\\epub-reader\\node_modules\\next\\dist\\server\\api-utils\\node.js:182:9)',
    name: 'TypeError'
  },
  providerId: 'google',
  message: 'id_token not present in TokenSet'
}
[next-auth][error][CALLBACK_OAUTH_ERROR] 
https://next-auth.js.org/errors#callback_oauth_error id_token not present in TokenSet TypeError: id_token not present in TokenSet
    at Client.validateIdToken (C:\Users\jo\Desktop\epub-reader\node_modules\openid-client\lib\client.js:757:15)
    at Client.callback (C:\Users\jo\Desktop\epub-reader\node_modules\openid-client\lib\client.js:486:18)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async oAuthCallback (C:\Users\jo\Desktop\epub-reader\node_modules\next-auth\core\lib\oauth\callback.js:112:16)
    at async Object.callback (C:\Users\jo\Desktop\epub-reader\node_modules\next-auth\core\routes\callback.js:50:11)
    at async NextAuthHandler (C:\Users\jo\Desktop\epub-reader\node_modules\next-auth\core\index.js:139:28)
    at async NextAuthNextHandler (C:\Users\jo\Desktop\epub-reader\node_modules\next-auth\next\index.js:21:19)
    at async C:\Users\jo\Desktop\epub-reader\node_modules\next-auth\next\index.js:57:32
    at async Object.apiResolver (C:\Users\jo\Desktop\epub-reader\node_modules\next\dist\server\api-utils\node.js:182:9) {
  name: 'OAuthCallbackError',
  code: undefined
}
```
my [...nextauth].ts file
```
import NextAuth from "next-auth";
import GoogleProvider from "next-auth/providers/google";

export default NextAuth({
  // Configure one or more authentication providers
  providers: [
    GoogleProvider({
      clientId: process.env.GOOGLE_ID,
      clientSecret: process.env.GOOGLE_SECRET,
      authorization:{
        params:{
          scope:"https://www.googleapis.com/auth/drive.file"
        }
      }
    }),
  ],
  secret: process.env.SECRET,
  callbacks: {
    session: async ({session, user,token}) => {
      session.user = user;
      session.token = token;
      return session
    }
  },
});
```

### How to reproduce ☕️

Create a google project and enable an API that uses OAuth for authentication, I am using google drive for this project. and add the below code to the `[...nextauth.js]` file as shown above. remember to add env variables, 

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by ma3ve** [comment]
thanks, it works

**Comment by fotoflo** [comment]
Thanks, this worked for me too... 

To be clear i added open id to the scopes in the OAuthConfig object's options:
```
      params: {
        scope: "openid https://www.googleapis.com/auth/gmail.send",
      },
```

**Comment by akshayraichur** [comment]
Thanks, this worked for me too...

**Comment by sidharrth2002** [comment]
works for me as well!

**Comment by sourabh32** [comment]
Thanks guyz saved another project going to bin😂
