### ISSUE TITLE
500 Error deploying NextAuth app on Vercel: Please install mysql2 package manually

### ISSUE THREAD

**Issue by thomasmost** [nextauthjs/next-auth#4315]
### Question 💬

How do I force Vercel to install mysql2 for my next-auth functions using the Sequelize adapter?

When I configure next-auth with the default Sequelize adapter, I have to install mysql2 to get it to work locally.

When Vercel deploys my app, the first auth page (signin) returns a 500 error, and the function logs display the following:

```
[POST] /api/auth/_log
16:45:44:02
2022-04-03T20:45:44.775Z	7ee8db08-0e39-451a-ba46-c2d4627cc05f	ERROR	Error: Please install mysql2 package manually
    at ConnectionManager._loadDialectModule (/var/task/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:55:15)
    at new ConnectionManager (/var/task/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:30:21)
    at new MysqlDialect (/var/task/node_modules/sequelize/lib/dialects/mysql/index.js:13:30)
    at new Sequelize (/var/task/node_modules/sequelize/lib/sequelize.js:188:20)
    at /var/task/.next/server/pages/api/auth/[...nextauth].js:58:19
RequestId: 7ee8db08-0e39-451a-ba46-c2d4627cc05f Error: Runtime exited with error: exit status 1
Runtime.ExitError
```

`mysql2` is in my package.json and my lockfile. I would imagine this is a common configuration (Vercel and Next.js with Next-Auth and Sequelize)! Any help will be appreciated

### How to reproduce ☕️

**package.json**
```json
{
  "name": "next-app",
  "private": true,
  "proxy": "http://127.0.0.1:8000",
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "@next-auth/sequelize-adapter": "^1.0.2",
    "date-fns": "^2.28.0",
    "graphql": "^16.3.0",
    "graphql-request": "^4.0.0",
    "mysql2": "^2.3.3",
    "next": "^12.1.0",
    "next-auth": "^4.3.1",
    "next-themes": "^0.1.1",
    "nodemailer": "^6.7.3",
    "react": "^17.0.2",
    "react-code-blocks": "^0.0.9-0",
    "react-dom": "^17.0.2",
    "react-feather": "^2.0.9",
    "react-transition-group": "^4.4.2",
    "sequelize": "^6.17.0"
  },
  "devDependencies": {
    "@types/node": "17.0.19",
    "@types/react": "17.0.39",
    "@types/react-transition-group": "^4.4.4",
    "eslint": "8.9.0",
    "eslint-config-next": "12.1.0",
    "typescript": "4.5.5"
  }
}
```

**[...nextauth].ts**

```ts
import NextAuth from "next-auth";
import EmailProvider from "next-auth/providers/email";

import SequelizeAdapter from "@next-auth/sequelize-adapter";
import { Sequelize } from "sequelize";

// https://sequelize.org/master/manual/getting-started.html#connecting-to-a-database
const sequelize = new Sequelize(process.env.DATABASE_URL);

const adapter = SequelizeAdapter(sequelize);

export default NextAuth({
  adapter,
  providers: [
    EmailProvider({
      server: process.env.EMAIL_SERVER,
      from: process.env.EMAIL_FROM,
    }),
    // ...add more providers here
  ],
});
```

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by thomasmost** [comment]
Oop, figured it out. To get the package properly included, you need to explicitly require the `dialectModule` as documented in [this similar issue](https://github.com/vercel/ncc/issues/345#issuecomment-487404520).

This resolves the problem:

```ts
const sequelize = new Sequelize(process.env.DATABASE_URL, {
    dialect: 'mysql',
    dialectModule: require('mysql2')
  })
```
