### ISSUE TITLE
Azure B2C jwt not active now with clock tolerance 10 issue 

### ISSUE THREAD

**Issue by ranjeetthorat** [nextauthjs/next-auth#4373]
### Provider type

Azure Active Directory B2C

### Environment

 System:
    OS: Windows 10 10.0.19043
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
    Memory: 885.07 MB / 7.69 GB
  Binaries:
    Node: 16.13.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.15 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.1.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (100.0.1185.36)
    Internet Explorer: 11.0.19041.1202
  npmPackages:
    next: 12.1.4 => 12.1.4
    next-auth: ^4.3.1 => 4.3.1
    react: 18.0.0 => 18.0.0

### Reproduction URL

https://github.com/ranjeetthorat/azureb2b

### Describe the issue

I am not able to fetch access and id token when using authcode flow with pkce . I get error 'JWT not valid now' 
I checked 
https://github.com/nextauthjs/next-auth/issues/3067   but clock tolerance of 10s  is not working for me . after making clock tolerance to 50s  i am getting id token and profile data.
here are changes i made  
**core\lib\oauth\client.js**
```
client[_openidClient.custom.clock_tolerance] = 10; // changed this to 50
```
My system  time is  correctly sync . I am at utc + 5.30.

Here is o/p i am getting in console in debug mode when clock tolerance is 10

```
event - compiled client and server successfully in 289 ms (169 modules)
[next-auth][debug][CREATE_PKCE_CHALLENGE_VERIFIER] {
  code_challenge: 'ZAgad6A_4E_9mizBfuCTkSdaPZjGYyJ4oihjlIHnE_Y',
  code_challenge_method: 'S256',
  code_verifier: 'A73fPZ-_atO5pFiW8OARXLf-a2z3uFocU2vdZEQdC28',
  PKCE_MAX_AGE: 900
}
[next-auth][debug][GET_AUTHORIZATION_URL] {
  url: 'https://mytenant.b2clogin.com/mytenant/b2c_1_susi/oauth2/v2.0/authorize?client_id=b8ba072d-6e7c-4d72-ad87-df82ac3cd426&scope=offline_access%20openid%20b8ba072d-6e7c-4d72-ad87-df82ac3cd426&response_type=code&redirect_uri=https%3A%2F%2Fmyredirect.uri-dev.com%2Fapi%2Fauth%2Fcallback%2Fazure-ad-b2c&code_challenge=ZAgad6A_4E_9mizBfuCTkSdaPZjGYyJ4oihjlIHnE_Y&code_challenge_method=S256',
  cookies: [
    {
      name: '__Secure-next-auth.pkce.code_verifier',
      value: 'eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..zhRZxdLoVJUgbt70.bn3HMmF4usVvAMJu93vZmpgeY-cK081A7Rkq9qkK50yJsxASD9sLenJXLntreeJni7hNj1g_-Ae9WjghIvDdaFJAhVH7Vi2-xgMioXBzBX1PDufqzA70KMDk3M-hY0sUqKWXyygUDApbp9Tb65lO5R8fz7QC-Z2fTohNhWCshsyfkc-_OND9iYRcrRINRA.ULyDwKnvKjoePptF_n9LDA',
      options: [Object]
    }
  ]
}
[next-auth][error][OAUTH_CALLBACK_ERROR] 
https://next-auth.js.org/errors#oauth_callback_error JWT not active yet, now 1649685704, nbf 1649685721 {
  error: {
    message: 'JWT not active yet, now 1649685704, nbf 1649685721',
    stack: 'RPError: JWT not active yet, now 1649685704, nbf 1649685721\n' +
      '    at Client.validateJWT (D:\\nextazure\\azureoauth\\node_modules\\openid-client\\lib\\client.js:947:15)\n' +
      '    at Client.validateIdToken (D:\\nextazure\\azureoauth\\node_modules\\openid-client\\lib\\client.js:765:60)\n' +
      '    at Client.callback (D:\\nextazure\\azureoauth\\node_modules\\openid-client\\lib\\client.js:486:18)\n' +
      '    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n' +
      '    at async oAuthCallback (D:\\nextazure\\azureoauth\\node_modules\\next-auth\\core\\lib\\oauth\\callback.js:112:16)\n' +   
      '    at async Object.callback (D:\\nextazure\\azureoauth\\node_modules\\next-auth\\core\\routes\\callback.js:50:11)\n' +      
      '    at async NextAuthHandler (D:\\nextazure\\azureoauth\\node_modules\\next-auth\\core\\index.js:139:28)\n' +
      '    at async NextAuthNextHandler (D:\\nextazure\\azureoauth\\node_modules\\next-auth\\next\\index.js:21:19)\n' +
      '    at async Object.apiResolver (D:\\nextazure\\azureoauth\\node_modules\\next\\dist\\server\\api-utils\\node.js:184:9)\n' + 
      '    at async DevServer.runApi (D:\\nextazure\\azureoauth\\node_modules\\next\\dist\\server\\next-server.js:395:9)',
    name: 'RPError'
  },
  providerId: 'azure-ad-b2c',
  message: 'JWT not active yet, now 1649685704, nbf 1649685721'
}
[next-auth][error][CALLBACK_OAUTH_ERROR] 
https://next-auth.js.org/errors#callback_oauth_error JWT not active yet, now 1649685704, nbf 1649685721 RPError: JWT not active yet, now 1649685704, nbf 1649685721
    at Client.validateJWT (D:\nextazure\azureoauth\node_modules\openid-client\lib\client.js:947:15)
    at Client.validateIdToken (D:\nextazure\azureoauth\node_modules\openid-client\lib\client.js:765:60)
    at Client.callback (D:\nextazure\azureoauth\node_modules\openid-client\lib\client.js:486:18)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async oAuthCallback (D:\nextazure\azureoauth\node_modules\next-auth\core\lib\oauth\callback.js:112:16)
    at async Object.callback (D:\nextazure\azureoauth\node_modules\next-auth\core\routes\callback.js:50:11)
    at async NextAuthHandler (D:\nextazure\azureoauth\node_modules\next-auth\core\index.js:139:28)
    at async NextAuthNextHandler (D:\nextazure\azureoauth\node_modules\next-auth\next\index.js:21:19)
    at async Object.apiResolver (D:\nextazure\azureoauth\node_modules\next\dist\server\api-utils\node.js:184:9)
    at async DevServer.runApi (D:\nextazure\azureoauth\node_modules\next\dist\server\next-server.js:395:9) {
  name: 'OAuthCallbackError',
  code: undefined
```

### How to reproduce

Register SPA in azure portal .  get client id .

### Expected behavior

It should work without clock tolerance  as current clock tolerance is unpredictable

**Comment by balazsorban44** [comment]
If 10s is not enough, there might be some clock syncing issues, and you should check that out.

https://github.com/nextauthjs/next-auth/issues/3032#issuecomment-955706008

I don't think we should be much more liberal with that setting. :thinking:
