### ISSUE TITLE
Access Token POST Request sent by openid-client has a Authorization BASIC header causing problems

### ISSUE THREAD

**Issue by ahmadawais** [nextauthjs/next-auth#4622]
### Environment

System:
    OS: macOS 12.3.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 17.00 GB / 64.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.1 - /usr/local/bin/node
    npm: 8.1.4 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 101.0.4951.64
    Safari: 15.4
  npmPackages:
    next: ^12.0.11-canary.4 => 12.1.6 
    next-auth: latest => 4.3.4 
    react: ^17.0.2 => 17.0.2 

### Reproduction URL

https://to.awais.dev/0JX1cK

### Describe the issue

I'm creating a custom provider for a WordPress based site. 

The provider looks like this:

```js
/** @type {import(".").OAuthProvider} */
const WP_URL = process.env.WORDLESS_WP_URL

export default function WP(options) {
  return {
    id: "WP",
    name: "WP",
    type: "oauth",
    authorization: `${WP_URL}/WP/oauth/authorize`,
    token: `${WP_URL}/wp-json/WP/oauth/token`,
    userinfo: {
      request: () => {},
    },
    profile(profile) {
      return {
        id: "1",
        name: "WP",
        email: "profile.email",
        image: "https://github.com/AhmadAwais.png",
      }
    },
    options,
  }
}

```

- ✅ Authorization code is generated successfully
- 🔴 But then I get an error `OAUTH_CALLBACK_ERROR` saying this `'expected 200 OK, got: 401 Unauthorized'` which is odd — and my access token function doesn't even run

![CleanShot 2022-05-26 at 15 08 44](https://user-images.githubusercontent.com/960133/170467394-e97138b4-477e-4b9f-8c25-8c10a137ad91.png)

```sh
[next-auth][error][OAUTH_CALLBACK_ERROR] 
https://next-auth.js.org/errors#oauth_callback_error expected 200 OK, got: 401 Unauthorized {
  error: {
    message: 'expected 200 OK, got: 401 Unauthorized',
    stack: 'OPError: expected 200 OK, got: 401 Unauthorized\n' +
      '    at processResponse (/Users/ahmadawais/Documents/Sandbox/wp-next-example/node_modules/openid-client/lib/helpers/process_response.js:41:11)\n' +
      '    at Client.grant (/Users/ahmadawais/Documents/Sandbox/wp-next-example/node_modules/openid-client/lib/client.js:1349:22)\n' +
      '    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n' +
      '    at async Client.oauthCallback (/Users/ahmadawais/Documents/Sandbox/wp-next-example/node_modules/openid-client/lib/client.js:612:24)\n' +
      '    at async oAuthCallback (/Users/ahmadawais/Documents/Sandbox/wp-next-example/node_modules/next-auth/core/lib/oauth/callback.js:114:16)\n' +
      '    at async Object.callback (/Users/ahmadawais/Documents/Sandbox/wp-next-example/node_modules/next-auth/core/routes/callback.js:50:11)\n' +
      '    at async NextAuthHandler (/Users/ahmadawais/Documents/Sandbox/wp-next-example/node_modules/next-auth/core/index.js:139:28)\n' +
      '    at async NextAuthNextHandler (/Users/ahmadawais/Documents/Sandbox/wp-next-example/node_modules/next-auth/next/index.js:21:19)\n' +
      '    at async /Users/ahmadawais/Documents/Sandbox/wp-next-example/node_modules/next-auth/next/index.js:57:32\n' +
      '    at async Object.apiResolver (/Users/ahmadawais/Documents/Sandbox/wp-next-example/node_modules/next/dist/server/api-utils/node.js:185:9)',
    name: 'OPError'
  },
  providerId: 'wp',
  message: 'expected 200 OK, got: 401 Unauthorized'
}
[next-auth][error][CALLBACK_OAUTH_ERROR] 
https://next-auth.js.org/errors#callback_oauth_error expected 200 OK, got: 401 Unauthorized OPError: expected 200 OK, got: 401 Unauthorized
    at processResponse (/Users/ahmadawais/Documents/Sandbox/wp-next-example/node_modules/openid-client/lib/helpers/process_response.js:41:11)
    at Client.grant (/Users/ahmadawais/Documents/Sandbox/wp-next-example/node_modules/openid-client/lib/client.js:1349:22)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Client.oauthCallback (/Users/ahmadawais/Documents/Sandbox/wp-next-example/node_modules/openid-client/lib/client.js:612:24)
    at async oAuthCallback (/Users/ahmadawais/Documents/Sandbox/wp-next-example/node_modules/next-auth/core/lib/oauth/callback.js:114:16)
    at async Object.callback (/Users/ahmadawais/Documents/Sandbox/wp-next-example/node_modules/next-auth/core/routes/callback.js:50:11)
    at async NextAuthHandler (/Users/ahmadawais/Documents/Sandbox/wp-next-example/node_modules/next-auth/core/index.js:139:28)
    at async NextAuthNextHandler (/Users/ahmadawais/Documents/Sandbox/wp-next-example/node_modules/next-auth/next/index.js:21:19)
    at async /Users/ahmadawais/Documents/Sandbox/wp-next-example/node_modules/next-auth/next/index.js:57:32
    at async Object.apiResolver (/Users/ahmadawais/Documents/Sandbox/wp-next-example/node_modules/next/dist/server/api-utils/node.js:185:9) {
  name: 'OAuthCallbackError',
  code: undefined
}
```

![CleanShot 2022-05-26 at 15 17 02](https://user-images.githubusercontent.com/960133/170468639-434da2f8-e2e3-400e-8f28-737b2e6a4529.png)

### How to reproduce

I dug deep and added a bunch of console logs in the `openid-client` node module and found out that the `POST` request it is sending to my WP site has the authorization `code` and everything (which btw works in an API client) — it has an unexpected `  'Authorization: Basic V09SRExFU1NfQ0xJRU5UX0lEOldPUkRMRVNTX0NMSUVOVF9TRUNSRVQ=\r\n' +` Auth header with `Basic` — which WordPress thinks of as `user:pass` and before even process the token endpoint — it says 401 unauthorized couldn't find a user like that. 

![CleanShot 2022-05-26 at 15 17 02](https://user-images.githubusercontent.com/960133/170468639-434da2f8-e2e3-400e-8f28-737b2e6a4529.png)

More reading on WP Basic auth: https://github.com/WP-API/Basic-Auth (now part of the core software of WP).

How can I make sure that `openid-client` will not send this unnecessary `  'Authorization: Basic XYZ' ` header? As that's what causing problems here and failing the sign-in.

### Expected behavior

If the `openid-client` doesn't send an `  'Authorization: Basic XYZ' ` header — everything will work as expected. 

This feels like a core issue that is not configurable through any config (I did read every inch of the docs here).

Please send help!

Happy to contribute a fix if you point me in the right direction.

Looking forward!

**Comment by ahmadawais** [comment]
This doesn't help to be honest. I did figure it out though. Appreciate this project a lot.

I had to improve and implement a patch on the WP side of things but I don't understand why `clientId` and `clientSecret` are required when that is unclear in the docs. 

Moreover, I checked every single provider, there's only one implementation where Twitter provider (I guess) uses the baked client. An example of using your own client and the API reference would be a lot better than the [options ts interface](https://next-auth.js.org/configuration/providers/oauth#options).

Lastly, the debugger provides half as much info — I had to open the `node-openid-client` add console logs to get more useful info on exactly what request is being sent by openid client to my links — to figure out what was wrong. 

I think improving docs, API reference, and debugger would go a long way to improve adoption of this amazing project.

I'll try to set aside some time to contribute as well.
