### ISSUE TITLE
Public client + authentication code flow with PKCE does not work in Azure AD B2C

### ISSUE THREAD

**Issue by hiko1ron** [nextauthjs/next-auth#4706]
### Question 💬

Hi, everyone!
Thank you for nice software.

When I try to authenticate with NextAuth.js + Azure AD B2C, it returns a callback error as an invalid request which said
`Public clients should not send a client_secret when redeeming a publicly acquired grant.`
I guess this problem is Authorization Header is given when the public client request to grant against token endpoint.
Is there any way around this?

`AADB2C90084: Public clients should not send a client_secret when redeeming a publicly acquired grant.`

```
frontend_1  | [next-auth][error][OAUTH_CALLBACK_ERROR]
frontend_1  | https://next-auth.js.org/errors#oauth_callback_error invalid_request (AADB2C90084: Public clients should not send a client_secret when redeeming a publicly acquired grant.
frontend_1  | Correlation ID: 75054f2b-52bf-486b-aa98-0eaba13f4621
frontend_1  | Timestamp: 2022-06-13 04:19:16Z
frontend_1  | ) {
frontend_1  |   error: {
frontend_1  |     message: 'invalid_request (AADB2C90084: Public clients should not send a client_secret when redeeming a publicly acquired grant.\r\n' +
frontend_1  |       'Correlation ID: 75054f2b-52bf-486b-aa98-0eaba13f4621\r\n' +
frontend_1  |       'Timestamp: 2022-06-13 04:19:16Z\r\n' +
frontend_1  |       ')',
frontend_1  |     stack: 'OPError: invalid_request (AADB2C90084: Public clients should not send a client_secret when redeeming a publicly acquired grant.\r\n' +
frontend_1  |       'Correlation ID: 75054f2b-52bf-486b-aa98-0eaba13f4621\r\n' +
frontend_1  |       'Timestamp: 2022-06-13 04:19:16Z\r\n' +
frontend_1  |       ')\n' +
frontend_1  |       '    at processResponse (/app/node_modules/openid-client/lib/helpers/process_response.js:38:13)\n' +
frontend_1  |       '    at Client.grant (/app/node_modules/openid-client/lib/client.js:1347:22)\n' +
frontend_1  |       '    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n' +
frontend_1  |       '    at async Client.callback (/app/node_modules/openid-client/lib/client.js:474:24)\n' +
frontend_1  |       '    at async oAuthCallback (/app/node_modules/next-auth/core/lib/oauth/callback.js:112:16)\n' +
frontend_1  |       '    at async Object.callback (/app/node_modules/next-auth/core/routes/callback.js:50:11)\n' +
frontend_1  |       '    at async NextAuthHandler (/app/node_modules/next-auth/core/index.js:139:28)\n' +
frontend_1  |       '    at async NextAuthNextHandler (/app/node_modules/next-auth/next/index.js:21:19)\n' +
frontend_1  |       '    at async /app/node_modules/next-auth/next/index.js:57:32\n' +
frontend_1  |       '    at async Object.apiResolver (/app/node_modules/next/dist/server/api-utils/node.js:185:9)',
frontend_1  |     name: 'OPError'
frontend_1  |   },
frontend_1  |   providerId: 'azure-ad-b2c',
frontend_1  |   message: 'invalid_request (AADB2C90084: Public clients should not send a client_secret when redeeming a publicly acquired grant.\r\n' +
frontend_1  |     'Correlation ID: 75054f2b-52bf-486b-aa98-0eaba13f4621\r\n' +
frontend_1  |     'Timestamp: 2022-06-13 04:19:16Z\r\n' +
frontend_1  |     ')'
frontend_1  | }
```

I tried to find out where this cause was, then I read code followed these error stacks.

- [next-auth] oAuthCallback [lib/oauth/callback.js](https://github.com/nextauthjs/next-auth/blob/49a8d51f79683edb6110a940764bc53e288e5294/packages/next-auth/src/core/lib/oauth/callback.ts#L112)
  - call callback of openid-client
- [openid-client] Client.callback [lib/client.js](https://github.com/panva/node-openid-client/blob/3f8dde8b891382d9adac586255c521f444b4bb81/lib/client.js#L474)
  - call grant
- [openid-client] Client.grant [lib/client.js](https://github.com/panva/node-openid-client/blob/3f8dde8b891382d9adac586255c521f444b4bb81/lib/client.js#L1312)
  - call authenticatedPost
- [openid-client] authenticatedPost [lib/helpers/client.js#L158](https://github.com/panva/node-openid-client/blob/3f8dde8b891382d9adac586255c521f444b4bb81/lib/helpers/client.js#L158)
  - call authFor
- [openid-client] authFor [lib/helpers/client.js#L163](https://github.com/panva/node-openid-client/blob/3f8dde8b891382d9adac586255c521f444b4bb81/lib/helpers/client.js#L163)
  - [openid-client] authFor [lib/helpers/client.js#L130](https://github.com/panva/node-openid-client/blob/3f8dde8b891382d9adac586255c521f444b4bb81/lib/helpers/client.js#L130)
    - -> this code returns authorization header.

So, I tried to assign ‘none’ for ‘token_endpoint_auth_method’ when client request to grant against token endpoint.
But, it couldn’t assign ‘none’ for  ‘token_endpoint_auth_method’ by NextAuth.js (and openid-client) and ‘client_secret_post’ was assigned forcibly if this method isn't included by 'token_endpoint_auth_methods_supported' which returned by well-known endpoint. code is [here](https://github.com/panva/node-openid-client/blob/3f8dde8b891382d9adac586255c521f444b4bb81/lib/client.js#L113).
I confirmed well-known endpoint of Azure AD B2C allows ‘client_secret_basic’ and  ‘client_secret_post’ only. ('none' is not included.)

By the way, It was processed successfully when I changed the code of ‘openid-client’ forcibly without Authentication Header.
It looks like an openid-client issue  (or composite issue) to me but I don't know it is correct because I am not an expertise of this issue.
Please let me know if I am using something incorrectly or misunderstanding something.

### How to reproduce ☕️

This occurs during callback after successful sign-in on the Azure AD B2C.

**Libraries**

* node 16.15.1
* next 12.1.6
* next-auth 4.3.4

**Azure AD B2C Settings**

* Allow public client flows: `Yes`
* Platform configurations: `Single-page application`
* Redirect URI: `http://localhost:3000/api/auth/callback/azure-ad-b2c`

**src/pages/index.tsx**

```
import { useSession, signIn, signOut } from "next-auth/react";

export default function Index() {
  const { data: session } = useSession();
  if(session) {
    return <>
      Signed in as {session.user.email} <br/>
      <button onClick={() => signOut()}>sign out</button>
    </>;
  }
  return <>
    Not signed in <br/>
    <button onClick={() => signIn()}>sign in</button>
  </>;
};
```

**src/pages/api/auth/[...nextauth].ts**
```
import AzureADB2CProvider from "next-auth/providers/azure-ad-b2c";

export default NextAuth({
  providers: [
...
    AzureADB2CProvider({
      tenantId: process.env.AZURE_AD_B2C_TENANT_NAME,
      clientId: process.env.AZURE_AD_B2C_CLIENT_ID,
      clientSecret: process.env.AZURE_AD_B2C_CLIENT_SECRET,
      primaryUserFlow: process.env.AZURE_AD_B2C_PRIMARY_USER_FLOW,
      authorization: { params: { scope: "offline_access openid" },  },
      checks: ["pkce"]
    }),
...
  ],
};
```

**next.config.js**
```
const nextConfig = {
  reactStrictMode: true,
  env: {
    AZURE_AD_B2C_TENANT_NAME: process.env.AZURE_AD_B2C_TENANT_NAME,
    AZURE_AD_B2C_CLIENT_ID: process.env.AZURE_AD_B2C_CLIENT_ID,
    AZURE_AD_B2C_CLIENT_SECRET: process.env.AZURE_AD_B2C_CLIENT_SECRET,
    AZURE_AD_B2C_PRIMARY_USER_FLOW: process.env.AZURE_AD_B2C_PRIMARY_USER_FLOW,
  }
};
module.exports = nextConfig;
```

** .env.local
* set  appropriate environment variables

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
`openid-client` configuration options are exposed to you, if you need to change the defaults. See: https://next-auth.js.org/configuration/providers/oauth#client-option

**Comment by jvtroyen** [comment]
I have the exact same problem. 
Even though we can apparently change it, it says "An advanced option, hopefully you won't need it in most cases."

Can you give us something more specific, as I don't immediately see how to proceed here?

**Comment by hiko1ron** [comment]
@balazsorban44 
Thank you for your answer.  🙇‍♂️ 
I changed the parameters based on the link you provided and it works! 🚀 

@jvtroyen 
Thanks. It worked with exactly the same parameters you described. 😄

**Comment by dotZak** [comment]
I followed the advice here but I'm still getting a ton of debug errors. I'm assuming that this is a config thing on the Azure side, but if someone who knows what's happening could enlighten me I would appreciate it.

The error at the bottom reads `https://next-auth.js.org/errors#oauth_parse_profile_error Cannot read properties of undefined (reading '0')` which makes me think that I'm not getting a `profile` back?

```[next-auth][debug][CREATE_PKCE_CHALLENGE_VERIFIER] {
  code_challenge: 'xxxxxx_xxxxxxx_xxxxxxx',
  code_challenge_method: 'S256',
  code_verifier: 'xxxxxx_xxxxxxx_xxxxxxx',
  PKCE_MAX_AGE: 900
}
[next-auth][debug][GET_AUTHORIZATION_URL] {
  url: 'https://xxx.b2clogin.com/xxx.onmicrosoft.com/b2c_1_signupsignin/oauth2/v2.0/authorize?client_id=xxxxxx-xxx-xxx-xxxxx&scope=https%3A%2F%2Fxxx.onmicrosoft.com%2Fxxx%2Fweb.read%20https%3A%2F%2Fxxx.onmicrosoft.com%2Fxxx%2Fweb.write%20offline_access%20openid&response_type=code&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Fapi%2Fauth%2Fcallback%2Fazure-ad-b2c&code_challenge=xxxxxx_xxxxxxx_xxxxxxx&code_challenge_method=S256',
  cookies: [
    {
      name: 'next-auth.pkce.code_verifier',
      value: 'xxxxxxxx..xxxxxxxx.xx',
      options: [Object]
    }
  ],
  provider: {
    id: 'azure-ad-b2c',
    name: 'Azure Active Directory B2C',
    type: 'oauth',
    wellKnown: 'https://xxx.b2clogin.com/xxx.onmicrosoft.com/B2C_1_SignUpSignIn/v2.0/.well-known/openid-configuration',
    idToken: true,
    profile: [Function: profile],
    checks: [ 'pkce' ],
    authorization: { params: [Object] },
    client: { token_endpoint_auth_method: 'none' },
    clientId: 'xxxxxx-xxx-xxx-xxxxx',
    clientSecret: 'xxxx~xxxxxxxxxxx',
    primaryUserFlow: 'B2C_1_SignUpSignIn',
    tenantId: 'xxx',
    signinUrl: 'http://localhost:3000/api/auth/signin/azure-ad-b2c',
    callbackUrl: 'http://localhost:3000/api/auth/callback/azure-ad-b2c'
  }
}
[next-auth][debug][CREATE_PKCE_CHALLENGE_VERIFIER] {
  code_challenge: 'DLug8FwFk3hD_gdT7V3aSgrsQ0PrjYIfKO57x8y3N1Y',
  code_challenge_method: 'S256',
  code_verifier: 'ONaJ82zWkSwiApcMmi9CtiLkpm1V7VWPxglBHE_G0TQ',
  PKCE_MAX_AGE: 900
}
[next-auth][debug][GET_AUTHORIZATION_URL] {
  url: 'https://xxx.b2clogin.com/xxx.onmicrosoft.com/b2c_1_signupsignin/oauth2/v2.0/authorize?client_id=xxxxxx-xxx-xxx-xxxxx&scope=https%3A%2F%2Fxxx.onmicrosoft.com%2Fxxx%2Fweb.read%20https%3A%2F%2Fxxx.onmicrosoft.com%2Fxxx%2Fweb.write%20offline_access%20openid&response_type=code&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Fapi%2Fauth%2Fcallback%2Fazure-ad-b2c&code_challenge=DLug8FwFk3hD_gdT7V3aSgrsQ0PrjYIfKO57x8y3N1Y&code_challenge_method=S256',
  cookies: [
    {
      name: 'next-auth.pkce.code_verifier',
      value: 'xxxxxxxx..xxxxxxxx.xx',
      options: [Object]
    }
  ],
  provider: {
    id: 'azure-ad-b2c',
    name: 'Azure Active Directory B2C',
    type: 'oauth',
    wellKnown: 'https://xxx.b2clogin.com/xxx.onmicrosoft.com/B2C_1_SignUpSignIn/v2.0/.well-known/openid-configuration',
    idToken: true,
    profile: [Function: profile],
    checks: [ 'pkce' ],
    authorization: { params: [Object] },
    client: { token_endpoint_auth_method: 'none' },
    clientId: 'xxxxxx-xxx-xxx-xxxxx',
    clientSecret: 'xxxx~xxxxxxxxxxx',
    primaryUserFlow: 'B2C_1_SignUpSignIn',
    tenantId: 'xxx',
    signinUrl: 'http://localhost:3000/api/auth/signin/azure-ad-b2c',
    callbackUrl: 'http://localhost:3000/api/auth/callback/azure-ad-b2c'
  }
}
[next-auth][debug][PROFILE_DATA] {
  OAuthProfile: {
    exp: xxxxxxxxxx,
    nbf: xxxxxxxxxx,
    ver: '1.0',
    iss: 'https://xxx.b2clogin.com/xxx-xxx-xx-x-xxx/v2.0/',
    sub: 'xxxxxx-xxx-xxx-xxxxx',
    aud: 'xxxxxx-xxx-xxx-xxxxx',
    iat: xxxxxxxxxx,
    auth_time: xxxxxxxxxx,
    oid: 'xxxxxx-xxx-xxx-xxxxx',
    city: 'xxx',
    country: 'xxx',
    given_name: 'xxx',
    family_name: 'xxx',
    tfp: 'B2C_1_SignUpSignIn'
  }
}
[next-auth][error][OAUTH_PARSE_PROFILE_ERROR]
https://next-auth.js.org/errors#oauth_parse_profile_error Cannot read properties of undefined (reading '0') {
  error: {
    message: "Cannot read properties of undefined (reading '0')",
    stack: "TypeError: Cannot read properties of undefined (reading '0')\n" +
      '    at Object.profile (/Users/user/Sites/next-app/node_modules/next-auth/providers/azure-ad-b2c.js:27:30)\n' +
      '    at getProfile (/Users/user/Sites/next-app/node_modules/next-auth/core/lib/oauth/callback.js:180:36)\n' +
      '    at oAuthCallback (/Users/user/Sites/next-app/node_modules/next-auth/core/lib/oauth/callback.js:154:33)\n' +
      '    at async Object.callback (/Users/user/Sites/next-app/node_modules/next-auth/core/routes/callback.js:52:11)\n' +
      '    at async NextAuthHandler (/Users/user/Sites/next-app/node_modules/next-auth/core/index.js:201:28)\n' +
      '    at async NextAuthNextHandler (/Users/user/Sites/next-app/node_modules/next-auth/next/index.js:23:19)\n' +
      '    at async /Users/user/Sites/next-app/node_modules/next-auth/next/index.js:59:32\n' +
      '    at async Object.apiResolver (/Users/user/Sites/next-app/node_modules/next/dist/server/api-utils/node.js:366:9)\n' +
      '    at async DevServer.runApi (/Users/user/Sites/next-app/node_modules/next/dist/server/next-server.js:481:9)\n' +
      '    at async Object.fn (/Users/user/Sites/next-app/node_modules/next/dist/server/next-server.js:735:37)',
    name: 'TypeError'
  },
  OAuthProfile: {
    exp: xxxxxxxxxx,
    nbf: xxxxxxxxxx,
    ver: '1.0',
    iss: 'https://xxx.b2clogin.com/xxx-xxx-xx-x-xxx/v2.0/',
    sub: 'xxxxxx-xxx-xxx-xxxxx',
    aud: 'xxxxxx-xxx-xxx-xxxxx',
    iat: xxxxxxxxxx,
    auth_time: xxxxxxxxxx,
    oid: 'xxxxxx-xxx-xxx-xxxxx',
    city: 'xxx',
    country: 'xxxx',
    given_name: 'xxx',
    family_name: 'xxx',
    tfp: 'B2C_1_SignUpSignIn'
  },
  message: "Cannot read properties of undefined (reading '0')"
}
[next-auth][debug][OAUTH_CALLBACK_RESPONSE] { profile: undefined, account: undefined, OAuthProfile: undefined }```
