### ISSUE TITLE
Firebase adapter - Error on getSession inside API routes (Discord authentication)

### ISSUE THREAD

**Issue by hawkyre** [nextauthjs/next-auth#4723]
### Adapter type

@next-auth/firebase-adapter

### Environment

 System:
    OS: Windows 10 10.0.22000
    CPU: (16) x64 AMD Ryzen 9 5900HX with Radeon Graphics
    Memory: 12.92 GB / 31.42 GB
  Binaries:
    Node: 16.13.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.1.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (98.0.1108.62)
    Internet Explorer: 11.0.22000.120
npmPackages:
    next: ^12.0.10 => 12.1.6
    next-auth: 3.29.0 => 3.29.0
    react: ^17.0.2 => 17.0.2
npmPackages:
    @next-auth/firebase-adapter: ^0.1.2 => 0.1.3

### Reproduction URL

N/A

### Describe the issue

When accessing getSession in the server, sometimes it will throw an error. This has only happened in the server, never on development. This is Vercel's output:

```
"2022-06-17T19":"27":12.979Z	174e7a75-7c43-4f6a-bab4-503493732187	ERROR	Unhandled Promise Rejection{
   "errorType":"Runtime.UnhandledPromiseRejection",
   "errorMessage":"Error: 4 DEADLINE_EXCEEDED: Deadline exceeded",
   "reason":{
      "errorType":"Error",
      "errorMessage":"4 DEADLINE_EXCEEDED: Deadline exceeded",
      "code":4,
      "details":"Deadline exceeded",
      "metadata":{
         
      },
      "note":"Exception occurred in retry method that was not classified as transient",
      "stack":[
         "Error: 4 DEADLINE_EXCEEDED: Deadline exceeded",
         "    at Object.callErrorFromStatus (/var/task/node_modules/@grpc/grpc-js/build/src/call.js:31:26)",
         "    at Object.onReceiveStatus (/var/task/node_modules/@grpc/grpc-js/build/src/client.js:189:52)",
         "    at Object.onReceiveStatus (/var/task/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:365:141)",
         "    at Object.onReceiveStatus (/var/task/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:328:181)",
         "    at /var/task/node_modules/@grpc/grpc-js/build/src/call-stream.js:187:78",
         "    at processTicksAndRejections (internal/process/task_queues.js:77:11)",
         "Caused by: Error",
         "    at WriteBatch.commit (/var/task/node_modules/@google-cloud/firestore/build/src/write-batch.js:417:23)",
         "    at DocumentReference.set (/var/task/node_modules/@google-cloud/firestore/build/src/reference.js:355:14)",
         "    at Object.session (/var/task/.next/server/chunks/764.js:213:24)",
         "    at processTicksAndRejections (internal/process/task_queues.js:95:5)",
         "    at async Object.session (/var/task/node_modules/next-auth/dist/server/routes/session.js:56:30)"
      ]
   },
   "promise":{
      
   },
   "stack":[
      "Runtime.UnhandledPromiseRejection: Error: 4 DEADLINE_EXCEEDED: Deadline exceeded",
      "    at process.<anonymous> (/var/runtime/index.js:35:15)",
      "    at process.emit (events.js:412:35)",
      "    at processPromiseRejections (internal/process/promises.js:245:33)",
      "    at processTicksAndRejections (internal/process/task_queues.js:96:32)"
   ]
}
```

It hints to line 56 of `next-auth/dist/server/routes/session.js`. The content of that zone is the following (Line 56 is marked with `>`):

```
      const sessionExpiresDate = new Date();
      sessionExpiresDate.setTime(sessionExpiresDate.getTime() + sessionMaxAge * 1000);
      const sessionExpires = sessionExpiresDate.toISOString();
      const defaultSessionPayload = {
        user: {
          name: decodedJwt.name || null,
          email: decodedJwt.email || null,
          image: decodedJwt.picture || null
        },
        expires: sessionExpires
      };
      const jwtPayload = await callbacks.jwt(decodedJwt);
>     const sessionPayload = await callbacks.session(defaultSessionPayload, jwtPayload);
      response = sessionPayload;
      const newEncodedJwt = await jwt.encode({ ...jwt,
        token: jwtPayload
      });
      cookie.set(res, cookies.sessionToken.name, newEncodedJwt, {
        expires: sessionExpires,
        ...cookies.sessionToken.options
      });
      await (0, _dispatchEvent.default)(events.session, {
        session: sessionPayload,
        jwt: jwtPayload
      });
```

Before anyone tells me I'm using v3, I have to because the firebase adapter isn't ready for v4 yet.
I believe it may be associated to next-auth thinking the authentication is outdated and needs to refresh it, but I have zero idea and it's annoying.

### How to reproduce

use discord provider with jwt and firebase adapter

### Expected behavior

Not throw an error and fetch session properly.

**Comment by DevCleverton** [comment]
## try this
 ☕️ Reasoning
https://github.com/leerob/nextjs-vercel-firebase

https://www.npmjs.com/package/@next-auth/firebase-adapter

## 🧢 Checklist

- [x] Documentation
- [ ] Tests
- [ ] Ready to be merged
Firebase Hosting, but I don't believe there's a Next.js adapter for ISR and their hosting platform. They would need to add that (or something open source) so that the Firebase CDN understands how to purge their cache.

I'm biased, but give Vercel a shot. Works out of the box.

https://vercel.com/import

## 🎫 Affected issues

Please [scout and link issues](https://github.com/nextauthjs/next-auth/issues) that might be solved by this PR.

Fixes: INSERT_ISSUE_LINK_HERE

## 📌 Resources

- [Contributing guidelines](./CONTRIBUTING.md)
- [Code of conduct](./CODE_OF_CONDUCT.md)
- [Contributing to Open Source](https://kcd.im/pull-request)
