### ISSUE TITLE
unexpected iss value, expected undefined, got: https://www.facebook.com

### ISSUE THREAD

**Issue by MohamedBenhnouk** [nextauthjs/next-auth#4740]
### Question 💬

I'm struggling with this issue so long now, does anyone have any idea what the probleme is . this my configuration : 

```
    FacebookProvider({
      clientId: process.env.FACEBOOK_CLIENT_ID,
      clientSecret: process.env.FACEBOOK_CLIENT_SECRET,
      idToken: true,
      scopes: ["email"],
      profileFields: ["id", "name", "email", "picture"],

    },
```

and this is the error i got : 

```
[next-auth][error][OAUTH_CALLBACK_ERROR]
https://next-auth.js.org/errors#oauth_callback_error unexpected iss value, expected undefined, got: https://www.facebook.com {
  error: {
    message: 'unexpected iss value, expected undefined, got: https://www.facebook.com',
    stack: 'RPError: unexpected iss value, expected undefined, got: https://www.facebook.com\n' +
      '    at Client.validateJWT (C:\\Users\\Dell\\desktop\\dev\\kinshi_next_web3.0\\node_modules\\openid-client\\lib\\client.js:921:15)\n' +
      '    at Client.validateIdToken (C:\\Users\\Dell\\desktop\\dev\\kinshi_next_web3.0\\node_modules\\openid-client\\lib\\client.js:763:60)\n' +
      '    at Client.callback (C:\\Users\\Dell\\desktop\\dev\\kinshi_next_web3.0\\node_modules\\openid-client\\lib\\client.js:484:18)\n' +
      '    at runMicrotasks (<anonymous>)\n' +
      '    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n' +
      '    at async oAuthCallback (C:\\Users\\Dell\\desktop\\dev\\kinshi_next_web3.0\\node_modules\\next-auth\\core\\lib\\oauth\\callback.js:112:16)\n' +
      '    at async Object.callback (C:\\Users\\Dell\\desktop\\dev\\kinshi_next_web3.0\\node_modules\\next-auth\\core\\routes\\callback.js:50:11)\n' +
      '    at async NextAuthHandler (C:\\Users\\Dell\\desktop\\dev\\kinshi_next_web3.0\\node_modules\\next-auth\\core\\index.js:139:28)\n' +
      '    at async NextAuthNextHandler (C:\\Users\\Dell\\desktop\\dev\\kinshi_next_web3.0\\node_modules\\next-auth\\next\\index.js:21:19)\n' +
      '    at async C:\\Users\\Dell\\desktop\\dev\\kinshi_next_web3.0\\node_modules\\next-auth\\next\\index.js:57:32',
    name: 'RPError'
  },
  providerId: 'facebook',
  message: 'unexpected iss value, expected undefined, got: https://www.facebook.com'
}
[next-auth][error][CALLBACK_OAUTH_ERROR]
https://next-auth.js.org/errors#callback_oauth_error unexpected iss value, expected undefined, got: https://www.facebook.com RPError: unexpected iss value, expected undefined, got: https://www.facebook.com
    at Client.validateJWT (C:\Users\Dell\desktop\dev\kinshi_next_web3.0\node_modules\openid-client\lib\client.js:921:15)
    at Client.validateIdToken (C:\Users\Dell\desktop\dev\kinshi_next_web3.0\node_modules\openid-client\lib\client.js:763:60)
    at Client.callback (C:\Users\Dell\desktop\dev\kinshi_next_web3.0\node_modules\openid-client\lib\client.js:484:18)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async oAuthCallback (C:\Users\Dell\desktop\dev\kinshi_next_web3.0\node_modules\next-auth\core\lib\oauth\callback.js:112:16)
    at async Object.callback (C:\Users\Dell\desktop\dev\kinshi_next_web3.0\node_modules\next-auth\core\routes\callback.js:50:11)
    at async NextAuthHandler (C:\Users\Dell\desktop\dev\kinshi_next_web3.0\node_modules\next-auth\core\index.js:139:28)
    at async NextAuthNextHandler (C:\Users\Dell\desktop\dev\kinshi_next_web3.0\node_modules\next-auth\next\index.js:21:19)
    at async C:\Users\Dell\desktop\dev\kinshi_next_web3.0\node_modules\next-auth\next\index.js:57:32 {
  name: 'OAuthCallbackError',
  code: undefined
}

```

### How to reproduce ☕️

    FacebookProvider({
      clientId: process.env.FACEBOOK_CLIENT_ID,
      clientSecret: process.env.FACEBOOK_CLIENT_SECRET,
      idToken: true,
      scopes: ["email"],
      profileFields: ["id", "name", "email", "picture"],

    },

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by MohamedBenhnouk** [comment]
i fixed it by adding the usser to the provider 👍 

FacebookProvider({
  clientId: process.env.FACEBOOK_CLIENT_ID,
  clientSecret: process.env.FACEBOOK_CLIENT_SECRET,
  idToken: true,
  scopes: ["email"],
  profileFields: ["id", "name", "email", "picture"],
  issuer: 'https://www.facebook.com',
},
