### ISSUE TITLE
WorkOS: error on login with any provider supported by workos both google and organizations

### ISSUE THREAD

**Issue by riccardogiorato** [nextauthjs/next-auth#4749]
### Provider type

WorkOS

### Environment

-   npmPackages:
- next: 12.0.9 => 12.0.9 
- next-auth: ^4.1.2 => 4.5.0 
- react: 17.0.2 => 17.0.2 

### Reproduction URL

https://next-auth-workos-demo.vercel.app/login

### Describe the issue

```2022-06-22T13:12:24.291Z	86a74e6d-f0d7-400d-b26f-ceafc213173f	ERROR	[next-auth][error][OAUTH_CALLBACK_ERROR] 
https://next-auth.js.org/errors#oauth_callback_error expected 200 OK, got: 201 Created {
  error: {
    message: 'expected 200 OK, got: 201 Created',
    stack: 'OPError: expected 200 OK, got: 201 Created\n' +
      '    at processResponse (/var/task/node_modules/openid-client/lib/helpers/process_response.js:41:11)\n' +
      '    at Client.grant (/var/task/node_modules/openid-client/lib/client.js:1347:22)\n' +
      '    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n' +
      '    at async Client.oauthCallback (/var/task/node_modules/openid-client/lib/client.js:612:24)\n' +
      '    at async oAuthCallback (/var/task/node_modules/next-auth/core/lib/oauth/callback.js:114:16)\n' +
      '    at async Object.callback (/var/task/node_modules/next-auth/core/routes/callback.js:50:11)\n' +
      '    at async NextAuthHandler (/var/task/node_modules/next-auth/core/index.js:139:28)\n' +
      '    at async NextAuthNextHandler (/var/task/node_modules/next-auth/next/index.js:21:19)\n' +
      '    at async /var/task/node_modules/next-auth/next/index.js:57:32\n' +
      '    at async Object.apiResolver (/var/task/node_modules/next/dist/server/api-utils.js:101:9)',
    name: 'OPError'
  },
  providerId: 'workos',
  message: 'expected 200 OK, got: 201 Created'
}
2022-06-22T13:12:24.292Z	86a74e6d-f0d7-400d-b26f-ceafc213173f	ERROR	[next-auth][error][CALLBACK_OAUTH_ERROR] 
https://next-auth.js.org/errors#callback_oauth_error expected 200 OK, got: 201 Created OPError: expected 200 OK, got: 201 Created
    at processResponse (/var/task/node_modules/openid-client/lib/helpers/process_response.js:41:11)
    at Client.grant (/var/task/node_modules/openid-client/lib/client.js:1347:22)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Client.oauthCallback (/var/task/node_modules/openid-client/lib/client.js:612:24)
    at async oAuthCallback (/var/task/node_modules/next-auth/core/lib/oauth/callback.js:114:16)
    at async Object.callback (/var/task/node_modules/next-auth/core/routes/callback.js:50:11)
    at async NextAuthHandler (/var/task/node_modules/next-auth/core/index.js:139:28)
    at async NextAuthNextHandler (/var/task/node_modules/next-auth/next/index.js:21:19)
    at async /var/task/node_modules/next-auth/next/index.js:57:32
    at async Object.apiResolver (/var/task/node_modules/next/dist/server/api-utils.js:101:9) {
  name: 'OAuthCallbackError',
  code: undefined
}```

### How to reproduce

I recreated this issue in a clean workos project: https://github.com/riccardogiorato/next-auth-workos-demo

### Expected behavior

Being able to have a successful login without getting OAuth errors when using Google or an Organization.

**Comment by riccardogiorato** [comment]
I have create a public repo where this issue can be reproduced: https://github.com/riccardogiorato/next-auth-workos-demo

**Comment by balazsorban44** [comment]
Correct, according to the OAuth spec, the particular response should be 200, not 201:

https://datatracker.ietf.org/doc/html/rfc6749#section-5.1

So this is not an issue with NextAuth.js.

cc @m-abdelwahab, this should probably be the default behavior in WorkOS to conform with the spec. :+1:
