### ISSUE TITLE
Window not defined while using production build

### ISSUE THREAD

**Issue by gaurishhs** [nextauthjs/next-auth#4854]
### Question 💬

Hello! I was deploying next-auth app to production. (It worked perfectly in development) and it seems as if it doesn't work!

Please help. 

```/vercel/path0/node_modules/next-auth/react/index.js:220
--
20:40:33.916 | _ref5 = options !== null && options !== void 0 ? options : {}, _ref5$callbackUrl = _ref5.callbackUrl, callbackUrl = _ref5$callbackUrl === void 0 ? window.location.href : _ref5$callbackUrl, _ref5$redirect = _ref5.redirect, redirect = _ref5$redirect === void 0 ? true : _ref5$redirect;
20:40:33.917 | ^
20:40:33.917 |  
20:40:33.917 | ReferenceError: window is not defined
20:40:33.917 | at _callee5$ (/vercel/path0/node_modules/next-auth/react/index.js:220:160)
20:40:33.917 | at tryCatch (/vercel/path0/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:86:17)
20:40:33.917 | at Generator._invoke (/vercel/path0/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:66:24)
20:40:33.917 | at Generator.next (/vercel/path0/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:117:21)
20:40:33.917 | at asyncGeneratorStep (/vercel/path0/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
20:40:33.917 | at _next (/vercel/path0/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
20:40:33.918 | at /vercel/path0/node_modules/@babel/runtime/helpers/asyncToGenerator.js:32:7
20:40:33.918 | at new Promise (<anonymous>)
20:40:33.918 | at /vercel/path0/node_modules/@babel/runtime/helpers/asyncToGenerator.js:21:12
20:40:33.918 | at _signIn (/vercel/path0/node_modules/next-auth/react/index.js:329:18)```



### How to reproduce ☕️

no idea if this can be 

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
This is the issue. This is a client-side method but accidentally was imported on the server https://github.com/gaurishhs/Groot-Dashboard/blob/d164f6dd3d1da744cfc4d1200d4ba7b7b0b2613b/pages/api/auth/%5B...nextauth%5D.ts#L4

**Comment by gaurishhs** [comment]
@balazsorban44 after i removed that method it worked yet i noticed i still get such an error but only in callback. i checked all my callbacks but they don't use window

```
export default NextAuth({
    providers: [
        DiscordProvider({
            clientId: process.env.CLIENT_ID as any,
            clientSecret: process.env.CLIENT_SECRET as any,
            authorization: { params: { scope: 'identify guilds' } },
        })
    ],
    callbacks: {
        async jwt({ token, user, account }: any) {
            if (account && user) {
                return {
                    accessToken: account.access_token,
                    accessTokenExpires: Date.now() + account.expires_at * 1000,
                    refreshToken: account.refresh_token,
                    user,
                }
            }

            if (Date.now() < token.accessTokenExpires) {
                return token
            }

            return refreshAccessToken(token)
        },
        async session({ session, token }: any) {
            session.user = token.user
            session.accessToken = token.accessToken
            session.error = token.error

            return session
        },
        async redirect() {
            return "/"
        }
    },
})
```

What could be the issue now?
