### ISSUE TITLE
ikm must be an instance of Uint8Array or a string

### ISSUE THREAD

**Issue by maticrivo** [nextauthjs/next-auth#4936]
### Question 💬

I'm trying to create social logins with facebook and when i press the social login button in the `/api/auth/signin` page i get the following error:
```
[next-auth][error][GET_AUTHORIZATION_URL_ERROR]
https://next-auth.js.org/errors#get_authorization_url_error "ikm"" must be an instance of Uint8Array or a string {
  message: '"ikm"" must be an instance of Uint8Array or a string',
  stack: 'TypeError: "ikm"" must be an instance of Uint8Array or a string\n' +
    '    at normalizeUint8Array (/.../node_modules/@panva/hkdf/dist/node/cjs/index.js:20:15)\n' +
    '    at normalizeIkm (/.../node_modules/@panva/hkdf/dist/node/cjs/index.js:24:17)\n' +
    '    at hkdf (/.../node_modules/@panva/hkdf/dist/node/cjs/index.js:47:60)\n' +
    '    at getDerivedEncryptionKey (/.../node_modules/next-auth/jwt/index.js:114:34)\n' +
    '    at Object.encode (/.../node_modules/next-auth/jwt/index.js:48:34)\n' +
    '    at createState (/.../node_modules/next-auth/core/lib/oauth/state-handler.js:29:34)\n' +
    '    at getAuthorizationUrl (/.../node_modules/next-auth/core/lib/oauth/authorization-url.js:70:55)\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n' +
    '    at async Object.signin (/.../node_modules/next-auth/core/routes/signin.js:37:24)\n' +
    '    at async NextAuthHandler (/.../node_modules/next-auth/core/index.js:230:26)',
  name: 'TypeError'
}
[next-auth][error][SIGNIN_OAUTH_ERROR]
https://next-auth.js.org/errors#signin_oauth_error "ikm"" must be an instance of Uint8Array or a string {
  error: {
    message: '"ikm"" must be an instance of Uint8Array or a string',
    stack: 'TypeError: "ikm"" must be an instance of Uint8Array or a string\n' +
      '    at normalizeUint8Array (/.../node_modules/@panva/hkdf/dist/node/cjs/index.js:20:15)\n' +
      '    at normalizeIkm (/.../node_modules/@panva/hkdf/dist/node/cjs/index.js:24:17)\n' +
      '    at hkdf (/.../node_modules/@panva/hkdf/dist/node/cjs/index.js:47:60)\n' +
      '    at getDerivedEncryptionKey (/.../node_modules/next-auth/jwt/index.js:114:34)\n' +
      '    at Object.encode (/.../node_modules/next-auth/jwt/index.js:48:34)\n' +
      '    at createState (/.../node_modules/next-auth/core/lib/oauth/state-handler.js:29:34)\n' +
      '    at getAuthorizationUrl (/.../node_modules/next-auth/core/lib/oauth/authorization-url.js:70:55)\n' +
      '    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n' +
      '    at async Object.signin (/.../node_modules/next-auth/core/routes/signin.js:37:24)\n' +
      '    at async NextAuthHandler (/.../node_modules/next-auth/core/index.js:230:26)',
    name: 'TypeError'
  },
  provider: {
    id: 'facebook',
    name: 'Facebook',
    type: 'oauth',
    authorization: {
      url: 'https://www.facebook.com/v11.0/dialog/oauth',
      params: [Object]
    },
    token: {
      url: 'https://graph.facebook.com/oauth/access_token',
      params: {}
    },
    userinfo: {
      url: 'https://graph.facebook.com/me',
      params: [Object],
      request: [AsyncFunction: request]
    },
    profile: [Function: profile],
    idToken: false,
    checks: [ 'state' ],
    clientId: 'XXX',
    clientSecret: 'XXX',
    signinUrl: 'http://localhost:3000/api/auth/signin/facebook',
    callbackUrl: 'http://localhost:3000/api/auth/callback/facebook'
  },
  message: '"ikm"" must be an instance of Uint8Array or a string'
}
```

can someone help me figure out if it's a wrong configuration or something?

I'm running node v16.16.0 if it helps..

Thanks.

### How to reproduce ☕️

this is the `[...nextauth].js` file:
```
export default NextAuth({
    adapter: PrismaAdapter(prisma),
    
    providers: [
      FacebookProvider({
        clientId: process.env.FACEBOOK_ID,
        clientSecret: process.env.FACEBOOK_SECRET,
      }),
    ],
  
    secret: process.env.NEXTAUTH_SECRET,
  
    jwt: {
      secret: process.env.SECRET,
    },
    debug: true,
  });
```

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
You did not set `SECRET` in your env file. It is required. We recommend setting `NEXTAUTH_SECRET`, so you don't have to remember passing it anywhere!

See: https://next-auth.js.org/configuration/options#nextauth_secret

**Comment by maticrivo** [comment]
Hi @balazsorban44 .
I do have the `NEXTAUTH_SECRET` set in my env file..
```
NODE_ENV=development

NEXTAUTH_URL=http://localhost:3000
NEXTAUTH_SECRET=XXX

FACEBOOK_ID=XXX
FACEBOOK_SECRET=XXX

DATABASE_URL=mysql://XXX
```

**Comment by maticrivo** [comment]
if i rename `NEXTAUTH_SECRET` to `SECRET` it works.
the question is if i should have both? or is just having `SECRET` good enough?
