### ISSUE TITLE
CannotDetermineEntityError on existing user update [next-auth][debug][typeorm_update_user]

### ISSUE THREAD

**Issue by ttoni** [nextauthjs/next-auth#495]
**Describe the bug**
I´ve updated to 3.0.0. 
Initial email signin is working. 
When I try to sign in via email a second time, the following error is thrown: 

`[next-auth][debug][typeorm_get_verification_request] [
  'a@b.com',
  '1648ba296b67009505780136322ad257442a8c9566a6b8d5a5b0168c45cc6787'
]
[next-auth][debug][typeorm_delete_verification] [
  'a@b.com',
  '1648ba296b67009505780136322ad257442a8c9566a6b8d5a5b0168c45cc6787'
]
[next-auth][debug][typeorm_get_user_by_email] a@b.com
[next-auth][debug][typeorm_get_user_by_email] a@b.com
[next-auth][debug][typeorm_update_user] {
  id: 1,
  name: null,
  email: a@b.com',
  emailVerified: 2020-07-28T09:27:10.257Z,
  image: null,
  createdAt: 2020-07-28T09:26:29.179Z,
  updatedAt: 2020-07-28T09:26:29.179Z
}
[next-auth][error][callback_email_error] CannotDetermineEntityError: Cannot save, given value must be instance of entity class, instead object literal is given. Or you must specify an entity target to method call.
    at new CannotDetermineEntityError (/Users/t/_work/node_modules/typeorm/error/CannotDetermineEntityError.js:10:28)
    at /Users/t/_work/node_modules/typeorm/persistence/EntityPersistExecutor.js:69:59
    at Array.forEach (<anonymous>)
    at EntityPersistExecutor.<anonymous> (/Users/t/node_modules/typeorm/persistence/EntityPersistExecutor.js:66:54)
    at step (/Users/t/node_modules/tslib/tslib.js:141:27)
    at Object.next (/Users/toni/_work/1tm/procontra-news/node_modules/tslib/tslib.js:122:57)
    at /Users/t/node_modules/tslib/tslib.js:115:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/Users/t/node_modules/tslib/tslib.js:111:16)
    at /Users/t/node_modules/typeorm/persistence/EntityPersistExecutor.js:58:116
    at Array.map (<anonymous>)
    at EntityPersistExecutor.<anonymous> (/Users/t/node_modules/typeorm/persistence/EntityPersistExecutor.js:58:75)
    at step (/Users/t/node_modules/tslib/tslib.js:141:27)
    at Object.next (/Users/t/node_modules/tslib/tslib.js:122:57)
    at /Users/t/node_modules/tslib/tslib.js:115:75
    at new Promise (<anonymous>) {
  name: 'CannotDetermineEntityError',
  message: 'Cannot save, given value must be instance of entity class, instead object literal is given. Or you must specify an entity target to method call.'
} `

**Comment by iaincollins** [comment]
Previously reported in #493 and resolved in 3.0.1 which went out earlier today.
