### ISSUE TITLE
[OAUTH_CALLBACK_ERROR] no valid key found in issuer's jwks_uri for key parameters

### ISSUE THREAD

**Issue by MoritzKn** [nextauthjs/next-auth#5137]
### Provider type

Azure Active Directory

### Environment

```
  System:
    OS: macOS 12.4
    CPU: (8) arm64 Apple M1
    Memory: 134.31 MB / 8.00 GB
    Shell: 3.1.2 - /opt/homebrew/bin/fish
  Binaries:
    Node: 16.16.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.12.1 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 104.0.5112.79
    Firefox: 100.0
    Safari: 15.5
  npmPackages:
    next: ^12.0.1 => 12.1.6
    next-auth: ^4.10.3 => 4.10.3
    react: ^17.0.2 => 17.0.2
```

### Reproduction URL

https://gist.github.com/MoritzKn/e3c485fcef04a04170ac14780fa0c6bc

### Describe the issue

Under specific circumstances (I'll elaborate), the ID Token JWT uses a different singing key (`kid` key claim in the JWT header). NextAuth (or node-openid-client to be precise) cannot find this key because it is not listed in the response of the`jwks_uri` contained in the well-known URL next-auth sets for Azure AD. 

This results in the following error:
```
2022-08-11T15:56:49.674Z	f3d28edd-e7d6-4810-ae23-70f2e748ae78	ERROR	[next-auth][error][OAUTH_CALLBACK_ERROR] 
https://next-auth.js.org/errors#oauth_callback_error no valid key found in issuer's jwks_uri for key parameters {"kid":"xXXx_XxXxx_xXXxx-xxXXxxx","alg":"RS256"} {
  error: {
    message: `no valid key found in issuer's jwks_uri for key parameters {"kid":"xXXx_XxXxx_xXXxx-xxXXxxx","alg":"RS256"}`,
    stack: `RPError: no valid key found in issuer's jwks_uri for key parameters {"kid":"xXXx_XxXxx_xXXxx-xxXXxxx","alg":"RS256"}\n` +
      '    at Issuer.queryKeyStore (/var/task/node_modules/openid-client/lib/helpers/issuer.js:88:11)\n' +
      '    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n' +
      '    at async Client.validateJWT (/var/task/node_modules/openid-client/lib/client.js:1033:14)\n' +
      '    at async Client.validateIdToken (/var/task/node_modules/openid-client/lib/client.js:743:49)\n' +
      '    at async Client.callback (/var/task/node_modules/openid-client/lib/client.js:486:7)\n' +
      '    at async oAuthCallback (/var/task/node_modules/next-auth/core/lib/oauth/callback.js:114:16)\n' +
      '    at async Object.callback (/var/task/node_modules/next-auth/core/routes/callback.js:50:11)\n' +
      '    at async NextAuthHandler (/var/task/node_modules/next-auth/core/index.js:186:28)\n' +
      '    at async NextAuthNextHandler (/var/task/node_modules/next-auth/next/index.js:23:19)\n' +
      '    at async /var/task/node_modules/next-auth/next/index.js:59:32',
    name: 'RPError'
  },
  providerId: 'azure-ad',
  message: `no valid key found in issuer's jwks_uri for key parameters {"kid":"xXXx_XxXxx_xXXxx-xxXXxxx","alg":"RS256"}`
}
```

According to [MS docs](https://docs.microsoft.com/en-us/azure/active-directory/develop/access-tokens#validating-the-signature):

> If the application has custom signing keys as a result of using the [claims-mapping](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-claims-mapping) feature, append an appid query parameter that contains the application ID to get a jwks_uri that points to the signing key information of the application, which should be used for validation. For example: https://login.microsoftonline.com/{tenant}/.well-known/openid-configuration?appid=6731de76-14a6-49ae-97bc-6eba6914391e contains a jwks_uri of https://login.microsoftonline.com/{tenant}/discovery/keys?appid=6731de76-14a6-49ae-97bc-6eba6914391e.

Different people seem to have ran into this before:
- https://techcommunity.microsoft.com/t5/microsoft-entra-azure-ad/id-token-issued-by-aad-doesn-t-match-public-signing-key/m-p/1525653
- https://github.com/panva/node-openid-client/issues/277

### How to reproduce

Set up Azrue AD with the [claims-mapping](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-claims-mapping) feature, setup a basic Azure AD provider, and try to log in.

The server will show the before-mentioned error and the client will show the login page with a blue info box:
> Try signing in with a different account.

### Expected behavior

Login work even when using this Azure AD feature.

**Comment by MoritzKn** [comment]
I found the following workaround for the issue:

```js
import NextAuth from "next-auth";
import AzureADProvider from "next-auth/providers/azure-ad";

const providers = [];

const tenantId = process.env.AZURE_AD_TENANT_NAME;
const clientId = process.env.AZURE_AD_CLIENT_ID;
const clientSecret = process.env.AZURE_AD_CLIENT_SECRET;
const provider = AzureADProvider({ tenantId, clientId, clientSecret });

if (provider.wellKnown && !provider.wellKnown.includes("appid")) {
  // Workaround for: https://github.com/nextauthjs/next-auth/issues/5137
  provider.wellKnown += `?appid=${clientId}`;
}

providers.push(provider);

export default NextAuth({
  secret: process.env.NEXTAUTH_SECRET,
  providers,
  debug: true,
});

```
