### ISSUE TITLE
Twitter Provider periodically throws error (expected 200 OK, got: 401 Unauthorized)

### ISSUE THREAD

**Issue by gaiverrr** [nextauthjs/next-auth#5228]
### Environment

  System:
    OS: macOS 12.5.1
    CPU: (6) x64 Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz
    Memory: 9.15 GB / 80.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.3.1 - /usr/local/bin/npm
  Browsers:
    Brave Browser: 104.1.42.88
    Chrome: 104.0.5112.101
    Firefox: 103.0.2
    Safari: 15.6.1
  npmPackages:
    next: ^12.2.0 => 12.2.0 
    next-auth: ^4.10.3 => 4.10.3 
    react: ^17.0.2 => 17.0.2 

### Reproduction URL

https://gist.github.com/gaiverrr/4210495dd90e58b9ae27d0cb5a884259

### Describe the issue

Periodically (every tenths case) user have been redirected to /api/auth/signin/?error=OAuthCallback page, when he try to use twiiter as auth provider. Here logs from vercel.

```
[POST] /api/auth/signin/twitter/
20:01:48:21
[next-auth][debug][CREATE_STATE] { state: '4LMh1-JEumrVoEBJYLjWzufitJHRBHt4KV-Z3cMB-e4', maxAge: 900 }
[next-auth][debug][CREATE_PKCE_CHALLENGE_VERIFIER] {
  code_challenge: '1HBxrVN_Fib_70kBpShtxWKStvToC1-aYetFXstnyqQ',
  code_challenge_method: 'S256',
  code_verifier: 'J8ty1kkScJGlTHbLT55DQfEajg2xa7R-5swIjuC9vqQ',
  PKCE_MAX_AGE: 900
}
[next-auth][debug][GET_AUTHORIZATION_URL] {
  url: 'https://twitter.com/i/oauth2/authorize?client_id=*****&scope=users.read%20tweet.read%20offline.access&response_type=code&redirect_uri=https%3A%2F%2Fog-web-dev.vercel.app%2Fapi%2Fauth%2Fcallback%2Ftwitter&state=4LMh1-JEumrVoEBJYLjWzufitJHRBHt4KV-Z3cMB-e4&code_challenge=1HBxrVN_Fib_70kBpShtxWKStvToC1-aYetFXstnyqQ&code_challenge_method=S256',
  cookies: [
    {
      name: '__Secure-next-auth.state',
      value: 'eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..82j_r3SBAi60X5Ks.KAdh1Vrsd4c3amoTbTpap_MLPsG-SrieIvSsr4WcvaiGepNJ6yE1GYgWGy8yZlGsRuACTLJmTYqBGLwN_zi99Z1PTyb3ry89PNr8w5wT6X5JO2xZKiwDohIWIsin9w37QSUyjqRNFcxlYWKK7uY7OlUgcF4UlU3ID1aNfvkM4nr1YiL5-Zo.DJ86my9EqPmrYbT3NcRx4Q',
      options: [Object]
    },
    {
      name: '__Secure-next-auth.pkce.code_verifier',
      value: 'eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..EpBr0PP_5tKqDiF3.qjOXl3BqifZAKv6XwrMyMmEs5SixzOA1N4p-txkdlBbTlS-7E5ccg3JSf2Xr60dYX3j63OO2oABcqKMH6u38WzASg63dq70yZV0MRmksH7KK3ntsuOFDXiQpeaZqpgg9yHbbuy-Phc47DMQP3t_TO4FiDMOsogyHQ1Gb0GRicN1mfEgu_Y7nR7xy-GaITw.5u8NNqOd6S2NtKtWemSYUA',
      options: [Object]
    }
  ],
  provider: {
    id: 'twitter',
    name: 'Twitter',
    version: '2.0',
    type: 'oauth',
    authorization: { url: 'https://twitter.com/i/oauth2/authorize', params: [Object] },
    token: {
      url: 'https://api.twitter.com/2/oauth2/token',
      request: [AsyncFunction: request]
    },
    userinfo: { url: 'https://api.twitter.com/2/users/me', params: [Object] },
    profile: [Function: profile],
    checks: [ 'pkce', 'state' ],
    idToken: false,
    clientId: '*****',
    clientSecret: '****',
    signinUrl: ''*****',,
    callbackUrl: ''*****','
  }
}


[GET] /api/auth/callback/twitter/?state=4LMh1-JEumrVoEBJYLjWzufitJHRBHt4KV-Z3cMB-e4&code=VEw0Y1I2czhOenVXOHJGVVBxbWIxX0poOFJldGpXcThhX2pSN0FUV281LUNKOjE2NjE1MzMzMTAwMTU6MToxOmFjOjE
20:01:51:41
2022-08-26T17:01:51.750Z  74e5f0a8-1a73-4150-b1cd-398120b10f54  ERROR [next-auth][error][OAUTH_CALLBACK_ERROR] 
https://next-auth.js.org/errors#oauth_callback_error expected 200 OK, got: 401 Unauthorized {
  error: {
    message: 'expected 200 OK, got: 401 Unauthorized',
    stack: 'OPError: expected 200 OK, got: 401 Unauthorized\n' +
      '    at processResponse (/var/task/node_modules/openid-client/lib/helpers/process_response.js:41:11)\n' +
      '    at Client.userinfo (/var/task/node_modules/openid-client/lib/client.js:1235:18)\n' +
      '    at runMicrotasks (<anonymous>)\n' +
      '    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n' +
      '    at async oAuthCallback (/var/task/node_modules/next-auth/core/lib/oauth/callback.js:136:17)\n' +
      '    at async Object.callback (/var/task/node_modules/next-auth/core/routes/callback.js:50:11)\n' +
      '    at async NextAuthHandler (/var/task/node_modules/next-auth/core/index.js:186:28)\n' +
      '    at async NextAuthNextHandler (/var/task/node_modules/next-auth/next/index.js:23:19)\n' +
      '    at async /var/task/node_modules/next-auth/next/index.js:59:32\n' +
      '    at async Object.apiResolver (/var/task/node_modules/next/dist/server/api-utils/node.js:179:9)\n' +
      '    at async NextNodeServer.runApi (/var/task/node_modules/next/dist/server/next-server.js:381:9)\n' +
      '    at async Object.fn (/var/task/node_modules/next/dist/server/base-server.js:488:37)\n' +
      '    at async Router.execute (/var/task/node_modules/next/dist/server/router.js:213:36)\n' +
      '    at async NextNodeServer.run (/var/task/node_modules/next/dist/server/base-server.js:621:29)\n' +
      '    at async NextNodeServer.handleRequest (/var/task/node_modules/next/dist/server/base-server.js:317:20)\n' +
      '    at async Server.module.exports (/var/task/___next_launcher.cjs:29:9)',
    name: 'OPError'
  },
  providerId: 'twitter',
  message: 'expected 200 OK, got: 401 Unauthorized'
}
2022-08-26T17:01:51.750Z  74e5f0a8-1a73-4150-b1cd-398120b10f54  ERROR [next-auth][error][CALLBACK_OAUTH_ERROR] 
https://next-auth.js.org/errors#callback_oauth_error expected 200 OK, got: 401 Unauthorized OPError: expected 200 OK, got: 401 Unauthorized
    at processResponse (/var/task/node_modules/openid-client/lib/helpers/process_response.js:41:11)
    at Client.userinfo (/var/task/node_modules/openid-client/lib/client.js:1235:18)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async oAuthCallback (/var/task/node_modules/next-auth/core/lib/oauth/callback.js:136:17)
    at async Object.callback (/var/task/node_modules/next-auth/core/routes/callback.js:50:11)
    at async NextAuthHandler (/var/task/node_modules/next-auth/core/index.js:186:28)
    at async NextAuthNextHandler (/var/task/node_modules/next-auth/next/index.js:23:19)
    at async /var/task/node_modules/next-auth/next/index.js:59:32
    at async Object.apiResolver (/var/task/node_modules/next/dist/server/api-utils/node.js:179:9)
    at async NextNodeServer.runApi (/var/task/node_modules/next/dist/server/next-server.js:381:9)
    at async Object.fn (/var/task/node_modules/next/dist/server/base-server.js:488:37)
    at async Router.execute (/var/task/node_modules/next/dist/server/router.js:213:36)
    at async NextNodeServer.run (/var/task/node_modules/next/dist/server/base-server.js:621:29)
    at async NextNodeServer.handleRequest (/var/task/node_modules/next/dist/server/base-server.js:317:20)
    at async Server.module.exports (/var/task/___next_launcher.cjs:29:9) {
  name: 'OAuthCallbackError',
  code: undefined
}
```

### How to reproduce

Steps are simple, I should press sign in button, then sign out. And after multiple succesfull operations, I have been redirected to api/auth/signin/?error=OAuthCallback page 

### Expected behavior

No redirection to error page

**Comment by balazsorban44** [comment]
I have tried to reproduce this, but I don't see a problem. Is this happening consistently? If not, I'm afraid there's not much we can do/debug here. NextAuth.js seems to work as expected anyway.
