### ISSUE TITLE
Get Session from getServerSideProps

### ISSUE THREAD

**Issue by radromanov** [nextauthjs/next-auth#5262]
### Question 💬

Hey guys, I'm trying to get `session` through `getServerSideProps`, which contains the logged in user's email, so as to make a follow-up request in that same `getServerSideProps` to fetch the user with the email in the `session`, and pass it as `props` in the client-side.
Is my approach correct to begin with and, if it's not, what's a better way to accomplish this?

### Error:
```
error - TypeError: options.providers is not iterable
    at assertConfig (C:\Users\Owner\Desktop\Projects\proj-v4\node_modules\next-auth\core\lib\assert.js:68:34)
    at NextAuthHandler (C:\Users\Owner\Desktop\Projects\proj-v4\node_modules\next-auth\core\index.js:70:52)
    at async unstable_getServerSession (C:\Users\Owner\Desktop\Projects\proj-v4\node_modules\next-auth\next\index.js:79:19)
    at async getServerSideProps (webpack-internal:///./pages/index.tsx:43:21)
    at async Object.renderToHTML (C:\Users\Owner\Desktop\Projects\proj-v4\node_modules\next\dist\server\render.js:490:20)
    at async doRender (C:\Users\Owner\Desktop\Projects\proj-v4\node_modules\next\dist\server\base-server.js:908:38)
    at async cacheEntry.responseCache.get.isManualRevalidate.isManualRevalidate (C:\Users\Owner\Desktop\Projects\proj-v4\node_modules\next\dist\server\base-server.js:1013:28)
    at async C:\Users\Owner\Desktop\Projects\proj-v4\node_modules\next\dist\server\response-cache.js:69:36 {
  page: '/'
}
```

### Dependencies:
```
  "dependencies": {
    "@next-auth/prisma-adapter": "^1.0.4",
    "@prisma/client": "^4.2.1",
    "next": "12.2.5",
    "next-auth": "^4.10.3",
    "nodemailer": "^6.7.8",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
  },
  "devDependencies": {
    "@babel/register": "^7.18.9",
    "@types/node": "^18.7.8",
    "@types/react": "18.0.17",
    "@types/react-dom": "18.0.6",
    "eslint": "8.22.0",
    "eslint-config-next": "12.2.5",
    "prisma": "^4.2.1",
    "ts-node": "^10.9.1",
    "typescript": "^4.7.4"
  }
  ```

### `authOptions` setup:
``` 
export default NextAuth({
  adapter: PrismaAdapter(prisma),

  providers: [
    Credentials({
      credentials: {
        username: { label: "Username", type: "text", placeholder: "jsmith" },
        password: { label: "Password", type: "text" },
      },
      async authorize(credentials, req) {
        if (credentials?.username && credentials?.password) {
          const user = await prisma.user.findUnique({
            where: {
              username: credentials.username,
            },
            include: {
              follows: true,
            },
          });

          if (user) {
            // Compares the password coming from the user input
            const password = await bcrypt.compare(
              credentials.password,
              user.password
            );
            // Checks if password === true and returns the user
            if (password) {
              return user;
            } else {
              return null; // password is incorrect
            }
          } else {
            return null; // user not found in db
          }
        } else {
          return null;
        }
      },
    }),
  ],
  session: {
    strategy: "jwt",
  },
});
```

### `getServerSideProps` setup:
```
export const getServerSideProps: GetServerSideProps = async (
  context: GetServerSidePropsContext
) => {
  const session = await unstable_getServerSession(
    context.req,
    context.res,
    authOptions()
  );

  // fetch user with session.user.email here

  return {
    props: {
      // user
    },
  };
};
```

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment]
`authOptions` is the config object inside `NextAuth`. You need to separate it out, and pass that to `unstable_getServerSession`. Please refer to the docs: https://next-auth.js.org/configuration/nextjs#unstable_getserversession
