### ISSUE TITLE
Can next-auth's session be used in multiple browsers (or multiple devices)?

### ISSUE THREAD

**Issue by usmanity** [nextauthjs/next-auth#5285]
### Question 💬

I have a standard setup with next-auth, I am using two providers at the moment (Github and email magic links). 

My question is, can a user be signed in to my website from multiple browsers or devices? I am testing the production setup now and I am noticing that in the first browser, the login flow works perfectly fine. But in the second browser (or device), I get `error=Callback` in the URL (after the callback URL). I looked at my Vercel logs and I see the following error: 

```
https://next-auth.js.org/errors#adapter_error_createsession 
Invalid `prisma.session.create()` invocation:Unique constraint failed on the (not available) 
{  message: '\n' +    'Invalid `prisma.session.create()` invocation:\n' +    '\n' +    '\n' +    'Unique constraint failed on the (not available)',  
stack: 'Error: \n' +    'Invalid `prisma.session.create()` invocation:\n' +    '\n' +    '\n' +    'Unique constraint failed on the (not available)\n' +    
'    at RequestHandler.handleRequestError (/var/task/node_modules/@prisma/client/runtime/index.js:29909:13)\n' +    
'    at RequestHandler.request (/var/task/node_modules/@prisma/client/runtime/index.js:29892:12)\n' +    
'    at async PrismaClient._request (/var/task/node_modules/@prisma/client/runtime/index.js:30864:16)',  
name: 'Error'}

ERROR	[next-auth][error][OAUTH_CALLBACK_HANDLER_ERROR] 
https://next-auth.js.org/errors#oauth_callback_handler_error 
Invalid `prisma.session.create()` invocation:Unique constraint failed on the (not available) 
Error: Invalid `prisma.session.create()` invocation:Unique constraint failed on the (not available)    
at RequestHandler.handleRequestError (/var/task/node_modules/@prisma/client/runtime/index.js:29909:13)    
at RequestHandler.request (/var/task/node_modules/@prisma/client/runtime/index.js:29892:12)    
at async PrismaClient._request (/var/task/node_modules/@prisma/client/runtime/index.js:30864:16) 
{  name: 'CreateSessionError',  code: 'P2002'}
```

### How to reproduce ☕️

This happens to my website when I am signed into a browser already and then use the same user in a separate browser. 

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by usmanity** [comment]
Update: it looks like my Prisma schema was using a `@unique` constraint on userId which I changed and updated the user's relation to have multiple sessions, see my changes below:
 
`schema.prisma`
```
model User {
  id             String    @id @default(cuid())
  name           String?
  email          String?   @unique
  emailVerified  DateTime?
  image          String?
  Session        Session[]
  Account        Account?
}


model Session {
  id           String   @id @default(cuid())
  sessionToken String   @unique
  userId       String
  expires      DateTime
  user         User     @relation(fields: [userId], references: [id])

  @@index([userId])
}
```
