### ISSUE TITLE
Signup with Azure Active Directory redirects with OAuthAccountNotLinked

### ISSUE THREAD

**Issue by palminha** [nextauthjs/next-auth#5454]
### Provider type

Azure Active Directory

### Environment

```
System:
    OS: macOS 12.6
    CPU: (8) arm64 Apple M1
    Memory: 83.34 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.8.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.18.0 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 105.0.5195.125
    Safari: 16.0
  npmPackages:
    next: 12.2.4 => 12.2.4 
    next-auth: ^4.10.3 => 4.10.3 
    react: latest => 17.0.2 
```

### Reproduction URL

not public

### Describe the issue

We have implemented three login methods: Email link, GitHub and Azure Active Directory
The EMail Link and GitHub are working ok.

With Azure the URI is redirected with error=OAuthAccountNotLinked

i followed these instructions: https://next-auth.js.org/providers/azure-ad

### How to reproduce

Azure the URI is redirected with error=OAuthAccountNotLinked

### Expected behavior

The redirect should work and user should be logged in into our application

**Comment by palminha** [comment]
In the User table I find the row related to the user, but no row is present in the Account table for this user.

**Comment by palminha** [comment]
@ikoichi is reporting a similar issue using Goolge SignUp: https://github.com/nextauthjs/next-auth/issues/5397

**Comment by palminha** [comment]
i think i found the problem...

i did the following

1. Empty all the user related tables... ensure that `Account`, `Session`, `User` and `VerificationToken` are empty...no users
2. Try to login using the Azure AD
3. The server crashes big
(see log below ...omitted some of the IDs)


```
[next-auth][error][adapter_error_linkAccount] 
https://next-auth.js.org/errors#adapter_error_linkaccount 
Invalid `p.account.create()` invocation in
/Users/palmito/Development/risk-util-tool/webapp/node_modules/@next-auth/prisma-adapter/dist/index.js:19:42

  16 },
  17 updateUser: ({ id, ...data }) => p.user.update({ where: { id }, data }),
  18 deleteUser: (id) => p.user.delete({ where: { id } }),
→ 19 linkAccount: (data) => p.account.create({
       data: {
         provider: 'azure-ad',
         type: 'oauth',
         providerAccountId: '....',
         token_type: 'Bearer',
         scope: 'email openid profile',
         expires_at: 1664455996,
         ext_expires_in: 5313,
         ~~~~~~~~~~~~~~
         access_token: '....',
         id_token: '....',
         session_state: 'f8a8b7dd-bfb9-40b4-b750-9fe15742edf0',
         userId: 'adb93a8a-0107-424b-947f-9d79eb568a5b'
       }
     })

Unknown arg `ext_expires_in` in data.ext_expires_in for type AccountUncheckedCreateInput. Available args:

type AccountUncheckedCreateInput {
  id?: String
  userId: String
  type: String
  provider: String
  providerAccountId: String
  refresh_token?: String | Null
  access_token?: String | Null
  expires_at?: Int | Null
  token_type?: String | Null
  scope?: String | Null
  id_token?: String | Null
  session_state?: String | Null
}

 {
  message: '\n' +
    'Invalid `p.account.create()` invocation in\n' +
    '/Users/palmito/Development/risk-util-tool/webapp/node_modules/@next-auth/prisma-adapter/dist/index.js:19:42\n' +
    '\n' +
    '  16 },\n' +
    '  17 updateUser: ({ id, ...data }) => p.user.update({ where: { id }, data }),\n' +
    '  18 deleteUser: (id) => p.user.delete({ where: { id } }),\n' +
    '→ 19 linkAccount: (data) => p.account.create({\n' +
    '       data: {\n' +
    "         provider: 'azure-ad',\n" +
    "         type: 'oauth',\n" +
    "         providerAccountId: '....',\n" +
    "         token_type: 'Bearer',\n" +
    "         scope: 'email openid profile',\n" +
    '         expires_at: 1664455996,\n' +
    '         ext_expires_in: 5313,\n' +
    '         ~~~~~~~~~~~~~~\n' +
    "         access_token: '...',\n" +
    "         id_token: '...',\n" +
    "         session_state: 'f8a8b7dd-bfb9-40b4-b750-9fe15742edf0',\n" +
    "         userId: 'adb93a8a-0107-424b-947f-9d79eb568a5b'\n" +
    '       }\n' +
    '     })\n' +
    '\n' +
    'Unknown arg `ext_expires_in` in data.ext_expires_in for type AccountUncheckedCreateInput. Available args:\n' +
    '\n' +
    'type AccountUncheckedCreateInput {\n' +
    '  id?: String\n' +
    '  userId: String\n' +
    '  type: String\n' +
    '  provider: String\n' +
    '  providerAccountId: String\n' +
    '  refresh_token?: String | Null\n' +
    '  access_token?: String | Null\n' +
    '  expires_at?: Int | Null\n' +
    '  token_type?: String | Null\n' +
    '  scope?: String | Null\n' +
    '  id_token?: String | Null\n' +
    '  session_state?: String | Null\n' +
    '}\n' +
    '\n',
  stack: 'Error: \n' +
    'Invalid `p.account.create()` invocation in\n' +
    '/Users/palmito/Development/risk-util-tool/webapp/node_modules/@next-auth/prisma-adapter/dist/index.js:19:42\n' +
    '\n' +
    '  16 },\n' +
    '  17 updateUser: ({ id, ...data }) => p.user.update({ where: { id }, data }),\n' +
    '  18 deleteUser: (id) => p.user.delete({ where: { id } }),\n' +
    '→ 19 linkAccount: (data) => p.account.create({\n' +
    '       data: {\n' +
    "         provider: 'azure-ad',\n" +
    "         type: 'oauth',\n" +
    "         providerAccountId: 'mrGrhNxwhmmHVCP8q7atjAzm3yusnqOP_dx7HKyCrkE',\n" +
    "         token_type: 'Bearer',\n" +
    "         scope: 'email openid profile',\n" +
    '         expires_at: 1664455996,\n' +
    '         ext_expires_in: 5313,\n' +
    '         ~~~~~~~~~~~~~~\n' +
    "         access_token: '...',\n" +
    "         id_token: '...',\n" +
    "         session_state: 'f8a8b7dd-bfb9-40b4-b750-9fe15742edf0',\n" +
    "         userId: 'adb93a8a-0107-424b-947f-9d79eb568a5b'\n" +
    '       }\n' +
    '     })\n' +
    '\n' +
    'Unknown arg `ext_expires_in` in data.ext_expires_in for type AccountUncheckedCreateInput. Available args:\n' +
    '\n' +
    'type AccountUncheckedCreateInput {\n' +
    '  id?: String\n' +
    '  userId: String\n' +
    '  type: String\n' +
    '  provider: String\n' +
    '  providerAccountId: String\n' +
    '  refresh_token?: String | Null\n' +
    '  access_token?: String | Null\n' +
    '  expires_at?: Int | Null\n' +
    '  token_type?: String | Null\n' +
    '  scope?: String | Null\n' +
    '  id_token?: String | Null\n' +
    '  session_state?: String | Null\n' +
    '}\n' +
    '\n' +
    '\n' +
    '    at Document.validate (/Users/palmito/Development/risk-util-tool/webapp/node_modules/@prisma/client/runtime/index.js:28174:20)\n' +
    '    at serializationFn (/Users/palmito/Development/risk-util-tool/webapp/node_modules/@prisma/client/runtime/index.js:30774:19)\n' +
    '    at runInChildSpan (/Users/palmito/Development/risk-util-tool/webapp/node_modules/@prisma/client/runtime/index.js:24002:12)\n' +
    '    at PrismaClient._executeRequest (/Users/palmito/Development/risk-util-tool/webapp/node_modules/@prisma/client/runtime/index.js:30781:31)\n' +
    '    at consumer (/Users/palmito/Development/risk-util-tool/webapp/node_modules/@prisma/client/runtime/index.js:30707:23)\n' +
    '    at /Users/palmito/Development/risk-util-tool/webapp/node_modules/@prisma/client/runtime/index.js:30712:51\n' +
    '    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)\n' +
    '    at /Users/palmito/Development/risk-util-tool/webapp/node_modules/@prisma/client/runtime/index.js:30712:29\n' +
    '    at runInChildSpan (/Users/palmito/Development/risk-util-tool/webapp/node_modules/@prisma/client/runtime/index.js:24002:12)\n' +
    '    at PrismaClient._request (/Users/palmito/Development/risk-util-tool/webapp/node_modules/@prisma/client/runtime/index.js:30709:22)',
  name: 'Error'
}
[next-auth][error][OAUTH_CALLBACK_HANDLER_ERROR] 
https://next-auth.js.org/errors#oauth_callback_handler_error 
Invalid `p.account.create()` invocation in
/Users/palmito/Development/risk-util-tool/webapp/node_modules/@next-auth/prisma-adapter/dist/index.js:19:42

  16 },
  17 updateUser: ({ id, ...data }) => p.user.update({ where: { id }, data }),
  18 deleteUser: (id) => p.user.delete({ where: { id } }),
→ 19 linkAccount: (data) => p.account.create({
       data: {
         provider: 'azure-ad',
         type: 'oauth',
         providerAccountId: '...',
         token_type: 'Bearer',
         scope: 'email openid profile',
         expires_at: 1664455996,
         ext_expires_in: 5313,
         ~~~~~~~~~~~~~~
         access_token: '...',
         id_token: '...',
         session_state: 'f8a8b7dd-bfb9-40b4-b750-9fe15742edf0',
         userId: 'adb93a8a-0107-424b-947f-9d79eb568a5b'
       }
     })

Unknown arg `ext_expires_in` in data.ext_expires_in for type AccountUncheckedCreateInput. Available args:

type AccountUncheckedCreateInput {
  id?: String
  userId: String
  type: String
  provider: String
  providerAccountId: String
  refresh_token?: String | Null
  access_token?: String | Null
  expires_at?: Int | Null
  token_type?: String | Null
  scope?: String | Null
  id_token?: String | Null
  session_state?: String | Null
}

 Error: 
Invalid `p.account.create()` invocation in
/Users/palmito/Development/risk-util-tool/webapp/node_modules/@next-auth/prisma-adapter/dist/index.js:19:42

  16 },
  17 updateUser: ({ id, ...data }) => p.user.update({ where: { id }, data }),
  18 deleteUser: (id) => p.user.delete({ where: { id } }),
→ 19 linkAccount: (data) => p.account.create({
       data: {
         provider: 'azure-ad',
         type: 'oauth',
         providerAccountId: '...',
         token_type: 'Bearer',
         scope: 'email openid profile',
         expires_at: 1664455996,
         ext_expires_in: 5313,
         ~~~~~~~~~~~~~~
         access_token: '...',
         id_token: '...',
         session_state: 'f8a8b7dd-bfb9-40b4-b750-9fe15742edf0',
         userId: 'adb93a8a-0107-424b-947f-9d79eb568a5b'
       }
     })

Unknown arg `ext_expires_in` in data.ext_expires_in for type AccountUncheckedCreateInput. Available args:

type AccountUncheckedCreateInput {
  id?: String
  userId: String
  type: String
  provider: String
  providerAccountId: String
  refresh_token?: String | Null
  access_token?: String | Null
  expires_at?: Int | Null
  token_type?: String | Null
  scope?: String | Null
  id_token?: String | Null
  session_state?: String | Null
}


    at Document.validate (/Users/palmito/Development/risk-util-tool/webapp/node_modules/@prisma/client/runtime/index.js:28174:20)
    at serializationFn (/Users/palmito/Development/risk-util-tool/webapp/node_modules/@prisma/client/runtime/index.js:30774:19)
    at runInChildSpan (/Users/palmito/Development/risk-util-tool/webapp/node_modules/@prisma/client/runtime/index.js:24002:12)
    at PrismaClient._executeRequest (/Users/palmito/Development/risk-util-tool/webapp/node_modules/@prisma/client/runtime/index.js:30781:31)
    at consumer (/Users/palmito/Development/risk-util-tool/webapp/node_modules/@prisma/client/runtime/index.js:30707:23)
    at /Users/palmito/Development/risk-util-tool/webapp/node_modules/@prisma/client/runtime/index.js:30712:51
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at /Users/palmito/Development/risk-util-tool/webapp/node_modules/@prisma/client/runtime/index.js:30712:29
    at runInChildSpan (/Users/palmito/Development/risk-util-tool/webapp/node_modules/@prisma/client/runtime/index.js:24002:12)
    at PrismaClient._request (/Users/palmito/Development/risk-util-tool/webapp/node_modules/@prisma/client/runtime/index.js:30709:22) {
  name: 'LinkAccountError',
  code: undefined
}

```

**Comment by balazsorban44** [comment]
`ext_expires_in` is not part of the default schema. Make sure to add it. https://next-auth.js.org/adapters/prisma#create-the-prisma-schema

**Comment by palminha** [comment]
@balazsorban44 since the field is not part of the default schema, other people may endup with this problem.
will https://github.com/nextauthjs/next-auth/pull/4893 avoid these type of problem in the future?

**Comment by balazsorban44** [comment]
I don't think that PR will be the right solution https://github.com/nextauthjs/next-auth/pull/4893#issuecomment-1180623709. Maybe a better error message, but if you use a certain adapter, I feel the error message should already be very clear what to do. :thinking:

**Comment by freshtechs** [comment]
I think it would be very useful if in the [docs](https://next-auth.js.org/providers/azure-ad) referring to Azure AD provider a comment or warning appeared and Guide you to add the to the Account model of your schema.prisma the additional field sent by Azure AD:


`ext_expires_in    Int?`
