### ISSUE TITLE
How to ignore / increase clock tolerance for nbf?

### ISSUE THREAD

**Issue by ryanelian** [nextauthjs/next-auth#5514]
### Question 💬

I am signing in to duende demo and I'm getting this error.

```
> @accelist/nextjs-starter@1.0.0 start
> next start -p 80

ready - started server on 0.0.0.0:80, url: http://localhost:80
NextAuth error when refreshing token:  OPError: invalid_grant
    at processResponse (D:\VS\accelist-nextjs-starter\node_modules\openid-client\lib\helpers\process_response.js:38:13)
    at Client.grant (D:\VS\accelist-nextjs-starter\node_modules\openid-client\lib\client.js:1325:22)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Client.refresh (D:\VS\accelist-nextjs-starter\node_modules\openid-client\lib\client.js:1069:22)
    at async refreshAccessToken (D:\VS\accelist-nextjs-starter\.next\server\pages\api\auth\[...nextauth].js:89:24)
    at async Object.session (D:\VS\accelist-nextjs-starter\node_modules\next-auth\core\routes\session.js:53:21)
    at async NextAuthHandler (D:\VS\accelist-nextjs-starter\node_modules\next-auth\core\index.js:158:27)
    at async NextAuthNextHandler (D:\VS\accelist-nextjs-starter\node_modules\next-auth\next\index.js:23:19)
    at async D:\VS\accelist-nextjs-starter\node_modules\next-auth\next\index.js:59:32
    at async Object.apiResolver (D:\VS\accelist-nextjs-starter\node_modules\next\dist\server\api-utils\node.js:366:9) {
  error: 'invalid_grant'
}
[next-auth][error][OAUTH_CALLBACK_ERROR]
https://next-auth.js.org/errors#oauth_callback_error JWT not active yet, now 1665128226, nbf 1665128280 {
  error: RPError: JWT not active yet, now 1665128226, nbf 1665128280
      at Client.validateJWT (D:\VS\accelist-nextjs-starter\node_modules\openid-client\lib\client.js:932:15)
      at Client.validateIdToken (D:\VS\accelist-nextjs-starter\node_modules\openid-client\lib\client.js:743:60)
      at Client.callback (D:\VS\accelist-nextjs-starter\node_modules\openid-client\lib\client.js:486:18)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async oAuthCallback (D:\VS\accelist-nextjs-starter\node_modules\next-auth\core\lib\oauth\callback.js:123:16)
      at async Object.callback (D:\VS\accelist-nextjs-starter\node_modules\next-auth\core\routes\callback.js:50:11)
      at async NextAuthHandler (D:\VS\accelist-nextjs-starter\node_modules\next-auth\core\index.js:201:28)
      at async NextAuthNextHandler (D:\VS\accelist-nextjs-starter\node_modules\next-auth\next\index.js:23:19)
      at async D:\VS\accelist-nextjs-starter\node_modules\next-auth\next\index.js:59:32
      at async Object.apiResolver (D:\VS\accelist-nextjs-starter\node_modules\next\dist\server\api-utils\node.js:366:9) {
    name: 'OAuthCallbackError',
    code: undefined
  },
  providerId: 'oidc',
  message: 'JWT not active yet, now 1665128226, nbf 1665128280'
}

```

This is the configuration I used to connect to Duende demo server:

```
OIDC_ISSUER=https://demo.duendesoftware.com
OIDC_CLIENT_ID=interactive.public.short
OIDC_SCOPE=openid profile email api offline_access

```

I just synced my laptop time, so my laptop time should probably be correct

![image](https://user-images.githubusercontent.com/8892187/194500511-bf0a071e-bce9-48f3-8c7b-2ed36291c138.png)

The duende server is just for testing but I can't help getting worried because my demo example doesn't work.

### How to reproduce ☕️

This is the authentication code I used to log into the OpenID Connect server. 

The complete source code is in this repository: https://github.com/accelist/nextjs-starter

```ts
import NextAuth, { NextAuthOptions } from "next-auth"
import type { JWT } from "next-auth/jwt";
import { Issuer } from 'openid-client';
import { custom } from 'openid-client';
import { AppSettings } from "../../../functions/AppSettings"
import { UserInfo } from "../../../functions/AuthorizationContext";

/**
 * Takes a token, and returns a new token with updated
 * `accessToken` and `accessTokenExpires`. If an error occurs,
 * returns the old token and an error property
 */
async function refreshAccessToken(token: JWT & { refreshToken?: string }) {
    try {
        if (!token.refreshToken) {
            throw new Error('Refresh token is empty!');
        }

        const discovery = await Issuer.discover(AppSettings.current.oidcIssuer);

        const client = new discovery.Client({
            client_id: AppSettings.current.oidcClientId,
            token_endpoint_auth_method: 'none',
        });

        client[custom.clock_tolerance] = 10; // to allow a 10 second skew

        // console.log('NextAuth refreshing token: ', token.refreshToken);
        const update = await client.refresh(token.refreshToken);

        return {
            ...token,
            accessToken: update.access_token,
            accessTokenExpires: calculateExpireAtMilliseconds(update.expires_at),
            refreshToken: update.refresh_token ?? token.refreshToken, // Fall back to old refresh token
        }
    } catch (err) {
        console.log('NextAuth error when refreshing token: ', err);

        return {
            ...token,
            error: "RefreshAccessTokenError",
        }
    }
}

function calculateExpireAtMilliseconds(expireAtSeconds: number | undefined) {
    // we didn't get expireAt value, just assume it will expire in 15 minutes
    if (!expireAtSeconds) {
        return Date.now() + 15 * 60 * 1000;
    }

    return expireAtSeconds * 1000;
}

function hasNotExpired(expireAtSeconds: unknown): boolean {
    if (typeof expireAtSeconds !== 'number') {
        return false;
    }

    if (!expireAtSeconds) {
        return false;
    }

    return (Date.now() < expireAtSeconds);
}

export const authOptions: NextAuthOptions = {
    providers: [
        {
            id: "oidc",
            name: "OpenID Connect",
            type: "oauth",
            wellKnown: AppSettings.current.oidcIssuer + '/.well-known/openid-configuration',
            client: {
                token_endpoint_auth_method: 'none'
            },
            clientId: AppSettings.current.oidcClientId,
            authorization: {
                params: {
                    scope: AppSettings.current.oidcScope,
                }
            },
            checks: ["pkce", "state"],
            idToken: true,
            userinfo: {
                async request(context) {
                    // idToken: true makes next-auth parse user info from id_token
                    // this code below makes next-auth query the user info endpoint instead
                    if (context.tokens.access_token) {
                        return await context.client.userinfo(context.tokens.access_token)
                    }
                    return {};
                }
            },
            async profile(profile) {
                // add claims obtained from user info endpoint to the session.user data
                // reference: https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims
                // console.log(profile);
                return {
                    id: profile.sub,
                    name: profile.name,
                    // given_name: profile.given_name,
                    // family_name: profile.family_name,
                    // middle_name: profile.middle_name,
                    // nickname: profile.nickname,
                    // preferred_username: profile.preferred_username,
                    // profile: profile.profile,
                    // picture: profile.picture,
                    // website: profile.website,
                    email: profile.email,
                    // email_verified: profile.email_verified,
                    // gender: profile.gender,
                    // birthdate: profile.birthdate,
                    // zoneinfo: profile.zoneinfo,
                    // locale: profile.locale,
                    // phone_number: profile.phone_number,
                    // phone_number_verified: profile.phone_number_verified,
                    // address: profile.address,
                    // updated_at: profile.updated_at
                    role: profile.role
                }
            },
        }
    ],
    callbacks: {
        async jwt({ token, account, user }) {
            // Initial sign in
            if (account && user) {
                // console.log(JSON.stringify(account, null, 4));
                return {
                    accessToken: account.access_token,
                    accessTokenExpires: calculateExpireAtMilliseconds(account.expires_at),
                    refreshToken: account.refresh_token,
                    user,
                }
            }

            // Return previous token if the access token has not expired yet
            // console.log(Date.now(), accessTokenExpires);
            if (hasNotExpired(token['accessTokenExpires'])) {
                // console.log('Token not expired yet');
                return token;
            }

            // console.log('Token has expired');
            // Access token has expired, try to update it
            return refreshAccessToken(token)
        },
        async session({ session, token }) {
            // Send properties to the client, like an access_token from a provider.
            session.user = token['user'] as UserInfo;
            session['accessToken'] = token['accessToken'];
            session['error'] = token['error'];
            return session
        }
    },
}

export default NextAuth(authOptions)

// generate new NEXTAUTH_SECRET for production
// https://generate-secret.vercel.app/32

```

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment]
Currently, it's not possible to set a different clock tolerance as it is hardcoded here:

https://github.com/nextauthjs/next-auth/blob/6132c3fa751b647dd8261ac9b30e24fb140a2f1a/packages/next-auth/src/core/lib/oauth/client.ts#L41-L44

If you see this issue, it is likely a sync issue on your laptop. I just tested the Duende provider via the [dev app](https://github.com/nextauthjs/next-auth/tree/main/apps/dev) and it worked fine.
