### ISSUE TITLE
Overwrite scope with custom scope with Cognito provider.

### ISSUE THREAD

**Issue by ketanip** [nextauthjs/next-auth#5555]
### Question 💬

I want to overwrite `Cognito` provider `scope` from `openid` to `openid profile email phone` but when I tried other solutions they didn't work.

Other solutions included:

1. In sign in hook.
```tsx
<button onClick={() => signIn("cognito", {}, "openid email phone profile")}>
    Sign In
</button>
```
2. By changing authorization params. 
```ts
CognitoProvider({
    clientId: String(process.env.COGNITO_CLIENT_ID),
    clientSecret: String(process.env.COGNITO_CLIENT_SECRET),
    issuer: String(process.env.COGNITO_ISSUER),
    authorization: {
        params: {
            claims: "openid profile email phone "
        }
    }
}),
```
But when I try to sign in it redirects me and shows this error page.

![screenshot](https://user-images.githubusercontent.com/50294674/195125388-85d42ce7-be48-4af5-ad27-862eb40b3710.png)

Complete next-auth options:

```ts
export const authOptions: NextAuthOptions = {
    providers: [
        CognitoProvider({
            clientId: String(process.env.COGNITO_CLIENT_ID),
            clientSecret: String(process.env.COGNITO_CLIENT_SECRET),
            issuer: String(process.env.COGNITO_ISSUER),
            authorization: {
                params: {
                    claims: "openid profile email phone "
                }
            }
        }),
    ],
    session: {
        strategy: "jwt",
    },
};

It has no database attached.

```

### How to reproduce ☕️

Create a AWS Cognito user pool with `name`, `email` and `phone` as required field. Then add Cognito as providers and set `openid profile email phone` as value to `authorization.params.claims` under its configuration.

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment]
Change this line:

```ts
claims: "openid profile email phone "
```
to
```ts
claims: "openid profile email phone"
```

**Comment by ketanip** [comment]
I changed `claims` to `scope` but it is still giving the same error.

Here is the error which is being displayed in terminal hope it helps to find the issue.

```bash
[next-auth][error][OAUTH_CALLBACK_ERROR]
https://next-auth.js.org/errors#oauth_callback_error invalid_request {
  message: 'invalid_request',
  stack: 'Error: invalid_request\n' +
    '    at oAuthCallback (C:\\Users\\user\\Desktop\\application-folder\\node_modules\\next-auth\\core\\lib\\oauth\\callback.js:39:19)\n' +
    '    at Object.callback (C:\\Users\\user\\Desktop\\application-folder\\node_modules\\next-auth\\core\\routes\\callback.js:52:39)\n' +
    '    at NextAuthHandler (C:\\Users\\user\\Desktop\\application-folder\\node_modules\\next-auth\\core\\index.js:201:41)\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n' +
    '    at async NextAuthNextHandler (C:\\Users\\user\\Desktop\\application-folder\\node_modules\\next-auth\\next\\index.js:23:19)\n' +
    '    at async C:\\Users\\user\\Desktop\\application-folder\\node_modules\\next-auth\\next\\index.js:59:32\n' +
    '    at async Object.apiResolver (C:\\Users\\user\\Desktop\\application-folder\\node_modules\\next\\dist\\server\\api-utils\\node.js:366:9)\n' +       
    '    at async DevServer.runApi (C:\\Users\\user\\Desktop\\application-folder\\node_modules\\next\\dist\\server\\next-server.js:481:9)\n' +
    '    at async Object.fn (C:\\Users\\user\\Desktop\\application-folder\\node_modules\\next\\dist\\server\\next-server.js:735:37)\n' +
    '    at async Router.execute (C:\\Users\\user\\Desktop\\application-folder\\node_modules\\next\\dist\\server\\router.js:247:36)',
  name: 'Error'
}
```

**Comment by xmlking** [comment]
I also see similar issue  with `Ping Identity` provider 
When I have only `issuer` ,  authorization params are not used.
I have to provide `token` and `userinfo`  to make authorization params taken. 

```
{
	debug: true,
	id: 'ping',
	name: 'Ping ID',
	type: 'oidc',
	issuer: PING_AUTHORITY,
	authorization: {
		params: { scope: 'profile openid email address phone', acr_values: PING_ACR_VALUES }
	},
	profile(profile) {
		return {
			id: profile.sub,
			name: profile.displayName,
			email: profile.email,
			image: null
		};
	},
	client: {
		token_endpoint_auth_method: 'none',
		id_token_signed_response_alg: 'ES256'
	},
	options: {
		clientId: PING_CLIENT_ID
	},
	style: {
		logo: '/azure.svg',
		logoDark: '/azure-dark.svg',
		bg: '#fff',
		text: '#0072c6',
		bgDark: '#0072c6',
		textDark: '#fff'
	}
}
```

**Comment by elranu** [comment]
@ketanip did you find a soluion?

**Comment by ketanip** [comment]
**Source** : https://stackoverflow.com/a/64800313

**Soulution**:

Basically, you add scope as a general option after the provider array.

import DiscordProvider from "next-auth/providers/discord";
...
providers: [
  DiscordProvider({
    clientId: process.env.DISCORD_CLIENT_ID,
    clientSecret: process.env.DISCORD_CLIENT_SECRET,
    authorization: { params: { scope: 'identify guilds' } },
  })
]
...
