### ISSUE TITLE
Customizing OAuth authorization url redirect_url causes broken flow

### ISSUE THREAD

**Issue by jasonkuhrt** [nextauthjs/next-auth#5733]
### Environment

```
  System:
    OS: macOS 12.6
    CPU: (8) arm64 Apple M1 Pro
    Memory: 101.44 MB / 32.00 GB
    Shell: 3.5.0 - /opt/homebrew/bin/fish
  Binaries:
    Node: 16.17.0 - ~/Library/pnpm/node
    npm: 8.15.0 - ~/Library/pnpm/npm
    Watchman: 2022.10.10.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 107.0.5304.87
    Safari: 16.0
```

### Reproduction URL

N/A

### Describe the issue

When customizing the redirect_url, e.g.:

<img width="440" alt="CleanShot 2022-11-04 at 14 18 13@2x" src="https://user-images.githubusercontent.com/284476/200047429-3b058832-611a-482a-b2ff-379521f911b8.png">

It turns out that later on in the OpenID Client request to fetch a token the redirect_urls array does not honour this. Here is an example of what is logged:

https://github.com/nextauthjs/next-auth/blob/2f3396d376d66c8184eb21e6de694df945304b38/packages/next-auth/src/core/lib/oauth/callback.ts#L110

```ts
{
    authorization_signed_response_alg: 'RS256',
    client_id: 'Iv1.eccde5d79d419a74',
    client_secret: 'a2fb64dd04b57cc4b699d88e21b9ea8fbaa2ca42',
    grant_types: [
      'authorization_code'
    ],
    id_token_signed_response_alg: 'RS256',
    redirect_uris: [
      'http://localhost:3000/api/auth/callback/github'     // <-- problem here
    ],
    response_types: [
      'code'
    ],
    token_endpoint_auth_method: 'client_secret_basic'
  }
```

The result of https://github.com/nextauthjs/next-auth/blob/2f3396d376d66c8184eb21e6de694df945304b38/packages/next-auth/src/core/lib/oauth/callback.ts#L112 is:

```ts
{
  tokens: TokenSet {
    error: 'redirect_uri_mismatch',
    error_description: 'The redirect_uri MUST match the registered callback URL for this application.',
    error_uri: 'https://docs.github.com/apps/managing-oauth-apps/troubleshooting-authorization-request-errors/#redirect-uri-mismatch2'
  }
}
```

But, another issue, it gets swalled up and turned into this incorrect error type/message:

```
[next-auth][error][OAUTH_CALLBACK_ERROR] 
https://next-auth.js.org/errors#oauth_callback_error no access token provided {
  error: TypeError: no access token provided
      at Client.requestResource (/Users/jasonkuhrt/projects/prisma/pdp-control-plane/node_modules/.pnpm/openid-client@5.2.1/node_modules/openid-client/lib/client.js:1123:13)
      at Client.userinfo (/Users/jasonkuhrt/projects/prisma/pdp-control-plane/node_modules/.pnpm/openid-client@5.2.1/node_modules/openid-client/lib/client.js:1235:33)
      at Object.request (/Users/jasonkuhrt/projects/prisma/pdp-control-plane/node_modules/.pnpm/next-auth@4.15.0_azq6kxkn3od7qdylwkyksrwopy/node_modules/next-auth/providers/github.js:27:38)
      at oAuthCallback (/Users/jasonkuhrt/projects/prisma/pdp-control-plane/node_modules/.pnpm/next-auth@4.15.0_azq6kxkn3od7qdylwkyksrwopy/node_modules/next-auth/core/lib/oauth/callback.js:153:41)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async Object.callback (/Users/jasonkuhrt/projects/prisma/pdp-control-plane/node_modules/.pnpm/next-auth@4.15.0_azq6kxkn3od7qdylwkyksrwopy/node_modules/next-auth/core/routes/callback.js:53:11)
      at async NextAuthHandler (/Users/jasonkuhrt/projects/prisma/pdp-control-plane/node_modules/.pnpm/next-auth@4.15.0_azq6kxkn3od7qdylwkyksrwopy/node_modules/next-auth/core/index.js:202:28)
      at async NextAuthNextHandler (/Users/jasonkuhrt/projects/prisma/pdp-control-plane/node_modules/.pnpm/next-auth@4.15.0_azq6kxkn3od7qdylwkyksrwopy/node_modules/next-auth/next/index.js:23:19)
      at async /Users/jasonkuhrt/projects/prisma/pdp-control-plane/node_modules/.pnpm/next-auth@4.15.0_azq6kxkn3od7qdylwkyksrwopy/node_modules/next-auth/next/index.js:60:32
      at async handlerWrapper (webpack-internal:///(api)/./pages/api/auth/[...nextauth].ts:80:9) {
    name: 'OAuthCallbackError',
    code: undefined
  },
  providerId: 'github',
  message: 'no access token provided'
}
```

Now, perhaps `authorization.redirect_url` in provider configuration is ONLY supposed to affect the authorization URL and not the rest of the OAuth flow. But at least for GitHub that is not acceptable for a successful flow. I suspect for other OAuth providers too, hence I put this as a general OAuth bug.

### How to reproduce

Setup GitHub provider and customize the redirect_uri to another server than the current one initiating the flow.

### Expected behavior

That configuring the provider cannot lead to a broken state. That error messages are clear and actionable.

**Comment by balazsorban44** [comment]
Closing as per https://github.com/nextauthjs/next-auth/pull/7038#issuecomment-1482110414

**Comment by hauerm** [comment]
Hi @balazsorban44,

I think this also prevents me from successfully using authjs oauth flow.

Relevant/used infrastructure: Cloudfront (sub.example.com), API-Gateway (api.sub.example.com), Cognito (Hosted-UI: auth.sub.example.com)

When the user/browser initiates the authorization (call to signIn("cognito")) the redirect_uri will be correctly built using the basic app url which is assigend to the Cloudfront CDN. 

But during the auth flow, when Cognito responds with the correct code, the subsequent call to the Cognito token endpoint always uses api.sub.example.com. I tried manipulating this using the params option with no success and I figured out, that always the request url.origin will be used. 

This is invalid because according to oauth spec the redirect_uri used for authorization endpoint and token endpoint must match. So Cognito is stating unauthorized_client because the urls do not match. And currently I cannot influence this behaviour.

Maybe you could suggest a workaround for this problem as it is a showstopper for me.

Nevertheless: Thanks for your and your teams great work!
