### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by alephart** [nextauthjs/next-auth#579]
**Your question**

**getSession()** can be used on server-side, requires **next-auth/client**. Into client.js of next-auth **window** object is checked. However **window** only exists in the **Browser**, so I get the error, **ReferenceError: window is not defined** .... and this is absolutely right.

This response is obtained by the server at build time (in dev and prod):

```
error:

UnhandledPromiseRejectionWarning: ReferenceError: window is not defined
    at /.../node_modules/next-auth/dist/client/index.js:279:69
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/.../node_modules/next-auth/dist/client/index.js:22:103)
    at _next (/.../node_modules/next-auth/dist/client/index.js:24:194)
    at /.../node_modules/next-auth/dist/client/index.js:24:364
    at new Promise (<anonymous>)
    at /.../node_modules/next-auth/dist/client/index.js:24:97
    at signIn (/.../node_modules/next-auth/dist/client/index.js:304:18) ...

```

**What are you trying to do**
I want to be able to get the session of a user from the server side, with the aim of returning data from a database.

**Feedback**
*Documentation **getSession()** Example:

```
import { getSession } from 'next-auth/client'

export default async (req, res) => {
  const session = await getSession({ req })
  if (session) {
    // Signed in
    console.log('Session', JSON.stringify(session, null, 2))
  } else {
    // Not Signed in
    res.status(401)
  }
  res.end()
}
```
* [*] Found the documentation helpful
* [*] Found documentation but was incomplete

Quite possibly the context I want to apply is not correct, I don't know, however using the code according to the example is the error that is obtained.

Any guide on how to correct this?

**Comment by iaincollins** [comment]
Hi there! I'm not sure how you are getting this error, we'd need to have a repo to look at to see what's going on.

The example repo has examples for using getSession in an API route and on a server side rendered page:
https://github.com/nextauthjs/next-auth-example/blob/main/pages/api/examples/session.js
https://github.com/nextauthjs/next-auth-example/blob/main/pages/protected-ssr.js

If signed in to the example site, you can confirm they both work:
https://next-auth-example.now.sh/api/examples/session
https://next-auth-example.now.sh/protected-ssr

I'm not sure what would cause the error you are seeing, perhaps something about the build process.

**Comment by alephart** [comment]
Hi Iain, this examples work perfect! no problem.

I was looking to perform a page redirect, using SignIn() without user action:


```javascript
if (!session) {
     signIn();
     return null;
   }
```
This was calling **window** from the Server ... my mistake, sorry!.

This is more correct:

```javascript
...
if (!session) {return <AccessDenied />}
...
```

And into **AccessDenied** click action to SignIn():

```javascript
...
<button onClick={() => signIn()}>Sign In</button>
...
```


Regards,

**Comment by iaincollins** [comment]
@alephart Thank you for the followup!

There are quite a few situations where this sort of thing trips folks up - it's a tricky area with a library designed to support client and server side rendering with both browser and server based imports  - and I really appreciate the detail as it helps us design behaviour that can help reduce confusing situations like this (e.g. via console warnings or additional conditional checks).

**Comment by chalkplum** [comment]
(node:31160) UnhandledPromiseRejectionWarning: ReferenceError: window is not defined
    at C:\Users\markh\OneDrive\Documents\code\webclients\react\nextjs\tests\firstnextjs\node_modules\next-auth\dist\client\index.js:279:69
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (C:\Users\markh\OneDrive\Documents\code\webclients\react\nextjs\tests\firstnextjs\node_modules\next-auth\dist\client\index.js:22:103)
    at _next (C:\Users\markh\OneDrive\Documents\code\webclients\react\nextjs\tests\firstnextjs\node_modules\next-auth\dist\client\index.js:24:194)
    at C:\Users\markh\OneDrive\Documents\code\webclients\react\nextjs\tests\firstnextjs\node_modules\next-auth\dist\client\index.js:24:364
    at new Promise (<anonymous>)
    at C:\Users\markh\OneDrive\Documents\code\webclients\react\nextjs\tests\firstnextjs\node_modules\next-auth\dist\client\index.js:24:97
    at signIn (C:\Users\markh\OneDrive\Documents\code\webclients\react\nextjs\tests\firstnextjs\node_modules\next-auth\dist\client\index.js:304:18)
    at Home (C:\Users\markh\OneDrive\Documents\code\webclients\react\nextjs\tests\firstnextjs\.next\server\pages\index.js:3858:77)
    at processChild (C:\Users\markh\OneDrive\Documents\code\webclients\react\nextjs\tests\firstnextjs\node_modules\react-dom\cjs\react-dom-server.node.development.js:3043:14)
    at resolve (C:\Users\markh\OneDrive\Documents\code\webclients\react\nextjs\tests\firstnextjs\node_modules\react-dom\cjs\react-dom-server.node.development.js:2960:5)
    at ReactDOMServerRenderer.render (C:\Users\markh\OneDrive\Documents\code\webclients\react\nextjs\tests\firstnextjs\node_modules\react-dom\cjs\react-dom-server.node.development.js:3435:22)
    at ReactDOMServerRenderer.read (C:\Users\markh\OneDrive\Documents\code\webclients\react\nextjs\tests\firstnextjs\node_modules\react-dom\cjs\react-dom-server.node.development.js:3373:29)
    at renderToString (C:\Users\markh\OneDrive\Documents\code\webclients\react\nextjs\tests\firstnextjs\node_modules\react-dom\cjs\react-dom-server.node.development.js:3988:27)
    at Object.renderPage (C:\Users\markh\OneDrive\Documents\code\webclients\react\nextjs\tests\firstnextjs\node_modules\next\dist\next-server\server\render.js:54:851)
    at Function.getInitialProps (C:\Users\markh\OneDrive\Documents\code\webclients\react\nextjs\tests\firstnextjs\.next\server\pages\_document.js:293:19)
(node:31160) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (reje

**Comment by GainorB** [comment]
What is the solution here? I am getting this error in production but not in development.

**Comment by fanto6314** [comment]
same here

**Comment by phaxz10** [comment]
I solved mine by using  `unstable_getServerSession`

**Comment by nsaicharan** [comment]
**Solution 1:** Put your code (`if (!session) { signIn() }` in this case) inside useEffect hook
**Solution 2:** As @alephart hinted above, ensure that the code is triggered only when user took some action

**Comment by razznblue** [comment]
I recently ran into this issue as well and was able to solve it with this working code:
It is similar to the answer by @nsaicharan except I wrapped that statement in a function.
```

const HomePage: NextPage = ({user}: {user: DefaultSession["user"]}) => {
  const { data: session } = useSession()

  const signInUser = () => {
    if (!session) signIn()
  }

  if (session) {
    return <Home user={session.user} />
  }
  return <Login onClick={signInUser} />
}

export default HomePage
```

**Comment by anonymous-dev-30** [comment]
I am working on latest version of next.js ie is 13.4 

I have route called localhost:3000/cart
Inside that i have kept code as following 
```
"use client";
import React from "react";
import { SessionProvider } from "next-auth/react";
import Cart from "@/components/Cart";

export default function CartUI() {
  return (
    <SessionProvider>
      <Cart />
    </SessionProvider>
  );
}
```

and Cart component is written as follows whihc is wrapped within Client Component but still I am getting above error

```
import React from 'react'
import { useSession, signIn, signOut } from 'next-auth/react';

export default function Cart() {
  const { data: session } = useSession();
  console.log("session", session);
  return (
      <div>
          <button onClick={ session ? signOut('google') : signIn('google') }>{ session ? "Log out" : "Log In"}</button>
    </div>
   {/* Other rendering */}
  )
}
```
