### ISSUE TITLE
403 when scope is users.read

### ISSUE THREAD

**Issue by Maskoe** [nextauthjs/next-auth#5838]
### Provider type

Twitter

### Environment

  System:
    OS: Windows 10 10.0.19044
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
    Memory: 43.47 GB / 63.73 GB
  Binaries:
    Node: 16.14.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.3.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (107.0.1418.42)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    next: 13.0.2 => 13.0.2
    next-auth: ^4.16.4 => 4.16.4
    react: 18.2.0 => 18.2.0

### Reproduction URL

I dont have one

### Describe the issue

When using oauth 2 and setting the scope to "users.read", the callback gives back a 403 error.

```
[next-auth][error][OAUTH_CALLBACK_ERROR] 
https://next-auth.js.org/errors#oauth_callback_error expected 200 OK, got: 403 Forbidden {
  error: OPError: expected 200 OK, got: 403 Forbidden
      at processResponse (C:\Users\Mirco\Desktop\authsample\authsample\node_modules\openid-client\lib\helpers\process_response.js:41:11)
      at Client.userinfo (C:\Users\Mirco\Desktop\authsample\authsample\node_modules\openid-client\lib\client.js:1237:18)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async oAuthCallback (C:\Users\Mirco\Desktop\authsample\authsample\node_modules\next-auth\core\lib\oauth\callback.js:149:17)
      at async Object.callback (C:\Users\Mirco\Desktop\authsample\authsample\node_modules\next-auth\core\routes\callback.js:52:11)
      at async NextAuthHandler (C:\Users\Mirco\Desktop\authsample\authsample\node_modules\next-auth\core\index.js:201:28)
      at async NextAuthNextHandler (C:\Users\Mirco\Desktop\authsample\authsample\node_modules\next-auth\next\index.js:23:19)
      at async C:\Users\Mirco\Desktop\authsample\authsample\node_modules\next-auth\next\index.js:59:32
      at async Object.apiResolver (C:\Users\Mirco\Desktop\authsample\authsample\node_modules\next\dist\server\api-utils\node.js:367:9)
      at async DevServer.runApi (C:\Users\Mirco\Desktop\authsample\authsample\node_modules\next\dist\server\next-server.js:474:9) {
    name: 'OAuthCallbackError',
    code: undefined
  },
  providerId: 'twitter',
  message: 'expected 200 OK, got: 403 Forbidden'
}
```

It works jut fine with "users.read tweets.read" or without any custom scope at all.

### How to reproduce

Set up the most basic nextjs and nextauth project and use this config

```
import NextAuth from "next-auth"
import TwitterProvider from "next-auth/providers/twitter"
export const authOptions = {
  // Configure one or more authentication providers
  providers: [
    TwitterProvider({
        clientId: "myid",
        clientSecret: "mysecret",
        version: "2.0", // opt-in to Twitter OAuth 2.0
        authorization: {
            params: {
              scope: "users.read", // "users.read tweets.read" works
            },
          },
      }),
    // ...add more providers here
  ],
  session: {
    strategy: "jwt",
  },
}
export default NextAuth(authOptions)
```

### Expected behavior

auth works

**Comment by Hasham-dev** [comment]
@Maskoe Just have a question because I'm implementing the same thing.
Are you getting oath_token or just access_token after authorization?

**Comment by ThangHuuVu** [comment]
Hi, this is not a bug because `tweet.read` is required by the userinfo endpoint: 
https://github.com/nextauthjs/next-auth/blob/a91b40512bf4ebcc474af6a11a658ead2cf5aaf3/packages/next-auth/src/providers/twitter.ts#L205

https://developer.twitter.com/en/docs/twitter-api/users/lookup/api-reference/get-users-me
