### ISSUE TITLE
Not working when deploy the AWS Amplify

### ISSUE THREAD

**Issue by zluo01** [nextauthjs/next-auth#5864]
### Question 💬

Having problem to make NextAuth work when deploy to AWS Amplify.

With Auth0 as provider, I will get following exception

```
|2022-11-20T17:15:23.858-08:00 | [next-auth][error][OAUTH_CALLBACK_ERROR]
| 2022-11-20T17:15:23.858-08:00 | https://next-auth.js.org/errors#oauth_callback_error invalid_request (Parameter 'code_verifier' is required) {
| 2022-11-20T17:15:23.858-08:00 | error: OPError: invalid_request (Parameter 'code_verifier' is required)
| 2022-11-20T17:15:23.858-08:00 | at processResponse (/var/task/node_modules/openid-client/lib/helpers/process_response.js:38:13)
| 2022-11-20T17:15:23.858-08:00 | at Client.grant (/var/task/node_modules/openid-client/lib/client.js:1327:22)
| 2022-11-20T17:15:23.858-08:00 | at processTicksAndRejections (node:internal/process/task_queues:96:5)
| 2022-11-20T17:15:23.858-08:00 | at async Client.callback (/var/task/node_modules/openid-client/lib/client.js:476:24)
| 2022-11-20T17:15:23.858-08:00 | at async oAuthCallback (/var/task/node_modules/next-auth/core/lib/oauth/callback.js:127:16)
| 2022-11-20T17:15:23.858-08:00 | at async Object.callback (/var/task/node_modules/next-auth/core/routes/callback.js:52:11)
| 2022-11-20T17:15:23.858-08:00 | at async NextAuthHandler (/var/task/node_modules/next-auth/core/index.js:201:28)
| 2022-11-20T17:15:23.858-08:00 | at async NextAuthNextHandler (/var/task/node_modules/next-auth/next/index.js:23:19)
| 2022-11-20T17:15:23.858-08:00 | at async /var/task/node_modules/next-auth/next/index.js:59:32
| 2022-11-20T17:15:23.858-08:00 | at async Object.apiResolver (/var/task/node_modules/next/dist/server/api-utils/node.js:367:9) {
| 2022-11-20T17:15:23.858-08:00 | name: 'OAuthCallbackError',
| 2022-11-20T17:15:23.858-08:00 | code: undefined
| 2022-11-20T17:15:23.858-08:00 | },
| 2022-11-20T17:15:23.858-08:00 | providerId: 'auth0',
| 2022-11-20T17:15:23.858-08:00 | message: "invalid_request (Parameter 'code_verifier' is required)"
| 2022-11-20T17:15:23.858-08:00 | }
```

When I am using Cognito, I can see profile data in cloudwatch but on frontend, all methods does not get any value.

Setting:
```
providers: [
        Auth0Provider({
            clientId: process.env.AUTH0_ID,
            clientSecret: process.env.AUTH0_SECRET,
            issuer: process.env.AUTH0_ISSUER,
            idToken: true,
            authorization: {
                params: {
                    audience: process.env.AUTH0_AUDIENCE,
                    scope: "openid email profile",
                },
            }
        }),
        CognitoProvider({
            clientId: process.env.COGNITO_CLIENT_ID as string,
            clientSecret: process.env.COGNITO_CLIENT_SECRET as string,
            issuer: process.env.COGNITO_CLIENT_ISSUER,
            authorization: {
                params: {
                    audience: process.env.AUTH0_AUDIENCE,
                },
            }
        })
    ],
    debug:true,
    callbacks: {
        async jwt({token, account }) {
            if (account?.access_token) {
                return {...token, access_token: account?.access_token}
            }
            return token
        },
    },
```

Want to ask if NextAuth support AWS amplify or there is some switch I need to turn.

Thanks.

### How to reproduce ☕️

Simple add these two provider to the sample package https://github.com/nextauthjs/next-auth-example/ and deploy the AWS amply through web console.

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by zluo01** [comment]
Also, I usually will get nounce mismatch when I try to log in using Cognito the first time. Click the login button to redirect to Cognito again can successfully login.

**Comment by Hasham-dev** [comment]
@zluo01 How you checking the server console on AWS ?
