### ISSUE TITLE
next-auth with google provider and prisma; vercel deployment fails

### ISSUE THREAD

**Issue by I-keep-trying** [nextauthjs/next-auth#5944]
### Environment

"next": "13.0.3",
"next-auth": "^4.16.4",
"@next-auth/prisma-adapter": "^1.0.5",
"@prisma/client": "^4.6.1",
"react": "18.2.0"
Node v18.12.1
Windows 
Chrome

### Reproduction URL

https://next-demo-brown-one.vercel.app/

### Describe the issue

Apologies if this is not a bug, lmk if I need to move this to discussions or whatever.

I can successfully sign in with google auth locally, but published app returns `500 Internal Server Error`, `CLIENT_FETCH_ERROR`.

NOTE: `localhost` is setting cookies (next-auth.callback-url and next-auth.csrf-token) immediately upon initial render, before I even log in, but published `vercel.app` never sets any cookies. This is obviously a big problem, but I have no idea why it is happening.

So, I'm not even sure if this is a vercel/next problem or a Prisma problem.

YES my environment variables are all set correctly in vercel settings, and yes, I have set the NEXTAUTH_URL value to the correct one (not localhost).

Error from vercel deployment log: 
```
2022-12-02T19:46:57.887Z	ae0576a2-26b5-4c47-a455-dd760b3cd6d1	ERROR	Error: @prisma/client did not initialize yet. Please run "prisma generate" and try to import it again.
In case this error is unexpected for you, please report it in https://github.com/prisma/prisma/issues
    at new PrismaClient (/var/task/node_modules/.prisma/client/index.js:3:11)
    at 4118 (/var/task/.next/server/pages/api/auth/[...nextauth].js:33:14)
    at __webpack_require__ (/var/task/.next/server/webpack-api-runtime.js:25:42)
    at __webpack_exec__ (/var/task/.next/server/pages/api/auth/[...nextauth].js:68:39)
    at /var/task/.next/server/pages/api/auth/[...nextauth].js:69:28
    at Object.<anonymous> (/var/task/.next/server/pages/api/auth/[...nextauth].js:72:3)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
RequestId: ae0576a2-26b5-4c47-a455-dd760b3cd6d1 Error: Runtime exited with error: exit status 1
Runtime.ExitError
```

Error in devtools console:
```
https://next-auth.js.org/errors#client_fetch_error
{
    "error": {
        "message": "Unexpected token '<', \"<!DOCTYPE \"... is not valid JSON",
        "stack": "SyntaxError: Unexpected token '<', \"<!DOCTYPE \"... is not valid JSON",
        "name": "SyntaxError"
    },
    "url": "/api/auth/session",
    "message": "Unexpected token '<', \"<!DOCTYPE \"... is not valid JSON",
    "client": true
}
```

What next-auth.js.org (link from console) says about this error: 
"CLIENT_FETCH_ERROR
If you see CLIENT_FETCH_ERROR make sure you have configured the NEXTAUTH_URL environment variable."

Like I said, MY CONFIG IS CORRECT ALREADY .

NEXTAUTH_URL environment variable value: https://next-demo-brown-one.vercel.app

Also, I have verified that my settings in Google Cloud Platform include the published url in "Authorized JavaScript origins" and "Authorized redirect URIs".

nextauth config file:
```js
//pages/api/auth/[...nextauth].js
export default NextAuth({
  adapter: PrismaAdapter(prisma),
  providers: [
    GoogleProvider({
      clientId: process.env.GOOGLE_CLIENT_ID,
      clientSecret: process.env.GOOGLE_CLIENT_SECRET,
    }),
  ],
  callbacks: {
    async session({ session, token, user }) {
      session.user.id = user.id
      return session
    },
  },
})
```

One other observation, `http://localhost:3000/api/auth/providers` returns 200 on localhost, but 500 on `https://next-demo-brown-one.vercel.app/api/auth/providers`. 

repo: https://github.com/I-keep-trying/next-demo

### How to reproduce

Clone [my repo](https://github.com/I-keep-trying/next-demo) and run it locally with your own environment variable values. You should be able to log in with your google account. 

Publish that same repo with vercel by connecting your github account, setting environment variables, and it should fail to set cookies or let you log in. 

### Expected behavior

Published app should set cookies and authenticate, same as locally running app.

**Comment by I-keep-trying** [comment]
I think I have resolved this. 

The error message from next-auth 

> "If you see CLIENT_FETCH_ERROR make sure you have configured the NEXTAUTH_URL environment variable." 

was a little misleading, because it does not mention `NEXTAUTH_SECRET`, and wouldn't you know, that's the one thing I overlooked in my Vercel settings. I added it, and my published app works now (for Google auth, haven't tried any others yet). It works even _without_ the `NEXTAUTH_URL` variable.
