### ISSUE TITLE
QueryFailedError: relation "accounts" does not exist

### ISSUE THREAD

**Issue by s-kris** [nextauthjs/next-auth#619]
**Describe the bug**
QueryFailedError: relation "accounts" does not exist is thrown after successful signin even though it exists. (Created the schema as mentioned here: https://next-auth.js.org/schemas/postgres)

**Steps to reproduce**
1. Clone next starter "with-next-auth"
2. Setup facebook/google keys, jwt and postgres.
3. Create schema from https://next-auth.js.org/schemas/postgres.
4. Run the project.
5. Try to login with social accounts.
6. Upon redirection from social website to localhost:3000, `[next-auth][error][get_user_by_provider_account_id_error] QueryFailedError: relation "accounts" does not exist` is thrown in terminal.
**Expected behavior**
1. User clicks sign with social account.
2. Redirect to social website
3. Signin successful and callback.
4. Show signin success

**Screenshots or error logs**
```
[next-auth][debug][typeorm_get_user_by_provider_account_id] [ 'facebook', 'XXXXXXXXXXXX' ]

[next-auth][error][get_user_by_provider_account_id_error] QueryFailedError: relation "accounts" does not exist
    at new QueryFailedError (/Users/xxxxxxx/xxxxxx/xxxxxxxxxx/node_modules/typeorm/error/QueryFailedError.js:11:28)
    at Query.callback (/Users/xxxxxxx/xxxxxx/xxxxxxxxxx/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:176:38)
    at Query.handleError (/Users/xxxxxxx/xxxxxx/xxxxxxxxxx/node_modules/pg/lib/query.js:139:19)
    at Client._handleErrorMessage (/Users/xxxxxxx/xxxxxx/xxxxxxxxxx/node_modules/pg/lib/client.js:326:17)
    at Connection.emit (events.js:315:20)
    at /Users/xxxxxxx/xxxxxx/xxxxxxxxxx/node_modules/pg/lib/connection.js:109:12
    at Parser.parse (/Users/xxxxxxx/xxxxxx/xxxxxxxxxx/node_modules/pg-protocol/dist/parser.js:40:17)
    at Socket.<anonymous> (/Users/xxxxxxx/xxxxxx/xxxxxxxxxx/node_modules/pg-protocol/dist/index.js:8:42)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:302:12) {
  length: 108,
  severity: 'ERROR',
  code: '42P01',
  detail: undefined,
  hint: undefined,
  position: '576',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '1194',
  routine: 'parserOpenTable',
  query: 'SELECT "Account"."id" AS "Account_id", "Account"."compound_id" AS "Account_compound_id", "Account"."user_id" AS "Account_user_id", "Account"."provider_type" AS "Account_provider_type", "Account"."provider_id" AS "Account_provider_id", "Account"."provider_account_id" AS "Account_provider_account_id", "Account"."refresh_token" AS "Account_refresh_token", "Account"."access_token" AS "Account_access_token", "Account"."access_token_expires" AS "Account_access_token_expires", "Account"."created_at" AS "Account_created_at", "Account"."updated_at" AS "Account_updated_at" FROM "accounts" "Account" WHERE "Account"."provider_id" = $1 AND "Account"."provider_account_id" = $2 LIMIT 1',
  parameters: [ 'facebook', 'xxxxxxxxxxxxx' ]
}

https://next-auth.js.org/errors#get_user_by_provider_account_id_error

[next-auth][error][oauth_callback_handler_error] Error: GET_USER_BY_PROVIDER_ACCOUNT_ID_ERROR
    at /Users/xxxxxxx/xxxxxx/xxxxxxxxxx/node_modules/next-auth/dist/adapters/typeorm/index.js:224:35
    at Generator.throw (<anonymous>)
    at asyncGeneratorStep (/Users/xxxxxxx/xxxxxx/xxxxxxxxxx/node_modules/next-auth/dist/adapters/typeorm/index.js:28:103)
    at _throw (/Users/xxxxxxx/xxxxxx/xxxxxxxxxx/node_modules/next-auth/dist/adapters/typeorm/index.js:30:291)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

https://next-auth.js.org/errors#oauth_callback_handler_error
```

**Feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [x] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [x] Could not find relevant documentation
* [x] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by s-kris** [comment]
I'm stupid. There was a typo in postgres url. 
Again, I'm stupid.
