### ISSUE TITLE
developer app throws errors if auth0 not configured

### ISSUE THREAD

**Issue by 1337cookie** [nextauthjs/next-auth#6211]
### Environment

  System:
    OS: Windows 10 10.0.19041
    CPU: (8) x64 Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
    Memory: 15.93 GB / 31.96 GB
  Binaries:
    Node: 16.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.18 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.5.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 96.0.4664.110
    Edge: Spartan (44.19041.964.0), Chromium (108.0.1462.54)
    Internet Explorer: 11.0.19041.1
    
    (actually using dev chrome 110)

### Reproduction URL

https://github.com/nextauthjs/next-auth

### Describe the issue

Cloning this repo and following the contributing steps to setup the developer app/server results in errors when trying to load the sign in page. 

Removing auth0 from .env.local doesn't help but adding auth0 details everything works as expected.

![image](https://user-images.githubusercontent.com/15826769/209744503-415c4f0d-b4a6-4038-9781-2805057705bb.png)

The following is the console output: 

```
InvalidEndpoints: Provider "auth0" is missing both `issuer` and `authorization` endpoint config. At least one of them is required.
    at assertConfig (webpack-internal:///(middleware)/../../packages/core/lib/assert.js:55:24)
    at Auth (webpack-internal:///(middleware)/../../packages/core/index.js:75:89)
[auth][error][InvalidEndpoints]: Read more at https://errors.authjs.dev#invalidendpoints
UnknownAction: Cannot detect action.
    at toInternalRequest (webpack-internal:///(middleware)/../../packages/core/lib/web.js:42:19)
    at Auth (webpack-internal:///(middleware)/../../packages/core/index.js:70:97)
    at Object.AuthHandler.args.<computed>.secret [as handler] (webpack-internal:///(middleware)/./pages/api/auth/[...nextauth].ts:260:68)
    at adapter (webpack-internal:///(middleware)/../../node_modules/.pnpm/next@13.1.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/server/web/adapter.js:112:33)
    at __WEBPACK_DEFAULT_EXPORT__ (webpack-internal:///(middleware)/../../node_modules/.pnpm/next@13.1.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/build/webpack/loaders/next-edge-function-loader.js?absolutePagePath=C%3A%5CUsers%5CROOT%5CDocuments%5Cdev%5Cnext-auth%5Capps%5Cdev%5Cpages%5Capi%5Cauth%5C%5B...nextauth%5D.ts&page=%2Fapi%2Fauth%2F%5B...nextauth%5D&rootDir=C%3A%5CUsers%5CROOT%5CDocuments%5Cdev%5Cnext-auth%5Capps%5Cdev!:19:91)
    at C:\Users\ROOT\Documents\dev\next-auth\node_modules\.pnpm\next@13.1.1_biqbaboplfbrettd7655fr4n2y\node_modules\next\dist\server\web\sandbox\sandbox.js:73:30
    at async DevServer.runEdgeFunction (C:\Users\ROOT\Documents\dev\next-auth\node_modules\.pnpm\next@13.1.1_biqbaboplfbrettd7655fr4n2y\node_modules\next\dist\server\next-server.js:1411:24)   
    at async DevServer.runApi (C:\Users\ROOT\Documents\dev\next-auth\node_modules\.pnpm\next@13.1.1_biqbaboplfbrettd7655fr4n2y\node_modules\next\dist\server\next-server.js:467:47)
    at async Object.fn (C:\Users\ROOT\Documents\dev\next-auth\node_modules\.pnpm\next@13.1.1_biqbaboplfbrettd7655fr4n2y\node_modules\next\dist\server\next-server.js:749:37)
    at async Router.execute (C:\Users\ROOT\Documents\dev\next-auth\node_modules\.pnpm\next@13.1.1_biqbaboplfbrettd7655fr4n2y\node_modules\next\dist\server\router.js:253:36)
[auth][error][UnknownAction]: Read more at https://errors.authjs.dev#unknownaction
InvalidEndpoints: Provider "auth0" is missing both `issuer` and `authorization` endpoint config. At least one of them is required.
    at assertConfig (webpack-internal:///(middleware)/../../packages/core/lib/assert.js:55:24)
    at Auth (webpack-internal:///(middleware)/../../packages/core/index.js:75:89)
[auth][error][InvalidEndpoints]: Read more at https://errors.authjs.dev#invalidendpoints
UnknownAction: Cannot detect action.
    at toInternalRequest (webpack-internal:///(middleware)/../../packages/core/lib/web.js:42:19)
    at Auth (webpack-internal:///(middleware)/../../packages/core/index.js:70:97)
    at Object.AuthHandler.args.<computed>.secret [as handler] (webpack-internal:///(middleware)/./pages/api/auth/[...nextauth].ts:260:68)
    at adapter (webpack-internal:///(middleware)/../../node_modules/.pnpm/next@13.1.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/server/web/adapter.js:112:33)
    at __WEBPACK_DEFAULT_EXPORT__ (webpack-internal:///(middleware)/../../node_modules/.pnpm/next@13.1.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/build/webpack/loaders/next-edge-function-loader.js?absolutePagePath=C%3A%5CUsers%5CROOT%5CDocuments%5Cdev%5Cnext-auth%5Capps%5Cdev%5Cpages%5Capi%5Cauth%5C%5B...nextauth%5D.ts&page=%2Fapi%2Fauth%2F%5B...nextauth%5D&rootDir=C%3A%5CUsers%5CROOT%5CDocuments%5Cdev%5Cnext-auth%5Capps%5Cdev!:19:91)
    at C:\Users\ROOT\Documents\dev\next-auth\node_modules\.pnpm\next@13.1.1_biqbaboplfbrettd7655fr4n2y\node_modules\next\dist\server\web\sandbox\sandbox.js:73:30
    at async DevServer.runEdgeFunction (C:\Users\ROOT\Documents\dev\next-auth\node_modules\.pnpm\next@13.1.1_biqbaboplfbrettd7655fr4n2y\node_modules\next\dist\server\next-server.js:1411:24)   
    at async DevServer.runApi (C:\Users\ROOT\Documents\dev\next-auth\node_modules\.pnpm\next@13.1.1_biqbaboplfbrettd7655fr4n2y\node_modules\next\dist\server\next-server.js:467:47)
    at async Object.fn (C:\Users\ROOT\Documents\dev\next-auth\node_modules\.pnpm\next@13.1.1_biqbaboplfbrettd7655fr4n2y\node_modules\next\dist\server\next-server.js:749:37)
    at async Router.execute (C:\Users\ROOT\Documents\dev\next-auth\node_modules\.pnpm\next@13.1.1_biqbaboplfbrettd7655fr4n2y\node_modules\next\dist\server\router.js:253:36)
[auth][error][UnknownAction]: Read more at https://errors.authjs.dev#unknownaction
InvalidEndpoints: Provider "auth0" is missing both `issuer` and `authorization` endpoint config. At least one of them is required.
    at assertConfig (webpack-internal:///(middleware)/../../packages/core/lib/assert.js:55:24)
    at Auth (webpack-internal:///(middleware)/../../packages/core/index.js:75:89)
[auth][error][InvalidEndpoints]: Read more at https://errors.authjs.dev#invalidendpoints
UnknownAction: Cannot detect action.
    at toInternalRequest (webpack-internal:///(middleware)/../../packages/core/lib/web.js:42:19)
    at Auth (webpack-internal:///(middleware)/../../packages/core/index.js:70:97)
    at Object.AuthHandler.args.<computed>.secret [as handler] (webpack-internal:///(middleware)/./pages/api/auth/[...nextauth].ts:260:68)
    at adapter (webpack-internal:///(middleware)/../../node_modules/.pnpm/next@13.1.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/server/web/adapter.js:112:33)
    at __WEBPACK_DEFAULT_EXPORT__ (webpack-internal:///(middleware)/../../node_modules/.pnpm/next@13.1.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/build/webpack/loaders/next-edge-function-loader.js?absolutePagePath=C%3A%5CUsers%5CROOT%5CDocuments%5Cdev%5Cnext-auth%5Capps%5Cdev%5Cpages%5Capi%5Cauth%5C%5B...nextauth%5D.ts&page=%2Fapi%2Fauth%2F%5B...nextauth%5D&rootDir=C%3A%5CUsers%5CROOT%5CDocuments%5Cdev%5Cnext-auth%5Capps%5Cdev!:19:91)
    at C:\Users\ROOT\Documents\dev\next-auth\node_modules\.pnpm\next@13.1.1_biqbaboplfbrettd7655fr4n2y\node_modules\next\dist\server\web\sandbox\sandbox.js:73:30
    at async DevServer.runEdgeFunction (C:\Users\ROOT\Documents\dev\next-auth\node_modules\.pnpm\next@13.1.1_biqbaboplfbrettd7655fr4n2y\node_modules\next\dist\server\next-server.js:1411:24)   
    at async DevServer.runApi (C:\Users\ROOT\Documents\dev\next-auth\node_modules\.pnpm\next@13.1.1_biqbaboplfbrettd7655fr4n2y\node_modules\next\dist\server\next-server.js:467:47)
    at async Object.fn (C:\Users\ROOT\Documents\dev\next-auth\node_modules\.pnpm\next@13.1.1_biqbaboplfbrettd7655fr4n2y\node_modules\next\dist\server\next-server.js:749:37)
    at async Router.execute (C:\Users\ROOT\Documents\dev\next-auth\node_modules\.pnpm\next@13.1.1_biqbaboplfbrettd7655fr4n2y\node_modules\next\dist\server\router.js:253:36)
[auth][error][UnknownAction]: Read more at https://errors.authjs.dev#unknownaction
InvalidEndpoints: Provider "auth0" is missing both `issuer` and `authorization` endpoint config. At least one of them is required.
    at assertConfig (webpack-internal:///(middleware)/../../packages/core/lib/assert.js:55:24)
    at Auth (webpack-internal:///(middleware)/../../packages/core/index.js:75:89)
[auth][error][InvalidEndpoints]: Read more at https://errors.authjs.dev#invalidendpoints
InvalidEndpoints: Provider "auth0" is missing both `issuer` and `authorization` endpoint config. At least one of them is required.
    at assertConfig (webpack-internal:///(middleware)/../../packages/core/lib/assert.js:55:24)
    at Auth (webpack-internal:///(middleware)/../../packages/core/index.js:75:89)
[auth][error][InvalidEndpoints]: Read more at https://errors.authjs.dev#invalidendpoints
UnknownAction: Cannot detect action.
    at toInternalRequest (webpack-internal:///(middleware)/../../packages/core/lib/web.js:42:19)
    at Auth (webpack-internal:///(middleware)/../../packages/core/index.js:70:97)
    at Object.AuthHandler.args.<computed>.secret [as handler] (webpack-internal:///(middleware)/./pages/api/auth/[...nextauth].ts:260:68)
    at adapter (webpack-internal:///(middleware)/../../node_modules/.pnpm/next@13.1.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/server/web/adapter.js:112:33)
    at __WEBPACK_DEFAULT_EXPORT__ (webpack-internal:///(middleware)/../../node_modules/.pnpm/next@13.1.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/build/webpack/loaders/next-edge-function-loader.js?absolutePagePath=C%3A%5CUsers%5CROOT%5CDocuments%5Cdev%5Cnext-auth%5Capps%5Cdev%5Cpages%5Capi%5Cauth%5C%5B...nextauth%5D.ts&page=%2Fapi%2Fauth%2F%5B...nextauth%5D&rootDir=C%3A%5CUsers%5CROOT%5CDocuments%5Cdev%5Cnext-auth%5Capps%5Cdev!:19:91)
    at C:\Users\ROOT\Documents\dev\next-auth\node_modules\.pnpm\next@13.1.1_biqbaboplfbrettd7655fr4n2y\node_modules\next\dist\server\web\sandbox\sandbox.js:73:30
    at async DevServer.runEdgeFunction (C:\Users\ROOT\Documents\dev\next-auth\node_modules\.pnpm\next@13.1.1_biqbaboplfbrettd7655fr4n2y\node_modules\next\dist\server\next-server.js:1411:24)   
    at async DevServer.runApi (C:\Users\ROOT\Documents\dev\next-auth\node_modules\.pnpm\next@13.1.1_biqbaboplfbrettd7655fr4n2y\node_modules\next\dist\server\next-server.js:467:47)
    at async Object.fn (C:\Users\ROOT\Documents\dev\next-auth\node_modules\.pnpm\next@13.1.1_biqbaboplfbrettd7655fr4n2y\node_modules\next\dist\server\next-server.js:749:37)
    at async Router.execute (C:\Users\ROOT\Documents\dev\next-auth\node_modules\.pnpm\next@13.1.1_biqbaboplfbrettd7655fr4n2y\node_modules\next\dist\server\router.js:253:36)
[auth][error][UnknownAction]: Read more at https://errors.authjs.dev#unknownaction
```

### How to reproduce

Clone repo with empty apps/dev/.env.local
Open developer app page (eg localhost:3000) and click `Sign in`.

### Expected behavior

No errors out of box from specific providers.

**Comment by balazsorban44** [comment]
you can comment out providers you haven't configured.
