### ISSUE TITLE
@auth/sveltekit error when using EmailProvider

### ISSUE THREAD

**Issue by vvvv-ops** [nextauthjs/next-auth#6222]
### Environment

  System:
    OS: macOS 12.5
    CPU: (10) arm64 Apple M1 Max
    Memory: 102.73 MB / 64.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.12.1 - /opt/homebrew/opt/node@18/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.2 - /opt/homebrew/opt/node@18/bin/npm
  Browsers:
    Chrome: 108.0.5359.124
    Safari: 15.6

### Reproduction URL

https://hyperviolet.io

### Describe the issue

CallbackRouteError: getAdapterUserFromEmail is not defined
    at Module.callback (file:///Users/vvvv/code/hyperviolet/node_modules/@auth/sveltekit/node_modules/@auth/core/lib/routes/callback.js:242:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async AuthInternal (file:///Users/vvvv/code/hyperviolet/node_modules/@auth/sveltekit/node_modules/@auth/core/lib/index.js:52:38)
    at async Proxy.Auth (file:///Users/vvvv/code/hyperviolet/node_modules/@auth/sveltekit/node_modules/@auth/core/index.js:95:30)
    at async respond (file:///Users/vvvv/code/hyperviolet/node_modules/@sveltejs/kit/src/runtime/server/index.js:229:20)
    at async file:///Users/vvvv/code/hyperviolet/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:444:22
[auth][error][CallbackRouteError]: Read more at https://errors.authjs.dev#callbackrouteerror
{
  "provider": "email"
}

### How to reproduce

Click sign-up -> Enter an email -> Click magic link -> CallbackRouteError

User is deleted from my adaptor during error

### Expected behavior

User should be signed in, and not have an error.

**Comment by balazsorban44** [comment]
We cannot recreate the issue with the provided information. **Please add a reproduction in order for us to be able to investigate.**

### **Why was this issue marked with the `incomplete` label?**

To be able to investigate, we need access to a reproduction to identify what triggered the issue. We prefer a link to a public GitHub repository ([template](https://github.com/nextauthjs/next-auth-example)), but you can also use a tool like [CodeSandbox](https://codesandbox.io/s/github/nextauthjs/next-auth-example/tree/main) or [StackBlitz](https://stackblitz.com/fork/github/nextauthjs/next-auth-example).

To make sure the issue is resolved as quickly as possible, please make sure that the reproduction is as **minimal** as possible. This means that you should **remove unnecessary code, files, and dependencies** that do not contribute to the issue.

Please test your reproduction against the latest version of NextAuth.js (`next-auth@latest`) to make sure your issue has not already been fixed.

### **I added a link, why was it still marked?**

Ensure the link is pointing to a codebase that is accessible (e.g. not a private repository). "[example.com](http://example.com/)", "n/a", "will add later", etc. are not acceptable links -- we need to see a public codebase. See the above section for accepted links.

### **What happens if I don't provide a sufficient minimal reproduction?**

Issues with the `incomplete` label that receives no meaningful activity (e.g. new comments with a reproduction link) are automatically closed and locked after 30 days.

If your issue has _not_ been resolved in that time and it has been closed/locked, please open a new issue with the required reproduction.

### **I did not open this issue, but it is relevant to me, what can I do to help?**

Anyone experiencing the same issue is welcome to provide a minimal reproduction following the above steps. Furthermore, you can upvote the issue using the :+1: reaction on the topmost comment (please **do not** comment "I have the same issue" without repro steps). Then, we can sort issues by votes to prioritize.

### **I think my reproduction is good enough, why aren't you looking into it quicker?**

We look into every NextAuth.js issue and constantly monitor open issues for new comments.

However, sometimes we might miss one or two. We apologize, and kindly ask you to refrain from tagging core maintainers, as that will usually not result in increased priority.

Upvoting issues to show your interest will help us prioritize and address them as quickly as possible. That said, every issue is important to us, and if an issue gets closed by accident, we encourage you to open a new one linking to the old issue and we will look into it.

### **Useful Resources**

- [How to create a Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve)
- [Reporting a NextAuth.js bug](https://github.com/nextauthjs/next-auth/blob/main/.github/ISSUE_TEMPLATE/1_bug_framework.yml)
- [How to Contribute to Open Source (Next.js)](https://www.youtube.com/watch?v=cuoNzXFLitc)

**Comment by vvvv-ops** [comment]
Email verification requires a database, so unless you'd like me to setup a complete stack for reproduction this is relatively complete and reproducible.

Also I'm certain this is directly related to recent changes in auth flow.

**Comment by balazsorban44** [comment]
might be related to #6226
