### ISSUE TITLE
authorization params without authorization.url  caused  **Invalid URL** Error 

### ISSUE THREAD

**Issue by xmlking** [nextauthjs/next-auth#6273]
### Environment

  System:
    OS: macOS 12.6.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 709.08 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.3.0 - ~/homebrew/bin/node
    npm: 9.2.0 - ~/homebrew/bin/npm
  Browsers:
    Chrome: 108.0.5359.124
    Safari: 16.2

### Reproduction URL

https://github.com/nextauthjs/next-auth-example

### Describe the issue

When I tested using latest commit code, with below provider config: getting **Invalid URL** Error.

As per documentation here: https://authjs.dev/guides/providers/custom-provider We should able to provide only `scopes` without `authorization` URL

<img width="999" alt="image" src="https://user-images.githubusercontent.com/627951/210480803-a46ce2e9-3698-4854-afac-51226cfb3b3a.png">

```
export const authjs = SvelteKitAuth({
	providers: [
		Google({
			clientId: GOOGLE_ID,
			clientSecret: GOOGLE_SECRET,
			authorization: { params: { prompt: 'consent' } }
		}),
		AzureAD({
			clientId: AZURE_AD_CLIENT_ID,
			clientSecret: AZURE_AD_CLIENT_SECRET,
			tenantId: AZURE_AD_TENANT_ID,
			authorization: { params: { scope: 'openid profile User.Read email' } }
		}),
		GitHub({ clientId: GITHUB_ID, clientSecret: GITHUB_SECRET }),
	],
}) satisfies Handle;
```

```log
{ params: { prompt: 'consent' } } https://accounts.google.com
Invalid URL
TypeError [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:400:5)
    at URL.onParseError (node:internal/url:565:9)
    at new URL (node:internal/url:645:5)
    at normalizeEndpoint (file:///Users/schinth/Developer/Work/SPA/hc360-ui/node_modules/.pnpm/@auth+core@0.2.4_imrjv3lrakgdw4vcvjnhhwyrze/node_modules/@auth/core/lib/providers.js:64:17)
    at normalizeOAuth (file:///Users/schinth/Developer/Work/SPA/hc360-ui/node_modules/.pnpm/@auth+core@0.2.4_imrjv3lrakgdw4vcvjnhhwyrze/node_modules/@auth/core/lib/providers.js:30:27)
    at file:///Users/schinth/Developer/Work/SPA/hc360-ui/node_modules/.pnpm/@auth+core@0.2.4_imrjv3lrakgdw4vcvjnhhwyrze/node_modules/@auth/core/lib/providers.js:16:20
    at Array.map (<anonymous>)
    at parseProviders (file:///Users/schinth/Developer/Work/SPA/hc360-ui/node_modules/.pnpm/@auth+core@0.2.4_imrjv3lrakgdw4vcvjnhhwyrze/node_modules/@auth/core/lib/providers.js:8:40)
    at init (file:///Users/schinth/Developer/Work/SPA/hc360-ui/node_modules/.pnpm/@auth+core@0.2.4_imrjv3lrakgdw4vcvjnhhwyrze/node_modules/@auth/core/lib/init.js:16:37)
    at AuthInternal (file:///Users/schinth/Developer/Work/SPA/hc360-ui/node_modules/.pnpm/@auth+core@0.2.4_imrjv3lrakgdw4vcvjnhhwyrze/node_modules/@auth/core/lib/index.js:8:40)
    at Proxy.Auth (file:///Users/schinth/Developer/Work/SPA/hc360-ui/node_modules/.pnpm/@auth+core@0.2.4_imrjv3lrakgdw4vcvjnhhwyrze/node_modules/@auth/core/index.js:95:36)
    at async getSession (/node_modules/.pnpm/@auth+sveltekit@0.1.11_f5fzfhbe3oooig6fzl5vkyl5v4/node_modules/@auth/sveltekit/index.js:88:22)
    at async guard (/Users/schinth/Developer/Work/SPA/hc360-ui/src/lib/server/middleware/guard.ts:21:9)
    at async respond (file:///Users/schinth/Developer/Work/SPA/hc360-ui/node_modules/.pnpm/@sveltejs+kit@1.0.1_svelte@3.55.0+vite@4.0.3/node_modules/@sveltejs/kit/src/runtime/server/index.js:229:20)
    at async file:///Users/schinth/Developer/Work/SPA/hc360-ui/node_modules/.pnpm/@sveltejs+kit@1.0.1_svelte@3.55.0+vite@4.0.3/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:444:22
```

### How to reproduce

Set Google provider with some `params`, e.g., 
```
export const authjs = SvelteKitAuth({
	providers: [
		Google({
			clientId: GOOGLE_ID,
			clientSecret: GOOGLE_SECRET,
			authorization: { params: { prompt: 'consent' } }
		})
	],
}) satisfies Handle;
```

### Expected behavior

Should able to Override default options with minimal custom options like :
```ts
authorization: { params: { scope: 'openid profile User.Read email' } }
```
or 
 ```ts
authorization: { params: { prompt: 'consent' } }
```

**Comment by balazsorban44** [comment]
Thanks for reporting, I saw #6244 but it seemed to be unfinished. The reason for this was that internally I only wanted to pass around an `URL` instance, but it wasn't done when there was no base url to attach the params to. I worked around it by having a fallback URL that we check against in the proper places to prefer the issuer in those cases. https://github.com/nextauthjs/next-auth/commit/01bb91612ae67c71f07ba1fbb61b927354292a1f
