### ISSUE TITLE
metadata.findEmbeddedWithPropertyPath is not a function

### ISSUE THREAD

**Issue by dimabolgov** [nextauthjs/next-auth#6319]
### Environment

  System:
    OS: macOS 13.0.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 76.16 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.20.0 - ~/.nvm/versions/node/v14.20.0/bin/node
    npm: 6.14.17 - ~/.nvm/versions/node/v14.20.0/bin/npm
  Browsers:
    Chrome: 108.0.5359.124
    Firefox Developer Edition: 109.0
    Safari: 16.1
  npmPackages:
    next: latest => 13.0.4
    next-auth: ^4.17.0 => 4.17.0
    react: ^18.2.0 => 18.2.0

### Reproduction URL

no URL

### Describe the issue

I'm using ```unstable_getServerSession``` function and MariaDB as session storage  in the NextJs API pages like that:

/pages/api/posts/index.js
```
import { unstable_getServerSession } from "next-auth/next";
import { authOptions } from "./../auth/[...nextauth]";

export default async function apiPosts(req, res) {
    const session = await unstable_getServerSession(req, res, authOptions);
    if (!session) {
        res.status(401).json({ error: "Unauthorized" });
        return;
    }
    
    // other code
}
```

And my auth file looks like that:
pages/api/auth/[...nextauth].js

```
import NextAuth from "next-auth";
import GithubProvider from "next-auth/providers/github";
import { TypeORMLegacyAdapter } from "@next-auth/typeorm-legacy-adapter";

let db = {
    type: "mariadb",
    host: "127.0.0.1",
    port: 3306,
    username: "",
    password: "",
    database: "",
    logging: true,
    synchronize: true,
}

export const authOptions = {
    adapter: TypeORMLegacyAdapter(
        db,
      ),
    // Configure one or more authentication providers
    providers: [
        GithubProvider({
            clientId: process.env.GITHUB_ID,
            clientSecret: process.env.GITHUB_SECRET,
        }),
        // ...add more providers here
    ],
    theme: {
        colorScheme: "ligth", // "auto" | "dark" | "light"
        brandColor: "", // Hex color code
        logo: "http://localhost:3000/images/coding-event.jpg", // Absolute URL to image
        buttonText: "", // Hex color code
    },
    // We use this callback only to pass a user ID to the sessions
    callbacks: {
        session: async (sessionData) => {
            sessionData.session.user.id = sessionData.user.id
            return Promise.resolve(sessionData.session)
        }
    },
    session: {
        strategy: "database",
        maxAge: 30 * 24 * 60 * 60, // 30 days
        updateAge: 24 * 60 * 60, // 24 hours
      }
};

export default NextAuth(authOptions);
```

And in general, it works well. But for some reason, if I don't click on a website for a few minutes and then refresh the page, ```unstable_getServerSession``` returns null with an error:

```
Session Error

event - compiled successfully in 35 ms (105 modules)
event - compiled successfully (106 modules)
[next-auth][warn][adapter_typeorm_updating_entities]
https://next-auth.js.org/warnings#adapter_typeorm_updating_entities
[next-auth][error][adapter_error_getSessionAndUser]
https://next-auth.js.org/errors#adapter_error_getsessionanduser metadata.findEmbeddedWithPropertyPath is not a function {
  message: 'metadata.findEmbeddedWithPropertyPath is not a function',
  stack: 'TypeError: metadata.findEmbeddedWithPropertyPath is not a function\n' +
    '    at /Users/user1/dev/user2/projectname-nextjs-docker/node_modules/typeorm/query-builder/SelectQueryBuilder.js:2140:36\n' +
    '    at Array.forEach (<anonymous>)\n' +
    '    at SelectQueryBuilder.buildRelations (/Users/user1/dev/user2/projectname-nextjs-docker/node_modules/typeorm/query-builder/SelectQueryBuilder.js:2135:32)\n' +
    '    at SelectQueryBuilder.applyFindOptions (/Users/user1/dev/user2/projectname-nextjs-docker/node_modules/typeorm/query-builder/SelectQueryBuilder.js:1651:22)\n' +
    '    at SelectQueryBuilder.setFindOptions (/Users/user1/dev/user2/projectname-nextjs-docker/node_modules/typeorm/query-builder/SelectQueryBuilder.js:69:14)\n' +
    '    at EntityManager.findOne (/Users/user1/dev/user2/projectname-nextjs-docker/node_modules/typeorm/entity-manager/EntityManager.js:544:14)\n' +
    '    at getSessionAndUser (/Users/user1/dev/user2/projectname-nextjs-docker/node_modules/@next-auth/typeorm-legacy-adapter/dist/index.js:131:44)\n' +
    '    at processTicksAndRejections (internal/process/task_queues.js:95:5)',
  name: 'TypeError'
}
[next-auth][error][SESSION_ERROR]
https://next-auth.js.org/errors#session_error metadata.findEmbeddedWithPropertyPath is not a function TypeError: metadata.findEmbeddedWithPropertyPath is not a function
    at /Users/user1/dev/user2/projectname-nextjs-docker/node_modules/typeorm/query-builder/SelectQueryBuilder.js:2140:36
    at Array.forEach (<anonymous>)
    at SelectQueryBuilder.buildRelations (/Users/user1/dev/user2/projectname-nextjs-docker/node_modules/typeorm/query-builder/SelectQueryBuilder.js:2135:32)
    at SelectQueryBuilder.applyFindOptions (/Users/user1/dev/user2/projectname-nextjs-docker/node_modules/typeorm/query-builder/SelectQueryBuilder.js:1651:22)
    at SelectQueryBuilder.setFindOptions (/Users/user1/dev/user2/projectname-nextjs-docker/node_modules/typeorm/query-builder/SelectQueryBuilder.js:69:14)
    at EntityManager.findOne (/Users/user1/dev/user2/projectname-nextjs-docker/node_modules/typeorm/entity-manager/EntityManager.js:544:14)
    at getSessionAndUser (/Users/user1/dev/user2/projectname-nextjs-docker/node_modules/@next-auth/typeorm-legacy-adapter/dist/index.js:131:44)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  name: 'GetSessionAndUserError',
  code: undefined
}
```

But if I refresh the page, it works well again. ```sessionToken``` id the same for both requests.

Any ideas on how to fix that?

Thank you!

### How to reproduce

See ```Describe the issue```

### Expected behavior

```unstable_getServerSession``` function should return session data.

**Comment by testvinder** [comment]
@dimabolgov Did you ever find a solution for this issue?

**Comment by mariokaram** [comment]
@dimabolgov  how did you solve it ?
