### ISSUE TITLE
Fetch doesn't work with node v18 and credentials provider

### ISSUE THREAD

**Issue by eucciferri** [nextauthjs/next-auth#6361]
### Provider type

Credentials

### Environment

```
  System:
    OS: macOS 13.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 65.31 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.13.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.3 - /usr/local/bin/npm
  Browsers:
    Chrome: 109.0.5414.87
    Firefox: 108.0.1
    Safari: 16.2
  npmPackages:
    next: 13.1.1 => 13.1.1
    next-auth: ^4.18.8 => 4.18.8
    react: 18.2.0 => 18.2.0
```

### Reproduction URL

N/A

### Describe the issue

When you try to use fetch with an external url (from other backend, eg. https://localhost:1337 not :3000) to validate user's credentials and node v18 there's an error, but if you use node v16, there's no problem at all.

```
TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:14062:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.authorize (webpack-internal:///(api)/./pages/api/auth/[...nextauth].ts:37:33)
    at async Object.callback (/Users/eucciferri/Development/labs/next-auth/node_modules/.pnpm/next-auth@4.18.8_q76c2b4vyoegvsbrcwkfvimnai/node_modules/next-auth/core/routes/callback.js:360:14)
    at async AuthHandler (/Users/eucciferri/Development/labs/next-auth/node_modules/.pnpm/next-auth@4.18.8_q76c2b4vyoegvsbrcwkfvimnai/node_modules/next-auth/core/index.js:295:28)
    at async NextAuthHandler (/Users/eucciferri/Development/labs/next-auth/node_modules/.pnpm/next-auth@4.18.8_q76c2b4vyoegvsbrcwkfvimnai/node_modules/next-auth/next/index.js:23:19)
    at async /Users/eucciferri/Development/labs/next-auth/node_modules/.pnpm/next-auth@4.18.8_q76c2b4vyoegvsbrcwkfvimnai/node_modules/next-auth/next/index.js:59:32
    at async Object.apiResolver (/Users/eucciferri/Development/labs/next-auth/node_modules/.pnpm/next@13.1.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/api-utils/node.js:363:9)
    at async DevServer.runApi (/Users/eucciferri/Development/labs/next-auth/node_modules/.pnpm/next@13.1.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/next-server.js:487:9)
    at async Object.fn (/Users/eucciferri/Development/labs/next-auth/node_modules/.pnpm/next@13.1.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/next-server.js:749:37)
    at async Router.execute (/Users/eucciferri/Development/labs/next-auth/node_modules/.pnpm/next@13.1.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/router.js:253:36)
    at async DevServer.run (/Users/eucciferri/Development/labs/next-auth/node_modules/.pnpm/next@13.1.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/base-server.js:384:29)
    at async DevServer.run (/Users/eucciferri/Development/labs/next-auth/node_modules/.pnpm/next@13.1.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/dev/next-dev-server.js:741:20)
    at async DevServer.handleRequest (/Users/eucciferri/Development/labs/next-auth/node_modules/.pnpm/next@13.1.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/base-server.js:322:20) {
  cause: Error: connect ECONNREFUSED ::1:1337
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1487:16) {
    errno: -61,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '::1',
    port: 1337
  }
}
```

### How to reproduce

```
export default NextAuth({
  // ---------------------------------------------------------------------------
  // Providers 👇
  // ---------------------------------------------------------------------------
  providers: [
    Credentials({
      name: 'Credentials',
      credentials: {
        email: {
          label: 'Email',
          type: 'email',
          placeholder: 'email@example.com',
        },
        password: {
          label: 'Password',
          type: 'password',
          placeholder: 'Password',
        },
      },
      async authorize(credentials) {
        if (!credentials?.email || !credentials?.password) return null;

        try {
          // Sign-in user
          const res = await fetch(`http://localhost:1337/api/users/login`, {
            method: 'POST',
            body: JSON.stringify({
              email: credentials.email,
              password: credentials.password,
            }),
            headers: { 'Content-Type': 'application/json' },
          });

          const data: AuthApiResponse = await res.json();
          if (!data) throw new Error('Error getting user data from server!');

          return data;

          // Error
        } catch (err) {
          console.error(err);
          throw new Error(`${err}`);
        }
      },
    }),
  ],

  // ---------------------------------------------------------------------------
  // Custom pages 👇
  // ---------------------------------------------------------------------------
  pages: {
    error: '/auth/login',
    signIn: '/auth/login',
    newUser: '/auth/register',
  },

  // ---------------------------------------------------------------------------
  // Callbacks 👇
  // ---------------------------------------------------------------------------
  callbacks: {
    session({ session, token, user }) {
      return session; // The return type will match the one returned in `useSession()`
    },
  },
});
```

### Expected behavior

Fetch should work to validate user and password and then get user's data with credentials provider.

**Comment by eucciferri** [comment]
I figured out that it's a problem of nodejs!
https://github.com/nodejs/undici/issues/1248

**Comment by Andeveling** [comment]
Hello, I have the same problem since I upgraded node from v16 to v18, were you able to fix the problem?

**Comment by eucciferri** [comment]
Hi @Andeveling, yes I was able to fix it doing this: https://github.com/nodejs/node/issues/46167#issuecomment-1379121059
