### ISSUE TITLE
Next Auth is throwing TypeError Invalid URL at build time in the gitlab pipelines right after => info - Collecting page data...

### ISSUE THREAD

**Issue by netdesignr** [nextauthjs/next-auth#6479]
### Environment

System:
    OS: macOS 12.6
    CPU: (8) x64 Apple M1
    Memory: 86.33 MB / 16.00 GB
    Shell: 3.2.57 - /bin/sh

  Binaries:
    Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm

  npmPackages:
    next: ^11.1.0 => 11.1.0
    next-auth: 4.5.0 => 4.5.0
    react: ^17.0.2 => 17.0.2

### Reproduction URL

https://unavailable.com

### Describe the issue

Hi,

I wonder if anyone ever get this error:
javascript TypeError [ERR_INVALID_URL]: Invalid URL

I've started seeing this after I've upgraded NextAuth to v4 due to issues around cookie size limit. In version 4 there's cookie chunk implementation which is great. The issue now is that although everything works fine on local env in the Gitlab pipeline it fails right before providing the page reports and finalising the build.

Unfortunately upgrading to next v12 and above won't work because of the Webpack 4 as it's not supported anymore in newer version. Upgrading to Webpack 5 it's bringing issues with the collocated test files etc. The application will be upgraded but incrementally and for now I would like to know if there's any way we can have a more verbose debug logging because 
javascript TypeError [ERR_INVALID_URL]: Invalid URL
 it doesn't help at all. 

To mention that NEXTAUTH_SECRET was added to the project during next-auth v4 upgrade.

Anyone can step in and provide some info on how this can be debugged further more?

Thanks a lot! 

### How to reproduce

This error only happens in the Gitlab pipelines and I can't seem to think an easy way to reproduce it nor I can't seem to get more details around the error as it's very vague.

### Expected behavior

Should allow to successfully build the project

**Comment by netgfx** [comment]
I have the same issue with github actions
```
Error occurred prerendering page "/login". Read more: https://nextjs.org/docs/messages/prerender-error
TypeError [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:387:5)
    at URL.onParseError (node:internal/url:565:9)
    at new URL (node:internal/url:641:5)
    at parseUrl (/home/runner/work/frontend-app/frontend-app/relivable-admin/relivable-admin/.next/server/chunks/8107.js:1370:16)
    at Object.63370 (/home/runner/work/frontend-app/frontend-app/relivable-admin/relivable-admin/.next/server/chunks/8107.js:621:34)
    at __webpack_require__ (/home/runner/work/frontend-app/frontend-app/relivable-admin/relivable-admin/.next/server/webpack-runtime.js:25:43)
    at Module.3512 (/home/runner/work/frontend-app/frontend-app/relivable-admin/relivable-admin/.next/server/app/login/page.js:291:73)
    at __webpack_require__ (/home/runner/work/frontend-app/frontend-app/relivable-admin/relivable-admin/.next/server/webpack-runtime.js:25:43)
    at O (/home/runner/work/frontend-app/frontend-app/relivable-admin/relivable-admin/node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-client.edge.production.min.js:23:142)
    at ia (/home/runner/work/frontend-app/frontend-app/relivable-admin/relivable-admin/node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-client.edge.production.min.js:27:301)
TypeError [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:387:5)
    at URL.onParseError (node:internal/url:565:9)
    at new URL (node:internal/url:641:5)
    at parseUrl (/home/runner/work/frontend-app/frontend-app/relivable-admin/relivable-admin/.next/server/chunks/8107.js:1370:16)
    at Object.63370 (/home/runner/work/frontend-app/frontend-app/relivable-admin/relivable-admin/.next/server/chunks/8107.js:621:34)
    at __webpack_require__ (/home/runner/work/frontend-app/frontend-app/relivable-admin/relivable-admin/.next/server/webpack-runtime.js:25:43)
    at Module.45829 (/home/runner/work/frontend-app/frontend-app/relivable-admin/relivable-admin/.next/server/chunks/3837.js:69:13)
    at __webpack_require__ (/home/runner/work/frontend-app/frontend-app/relivable-admin/relivable-admin/.next/server/webpack-runtime.js:25:43)
    at O (/home/runner/work/frontend-app/frontend-app/relivable-admin/relivable-admin/node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-client.edge.production.min.js:23:142)
    at da (/home/runner/work/frontend-app/frontend-app/relivable-admin/relivable-admin/node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-client.edge.production.min.js:20:89) {
  input: '',
  code: 'ERR_INVALID_URL'
}
```
Those issues shouldn't be closed

**Comment by bfg-coding** [comment]
I am getting a similar issue when I try to build using docker compose

`"next-auth": "^4.24.7"`

```log
29.31    Collecting page data ...
29.93 TypeError: Invalid URL
29.93     at new URL (node:internal/url:796:36)
29.93     at t.default (/app/.next/server/chunks/676.js:30:25816)
29.93     at 12653 (/app/.next/server/chunks/653.js:1:7825)
29.93     at t (/app/.next/server/webpack-runtime.js:1:128)
29.93     at 48847 (/app/.next/server/app/auth/login/page.js:1:2313)
29.93     at t (/app/.next/server/webpack-runtime.js:1:128)
29.93     at 76565 (/app/.next/server/app/auth/login/page.js:1:1288)
29.93     at t (/app/.next/server/webpack-runtime.js:1:128)
29.93     at t (/app/.next/server/app/auth/login/page.js:1:2721)
29.93     at /app/.next/server/app/auth/login/page.js:1:2771 {
29.93   code: 'ERR_INVALID_URL',
29.93   input: ''
29.93 }
29.93
29.93 > Build error occurred
29.94 Error: Failed to collect page data for /auth/login
29.94     at /app/node_modules/.pnpm/next@14.2.3_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/build/utils.js:1268:15
29.94     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
29.94   type: 'Error'
29.94 }
29.98  ELIFECYCLE  Command failed with exit code 1.
```

**Comment by VladBo** [comment]
In my case it was `NEXTAUTH_URL_INTERNAL` env variable that was missing in docker image
