### ISSUE TITLE
Error: No valid exports main found for '…/node_modules/preact'

### ISSUE THREAD

**Issue by maxnowack** [nextauthjs/next-auth#657]
Hey, I'm getting the following exception if I try to run the [example](https://github.com/nextauthjs/next-auth-example).

````
Error: No valid exports main found for '/Users/maxnowack/code/next-auth-example/node_modules/preact'
    at resolveExportsTarget (internal/modules/cjs/loader.js:618:9)
    at applyExports (internal/modules/cjs/loader.js:499:14)
    at resolveExports (internal/modules/cjs/loader.js:548:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:650:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:948:27)
    at Function.Module._load (internal/modules/cjs/loader.js:854:27)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/maxnowack/code/next-auth-example/node_modules/next-auth/dist/server/pages/signin.js:8:15)
    at Module._compile (internal/modules/cjs/loader.js:1128:30) {
  code: 'MODULE_NOT_FOUND'
}
````

I'm not sure if it's related to `next-auth`, `nextjs` or `preact`, but since the example is broken, I think this is the right place to open an issue.

**Comment by iaincollins** [comment]
Hi

* The example project deployed at https://next-auth-example.now.sh is working.
* We have Build Tests for Node.js 10.x, 12.x, and 14.x and they are passing.
* We have Integration Tests for OAuth 1 and OAuth 2 flows and they are passing.
* I'm not able to replicate this issue with the example project.
  I just cloned it and ran `npm i && npm run build && npm start` and it works.


Please use the issue template as requested we can understand how you are getting this error and help you.

We are probably going to need an example of how to replicate this issue to understand what is going on.

**Comment by maxnowack** [comment]
I got it. I was using an old node version (`v13.3.0`). I've upgraded to `v14.x.x` and now it's working 🙂 
Thanks!
