### ISSUE TITLE
google OAuthCallbackError signin?error=OAuthCallback

### ISSUE THREAD

**Issue by MR-Khaleghi** [nextauthjs/next-auth#6572]
### Environment

```
System:
    OS: Windows 10 10.0.15063
    CPU: (4) x64 Intel(R) Core(TM) i3-3240 CPU @ 3.40GHz
    Memory: 1.40 GB / 5.88 GB
  Binaries:
    Node: 16.16.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
  Chrome Version 107.0.5304.88 
---------------------------- 

"next": "13.1.6",
    "next-auth": "^4.19.0",
    "react": "18.2.0",

Windows10
```

### Reproduction URL

https://github.com/MR-Khaleghi/ChatApp-Next-TS

### Describe the issue

I am adding next-auth with google provider to my next.js project in developement mode, but I am geeting this error on the browser URL : http://localhost:3000/api/auth/signin?error=OAuthCallback evev when trying signing in with a different account message on the screen. and after signing in with signIn('google') everytime the following error appears in my terminal in vscode:

```
[next-auth][warn][NEXTAUTH_URL]
https://next-auth.js.org/warnings#nextauth_url
data unauthenticated
[next-auth][error][OAUTH_CALLBACK_ERROR]
https://next-auth.js.org/errors#oauth_callback_error JWT expired, now 1675094480, exp 1675094221 {
  error: RPError: JWT expired, now 1675094480, exp 1675094221
      at Client.validateJWT (D:\React_prj\ChatApp\frontend\node_modules\openid-client\lib\client.js:956:15)
      at Client.validateIdToken (D:\React_prj\ChatApp\frontend\node_modules\openid-client\lib\client.js:745:60)
      at Client.callback (D:\React_prj\ChatApp\frontend\node_modules\openid-client\lib\client.js:488:18)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async oAuthCallback (D:\React_prj\ChatApp\frontend\node_modules\next-auth\core\lib\oauth\callback.js:129:16)
      at async Object.callback (D:\React_prj\ChatApp\frontend\node_modules\next-auth\core\routes\callback.js:52:11)
      at async AuthHandler (D:\React_prj\ChatApp\frontend\node_modules\next-auth\core\index.js:201:28)
      at async NextAuthHandler (D:\React_prj\ChatApp\frontend\node_modules\next-auth\next\index.js:24:19)
      at async D:\React_prj\ChatApp\frontend\node_modules\next-auth\next\index.js:60:32
      at async Object.apiResolver (D:\React_prj\ChatApp\frontend\node_modules\next\dist\server\api-utils\node.js:372:9)      at async DevServer.runApi (D:\React_prj\ChatApp\frontend\node_modules\next\dist\server\next-server.js:488:9)
      at async Object.fn (D:\React_prj\ChatApp\frontend\node_modules\next\dist\server\next-server.js:751:37)
      at async Router.execute (D:\React_prj\ChatApp\frontend\node_modules\next\dist\server\router.js:253:36)
      at async DevServer.run (D:\React_prj\ChatApp\frontend\node_modules\next\dist\server\base-server.js:384:29)
      at async DevServer.run (D:\React_prj\ChatApp\frontend\node_modules\next\dist\server\dev\next-dev-server.js:743:20)
      at async DevServer.handleRequest (D:\React_prj\ChatApp\frontend\node_modules\next\dist\server\base-server.js:322:20) {
    name: 'OAuthCallbackError',
    code: undefined
  },
  providerId: 'google',
  message: 'JWT expired, now 1675094480, exp 1675094221'
}
```

everytime on the browser I see the following image (Try signing in with a different account.)even trying with another account I 

![](https://i.stack.imgur.com/kAL1I.jpg)

also, I use prisma as the adapter as well

the following are my codes:

[...nextauth].ts

```
import NextAuth from 'next-auth';
import GoogleProvider from 'next-auth/providers/google';
import { PrismaAdapter } from '@next-auth/prisma-adapter';
import prisma from '../../../lib/prismadb';

export default NextAuth({
  adapter: PrismaAdapter(prisma),
  providers: [
    GoogleProvider({
      clientId: process.env.GOOGLE_CLIENT_ID as string,
      clientSecret: process.env.GOOGLE_CLIENT_SECRET as string,
    }),
  ],
});
```

prismadb.ts
```
import { PrismaClient } from '@prisma/client';
declare global {
  var prisma: PrismaClient | undefined;
}
const client = globalThis.prisma || new PrismaClient();
if (process.env.NODE_ENV !== 'production') globalThis.prisma = client;
export default client;
```
and .env.local
```
GOOGLE_CLIENT_ID=46255473************od0rt849b.apps.googleusercontent.com
GOOGLE_CLIENT_SECRET=GOCSPX-*************I7SNBuJ6
MONGODB_URI =mongodb://localhost/chatapp
```

I tried many othersolution provided on the google and other providers but I cannot fix this issue. please help thx

### How to reproduce

I run in development and use http://localhost:3000/ as the server. and I use the configurations mentioned in https://next-auth.js.org/providers/google

### Expected behavior

I use thgis code `<Button onClick={() => signIn('google')}>Sign In</Button>` to sign in and I expect to have a successful login and get back user information in `{data}` by using 
```
const session = useSession();
  const { data } = session;
```

**Comment by balazsorban44** [comment]
I think this has nothing to do with Prisma.

It sounds like something is skewing the clock on your machine and the dev server will think the `id_token` from Google has already expired.

We tolerate a max of 10 seconds skewing https://github.com/nextauthjs/next-auth/blob/5b1555ed97883ee49dbccbdb3a25b006b235d104/packages/next-auth/src/core/lib/oauth/client.ts#L44

I suggest you look into why the clock is off on your computer.

**Comment by yabusila** [comment]
In my experience this happens when your computer is in an invalid timezone. I got this error once and solve it instantly by correcting date and time settings
