### ISSUE TITLE
Doesn't work with IdentityServer4Provider blazor _Host landing page redirection?

### ISSUE THREAD

**Issue by khteh** [nextauthjs/next-auth#6692]
### Environment

```
  System:
    OS: Linux 5.19 Ubuntu 22.10 22.10 (Kinetic Kudu)
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i9-11950H @ 2.60GHz
    Memory: 51.70 GB / 70.39 GB
    Container: Yes
    Shell: 5.2.2 - /bin/bash
  Binaries:
    Node: 19.6.0 - /usr/local/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 9.4.2 - /usr/local/bin/npm
  Browsers:
    Chrome: 110.0.5481.77
    Firefox: 109.0.1
```

### Reproduction URL

http://localhost:3000

### Describe the issue

I use ASP.Net Core 7 IdentityServer with server-side blazor. I have a landing page, `_Host` which redirects the `next-auth` client to respective page depending on whether the current use is already logged in. Here is the `next-auth` config:
```
{
    "SECRET": "mysecret",
    "NEXTAUTH_URL": "http://localhost:3000",
    "IdentityServer4_Issuer": "https://iam.kyberlife.io",
    "IdentityServer4_CLIENT_ID": "buyerportal",
    "IdentityServer4_CLIENT_SECRET": "anything"
}
```
`https://aspnetcoreidentity.com` will redirect to `/Identity/Account/Login` if the user is not logged in. However, the `next-auth` client doesn't successfully land at the landing page at all. Here is the console log of `yarn start`:
```
https://next-auth.js.org/errors#signin_oauth_error expected 200 OK, got: 302 Found {
  error: {
    message: 'expected 200 OK, got: 302 Found',
    stack: 'OPError: expected 200 OK, got: 302 Found\n' +
      '    at processResponse (/usr/src/next-auth-example/node_modules/openid-client/lib/helpers/process_response.js:41:11)\n' +
      '    at Issuer.discover (/usr/src/next-auth-example/node_modules/openid-client/lib/issuer.js:152:20)\n' +
      '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
      '    at async openidClient (/usr/src/next-auth-example/node_modules/next-auth/core/lib/oauth/client.js:16:14)\n' +
      '    at async getAuthorizationUrl (/usr/src/next-auth-example/node_modules/next-auth/core/lib/oauth/authorization-url.js:70:18)\n' +
      '    at async Object.signin (/usr/src/next-auth-example/node_modules/next-auth/core/routes/signin.js:38:24)\n' +
      '    at async AuthHandler (/usr/src/next-auth-example/node_modules/next-auth/core/index.js:253:26)\n' +
      '    at async NextAuthHandler (/usr/src/next-auth-example/node_modules/next-auth/next/index.js:24:19)\n' +
      '    at async /usr/src/next-auth-example/node_modules/next-auth/next/index.js:60:32\n' +
      '    at async Object.apiResolver (/usr/src/next-auth-example/node_modules/next/dist/server/api-utils/node.js:372:9)',
    name: 'OPError'
  },
  providerId: 'client123',
  message: 'expected 200 OK, got: 302 Found'
}
```

### How to reproduce

Use the sample app with the following config:
```
{
    "SECRET": "mysecret",
    "NEXTAUTH_URL": "http://localhost:3000",
    "IdentityServer4_Issuer": "https://iam.kyberlife.io",
    "IdentityServer4_CLIENT_ID": "buyerportal",
    "IdentityServer4_CLIENT_SECRET": "anything"
}
```
and add/use `IdentityServer4Provider` provider.

### Expected behavior

Should be able to land at the `https://iam.kyberlife.io` login page.

**Comment by balazsorban44** [comment]
I am unfortunately unfamiliar with .NET, but I can tell you that IDS4 has reached end-of-life, so it's likely a bad choice anyway, as it does not get security patches anymore. See: 

https://identityserver4.readthedocs.io/en/latest/

https://next-auth.js.org/providers/identity-server4
