### ISSUE TITLE
Prisma adapter is not working with the KakaoProvider due to additional properties

### ISSUE THREAD

**Issue by mjy9088** [nextauthjs/next-auth#6708]
### Adapter type

@next-auth/prisma-adapter

### Environment

```
  System:
    OS: macOS 13.1
    CPU: (8) arm64 Apple M1
    Memory: 56.77 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.5.0 - /opt/homebrew/bin/node
    npm: 9.3.1 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 109.0.5414.119
    Firefox: 109.0.1
    Firefox Developer Edition: 107.0
    Safari: 16.2

```

### Reproduction URL

https://github.com/my-trash-bin/230213

### Describe the issue

- It looks like Kakao is sending extra properties.
- Prisma doesn't accept extra properties.

log:
```
[next-auth][error][adapter_error_linkAccount] 
https://next-auth.js.org/errors#adapter_error_linkaccount 
Invalid `p.account.create()` invocation in
/Users/mjy/workspace/web-draft/node_modules/@next-auth/prisma-adapter/dist/index.js:19:42

  16 },
  17 updateUser: ({ id, ...data }) => p.user.update({ where: { id }, data }),
  18 deleteUser: (id) => p.user.delete({ where: { id } }),
→ 19 linkAccount: (data) => p.account.create({
       data: {
         provider: 'kakao',
         type: 'oauth',
         providerAccountId: '1824062441',
         access_token: 'epwSkGiu1DTvR5f_E__a2jubqUmHhjCJU3phOgr3Cj1ymAAAAYZIvkRP',
         token_type: 'bearer',
         refresh_token: '6vM6jA-B3OHXVIMdSmQsRbCzdtU4nkbSS7GZtr6SCj1ymAAAAYZIvkRN',
         expires_at: 1676279273,
         refresh_token_expires_in: 5183999,
         ~~~~~~~~~~~~~~~~~~~~~~~~
         userId: 'cle28jfj90000suezuhpc8qxj'
       }
     })

Unknown arg `refresh_token_expires_in` in data.refresh_token_expires_in for type AccountUncheckedCreateInput. Available args:

type AccountUncheckedCreateInput {
  id?: String
  userId: String
  type: String
  provider: String
  providerAccountId: String
  refresh_token?: String | Null
  access_token?: String | Null
  expires_at?: Int | Null
  token_type?: String | Null
  scope?: String | Null
  id_token?: String | Null
  session_state?: String | Null
}

 {
  message: '\n' +
    'Invalid `p.account.create()` invocation in\n' +
    '/Users/mjy/workspace/web-draft/node_modules/@next-auth/prisma-adapter/dist/index.js:19:42\n' +
    '\n' +
    '  16 },\n' +
    '  17 updateUser: ({ id, ...data }) => p.user.update({ where: { id }, data }),\n' +
    '  18 deleteUser: (id) => p.user.delete({ where: { id } }),\n' +
    '→ 19 linkAccount: (data) => p.account.create({\n' +
    '       data: {\n' +
    "         provider: 'kakao',\n" +
    "         type: 'oauth',\n" +
    "         providerAccountId: '1824062441',\n" +
    "         access_token: 'epwSkGiu1DTvR5f_E__a2jubqUmHhjCJU3phOgr3Cj1ymAAAAYZIvkRP',\n" +
    "         token_type: 'bearer',\n" +
    "         refresh_token: '6vM6jA-B3OHXVIMdSmQsRbCzdtU4nkbSS7GZtr6SCj1ymAAAAYZIvkRN',\n" +
    '         expires_at: 1676279273,\n' +
    '         refresh_token_expires_in: 5183999,\n' +
    '         ~~~~~~~~~~~~~~~~~~~~~~~~\n' +
    "         userId: 'cle28jfj90000suezuhpc8qxj'\n" +
    '       }\n' +
    '     })\n' +
    '\n' +
    'Unknown arg `refresh_token_expires_in` in data.refresh_token_expires_in for type AccountUncheckedCreateInput. Available args:\n' +
    '\n' +
    'type AccountUncheckedCreateInput {\n' +
    '  id?: String\n' +
    '  userId: String\n' +
    '  type: String\n' +
    '  provider: String\n' +
    '  providerAccountId: String\n' +
    '  refresh_token?: String | Null\n' +
    '  access_token?: String | Null\n' +
    '  expires_at?: Int | Null\n' +
    '  token_type?: String | Null\n' +
    '  scope?: String | Null\n' +
    '  id_token?: String | Null\n' +
    '  session_state?: String | Null\n' +
    '}\n' +
    '\n',
  stack: 'Error: \n' +
    'Invalid `p.account.create()` invocation in\n' +
    '/Users/mjy/workspace/web-draft/node_modules/@next-auth/prisma-adapter/dist/index.js:19:42\n' +
    '\n' +
    '  16 },\n' +
    '  17 updateUser: ({ id, ...data }) => p.user.update({ where: { id }, data }),\n' +
    '  18 deleteUser: (id) => p.user.delete({ where: { id } }),\n' +
    '→ 19 linkAccount: (data) => p.account.create({\n' +
    '       data: {\n' +
    "         provider: 'kakao',\n" +
    "         type: 'oauth',\n" +
    "         providerAccountId: '1824062441',\n" +
    "         access_token: 'epwSkGiu1DTvR5f_E__a2jubqUmHhjCJU3phOgr3Cj1ymAAAAYZIvkRP',\n" +
    "         token_type: 'bearer',\n" +
    "         refresh_token: '6vM6jA-B3OHXVIMdSmQsRbCzdtU4nkbSS7GZtr6SCj1ymAAAAYZIvkRN',\n" +
    '         expires_at: 1676279273,\n' +
    '         refresh_token_expires_in: 5183999,\n' +
    '         ~~~~~~~~~~~~~~~~~~~~~~~~\n' +
    "         userId: 'cle28jfj90000suezuhpc8qxj'\n" +
    '       }\n' +
    '     })\n' +
    '\n' +
    'Unknown arg `refresh_token_expires_in` in data.refresh_token_expires_in for type AccountUncheckedCreateInput. Available args:\n' +
    '\n' +
    'type AccountUncheckedCreateInput {\n' +
    '  id?: String\n' +
    '  userId: String\n' +
    '  type: String\n' +
    '  provider: String\n' +
    '  providerAccountId: String\n' +
    '  refresh_token?: String | Null\n' +
    '  access_token?: String | Null\n' +
    '  expires_at?: Int | Null\n' +
    '  token_type?: String | Null\n' +
    '  scope?: String | Null\n' +
    '  id_token?: String | Null\n' +
    '  session_state?: String | Null\n' +
    '}\n' +
    '\n' +
    '\n' +
    '    at Yn.validate (/Users/mjy/workspace/web-draft/node_modules/@prisma/client/runtime/library.js:148:91)\n' +
    '    at Ur.createMessage (/Users/mjy/workspace/web-draft/node_modules/@prisma/client/runtime/library.js:163:13577)\n' +
    '    at /Users/mjy/workspace/web-draft/node_modules/@prisma/client/runtime/library.js:173:10192\n' +
    '    at runInChildSpan (/Users/mjy/workspace/web-draft/node_modules/@prisma/client/runtime/library.js:70:25749)\n' +
    '    at t._executeRequest (/Users/mjy/workspace/web-draft/node_modules/@prisma/client/runtime/library.js:173:10181)',
  name: 'Error'
}
[next-auth][error][OAUTH_CALLBACK_HANDLER_ERROR] 
https://next-auth.js.org/errors#oauth_callback_handler_error 
Invalid `p.account.create()` invocation in
/Users/mjy/workspace/web-draft/node_modules/@next-auth/prisma-adapter/dist/index.js:19:42

  16 },
  17 updateUser: ({ id, ...data }) => p.user.update({ where: { id }, data }),
  18 deleteUser: (id) => p.user.delete({ where: { id } }),
→ 19 linkAccount: (data) => p.account.create({
       data: {
         provider: 'kakao',
         type: 'oauth',
         providerAccountId: '1824062441',
         access_token: 'epwSkGiu1DTvR5f_E__a2jubqUmHhjCJU3phOgr3Cj1ymAAAAYZIvkRP',
         token_type: 'bearer',
         refresh_token: '6vM6jA-B3OHXVIMdSmQsRbCzdtU4nkbSS7GZtr6SCj1ymAAAAYZIvkRN',
         expires_at: 1676279273,
         refresh_token_expires_in: 5183999,
         ~~~~~~~~~~~~~~~~~~~~~~~~
         userId: 'cle28jfj90000suezuhpc8qxj'
       }
     })

Unknown arg `refresh_token_expires_in` in data.refresh_token_expires_in for type AccountUncheckedCreateInput. Available args:

type AccountUncheckedCreateInput {
  id?: String
  userId: String
  type: String
  provider: String
  providerAccountId: String
  refresh_token?: String | Null
  access_token?: String | Null
  expires_at?: Int | Null
  token_type?: String | Null
  scope?: String | Null
  id_token?: String | Null
  session_state?: String | Null
}

 Error: 
Invalid `p.account.create()` invocation in
/Users/mjy/workspace/web-draft/node_modules/@next-auth/prisma-adapter/dist/index.js:19:42

  16 },
  17 updateUser: ({ id, ...data }) => p.user.update({ where: { id }, data }),
  18 deleteUser: (id) => p.user.delete({ where: { id } }),
→ 19 linkAccount: (data) => p.account.create({
       data: {
         provider: 'kakao',
         type: 'oauth',
         providerAccountId: '(...)',
         access_token: '(...)',
         token_type: 'bearer',
         refresh_token: '(...)',
         expires_at: 1676279273,
         refresh_token_expires_in: 5183999,
         ~~~~~~~~~~~~~~~~~~~~~~~~
         userId: '(...)'
       }
     })

Unknown arg `refresh_token_expires_in` in data.refresh_token_expires_in for type AccountUncheckedCreateInput. Available args:

type AccountUncheckedCreateInput {
  id?: String
  userId: String
  type: String
  provider: String
  providerAccountId: String
  refresh_token?: String | Null
  access_token?: String | Null
  expires_at?: Int | Null
  token_type?: String | Null
  scope?: String | Null
  id_token?: String | Null
  session_state?: String | Null
}


    at Yn.validate (/Users/mjy/workspace/web-draft/node_modules/@prisma/client/runtime/library.js:148:91)
    at Ur.createMessage (/Users/mjy/workspace/web-draft/node_modules/@prisma/client/runtime/library.js:163:13577)
    at /Users/mjy/workspace/web-draft/node_modules/@prisma/client/runtime/library.js:173:10192
    at runInChildSpan (/Users/mjy/workspace/web-draft/node_modules/@prisma/client/runtime/library.js:70:25749)
    at t._executeRequest (/Users/mjy/workspace/web-draft/node_modules/@prisma/client/runtime/library.js:173:10181) {
  name: 'LinkAccountError',
  code: undefined
}
```

### How to reproduce

1. clone https://github.com/my-trash-bin/230213
2. `npm i`
3. put .env variables (refer [kakao](https://developers.kakao.com/), [comment](https://github.com/my-trash-bin/230213/blob/22d38807e8a9fd3c740686449d0da7dbd5161247/.env.local.example#L4-L9))
4. `npm run dev`
5. sign with kakao at [localhost](http://localhost:3000/api/auth/signin)

### Expected behavior

no error

**Comment by mjy9088** [comment]
closed by mistake?

**Comment by mjy9088** [comment]
closed by mistake. sorry

**Comment by balazsorban44** [comment]
See https://github.com/nextauthjs/next-auth/pull/6709#issuecomment-1427868440
