### ISSUE TITLE
[next-auth][error][OAUTH_CALLBACK_ERROR]

### ISSUE THREAD

**Issue by Gregory-Hepicloud** [nextauthjs/next-auth#6737]
### Provider type

Twitch

### Environment

  System:
    OS: Linux 4.18 AlmaLinux 8.7 (Stone Smilodon)
    CPU: (2) x64 Intel(R) Xeon(R) Gold 6230R CPU @ 2.10GHz
    Memory: 1.91 GB / 3.62 GB
    Container: Yes
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 18.14.0 - /usr/bin/node
    npm: 9.3.1 - /usr/bin/npm

### Reproduction URL

https://fiakomon.fiakopolis.com/

### Describe the issue

On login with twitch provider get a wrong url

### How to reproduce

click to login go to twitch page accept return to wrong url erro

### Expected behavior

```
[next-auth][error][OAUTH_CALLBACK_ERROR]
https://next-auth.js.org/errors#oauth_callback_error redirect_mismatch {
  message: 'redirect_mismatch',
  stack: 'Error: redirect_mismatch\n' +
    '    at oAuthCallback (/root/fiakomon/dashboard/node_modules/next-auth/core/lib/oauth/callback.js:39:19)\n' +
    '    at Object.callback (/root/fiakomon/dashboard/node_modules/next-auth/core/routes/callback.js:52:39)\n' +
    '    at AuthHandler (/root/fiakomon/dashboard/node_modules/next-auth/core/index.js:201:41)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async NextAuthHandler (/root/fiakomon/dashboard/node_modules/next-auth/next/index.js:24:19)\n' +
    '    at async Object.apiResolver (/root/fiakomon/dashboard/node_modules/next/dist/server/api-utils/node.js:372:9)\n' +
    '    at async DevServer.runApi (/root/fiakomon/dashboard/node_modules/next/dist/server/next-server.js:488:9)\n' +
    '    at async Object.fn (/root/fiakomon/dashboard/node_modules/next/dist/server/next-server.js:751:37)\n' +
    '    at async Router.execute (/root/fiakomon/dashboard/node_modules/next/dist/server/router.js:253:36)\n' +
    '    at async DevServer.run (/root/fiakomon/dashboard/node_modules/next/dist/server/base-server.js:384:29)\n' +
    '    at async DevServer.run (/root/fiakomon/dashboard/node_modules/next/dist/server/dev/next-dev-server.js:743:20)\n' +
    '    at async DevServer.handleRequest (/root/fiakomon/dashboard/node_modules/next/dist/server/base-server.js:322:20)',
  name: 'Error'
}
```
.env 
```
TWITCH_CLIENT_ID='6s4t75g1XXXXXXXXXXXXXXXd9reaqhjpm',
TWITCH_CLIENT_SECRET='djpnq29tXXXXXXXXXXXXXXXma22d5fj4',
NEXTAUTH_URL='https://fiakomon.fiakopolis.com',
NEXTAUTH_SECRET='Ey7nTKnggBc0XXXXXXXXXXXXXX4fUyqcKBePxY=',
```

```
const options = {
  adapter: PrismaAdapter(prisma),
  providers: [
    TwitchProvider({
      clientId: process.env.TWITCH_CLIENT_ID,
      clientSecret: process.env.TWITCH_CLIENT_SECRET
    })
  ],
  events: {
    async signIn({ user, account, profile, isNewUser }) {
      if(isNewUser) {
        await prisma.user.update({
          where: { id: user.id },
          data: { idtwitch: profile.id },
        })
      } else {
        await prisma.user.update({
          where: { id: user.id },
          data: { name: profile.name, image: profile.image },
        })
      }
    },
  },
  callbacks: {
    async session({ session, token, user }) {
      // Send properties to the client, like an access_token from a provider.
      session.account = user
      return session
    }
  },
  secret: process.env.NEXTAUTH_SECRET,
};
```

![image](https://user-images.githubusercontent.com/4592618/219365995-86beb47a-262d-4ec9-b7f7-bb1578f8bbaa.png)

![image](https://user-images.githubusercontent.com/4592618/219367189-8ab08f25-7428-46a6-9bee-7bd99f698d2c.png)

**Comment by balazsorban44** [comment]
`.env` files do not need a `,` and `'` for values and new lines. They are being included as part of the `NEXTAUTH_URL` value in your case.
