### ISSUE TITLE
Support Route Handlers in the `app` folder of Nextjs 13

### ISSUE THREAD

**Issue by benderillo** [nextauthjs/next-auth#6792]
## TL;DR
Need support for setting up NextAuth in route handler.

## Details
As API routes being replaced by Route handlers (https://beta.nextjs.org/docs/routing/route-handlers) NextAuth need to support running in the `route handler`. 

And documentation need to provide an example how to setup the nextjs authentication with NextAuth that uses route handler instead of the API route `pages/api/auth/[...nextauth].ts`

### How to reproduce ☕️

N/A

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
There is already a PR for it, and you can find an experimental version here https://github.com/nextauthjs/next-auth/pull/6777#issuecomment-1439312304 to try it out!

**Comment by benderillo** [comment]
> There is already a PR for it, and you can find an experimental version here [#6777 (comment)](https://github.com/nextauthjs/next-auth/pull/6777#issuecomment-1439312304) to try it out!
> 
> _Note, It's more of an incremental/gradual migration over a longer time period, API Routes are not "replaced"._

This is great! Do you know when (approximately) this will make it to the next official release?

**Comment by balazsorban44** [comment]
I would like to get this released maybe next week, if not sooner.

**Comment by benderillo** [comment]
@balazsorban44 I tried the latest code from https://github.com/nextauthjs/next-auth/pull/6777#issuecomment-1439312304 today. 
CORS issue is gone but now I am getting this:

```
[next-auth][error][OAUTH_CALLBACK_ERROR] 
https://next-auth.js.org/errors#oauth_callback_error checks.state argument is missing {
  error: TypeError: checks.state argument is missing
      at Client.callback (webpack-internal:///(sc_server)/./node_modules/openid-client/lib/client.js:321:19)
      at oAuthCallback (webpack-internal:///(sc_server)/./node_modules/next-auth/core/lib/oauth/callback.js:95:35)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async Object.callback (webpack-internal:///(sc_server)/./node_modules/next-auth/core/routes/callback.js:18:83)
      at async AuthHandler (webpack-internal:///(sc_server)/./node_modules/next-auth/core/index.js:198:38)
      at async NextAuthRouteHandler (webpack-internal:///(sc_server)/./node_modules/next-auth/next/index.js:51:30)
      at async eval (webpack-internal:///(sc_server)/./node_modules/next-auth/next/index.js:85:24)
      at async AppRouteRouteHandler.execute (~/nextjs-temp-prep/node_modules/next/dist/server/future/route-handlers/app-route-route-handler.js:214:26)

    name: 'OAuthCallbackError',
    code: undefined
  },
  providerId: 'google',
  message: 'checks.state argument is missing'
```

I get the google's consent screen first, and after I give my consent I get redirected to the callback but with the error.
`http://localhost:3000/auth/signin?callbackUrl=http%3A%2F%2Flocalhost%3A3000%2Fauth%2Fsignin&error=OAuthCallback`

Not quite sure what this is.

**Comment by akisly** [comment]
@balazsorban44 i also tried this one [pr](https://github.com/nextauthjs/next-auth/pull/6777), and i have this error:
```
[next-auth][error][OAUTH_CALLBACK_ERROR] 
https://next-auth.js.org/errors#oauth_callback_error invalid_grant (grant request is invalid) {
  error: OPError: invalid_grant (grant request is invalid)
      at processResponse (webpack-internal:///(sc_server)/./node_modules/openid-client/lib/helpers/process_response.js:35:19)
      at Client.grant (webpack-internal:///(sc_server)/./node_modules/openid-client/lib/client.js:1191:28)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async Client.callback (webpack-internal:///(sc_server)/./node_modules/openid-client/lib/client.js:406:30)
      at async oAuthCallback (webpack-internal:///(sc_server)/./node_modules/next-auth/core/lib/oauth/callback.js:95:22)
      at async Object.callback (webpack-internal:///(sc_server)/./node_modules/next-auth/core/routes/callback.js:18:83)
      at async AuthHandler (webpack-internal:///(sc_server)/./node_modules/next-auth/core/index.js:198:38)
      at async NextAuthRouteHandler (webpack-internal:///(sc_server)/./node_modules/next-auth/next/index.js:51:30)
      at async eval (webpack-internal:///(sc_server)/./node_modules/next-auth/next/index.js:85:24)
      at async AppRouteRouteHandler.execute (/home/alex/OnixPet/hydra-projects-ts/node_modules/next/dist/server/future/route-handlers/app-route-route-handler.js:214:26)
      at async AppRouteRouteHandler.handle (/home/alex/OnixPet/hydra-projects-ts/node_modules/next/dist/server/future/route-handlers/app-route-route-handler.js:348:30)
      at async RouteHandlerManager.handle (/home/alex/OnixPet/hydra-projects-ts/node_modules/next/dist/server/future/route-handler-managers/route-handler-manager.js:16:24)
      at async doRender (/home/alex/OnixPet/hydra-projects-ts/node_modules/next/dist/server/base-server.js:743:32)
      at async cacheEntry1.responseCache.get.incrementalCache.incrementalCache (/home/alex/OnixPet/hydra-projects-ts/node_modules/next/dist/server/base-server.js:926:28)
      at async /home/alex/OnixPet/hydra-projects-ts/node_modules/next/dist/server/response-cache/index.js:83:36 {
    name: 'OAuthCallbackError',
    code: undefined
  },
  providerId: 'hydra_passport',
  message: 'invalid_grant (grant request is invalid)'
}

```
I am use custom provider.
```
providers: [
    {
      id: 'hydra_passport',
      name: 'Hydra Passport',
      type: 'oauth',
      wellKnown: '.../.well-known/openid-configuration',
      authorization: {
        params: {
          prompt: 'consent',
          scope: 'openid offline_access profile',
        },
      },
      checks: ['pkce', 'state'],
      client: {
        token_endpoint_auth_method: 'none',
      },
      profile(profile) {
        return profile;
      },
      clientId: '...',
    },
  ],
```
in page/api everything works fine

**Comment by tom-brulin** [comment]
Same here using `DiscordProvider`

`checks.state argument is missing`

**Comment by tom-brulin** [comment]
@balazsorban44 Thanks for investigating this issue.

Let us know when you have more information.

**Comment by grezle** [comment]
@balazsorban44 - I'm struggling to get your fork working once deployed on vercel, its not picking up the `NEXTAUTH_URL` and is instead passing `localhost:3000`.

Everything is working great if I export the handlers from `pages/api/auth/[...nextauth].ts` and use `next-auth@latest`, so I'm wondering if anything else has changed in `next-auth@0.0.0-pr.6777.c5550344` that could break the `NEXTAUTH_URL` env?

**Comment by balazsorban44** [comment]
Vercel does not need `NEXTAUTH_URL` to be set as [documented](https://next-auth.js.org/deployment#vercel).

**Comment by trpipher** [comment]
I keep getting this everytime I try and use the PR
```
[next-auth][error][CLIENT_FETCH_ERROR] 
https://next-auth.js.org/errors#client_fetch_error Unexpected token < in JSON at position 0 {
  error: {
    message: 'Unexpected token < in JSON at position 0',
    stack: 'SyntaxError: Unexpected token < in JSON at position 0\n' +
      '    at JSON.parse (<anonymous>)\n' +
      '    at parseJSONFromBytes (node:internal/deps/undici/undici:6492:19)\n' +
      '    at successSteps (node:internal/deps/undici/undici:6466:27)\n' +
      '    at node:internal/deps/undici/undici:1141:60\n' +
      '    at node:internal/process/task_queues:140:7\n' +
      '    at AsyncResource.runInAsyncScope (node:async_hooks:204:9)\n' +
      '    at AsyncResource.runMicrotask (node:internal/process/task_queues:137:8)\n' +
      '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)',
    name: 'SyntaxError'
  },
  url: 'http://localhost:3000/api/auth/session',
  message: 'Unexpected token < in JSON at position 0'
}
```

**Comment by balazsorban44** [comment]
@trpipher you have a minimal reproduction?

**Comment by trpipher** [comment]
@balazsorban44 removed .next folder and it worked like magic however ever since updating to 13.2 not even with the PR im getting 
`Failed to set fetch cache http://localhost:3000/api/auth/session TypeError: cookies is not iterable` debugging atm

**Comment by balazsorban44** [comment]
Will need a reproduction please :pray:

**Comment by trpipher** [comment]
yeah i tore it all down to the barest it can and its still not working [Broken Repo](https://github.com/trpipher/next-auth-sessions-error)

**Comment by tom-brulin** [comment]
Someone was able to make next-auth work with new Route Handler ?

I tried today with the new `Next 13.2.3` version, and `next-auth@0.0.0-pr.6777.faa4ea2a ` but I can't get that working without getting `'checks.state argument is missing'`.

**Comment by benderillo** [comment]
@balazsorban44 Do I understand correctly that the fix for this ticket depends on https://github.com/vercel/next.js/issues/46355? 
If so I want it to be here so people can get current status posting that your PR does not work for them yet.

**Comment by balazsorban44** [comment]
Yes, see: https://github.com/nextauthjs/next-auth/issues/6792#issuecomment-1446204623

That issue you linked is more correct to link to though, so thanks. 👍

**Comment by NiranjithCU** [comment]
to resolve this temporarily, setting ```checks: ['pkce']``` in the config seems to be working with github login.

**Comment by EliasGcf** [comment]
Hi @balazsorban44, sorry for the late reply. Here is the reproduction repo as you requested: https://github.com/EliasGcf/next-auth-with-route-handler

**Comment by mattddean** [comment]
In case it's helpful, I found that using @auth/core with the Solid implementation works almost out of the box with Route Handlers on the Edge runtime.
https://github.com/mattddean/t3-app-router-edge/tree/07e322d717a9546a9a1764936b8044e2d6bc724a/src/auth

**Comment by codinesh** [comment]
Hi, please share if there is there any update on this.

**Comment by mrxbox98** [comment]
Hey I'm getting a error 500 whenever I try to preform an action that uses next-auth in any way.

Here is the repository: https://github.com/EmergencyBucket/pail

And here is the error: 
```js
error - TypeError: Cannot destructure property 'nextauth' of 'req.query' as it is undefined.
    at NextAuthHandler (webpack-internal:///(sc_server)/./node_modules/next-auth/next/index.js:13:13)
    at eval (webpack-internal:///(sc_server)/./node_modules/next-auth/next/index.js:46:40)
    at /home/pail/node_modules/next/dist/server/future/route-handlers/app-route-route-handler.js:368:24
    at AsyncLocalStorage.run (node:async_hooks:330:14)
    at Function.wrap (/home/pail/node_modules/next/dist/server/async-storage/static-generation-async-storage-wrapper.js:33:24)
    at StaticGenerationAsyncStorageWrapper.wrap (/home/pail/node_modules/next/dist/server/async-storage/static-generation-async-storage-wrapper.js:7:52)
    at /home/pail/node_modules/next/dist/server/future/route-handlers/app-route-route-handler.js:330:151
    at AsyncLocalStorage.run (node:async_hooks:330:14)
    at Function.wrap (/home/pail/node_modules/next/dist/server/async-storage/request-async-storage-wrapper.js:65:24)
    at RequestAsyncStorageWrapper.wrap (/home/pail/node_modules/next/dist/server/async-storage/request-async-storage-wrapper.js:30:43)
    at AppRouteRouteHandler.execute (/home/pail/node_modules/next/dist/server/future/route-handlers/app-route-route-handler.js:330:69)
    at AppRouteRouteHandler.handle (/home/pail/node_modules/next/dist/server/future/route-handlers/app-route-route-handler.js:410:41)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RouteHandlerManager.handle (/home/pail/node_modules/next/dist/server/future/route-handler-managers/route-handler-manager.js:16:24)
    at async doRender (/home/pail/node_modules/next/dist/server/base-server.js:744:32)
    at async cacheEntry1.responseCache.get.incrementalCache.incrementalCache (/home/pail/node_modules/next/dist/server/base-server.js:931:28)
    at async /home/pail/node_modules/next/dist/server/response-cache/index.js:83:36
```

**Comment by mattddean** [comment]
@mrxbox98 try this https://github.com/mattddean/t3-app-router-edge-drizzle/blob/df4bb0f5b14496514486435d01d2e735d7776d9e/src/app/api/auth/%5B...nextauth%5D/route.ts

**Comment by y-nk** [comment]
@balazsorban44 please don't close hastily issues without reading them properly.

**Comment by jdrada** [comment]
I did what you mention but app/api/auth/[...nextauth]/route.ts just give me a 405 Error.

So I ended moving the [...nextauth].ts file from app/api/auth folder and created a pages/api/auth folder, and it is working fine. 
But had to delete the app/api folder in order for it to work.

Any other solution?

**Comment by balazsorban44** [comment]
Thank you for everyone's patience, this is now available in `4.22.0`! 🎉 Check out the docs: https://next-auth.js.org/configuration/initialization#route-handlers-app

Remember, this is opt-in, `pages` will be still supported!

**Comment by wowczarczyk** [comment]
@balazsorban44 is it possible to use Route Handlers with advanced initialization?

**Comment by nils42gh** [comment]
Hey @balazsorban44 	MISSING_NEXTAUTH_API_ROUTE_ERROR is returned in 4.22.0 with src/ directory setup.

**Comment by leeren** [comment]
Even though I can correctly source my provider configuration from api/auth/[...nextauth].ts I get an API resolver error unless I define the same NextAuth settings in pages/api/auth/[...nextauth].ts 

This happens when I trigger the signIn callback from next-auth/react

Does anyone have a similar issue? Or anyone have tips on how to debug / resolve this problem?

**Comment by octet-stream** [comment]
> api/auth/[...nextauth].ts

In App Router, Route Hanlders must be defined at file named `route.{ts,js}`, so I think you nett to rename this to `api/auth/[...nextauth]/route.ts`. See it in [documentation](https://next-auth.js.org/configuration/initialization#route-handlers-app).

**Comment by leeren** [comment]
I tried the above but still get the same issue.

Putting the following in `api/auth/[...nextauth]/route.ts`:
```
import NextAuth from "next-auth"
import type { NextAuthOptions } from 'next-auth'
import GoogleProvider from "next-auth/providers/google";

export const authOptions: NextAuthOptions = {
	providers: [
		GoogleProvider({
			clientId: process.env.GOOGLE_CLIENT_ID,
			clientSecret: process.env.GOOGLE_CLIENT_SECRET
		}),
	],
}

const handler = NextAuth(authOptions);
export { handler as GET, handler as POST };
```

Putting it in `api/auth/[...nextauth].ts`:
```
import NextAuth from "next-auth"
import type { NextAuthOptions } from 'next-auth'
import GoogleProvider from "next-auth/providers/google";

export const authOptions: NextAuthOptions = {
	providers: [
		GoogleProvider({
			clientId: process.env.GOOGLE_CLIENT_ID,
			clientSecret: process.env.GOOGLE_CLIENT_SECRET
		}),
	],
}

export default NextAuth(authOptions);
```

Both fail for me unless I explicitly define them in the `pages` folder. Anyone have a working example using Next.js 13?

**Comment by dstarosta** [comment]
`api/auth` routes are not resolving for me either.

**Comment by Jarpiino** [comment]
> > api/auth/[...nextauth].ts
> 
> In App Router, Route Hanlders must be defined at file named `route.{ts,js}`, so I think you nett to rename this to `api/auth/[...nextauth]/route.ts`. See it in [documentation](https://next-auth.js.org/configuration/initialization#route-handlers-app).

./api/auth/[...nextauth]/route.js actually works, ty!

**Comment by dstarosta** [comment]
I have tried `/api/auth/[...nextauth]/route.ts` and `/api/auth/[...nextauth]/route.js` without any success.

Only the `pages/api/auth/[...nextauth].ts` route works.

**Comment by Jarpiino** [comment]
> I have tried `/api/auth/[...nextauth]/route.ts` and `/api/auth/[...nextauth]/route.js` without any success.
> 
> Only the `pages/api/auth/[...nextauth].ts` route works.

I also found a great guide which was made just 10 days ago https://youtu.be/VE8BkImUciY?t=8085
his github repo with the new routes > https://github.com/safak/nextjs-tutorial/blob/main/src/app/api/auth/%5B...nextauth%5D/route.js

**Comment by dstarosta** [comment]
The issue was caused by a redirect regex on the backend.

**Comment by arilotter** [comment]
Found & resolved an issue on my end;
`app/api/auth/[...nextauth]/route.ts` doesn't work, but
`app/auth/[...nextauth]/route.ts` works perfectly.

**Comment by makhtardiouf** [comment]
For those that deployed their app on the Cloud and use a custom base path, refer to https://next-auth.js.org/getting-started/client#custom-base-path 

Was a major headache on my Next.js 14.2 app
