### ISSUE TITLE
MISSING_NEXTAUTH_API_ROUTE_ERROR despite folder and file correctly named

### ISSUE THREAD

**Issue by dsine-eth** [nextauthjs/next-auth#6824]
### Environment

System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
    Memory: 5.96 GB / 15.59 GB
  Binaries:
    Node: 16.17.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.15.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1265.0), Chromium (110.0.1587.50)
    Internet Explorer: 11.0.22621.1

### Reproduction URL

https://github.com/dsine-eth/8bit-brewery-website

### Describe the issue

Every call that involves a NextAuth function prints out an error that says it can't find the nextauth path and shows something like this:

[next-auth][error][MISSING_NEXTAUTH_API_ROUTE_ERROR] 
https://next-auth.js.org/errors#missing_nextauth_api_route_error Cannot find [...nextauth].{js,ts} in `/pages/api/auth`. Make sure the filename is written correctly. MissingAPIRoute [MissingAPIRouteError]: Cannot find [...nextauth].{js,ts} in `/pages/api/auth`. Make sure the filename is written correctly.
    at assertConfig (C:\Users\dylan\repos\8bit-brewery-website\node_modules\next-auth\core\lib\assert.js:46:12)
    at NextAuthHandler (C:\Users\dylan\repos\8bit-brewery-website\node_modules\next-auth\core\index.js:70:52)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async NextAuthNextHandler (C:\Users\dylan\repos\8bit-brewery-website\node_modules\next-auth\next\index.js:23:19)  
    at async isUserAuthorized (webpack-internal:///(api)/./libs/auth.ts:11:21) {
  code: 'MISSING_NEXTAUTH_API_ROUTE_ERROR'
}
error - Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at new NodeError (node:internal/errors:387:5)
    at ServerResponse.setHeader (node:_http_outgoing:603:11)
    at async DevServer.runImpl (C:\Users\dylan\repos\8bit-brewery-website\node_modules\next\dist\server\base-server.js:432:29)
    at async DevServer.run (C:\Users\dylan\repos\8bit-brewery-website\node_modules\next\dist\server\dev\next-dev-server.js:814:20)    at async DevServer.handleRequestImpl (C:\Users\dylan\repos\8bit-brewery-website\node_modules\next\dist\server\base-server.js:375:20)
    at async C:\Users\dylan\repos\8bit-brewery-website\node_modules\next\dist\server\base-server.js:157:99 {  code: 'ERR_HTTP_HEADERS_SENT',
  page: '/api/promotion'}

### How to reproduce

Any call that goes to an /api/ route which usually calls getServerSession to check permissions results in a MISSING_NEXTAUTH_API_ROUTE_ERROR. I was not getting this error until suddenly I was! The strange thing is that usually the change goes through but it shows this error.

### Expected behavior

I should see no error. The file is there and in the correct folder path.

**Comment by ben-sommer** [comment]
I have this exact same error

**Comment by dsine-eth** [comment]
@ben-sommer What version of Next are you using? I'm on version 13.0.4.

**Comment by ben-sommer** [comment]
13.2

**Comment by ben-sommer** [comment]
I'm also on Windows (11) but on an AMD based machine.

**Comment by ben-sommer** [comment]
Fixed it! The code example I copied was written on a blog that converted three consecutive periods to an ellipsis character.

@dsine-eth try typing out the three dots at the start of `[...nextauth]` manually yourself and that should fix this issue.

**Comment by dsine-eth** [comment]
@ben-sommer hey congrats! I think I'm having a different issue as that wasn't the problem for me.

**Comment by dsine-eth** [comment]
@balazsorban44 can we reopen this?

**Comment by tom-plaa** [comment]
same issue here
