### ISSUE TITLE
DuendeIDS6Provider `userinfo` endpoint to get user claims

### ISSUE THREAD

**Issue by khteh** [nextauthjs/next-auth#6838]
### Provider type

Identity Server 4

### Environment

  System:
    OS: Linux 5.19 Ubuntu 22.10 22.10 (Kinetic Kudu)
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i9-11950H @ 2.60GHz
    Memory: 58.41 GB / 70.39 GB
    Container: Yes
    Shell: 5.2.2 - /bin/bash
  Binaries:
    Node: 19.6.0 - /usr/local/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 9.4.2 - /usr/local/bin/npm
  Browsers:
    Chrome: 110.0.5481.177
    Firefox: 110.0

### Reproduction URL

http://localhost:3000

### Describe the issue

I am using `DuendeIDS6Provider`. When I set `idToken: true`, I don't get the claims from the server. When I set it to false, I get the following error:
```
https://next-auth.js.org/errors#oauth_callback_error id_token detected in the response, you must use client.callback() instead of client.oauthCallback() {
  error: RPError: id_token detected in the response, you must use client.callback() instead of client.oauthCallback()
      at Client.oauthCallback (/usr/src/next-auth-example/node_modules/openid-client/lib/client.js:615:15)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async oAuthCallback (/usr/src/next-auth-example/node_modules/next-auth/core/lib/oauth/callback.js:131:16)
      at async Object.callback (/usr/src/next-auth-example/node_modules/next-auth/core/routes/callback.js:52:11)
      at async AuthHandler (/usr/src/next-auth-example/node_modules/next-auth/core/index.js:201:28)
      at async NextAuthHandler (/usr/src/next-auth-example/node_modules/next-auth/next/index.js:24:19)
      at async /usr/src/next-auth-example/node_modules/next-auth/next/index.js:60:32
      at async Object.apiResolver (/usr/src/next-auth-example/node_modules/next/dist/server/api-utils/node.js:372:9)
      at async NextNodeServer.runApi (/usr/src/next-auth-example/node_modules/next/dist/server/next-server.js:513:9)
      at async Object.fn (/usr/src/next-auth-example/node_modules/next/dist/server/next-server.js:815:35) {
    name: 'OAuthCallbackError',
    code: undefined
  },
```

### How to reproduce

Runs `next-auth-example` using `DuendeIDS6Provider` using the following config:
```
    DuendeIDS6Provider({
      id: "buyerportal",
      name: "buyerportal",
      authorization: {
        params: { scope: "openid email address phone profile buyerportal", protection: "pkce" },
      },
      issuer: process.env.DUENDE_IDS6_ISSUER || config.get('DUENDE_IDS6_ISSUER'),
      clientId: process.env.DUENDE_IDS6_CLIENT_ID || config.get('DUENDE_IDS6_CLIENT_ID'),
      clientSecret: process.env.DUENDE_IDS6_CLIENT_SECRET || config.get('DUENDE_IDS6_CLIENT_SECRET'),
      wellKnown: `${process.env.DUENDE_IDS6_ISSUER || config.get('DUENDE_IDS6_ISSUER')}/.well-known/openid-configuration`,
      idToken: false,
      userinfo: {
        url: `${process.env.DUENDE_IDS6_ISSUER || config.get('DUENDE_IDS6_ISSUER')}/connect/userinfo`
      },
    }),
```

### Expected behavior

Return claims of authenticated user.

**Comment by khteh** [comment]
What's `client.callback()` vs `client.oauthCallback()`?

**Comment by khteh** [comment]
I can see the claims in `ProfileService` `public override async Task GetProfileDataAsync(ProfileDataRequestContext context)` function logs. https://docs.duendesoftware.com/identityserver/v6/fundamentals/claims/

**Comment by khteh** [comment]
And I can see the claims from postman GET request to `userinfo` endpoint. Is this a bug?
