### ISSUE TITLE
SvelteKit Client signIn email sends email in url but core expects it in body

### ISSUE THREAD

**Issue by subzero79** [nextauthjs/next-auth#7091]
### Provider type

Email

### Environment

  System:
    OS: Linux 5.15 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
    CPU: (6) x64 AMD Ryzen 5 4500U with Radeon Graphics
    Memory: 17.84 GB / 30.78 GB
    Container: Yes
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.19.1 - ~/.nvm/versions/node/v16.19.1/bin/node
    Yarn: 1.22.4 - /usr/bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v16.19.1/bin/npm
  Browsers:
    Chrome: 110.0.5481.177
    Firefox: 111.0.1

### Reproduction URL

https://github.com/nextauthjs/next-auth-example

### Describe the issue

I am just trying to setup the @auth/sveltekit package. And the signIn with email provider doesn't work.

This is the error

```sh
[auth][details]: {
  "provider": "email"
}
[auth][error][SignInError]: Read more at https://errors.authjs.dev#signinerror
[auth][cause]: Error: Missing email from request body.
    at defaultNormalizer (file:///home/ricardo/Developer/scratch/sveltekit-test/node_modules/@auth/core/lib/routes/signin.js:45:15)
    at Module.signin (file:///home/ricardo/Developer/scratch/sveltekit-test/node_modules/@auth/core/lib/routes/signin.js:18:27)
    at AuthInternal (file:///home/ricardo/Developer/scratch/sveltekit-test/node_modules/@auth/core/lib/index.js:115:49)
    at async Proxy.Auth (file:///home/ricardo/Developer/scratch/sveltekit-test/node_modules/@auth/core/index.js:100:30)
    at async Module.respond (/node_modules/@sveltejs/kit/src/runtime/server/respond.js:248:20)
    at async file:///home/ricardo/Developer/scratch/sveltekit-test/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:505:22
[auth][details]: {
  "provider": "email"
}
```

From what it looks in the network console the singIn method POST to `http://localhost:5173/auth/signin/email?email=jonny%40gmail.com` with crsfToken and callback url in body. Looking at the code also that's expected.

But from what i see in the @auth/core package the email is expected to come in the body not in the URL

If I use the default signIn path /auth/signin there is no error, and i can see the form sending the email in the body and then receiving the verification email.

### How to reproduce

Setup the hooks.server.ts according to documentation

```ts
import { SvelteKitAuth, type SvelteKitAuthConfig } from '@auth/sveltekit';
import Email from '@auth/core/providers/email';
import { MAILSENDER } from '$lib/constants';

import transporter from '$lib/transporter';
import type { Theme } from 'next-auth';
import { redirect, type Handle } from '@sveltejs/kit';
import { sequence } from '@sveltejs/kit/hooks';
import { PrismaAdapter } from '@next-auth/prisma-adapter';
import prisma from '$lib/prisma';

export const handle = sequence(
	SvelteKitAuth(async (evt) => {
		const authOptions: SvelteKitAuthConfig = {
			secret: 'secret',
			trustHost: true,
			debug: true,
			// @ts-ignore
			adapter: PrismaAdapter(prisma),
			callbacks: {
				async signIn({ account, user, credentials, email, profile }) {
					console.log(
						'file: hooks.server.ts:21 ~ signIn ~  account, user, credentials, email, profile :',
						account,
						user,
						credentials,
						email,
						profile
					);
					return true;
				}
			},

			providers: [
				Email({
					id: 'email',
					name: 'Email',
					type: 'email',
					secret: 'secret',
					from: MAILSENDER,

					server: {
						host: 'smtp.gmail.com',
						port: 465,
						auth: {
							user: MAILSENDER,
							pass: 'password'
						}
					},

					sendVerificationRequest: async ({ identifier: email, url, token, provider, theme }) => {
						console.log('file: hooks.server.ts:42 ~ sendVerificationRequest: ~ email:', email);
						const { host } = new URL(url);
						// NOTE: You are not required to use `nodemailer`, use whatever you want.

						const result = await transporter.sendMail({
							to: email,
							from: provider.from,
							subject: `Sign in to ${host}`,
							text: text({ url, host }),
							html: html({ url, host, theme })
						});
						
					}
				})
			]
		};
		return authOptions;
	}),
	async ({ event, resolve }) => {
		if (event.url.pathname.startsWith('/org')) {
			const session = await event.locals.getSession();
			if (!session) {
				throw redirect(303, '/login');
			}
		}

		return resolve(event);
	}
) satisfies Handle;

/**
 * Email HTML body
 * Insert invisible space into domains from being turned into a hyperlink by email
 * clients like Outlook and Apple mail, as this is confusing because it seems
 * like they are supposed to click on it to sign in.
 *
 * @note We don't add the email address to avoid needing to escape it, if you do, remember to sanitize it!
 */
function html(params: { url: string; host: string; theme: Theme }) {
	const { url, host, theme } = params;

	const escapedHost = host.replace(/\./g, '&#8203;.');

	const brandColor = theme.brandColor || '#346df1';
	const color = {
		background: '#f9f9f9',
		text: '#444',
		mainBackground: '#fff',
		buttonBackground: brandColor,
		buttonBorder: brandColor,
		buttonText: theme.buttonText || '#fff'
	};

	return `
<body style="background: ${color.background};">
  <table width="100%" border="0" cellspacing="20" cellpadding="0"
    style="background: ${color.mainBackground}; max-width: 600px; margin: auto; border-radius: 10px;">
    <tr>
      <td align="center"
        style="padding: 10px 0px; font-size: 22px; font-family: Helvetica, Arial, sans-serif; color: ${color.text};">
        Sign in to <strong>${escapedHost}</strong>
      </td>
    </tr>
    <tr>
      <td align="center" style="padding: 20px 0;">
        <table border="0" cellspacing="0" cellpadding="0">
          <tr>
            <td align="center" style="border-radius: 5px;" bgcolor="${color.buttonBackground}"><a href="${url}"
                target="_blank"
                style="font-size: 18px; font-family: Helvetica, Arial, sans-serif; color: ${color.buttonText}; text-decoration: none; border-radius: 5px; padding: 10px 20px; border: 1px solid ${color.buttonBorder}; display: inline-block; font-weight: bold;">Sign
                in</a></td>
          </tr>
        </table>
      </td>
    </tr>
    <tr>
      <td align="center"
        style="padding: 0px 0px 10px 0px; font-size: 16px; line-height: 22px; font-family: Helvetica, Arial, sans-serif; color: ${color.text};">
        If you did not request this email you can safely ignore it.
      </td>
    </tr>
  </table>
</body>
`;
}

/** Email Text body (fallback for email clients that don't render HTML, e.g. feature phones) */
function text({ url, host }: { url: string; host: string }) {
	return `Sign in to ${host}\n${url}\n\n`;
}
```

Create a login page 

```svelte
<script lang="ts">
	import { signIn } from '@auth/sveltekit/client';
	let email = '';
</script>

<div class="flex flex-col gap-2 max-w-md">
	<h1>Login</h1>
	<!-- <form method="post" class="flex flex-col gap-2"> -->
	<label for="email">Email</label>
	<input id="email" bind:value={email} class="input input-sm rounded-md" />
	<button
		class="btn btn-primary btn-sm"
		on:click={() => {
			signIn('email', {}, { email });
		}}>Login</button
	>
	<!-- </form> -->
</div>
```

### Expected behavior

I would expect to the adapter to redirect me and receive an email

**Comment by ThangHuuVu** [comment]
You need to pass the `email` in the second parameter (`options`) instead of the third parameter (`authorizationParam`) 
See our React example here: https://next-auth.js.org/getting-started/client#starts-email-sign-in-flow-when-clicked

```tsx
import { signIn } from "next-auth/react"

export default ({ email }) => (
  <button onClick={() => signIn("email", { email })}>Sign in with Email</button>
)
```
