### ISSUE TITLE
/auth/crsf 404 on Vercel with SvelteKitAuth

### ISSUE THREAD

**Issue by ColinLienard** [nextauthjs/next-auth#7133]
### Environment

System:
    OS: macOS 13.2.1
    CPU: (8) arm64 Apple M2
    Memory: 1.78 GB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
  Browsers:
    Chrome: 111.0.5563.146
    Firefox: 111.0
    Safari: 16.3

### Reproduction URL

https://github.com/ColinLienard/gitlight/tree/fix/vercel-auth

### Describe the issue

When trying to sign in, I get this error: `GET https://....vercel.app/auth/csrf 404` and nothing happens. I don't have this issue in dev nor when doing `build` then `preview`, but only in production on Vercel.
I'm using `@auth/core` and `@auth/sveltekit`. I use sveltekit with the static adapter because this is required for Tauri

### How to reproduce

The latest deployment: https://gitlight-72vcvyxb2-colinlienard.vercel.app/
Click on `Sign in` and open the console, you should see the error.
My repo: https://github.com/ColinLienard/gitlight/tree/fix/vercel-auth

### Expected behavior

The user should authenticate with GitHub

**Comment by balazsorban44** [comment]
Interestingly, our [deployed example](https://github.com/nextauthjs/next-auth/tree/main/apps/examples/sveltekit) works fine. :thinking: https://sveltekit-auth-example.vercel.app/auth/csrf

**Comment by ColinLienard** [comment]
I was previously signing in with the `signIn` function so i tried the `<a href="/auth/signin"` way which should send me to the default page with a sign in button, but I get 404: NOT_FOUND
Try it: go [here](https://gitlight-4v2694juv-colinlienard.vercel.app/) and click on _Sign in 2_

Again, this problem occurs only in production on Vercel and not in dev nor when previewing local build

**Comment by ThangHuuVu** [comment]
This seems like a configuration issue to me - I cannot visit https://gitlight-72vcvyxb2-colinlienard.vercel.app/auth/signin either
@ColinLienard could you provide a minimal reproduction with only the relevant code & deploy it to production (don't use a Preview link) to demonstrate? 🙏

**Comment by ColinLienard** [comment]
There is the minimal reproduction: https://github.com/ColinLienard/sveltekit-auth-example
You can visit it here: https://sveltekit-auth-example-nu.vercel.app/

The sign in button still redirects to a 404 page but I found the solution: I was using the static adapter for sveltekit because I want to do a Tauri app afterwards and it is needed, and I was setting the fallback option but as said on the [documentation](https://kit.svelte.dev/docs/adapter-static#zero-config-support), it should be omitted for Vercel.

 In my `svelte.config.js`, I now check if I'm deploying on vercel and use the vercel adapter based on that

```js
kit: {
  adapter:
    process.env.APP_ENV === 'vercel'
      ? vercelAdapter()
      : staticAdapter({ fallback: 'index.html' })
}
```

**Comment by socketopp** [comment]
I am experiencing the same issue, did we find a fix for this issue? 
I am deploying on Cloudflare with the same provider and I'm also getting the same issue.

**Comment by sillvva** [comment]
I am also experiencing this in local after upgrading to latest `@auth/core` and `@auth/sveltekit`

I am using the `signIn` function.

The problem:
```
SvelteKitError: Not found: /auth/csrf
    at resolve (/Users/sillvva/Projects/ddal-svelte/node_modules/.pnpm/@sveltejs+kit@2.5.0_@sveltejs+vite-plugin-svelte@3.0.2_svelte@4.2.9_vite@5.0.12/node_modules/@sveltejs/kit/src/runtime/server/respond.js:522:13)
    at resolve (/Users/sillvva/Projects/ddal-svelte/node_modules/.pnpm/@sveltejs+kit@2.5.0_@sveltejs+vite-plugin-svelte@3.0.2_svelte@4.2.9_vite@5.0.12/node_modules/@sveltejs/kit/src/runtime/server/respond.js:322:5)
    at resolve (/Users/sillvva/Projects/ddal-svelte/node_modules/.pnpm/@sveltejs+kit@2.5.0_@sveltejs+vite-plugin-svelte@3.0.2_svelte@4.2.9_vite@5.0.12/node_modules/@sveltejs/kit/src/exports/hooks/sequence.js:115:9)
    at handle (/Users/sillvva/Projects/ddal-svelte/node_modules/.pnpm/@sveltekit-addons+document@1.0.1_svelte@4.2.9/node_modules/@sveltekit-addons/document/dist/hooks.js:8:2)
    at apply_handle (/Users/sillvva/Projects/ddal-svelte/node_modules/.pnpm/@sveltejs+kit@2.5.0_@sveltejs+vite-plugin-svelte@3.0.2_svelte@4.2.9_vite@5.0.12/node_modules/@sveltejs/kit/src/exports/hooks/sequence.js:85:11)
    at resolve (/Users/sillvva/Projects/ddal-svelte/node_modules/.pnpm/@sveltejs+kit@2.5.0_@sveltejs+vite-plugin-svelte@3.0.2_svelte@4.2.9_vite@5.0.12/node_modules/@sveltejs/kit/src/exports/hooks/sequence.js:110:9)
    at session (/Users/sillvva/Projects/ddal-svelte/src/hooks.server.ts:190:25)
    at async Module.respond (/Users/sillvva/Projects/ddal-svelte/node_modules/.pnpm/@sveltejs+kit@2.5.0_@sveltejs+vite-plugin-svelte@3.0.2_svelte@4.2.9_vite@5.0.12/node_modules/@sveltejs/kit/src/runtime/server/respond.js:319:20)
    at async file:///Users/sillvva/Projects/ddal-svelte/node_modules/.pnpm/@sveltejs+kit@2.5.0_@sveltejs+vite-plugin-svelte@3.0.2_svelte@4.2.9_vite@5.0.12/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:524:22 {
  status: 404,
  text: 'Not Found'
}
```

My hooks:
```
interface OAuthProvider {
	id: string;
	tokenUrl: string;
	clientId: string;
	clientSecret: string;
	oauth: () => Provider;
}
const providers: OAuthProvider[] = [
	{
		id: "google",
		tokenUrl: "https://oauth2.googleapis.com/token",
		clientId: GOOGLE_CLIENT_ID,
		clientSecret: GOOGLE_CLIENT_SECRET,
		oauth: function () {
			return Google({
				clientId: this.clientId,
				clientSecret: this.clientSecret,
				authorization: { params: { access_type: "offline", prompt: "consent" } }
			});
		}
	},
	{
		id: "discord",
		tokenUrl: "https://discord.com/api/v10/oauth2/token",
		clientId: DISCORD_CLIENT_ID,
		clientSecret: DISCORD_CLIENT_SECRET,
		oauth: function () {
			return Discord({
				clientId: this.clientId,
				clientSecret: this.clientSecret
			});
		}
	}
];

export const auth = SvelteKitAuth(async (event) => {
	return {
		callbacks: {
			...
		},
		secret: AUTH_SECRET,
		adapter: PrismaAdapter(prisma),
		providers: providers.map((p) => p.oauth()),
		trustHost: true
	} satisfies SvelteKitAuthConfig;
}) satisfies Handle;
```

@ThangHuuVu

**Comment by aakash14goplani** [comment]
Add property `basePath: "/auth"` in SvelteKitAuth config. [Refer docs](https://authjs.dev/reference/sveltekit#sveltekitauthconfig). This property was newly added and made mandatory from v0.11.0

**Comment by socketopp** [comment]
@sillvva 
Did you manage to fix this error? I started experiencing this when upgrading to SvelteKit 2
