### ISSUE TITLE
unexpected ID Token "nonce" claim value

### ISSUE THREAD

**Issue by half2me** [nextauthjs/next-auth#7313]
### Provider type

Cognito

### Environment

System:
    OS: macOS 13.3.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 153.55 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 19.9.0 - /opt/homebrew/bin/node
    npm: 9.6.3 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 112.0.5615.121
    Firefox: 101.0
    Safari: 16.4

### Reproduction URL

https://github.com/half2me/sveltekit-authjs-houdini

### Describe the issue

I'm using SvelteKit with Auth.js using the Cognito provider with `pcke` and `nonce` checks.
```typscript
Cognito({
  ...
  checks: ['pkce', 'nonce']
})
```

After logging in, when being redirected to the my site, I get this error:
```
[auth][error][CallbackRouteError]: Read more at https://errors.authjs.dev#callbackrouteerror
[auth][cause]: OperationProcessingError: unexpected ID Token "nonce" claim value
    at Module.processAuthorizationCodeOpenIDResponse (file:///Users/halftome/sveltekit-authjs-houdini/node_modules/oauth4webapi/build/index.js:1038:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async handleOAuth (file:///Users/halftome/sveltekit-authjs-houdini/node_modules/@auth/sveltekit/node_modules/@auth/core/lib/oauth/callback.js:79:24)
    at async Module.callback (file:///Users/halftome/sveltekit-authjs-houdini/node_modules/@auth/sveltekit/node_modules/@auth/core/lib/routes/callback.js:14:41)
    at async AuthInternal (file:///Users/halftome/sveltekit-authjs-houdini/node_modules/@auth/sveltekit/node_modules/@auth/core/lib/index.js:64:38)
    at async Proxy.Auth (file:///Users/halftome/sveltekit-authjs-houdini/node_modules/@auth/sveltekit/node_modules/@auth/core/index.js:100:30)
    at async Module.respond (/node_modules/@sveltejs/kit/src/runtime/server/respond.js:257:20)
    at async file:///Users/halftome/sveltekit-authjs-houdini/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:513:22
[auth][details]: {
  "provider": "cognito"
}
```

### How to reproduce

I have a sample repo attached showing the issue. I've just updated to `@auth/core@0.6.0`.
Previously I had this issue fixed by using `@auth/core@0.5.1`, and applying this patch:
```patch
--- node_modules/@auth/core/lib/oauth/callback.js	2023-03-28 16:30:20
+++ node_modules/@auth/core/lib/oauth/callback.js	2023-04-17 14:11:07
@@ -76,7 +76,8 @@
     let profile = {};
     let tokens;
     if (provider.type === "oidc") {
-        const result = await o.processAuthorizationCodeOpenIDResponse(as, client, codeGrantResponse);
+        const result = await o.processAuthorizationCodeOpenIDResponse(as, client, codeGrantResponse, nonce?.value ??
+o.expectNoNonce);
         if (o.isOAuth2Error(result)) {
             console.log("error", result);
             throw new Error("TODO: Handle OIDC response body error");
```
You can see the working version at this commit: https://github.com/half2me/sveltekit-authjs-houdini/tree/a3f19a03c79e8b2e20a06c6acacb240ac434d8c3

After updating to the new version, I'm getting the same error I used to have before.

### Expected behavior

`nonce` value was specified as a check, so I'd expect it to work.

**Comment by half2me** [comment]
It's the same error I was getting on #6865

**Comment by balazsorban44** [comment]
We are consuming the nonce twice:

https://github.com/nextauthjs/next-auth/blob/9eeea02fe2565e36bafe86f2970b5bd453483d4a/packages/core/src/lib/oauth/callback.ts#L100

https://github.com/nextauthjs/next-auth/blob/9eeea02fe2565e36bafe86f2970b5bd453483d4a/packages/core/src/lib/oauth/callback.ts#L132

Will get this fixed!

**Comment by balazsorban44** [comment]
I tested with Auth0, and using a nonce checked worked fine either with the old code. I'll try to have a look at your reproduction now.

**Comment by balazsorban44** [comment]
Before I dive deeper, could you see if https://github.com/nextauthjs/next-auth/issues/6226#issuecomment-1368277163 helps? :pray:

**Comment by ollema** [comment]
I'm also seeing this for Slack:
```
[auth][error][CallbackRouteError]: Read more at https://errors.authjs.dev#callbackrouteerror
[auth][cause]: OperationProcessingError: unexpected ID Token "nonce" claim value
```

with 
```
	"dependencies": {
		"@auth/core": "^0.7.1",
		"@auth/sveltekit": "^0.3.1"
	}
	```

**Comment by half2me** [comment]
any updates on this?

**Comment by mikle7** [comment]
any updates on this???

**Comment by Starefossen** [comment]
I have posed a similar issue for the SlackProvider in #9002. If anyone can point me in the right direction I'd me more than happy to make an attempt to fix this 😄

**Comment by half2me** [comment]
@Starefossen lmk if you manage to solve this. Currently I'm stuck on an older version of this lib, with a patch I made and that's the only way I got it to work...

**Comment by Starefossen** [comment]
I have no idea where to get started to fix this 🤷🏼

**Comment by ollema** [comment]
my solution was to migrate to Lucia...

**Comment by neptaco** [comment]
For Slack it worked by adding nonce to checks
https://github.com/nextauthjs/next-auth/issues/9002#issuecomment-1900334658
