### ISSUE TITLE
Using postgres database fails.

### ISSUE THREAD

**Issue by shkfnly** [nextauthjs/next-auth#739]
**Describe the bug**
I added a database and am using a email provider. I am getting a TYPE ORM error.

[next-auth][error][adapter_connection_error] MissingDriverError: Wrong driver: "postgresql" given.

I'm not sure where 'postgresql' is being passed.

Errors:

```
[next-auth][error][adapter_connection_error] MissingDriverError: Wrong driver: "postgresql" given. Supported drivers are: "cordova", "expo", "mariadb", "mongodb", "mssql", "mysql", "oracle", "postgres", "sqlite", "better-sqlite3", "sqljs", "react-native", "aurora-data-api", "aurora-data-api-pg".
    at new MissingDriverError (/Users/shokishoki/development/ontologie/tolo/node_modules/typeorm/error/MissingDriverError.js:10:28)
    at DriverFactory.create (/Users/shokishoki/development/ontologie/tolo/node_modules/typeorm/driver/DriverFactory.js:67:23)
    at new Connection (/Users/shokishoki/development/ontologie/tolo/node_modules/typeorm/connection/Connection.js:53:59)
    at ConnectionManager.create (/Users/shokishoki/development/ontologie/tolo/node_modules/typeorm/connection/ConnectionManager.js:56:26)
    at /Users/shokishoki/development/ontologie/tolo/node_modules/typeorm/index.js:194:66
    at step (/Users/shokishoki/development/ontologie/tolo/node_modules/typeorm/node_modules/tslib/tslib.js:141:27)
    at Object.next (/Users/shokishoki/development/ontologie/tolo/node_modules/typeorm/node_modules/tslib/tslib.js:122:57)
    at /Users/shokishoki/development/ontologie/tolo/node_modules/typeorm/node_modules/tslib/tslib.js:115:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/Users/shokishoki/development/ontologie/tolo/node_modules/typeorm/node_modules/tslib/tslib.js:111:16) {
  name: 'MissingDriverError',
  message: 'Wrong driver: "postgresql" given. Supported drivers are: "cordova", "expo", "mariadb", "mongodb", "mssql", "mysql", "oracle", "postgres", "sqlite", "better-sqlite3", "sqljs", "react-native", "aurora-data-api", "aurora-data-api-pg".'
}
https://next-auth.js.org/errors#adapter_connection_error
(node:34898) UnhandledPromiseRejectionWarning: TypeError: Cannot destructure property 'manager' of 'connection' as it is null.
    at Object.<anonymous> (/Users/shokishoki/development/ontologie/tolo/node_modules/next-auth/dist/adapters/typeorm/index.js:102:9)
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/shokishoki/development/ontologie/tolo/node_modules/next-auth/dist/adapters/typeorm/index.js:28:103)
    at _next (/Users/shokishoki/development/ontologie/tolo/node_modules/next-auth/dist/adapters/typeorm/index.js:30:194)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:34898) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
(node:34898) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [X] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [ ] Could not find relevant documentation
* [ ] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by PaulKushch** [comment]
@shkfnly any news on your issue? I have the same issue. Best regards

**Comment by morganhvidt** [comment]
Could you paste your NextAuth config file here?
Just for reference, I'm using a connection string without issues for my local development.
`database: 'postgres://postgres:password@localhost:5432/postgres'`

I've also installed the Postgres package via npm. 
` npm install pg`

**Comment by dayvista** [comment]
I ran into this issue and was able to solve it using the comment from @morganhvidt 
My database connection string was using 'postgres**ql**://...' instead of 'postgres://...'
Hope this saves someone else ~10 minutes of Googling.
