### ISSUE TITLE
Getting a oauth_parse_profile_error for the Spotify provider when the user has no profile images

### ISSUE THREAD

**Issue by davidnoorda** [nextauthjs/next-auth#740]
**Describe the bug**
Getting a oauth_parse_profile_error for the Spotify provider when the authenticating user has no profile images.

**Steps to reproduce**
1. Setup the Spotify provider
2. Log in as a user with no profile images in Spotify

**Expected behavior**
The user is able to login successfully.

**Screenshots or error logs**
`[next-auth][error][oauth_parse_profile_error] [
  TypeError: Cannot read property 'url' of undefined
      at Object.profile (C:\...\node_modules\next-auth\dist\providers\spotify.js:32:35)
      at C:\...\node_modules\next-auth\dist\server\lib\oauth\callback.js:172:32
      at Generator.next (<anonymous>)
      at asyncGeneratorStep (C:\...\node_modules\next-auth\dist\server\lib\oauth\callback.js:26:103)
      at _next (C:\...\node_modules\next-auth\dist\server\lib\oauth\callback.js:28:194)
      at C:\...\node_modules\next-auth\dist\server\lib\oauth\callback.js:28:364
      at new Promise (<anonymous>)
      at C:\...\node_modules\next-auth\dist\server\lib\oauth\callback.js:28:97
      at _getProfile2 (C:\...\node_modules\next-auth\dist\server\lib\oauth\callback.js:200:23)
      at _getProfile (C:\...\node_modules\next-auth\dist\server\lib\oauth\callback.js:150:23),
  {
    display_name: 'david',
    email: 'david@test.com',
    external_urls: {
      spotify: 'https://open.spotify.com/user/{id}'
    },
    followers: { href: null, total: 0 },
    href: 'https://api.spotify.com/v1/users/{id}',
    id: '{id}',
    images: [],
    type: 'user',
    uri: 'spotify:user:{id}'
  }
]
https://next-auth.js.org/errors#oauth_parse_profile_error`

**Additional context**
I think this is a pretty simple fix in the providers/spotify.js file but let me know if you need any further information.

Thanks!

**Comment by davidnoorda** [comment]
Sorry just found that this has been fixed already.

https://github.com/nextauthjs/next-auth/pull/612

I'll wait for the next release. Thanks.
