### ISSUE TITLE
authentik: Misleading/Wrong error message

### ISSUE THREAD

**Issue by mpldr** [nextauthjs/next-auth#7428]
### Provider type

Authentik

### Environment

  System:
    OS: Linux 6.2 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (4) x64 QEMU Virtual CPU version 2.5+
    Memory: 2.03 GB / 9.72 GB
    Container: Yes
    Shell: 5.1.4 - /bin/bash
  Binaries:
    Node: 16.20.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.4 - /usr/local/bin/npm

### Reproduction URL

https://github.com/ndom91/briefkasten

### Describe the issue

With this config:
```
NEXTAUTH_URL: https://briefkasten.[redacted]
NEXTAUTH_SECRET: [redacted]
AUTHENTIK_NAME: ID Server
AUTHENTIK_ID: [redacted]
AUTHENTIK_SECRET: [redacted]
AUTHENTIK_ISSUER: https://id.[redacted]/application/o/briefkasten/
```

I get this error:
```
briefkasten-briefkasten-1  | [next-auth][error][SIGNIN_OAUTH_ERROR] 
briefkasten-briefkasten-1  | https://next-auth.js.org/errors#signin_oauth_error expected 200 OK, got: 301 Moved Permanently {
briefkasten-briefkasten-1  |   error: {
briefkasten-briefkasten-1  |     message: 'expected 200 OK, got: 301 Moved Permanently',
briefkasten-briefkasten-1  |     stack: 'OPError: expected 200 OK, got: 301 Moved Permanently\n' +
briefkasten-briefkasten-1  |       '    at processResponse (/app/node_modules/.pnpm/openid-client@5.1.6/node_modules/openid-client/lib/helpers/process_response.js:41:11)\n' +
briefkasten-briefkasten-1  |       '    at Function.discover (/app/node_modules/.pnpm/openid-client@5.1.6/node_modules/openid-client/lib/issuer.js:152:20)\n' +
briefkasten-briefkasten-1  |       '    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n' +
briefkasten-briefkasten-1  |       '    at async openidClient (/app/node_modules/.pnpm/next-auth@4.18.8_next@13.1.6_nodemailer@6.9.0_react-dom@18.2.0_react@18.2.0/node_modules/next-auth/core/lib/oauth/client.js:16:14)\n' +
briefkasten-briefkasten-1  |       '    at async getAuthorizationUrl (/app/node_modules/.pnpm/next-auth@4.18.8_next@13.1.6_nodemailer@6.9.0_react-dom@18.2.0_react@18.2.0/node_modules/next-auth/core/lib/oauth/authorization-url.js:67:18)\n' +
briefkasten-briefkasten-1  |       '    at async Object.signin (/app/node_modules/.pnpm/next-auth@4.18.8_next@13.1.6_nodemailer@6.9.0_react-dom@18.2.0_react@18.2.0/node_modules/next-auth/core/routes/signin.js:38:24)\n' +
briefkasten-briefkasten-1  |       '    at async AuthHandler (/app/node_modules/.pnpm/next-auth@4.18.8_next@13.1.6_nodemailer@6.9.0_react-dom@18.2.0_react@18.2.0/node_modules/next-auth/core/index.js:253:26)\n' +
briefkasten-briefkasten-1  |       '    at async NextAuthHandler (/app/node_modules/.pnpm/next-auth@4.18.8_next@13.1.6_nodemailer@6.9.0_react-dom@18.2.0_react@18.2.0/node_modules/next-auth/next/index.js:23:19)\n' +
briefkasten-briefkasten-1  |       '    at async /app/node_modules/.pnpm/next-auth@4.18.8_next@13.1.6_nodemailer@6.9.0_react-dom@18.2.0_react@18.2.0/node_modules/next-auth/next/index.js:59:32\n' +
briefkasten-briefkasten-1  |       '    at async Object.apiResolver (/app/node_modules/.pnpm/next@13.1.6_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/api-utils/node.js:372:9)',
briefkasten-briefkasten-1  |     name: 'OPError'
briefkasten-briefkasten-1  |   },
briefkasten-briefkasten-1  |   providerId: 'authentik',
briefkasten-briefkasten-1  |   message: 'expected 200 OK, got: 301 Moved Permanently'
briefkasten-briefkasten-1  | }
```

### How to reproduce

1. set up as documented
2. disable TLS1.3 because Node apparently can't handle that
3. try a variety of other URLS (.well-known URL, localhost as `NEXTAUTH_URL`, …)

Things that don't add up:
- the HTTP response code of the application-URL is: `HTTP/2 302`
- TLS1.3 prints `https://next-auth.js.org/errors#client_fetch_error request to https://briefkasten.[redacted]/api/auth/providers failed, reason: getaddrinfo ENOTFOUND briefkasten.[redacted] {` which looks like a DNS issue, which it is decidedly not.
- Pretty sure it is not related to cookies

### Expected behavior

a clearer error message **or** it follows the redirect

**Comment by balazsorban44** [comment]
From the looks of it, it might be the trailing slash on the issuer.

Could you remove it?

```diff
+ https://id.[redacted]/application/o/briefkasten
- https://id.[redacted]/application/o/briefkasten/
```

**Comment by mpldr** [comment]
Thanks, that indeed fixed it. I have no idea why though as it simply redirects to the with-slash-version. But at least with this the return code matches.

## **without** slash:
```console
$ curl -IL https://id.[redacted]/application/o/briefkasten
HTTP/2 301 
alt-svc: h3=":443"; ma=2592000
content-type: text/html; charset=utf-8
date: Wed, 03 May 2023 12:03:26 GMT
location: /application/o/briefkasten/
referrer-policy: same-origin
server: Caddy
vary: Accept-Encoding
vary: Cookie
x-authentik-id: e4d4d43daddd469db01a0f0236ce4e6c
x-content-type-options: nosniff
x-powered-by: authentik
content-length: 0

HTTP/2 302 
alt-svc: h3=":443"; ma=2592000
content-type: text/html; charset=utf-8
date: Wed, 03 May 2023 12:03:26 GMT
location: /application/o/briefkasten/.well-known/openid-configuration
referrer-policy: same-origin
server: Caddy
vary: Accept-Encoding
vary: Cookie
x-authentik-id: 7525bc37dd7945f499dca7662d6a3304
x-content-type-options: nosniff
x-frame-options: DENY
x-powered-by: authentik
content-length: 0

HTTP/2 200 
alt-svc: h3=":443"; ma=2592000
content-type: application/json
date: Wed, 03 May 2023 12:03:26 GMT
referrer-policy: same-origin
server: Caddy
vary: Accept-Encoding
vary: Cookie
x-authentik-id: 1e1bdf7346804a3b826e0ac9719dee25
x-content-type-options: nosniff
x-frame-options: DENY
x-powered-by: authentik
content-length: 1788
```

## with slash

```console
$ curl -IL https://id.[redacted]/application/o/briefkasten/
HTTP/2 302 
alt-svc: h3=":443"; ma=2592000
content-type: text/html; charset=utf-8
date: Wed, 03 May 2023 12:05:40 GMT
location: /application/o/briefkasten/.well-known/openid-configuration
referrer-policy: same-origin
server: Caddy
vary: Accept-Encoding
vary: Cookie
x-authentik-id: f4a3b929f8614b2d94b4e84aa612c922
x-content-type-options: nosniff
x-frame-options: DENY
x-powered-by: authentik
content-length: 0

HTTP/2 200 
alt-svc: h3=":443"; ma=2592000
content-type: application/json
date: Wed, 03 May 2023 12:05:40 GMT
referrer-policy: same-origin
server: Caddy
vary: Accept-Encoding
vary: Cookie
x-authentik-id: 21b25784f1384fc588911ed7f109f0d1
x-content-type-options: nosniff
x-frame-options: DENY
x-powered-by: authentik
content-length: 1788
```

**Comment by mpldr** [comment]
While I agree that my problem has been solved, I don't think the underlying issue has been. In fact, the solution made it even weirder and more confusing.

**Comment by mpldr** [comment]
> even though it is not expected to do so

To be honest, if a .well-known URL is expected it would be better to just take that.
![2023-05-04-19-14-43](https://user-images.githubusercontent.com/33086936/236277701-1f403862-bf50-4c19-9a1d-84cbd8192319.png)

Adding to that that URLs with multiple slashes in the path [are invalid](https://www.rfc-editor.org/rfc/rfc3986#section-3.3), so I think it's somewhat reasonable to expect servers to auto-correct them.
