### ISSUE TITLE
The error message on authentication failure has very little information 

### ISSUE THREAD

**Issue by ziedHamdi** [nextauthjs/next-auth#7444]
### Environment

  System:
    OS: Linux 5.19 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Memory: 22.90 GB / 31.25 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.14.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 9.3.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 112.0.5615.165
    Firefox: 112.0.2

### Reproduction URL

https://github.com/ziedHamdi/authsvelte

### Describe the issue

error {
  error: 'invalid_client',
  error_description: 'Client authentication failed'
}
[auth][error][CallbackRouteError]: Read more at https://errors.authjs.dev#callbackrouteerror
[auth][cause]: Error: TODO: Handle OAuth 2.0 response body error
    at handleOAuth (file:///home/zied/WebstormProjects/sveltekit/node_modules/.pnpm/@auth+core@0.5.1/node_modules/@auth/core/lib/oauth/callback.js:91:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Module.callback (file:///home/zied/WebstormProjects/sveltekit/node_modules/.pnpm/@auth+core@0.5.1/node_modules/@auth/core/lib/routes/callback.js:14:41)
    at async AuthInternal (file:///home/zied/WebstormProjects/sveltekit/node_modules/.pnpm/@auth+core@0.5.1/node_modules/@auth/core/lib/index.js:64:38)
    at async Proxy.Auth (file:///home/zied/WebstormProjects/sveltekit/node_modules/.pnpm/@auth+core@0.5.1/node_modules/@auth/core/index.js:100:30)
    at async respond (file:///home/zied/WebstormProjects/sveltekit/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.589_svelte@3.55.0_vite@4.0.1/node_modules/@sveltejs/kit/src/runtime/server/index.js:229:20)
    at async file:///home/zied/WebstormProjects/sveltekit/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.589_svelte@3.55.0_vite@4.0.1/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:444:22
[auth][details]: {
  "provider": "linkedin"
}

### How to reproduce

Just try to login with a valid values in .env for
```
LINKED_IN_CLIENT_ID="your client id"
LINKED_IN_CLIENT_SECRET="your client secret"

```
(add localhost to callback urls in linkedIn)

then run the app 
```
pnpm install
pnpm run dev

```
and click on the LinkedIn login button, everything will work fine until the callback is called on the server: it throws he mentioned error

### Expected behavior

To have the user logged in successfully

**Comment by balazsorban44** [comment]
This information comes directly from your provider. We forward everything in the logs that we receive.

Check out the spec: https://www.ietf.org/rfc/rfc6749.html#section-5.2

`invalid_client` indicates:

> Client authentication failed (e.g., unknown client, no client authentication included, or unsupported authentication method).  The authorization server MAY return an HTTP 401 (Unauthorized) status code to indicate which HTTP authentication schemes are supported.  If the client attempted to authenticate via the "Authorization" request header field, the authorization server MUST respond with an HTTP 401 (Unauthorized) status code and include the "WWW-Authenticate" response header field matching the authentication scheme used by the client.

**Comment by geraldserafin** [comment]
Hey, @ziedHamdi did you manage to resolve this issue?
