### ISSUE TITLE
Broken on Next 13.4

### ISSUE THREAD

**Issue by AlvaroAquijeDiaz** [nextauthjs/next-auth#7449]
### Environment

  System:
    OS: macOS 13.3.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 1.34 GB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 19.8.1 - /opt/homebrew/bin/node
    npm: 9.5.1 - /opt/homebrew/bin/npm
    Watchman: 2023.01.16.00 - /opt/homebrew/bin/watchman
  Browsers:
    Safari: 16.4

### Reproduction URL

https://github.com/AlvaroAquijeDiaz/regiftt

### Describe the issue

Using next app router and setup an api-route for next-auth at `app/api/auth/[...nextauth]/route.ts` and I'm getting the following error when trying to login

```ts
error - TypeError: Cannot destructure property 'nextauth' of 'req.query' as it is undefined.
    at NextAuthHandler (webpack-internal:///(sc_server)/./node_modules/.pnpm/next-auth@4.21.0_next@13.4.0_react-dom@18.2.0_react@18.2.0/node_modules/next-auth/next/index.js:13:13)
    at eval (webpack-internal:///(sc_server)/./node_modules/.pnpm/next-auth@4.21.0_next@13.4.0_react-dom@18.2.0_react@18.2.0/node_modules/next-auth/next/index.js:46:40)
    at eval (webpack-internal:///(sc_server)/./node_modules/.pnpm/next@13.4.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/future/route-modules/app-route/module.js:244:43)
    at eval (webpack-internal:///(sc_server)/./node_modules/.pnpm/next@13.4.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/lib/trace/tracer.js:109:36)
    at NoopContextManager.with (webpack-internal:///(sc_server)/./node_modules/.pnpm/next@13.4.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/@opentelemetry/api/index.js:360:30)
    at ContextAPI.with (webpack-internal:///(sc_server)/./node_modules/.pnpm/next@13.4.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/@opentelemetry/api/index.js:30:58)
    at NoopTracer.startActiveSpan (webpack-internal:///(sc_server)/./node_modules/.pnpm/next@13.4.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/@opentelemetry/api/index.js:953:34)
    at ProxyTracer.startActiveSpan (webpack-internal:///(sc_server)/./node_modules/.pnpm/next@13.4.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/@opentelemetry/api/index.js:993:36)
    at eval (webpack-internal:///(sc_server)/./node_modules/.pnpm/next@13.4.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/lib/trace/tracer.js:98:107)
    at NoopContextManager.with (webpack-internal:///(sc_server)/./node_modules/.pnpm/next@13.4.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/@opentelemetry/api/index.js:360:30)
    at ContextAPI.with (webpack-internal:///(sc_server)/./node_modules/.pnpm/next@13.4.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/@opentelemetry/api/index.js:30:58)
    at NextTracerImpl.trace (webpack-internal:///(sc_server)/./node_modules/.pnpm/next@13.4.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/lib/trace/tracer.js:98:32)
    at eval (webpack-internal:///(sc_server)/./node_modules/.pnpm/next@13.4.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/future/route-modules/app-route/module.js:232:53)
    at AsyncLocalStorage.run (node:async_hooks:338:14)
    at Object.wrap (webpack-internal:///(sc_server)/./node_modules/.pnpm/next@13.4.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/async-storage/static-generation-async-storage-wrapper.js:39:24)
    at eval (webpack-internal:///(sc_server)/./node_modules/.pnpm/next@13.4.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/future/route-modules/app-route/module.js:186:97)
    at AsyncLocalStorage.run (node:async_hooks:338:14)
    at Object.wrap (webpack-internal:///(sc_server)/./node_modules/.pnpm/next@13.4.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/async-storage/request-async-storage-wrapper.js:77:24)
    at eval (webpack-internal:///(sc_server)/./node_modules/.pnpm/next@13.4.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/future/route-modules/app-route/module.js:185:75)
    at AsyncLocalStorage.run (node:async_hooks:338:14)
    at AppRouteRouteModule.execute (webpack-internal:///(sc_server)/./node_modules/.pnpm/next@13.4.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/future/route-modules/app-route/module.js:182:56)
    at AppRouteRouteModule.handle (webpack-internal:///(sc_server)/./node_modules/.pnpm/next@13.4.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/future/route-modules/app-route/module.js:332:41)
    at RouteHandlerManager.handle (/Users/a3tech/Developer/personal_projects/regiftt/node_modules/.pnpm/next@13.4.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/future/route-handler-managers/route-handler-manager.js:28:29)
    at doRender (/Users/a3tech/Developer/personal_projects/regiftt/node_modules/.pnpm/next@13.4.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/base-server.js:935:58)
    at cacheEntry.responseCache.get.incrementalCache.incrementalCache (/Users/a3tech/Developer/personal_projects/regiftt/node_modules/.pnpm/next@13.4.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/base-server.js:1149:46)
    at /Users/a3tech/Developer/personal_projects/regiftt/node_modules/.pnpm/next@13.4.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/response-cache/index.js:99:42
    at ResponseCache.get (/Users/a3tech/Developer/personal_projects/regiftt/node_modules/.pnpm/next@13.4.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/response-cache/index.js:149:11)
    at DevServer.renderToResponseWithComponentsImpl (/Users/a3tech/Developer/personal_projects/regiftt/node_modules/.pnpm/next@13.4.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/base-server.js:1078:53)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

```

### How to reproduce

1. See the repo
2. click on SignIn, you'll get the error
3. also trying to use `getServerSession` return null and also getting the same error

### Expected behavior

it should work as with `pages`

**Comment by AlvaroAquijeDiaz** [comment]
seems to be fixed in `4.22.1` 🎉

**Comment by miro-zone** [comment]
have the same problem with exact environment

**Comment by salman0ansari** [comment]
how to fix this i am using app router
