### ISSUE TITLE
signin_oauth_error azure-ad outgoing request timed out after 3500ms

### ISSUE THREAD

**Issue by walidmourou** [nextauthjs/next-auth#7516]
### Environment

```javascript
{
  "name": "my_app",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
  },
  "dependencies": {
    "@emotion/react": "^11.10.6",
    "@testing-library/react": "^14.0.0",
    "@types/node": "18.15.11",
    "@types/react": "18.0.37",
    "@types/react-dom": "18.0.11",
    "next": "13.2.4",
    "next-auth": "^4.22.1",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "sharp": "^0.32.0",
    "typescript": "5.0.4"
  }
}
```

### Describe the issue

I am using SSO Azure AD authentication in my application. Locally (http://localhost:3000) it works fine. But when I deployed on K8s cluster (internal network of a private company) I get such an error displayed on the Pod logs:
```sh
[next-auth][warn][DEBUG_ENABLED]
https://next-auth.js.org/warnings#debug_enabled
[next-auth][error][SIGNIN_OAUTH_ERROR]
https://next-auth.js.org/errors#signin_oauth_error outgoing request timed out after 3500ms {
error: {
message: 'outgoing request timed out after 3500ms',
stack: 'RPError: outgoing request timed out after 3500ms\n' +
' at /app/node_modules/openid-client/lib/helpers/request.js:137:13\n' +
' at async Issuer.discover (/app/node_modules/openid-client/lib/issuer.js:144:24)\n' +
' at async openidClient (/app/node_modules/next-auth/core/lib/oauth/client.js:16:14)\n' +
' at async getAuthorizationUrl (/app/node_modules/next-auth/core/lib/oauth/authorization-url.js:70:18)\n' +
' at async Object.signin (/app/node_modules/next-auth/core/routes/signin.js:38:24)\n' +
' at async AuthHandler (/app/node_modules/next-auth/core/index.js:260:26)\n' +
' at async NextAuthApiHandler (/app/node_modules/next-auth/next/index.js:22:19)\n' +
' at async NextAuth._args$ (/app/node_modules/next-auth/next/index.js:106:14)\n' +
' at async Object.apiResolver (/app/node_modules/next/dist/server/api-utils/node.js:372:9)\n' +
' at async NextNodeServer.runApi (/app/node_modules/next/dist/server/next-server.js:514:9)',
name: 'RPError'
},
providerId: 'azure-ad',
message: 'outgoing request timed out after 3500ms'
}
```
The front-end UI display **Try signing in with a different account.**
![image](https://github.com/nextauthjs/next-auth/assets/46028071/0a6a7965-3924-4d27-b487-063fa2a5dbcc)

### How to reproduce

In *[...nextauth].ts*:
```
import NextAuth, { NextAuthOptions } from "next-auth";
import AzureADProvider from "next-auth/providers/azure-ad";
import { HttpsProxyAgent } from "https-proxy-agent";

const authOptions: NextAuthOptions = {
  providers: [
    AzureADProvider({
      id: "azure-ad",
      name: "Azure AD",
      tenantId: process.env.NEXT_PUBLIC_TENANT_NAME as string,
      clientId: process.env.NEXT_PUBLIC_CLIENT_ID as string,
      clientSecret: process.env.NEXTAUTH_SECRET as string,
    }),
  ],
  callbacks: {
    async jwt({ token, account }) {
      var myHeaders = new Headers();
      if (account) {
        myHeaders.append("Authorization", account.access_token);
        let fetchOptions = {
          method: "GET",
          headers: myHeaders,
          redirect: "follow",
          agent: new HttpsProxyAgent("http://proxy.company.com:8080"),
        } as RequestInit;
        token.iNumber = await fetch(
          "https://graph.microsoft.com/v1.0/me?$select=displayName,mail",
          fetchOptions
        )
          .then((response) => response.json())
          .then((response) => response["onPremisesSamAccountName"])
          .catch((error) => console.log("error", error));
      }
      return token;
    },
    async session({ session, token, user }) {
      return {
        ...session,
        user: {
          ...session.user,
          iNumber: token.iNumber,
        },
      };
    },
  },
  debug: true,
};

export default NextAuth(authOptions);
```
You can see that I added a *HttpsProxyAgent* agent to the options of the fetch function as indicated here https://next-auth.js.org/tutorials/corporate-proxy

### Expected behavior

I expected to be redirected to the root page after authentification.
But here is the URL: https://app-hostname.com/api/auth/signin?error=OAuthSignin

**Comment by walidmourou** [comment]
Since [NextAuth](https://next-auth.js.org/) don't support HTTTP proxy (corporate-proxy), the solution of this issue is mentioned here:
https://next-auth.js.org/tutorials/corporate-proxy
and here 
https://github.com/nextauthjs/next-auth/issues/2509#issuecomment-1035410802
Then if someone use one of the defined providers like [`azure-ad`](https://github.com/nextauthjs/next-auth/blob/main/packages/next-auth/src/providers/azure-ad.ts), he will get then this error:
```sh
[next-auth][error][OAUTH_PARSE_PROFILE_ERROR]
https://next-auth.js.org/errors#oauth_parse_profile_error fetch failed {
error: {
message: 'fetch failed',
stack: 'TypeError: fetch failed\n' +
' at Object.fetch (node:internal/deps/undici/undici:11457:11)\n' +
' at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
' at async Object.profile (/app/node_modules/next-auth/providers/azure-ad.js:27:24)\n' +
' at async getProfile (/app/node_modules/next-auth/core/lib/oauth/callback.js:162:21)\n' +
' at async oAuthCallback (/app/node_modules/next-auth/core/lib/oauth/callback.js:136:27)\n' +
' at async Object.callback (/app/node_modules/next-auth/core/routes/callback.js:52:11)\n' +
' at async AuthHandler (/app/node_modules/next-auth/core/index.js:208:28)\n' +
' at async NextAuthApiHandler (/app/node_modules/next-auth/next/index.js:22:19)\n' +
' at async NextAuth._args$ (/app/node_modules/next-auth/next/index.js:106:14)\n' +
' at async Object.apiResolver (/app/node_modules/next/dist/server/api-utils/node.js:372:9)',
name: 'TypeError'
},
```
This is because the fetch here is done without proxy agent definition:
https://github.com/nextauthjs/next-auth/blob/main/packages/next-auth/src/providers/azure-ad.ts#L36

I fix it by using `fetch` of [`node-fetch`](https://www.npmjs.com/package/node-fetch) and [`HttpsProxyAgent`](https://www.npmjs.com/package/https-proxy-agent)
```javascript
var HttpsProxyAgent = require("https-proxy-agent");
const fetch = (...args) => import("node-fetch").then(({ default: fetch }) => fetch(...args));

const response = await fetch(
        `https://graph.microsoft.com/v1.0/me/photos/${profilePhotoSize}x${profilePhotoSize}/$value`,
        {
          agent: new HttpsProxyAgent(process.env.http_proxy),
          headers: {
            Authorization: `Bearer ${tokens.access_token}`,
          },
        }
      );

```
