### ISSUE TITLE
SvelteKit: The callback error code doesn't change

### ISSUE THREAD

**Issue by skyf0l** [nextauthjs/next-auth#7530]
### Question 💬

I'm using AuthJs in a SvelteKit application with @auth/sveltekit. I figured out that all callbacks errors are redirected to <https://example.com/auth/error?error=CallbackRouteError>. Is it a bug or it's not possible to be redirected with a more specific error code like `AccountNotLinked`?

Here my logs:

```
[auth][error][AccountNotLinked]: Read more at https://errors.authjs.dev#accountnotlinked
[auth][cause]: AccountNotLinked: Another account already exists with the same e-mail address
    at handleLogin (file:///workspaces/monorepo/node_modules/.pnpm/@auth+core@0.5.1/node_modules/@auth/core/lib/callback-handler.js:158:27)
    at async Module.callback (file:///workspaces/monorepo/node_modules/.pnpm/@auth+core@0.5.1/node_modules/@auth/core/lib/routes/callback.js:46:50)
    at async AuthInternal (file:///workspaces/monorepo/node_modules/.pnpm/@auth+core@0.5.1/node_modules/@auth/core/lib/index.js:64:38)
    at async Proxy.Auth (file:///workspaces/monorepo/node_modules/.pnpm/@auth+core@0.5.1/node_modules/@auth/core/index.js:100:30)
    at async Module.respond (/@fs/workspaces/monorepo/node_modules/.pnpm/@sveltejs+kit@1.15.10_svelte@3.58.0_vite@4.3.4/node_modules/@sveltejs/kit/src/runtime/server/respond.js:259:20)
    at async file:///workspaces/monorepo/node_modules/.pnpm/@sveltejs+kit@1.15.10_svelte@3.58.0_vite@4.3.4/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:506:22
[auth][details]: {
  "provider": "github"
}
```

### How to reproduce ☕️

.

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by klaemo** [comment]
Yep, I'm experiencing the same. I'd like to show a more descriptive error message to the user.

I'm using `@auth/core@0.7.1`.

In the logs you can see that auth0 (in my case) responds with `access_denied` and even a human readable error_description`. Those then get turned into a generic `CallbackRouteError`.

Is there a way to get at this more specific error?

```
GET /api/auth/login 302 Found (163.72ms)
[auth][error][OAuthCallbackError]: Read more at https://errors.authjs.dev#oauthcallbackerror
[auth][cause]: OAuthCallbackError: access_denied
    at handleOAuth (/private/Users/clemens/Projects/webapp/node_modules/@auth/core/lib/oauth/callback.js:52:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at callback (/private/Users/clemens/Projects/webapp/node_modules/@auth/core/lib/routes/callback.js:20:41)
    at AuthInternal (/private/Users/clemens/Projects/webapp/node_modules/@auth/core/lib/index.js:65:38)
    at Auth (/private/Users/clemens/Projects/webapp/node_modules/@auth/core/index.js:100:30)
    at next (/private/Users/clemens/Projects/webapp/node_modules/wrangler/templates/pages-template-worker.ts:152:22)
    at errorHandler (/private/Users/clemens/Projects/webapp/functions/api/_middleware.ts:166:12)
    at next (/private/Users/clemens/Projects/webapp/node_modules/wrangler/templates/pages-template-worker.ts:152:22)
    at next (/private/Users/clemens/Projects/webapp/node_modules/wrangler/templates/pages-template-worker.ts:152:22)
    at next (/private/Users/clemens/Projects/webapp/node_modules/wrangler/templates/pages-template-worker.ts:152:22)
[auth][details]: {
  "provider": "auth0"
}
GET /api/auth/callback/auth0?error=access_denied&error_description=Please%20verify%20your%20email%20before%20logging%20in. 302 Found (235.00ms)
GET /api/auth/error?error=CallbackRouteError 302 Found (4.12ms)
```

**Comment by zimonitrome** [comment]
Same with SolidStart.

Ideally I'd like to make it such that each user is unique on provider and id instead of email like mentioned in #7731.

But since idk how that is possible, displaying an error would do, but unfortunately that also isn't possible.
