### ISSUE TITLE
Auth0 Provider TypeError: Invalid character in header content ["Location"]

### ISSUE THREAD

**Issue by shahbhavik01** [nextauthjs/next-auth#7561]
### Provider type

Auth0

### Environment

  System:
    OS: macOS 13.3.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 2.03 GB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 19.1.0 - /opt/homebrew/bin/node
    npm: 9.4.2 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 113.0.5672.92
    Firefox: 110.0
    Safari: 16.4

### Reproduction URL

Unable to provide

### Describe the issue

I had Auth0 provider integration working. This is my [...nextauth].js configuration. 

```
import NextAuth from "next-auth";
import Auth0Provider from "next-auth/providers/auth0";
import { PrismaAdapter } from "@next-auth/prisma-adapter";
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

export const authOptions = {
  adapter: PrismaAdapter(prisma),
  providers: [
    Auth0Provider({
      clientId: process.env.AUTH0_CLIENT_ID || "",
      clientSecret: process.env.AUTH0_CLIENT_SECRET || "",
      issuer: process.env.AUTH0_ISSUER,
      authorization: {
        params: {
          prompt: "login",
        },
      },
    }),
  ],
  secret: process.env.NEXTAUTH_SECRET,
  pages: {
    signIn: "/auth/signin",
    error: "/auth/error",
  },
  callbacks: {
    // TODO: Move this code to signup event
    async signIn(user, account, profile) {
      // // Update user name to match the name from profile
      const updateUser = await prisma.user.update({
        where: { email: user.user.email },
        data: { name: user.profile.name, id: user.id },
      });

      return true;
    },
    async session({ session, user, token }) {
      session = {
        ...session,
        user: {
          id: user.id,
          ...session.user,
        },
      };
      return session;
    },
  },
};

export default NextAuth(authOptions);
```

I didn't make any changes to the provider config, env vars or auth0 but for some reason, I'm getting the following error now. 

```
error - TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Location"]
    at ServerResponse.setHeader (node:_http_outgoing:647:3)
    at _res.setHeader (/Users/bshah/Documents/OneAct/oneact/node_modules/next/dist/server/base-server.js:129:24)
    at NextAuthApiHandler (/Users/bshah/Documents/OneAct/oneact/node_modules/next-auth/next/index.js:43:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async NextAuth._args$ (/Users/bshah/Documents/OneAct/oneact/node_modules/next-auth/next/index.js:106:14)
    at async Object.apiResolver (/Users/bshah/Documents/OneAct/oneact/node_modules/next/dist/server/api-utils/node.js:372:9)
    at async DevServer.runApi (/Users/bshah/Documents/OneAct/oneact/node_modules/next/dist/server/next-server.js:488:9)
    at async Object.fn (/Users/bshah/Documents/OneAct/oneact/node_modules/next/dist/server/next-server.js:751:37)
    at async Router.execute (/Users/bshah/Documents/OneAct/oneact/node_modules/next/dist/server/router.js:253:36)
    at async DevServer.run (/Users/bshah/Documents/OneAct/oneact/node_modules/next/dist/server/base-server.js:384:29)
    at async DevServer.run (/Users/bshah/Documents/OneAct/oneact/node_modules/next/dist/server/dev/next-dev-server.js:743:20)
    at async DevServer.handleRequest (/Users/bshah/Documents/OneAct/oneact/node_modules/next/dist/server/base-server.js:322:20) {
  code: 'ERR_INVALID_CHAR',
  page: '/api/auth/[...nextauth]'
}
```

Can someone please help me debug this? I triple checked that the issue is not with the env vars or auth callback urls. 

### How to reproduce

I'm using Prisma with Auth0. I have the settings as described above. I'm using the latest next-auth package  "next-auth": "^4.22.1". This error happens when a user tries to login/signup. I can see that auth0 actually creates the user but the error happens when it's directed back to the application. 

### Expected behavior

Upon login, user should be redirected to the callback url without any errors.

**Comment by shahbhavik01** [comment]
There is this thread from 2020 but I am using the latest modules. I don't have any special characters either. I have Alpha-numeric characters in my callback URL only. https://github.com/vercel/next.js/issues/17907
