### ISSUE TITLE
After switching to Turbopack i get crypto.getRandomValues() not supported.

### ISSUE THREAD

**Issue by kapitalistn** [nextauthjs/next-auth#7609]
### Question 💬

When I enable Turbopack i get following error: 

[next-auth][error][JWT_SESSION_ERROR]
https://next-auth.js.org/errors#jwt_session_error crypto.getRandomValues() not supported. See https://github.com/uuidjs/uuid#getrandomvalues-not-supported {
  message: 'crypto.getRandomValues() not supported. See https://github.com/uuidjs/uuid#getrandomvalues-not-supported',
  stack: 'Error: crypto.getRandomValues() not supported. See https://github.com/uuidjs/uuid#getrandomvalues-not-supported\n' +
    '    at rng (C:\\akademia\\.next\\server\\app\\chunks\\ssr\\node_modules_34ddeb._.js:235203:19)\n' +
    '    at v4 (C:\\akademia\\.next\\server\\app\\chunks\\ssr\\node_modules_34ddeb._.js:235222:191)\n' +
    '    at Object.encode (C:\\akademia\\.next\\server\\app\\chunks\\ssr\\node_modules_34ddeb._.js:215033:76)\n' +
    '    at async Object.session (C:\\akademia\\.next\\server\\app\\chunks\\ssr\\node_modules_34ddeb._.js:215940:30)\n' +
    '    at async AuthHandler (C:\\akademia\\.next\\server\\app\\chunks\\ssr\\node_modules_34ddeb._.js:217578:37)\n' +
    '    at async Module.getServerSession (C:\\akademia\\.next\\server\\app\\chunks\\ssr\\node_modules_34ddeb._.js:217906:21)\n' +
    '    at async getSession (C:\\akademia\\.next\\server\\app\\chunks\\ssr\\app_actions_getCurrentUser.ts_e5e7e1._.js:17:12)\n' +
    '    at async Module.getCurrentUser (C:\\akademia\\.next\\server\\app\\chunks\\ssr\\app_actions_getCurrentUser.ts_e5e7e1._.js:21:25)\n' +
    '    at async GET (C:\\akademia\\.next\\server\\app\\chunks\\ssr\\app_api_courses_route.ts_f91375._.js:49:25)\n' +
    '    at async C:\\akademia\\.next\\server\\app\\chunks\\ssr\\node_modules_34ddeb._.js:210465:37',
  name: 'Error'
}
warning - [parse]
  ... [2 paths] are hidden, run with --show-all to show them
event - 7 requests (GET /api/courses, ...) 1540ms
event - 62 requests (GET /turbopack-hmr, ...) 40ms
event - 7 requests (GET /api/courses, ...) 745ms

### How to reproduce ☕️

Install Next.js 13.4.2, NextAuth 4.22.1, bcryptjs 2.4.3 and enable turbopack in package.json.

Configure credentials sign in.

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by godfrednanaowusu** [comment]
its same as this issue here https://github.com/nextauthjs/next-auth/discussions/7361
