### ISSUE TITLE
Unable to access session using getSession() in api routes

### ISSUE THREAD

**Issue by jrereyi2000** [nextauthjs/next-auth#762]
Bug Description:

In the next-auth-example project, ```getSession({req})``` is used to access the session in an api route (https://github.com/nextauthjs/next-auth-example/blob/main/pages/api/examples/session.js).  Every time I try to use getSession({req}) in an api route, however, I get a CLIENT_FETCH_ERROR.

Steps to reproduce:

1. Clone next-auth-example repository 
2. Follow next-auth-example setup as specified @ https://github.com/nextauthjs/next-auth-example
3. In protected.js or session.js, try to log the session variable created as a result of getSession({req})

Expected Behavior:

Expected that using ```const session = await getSession({ req });``` would store the auth session in the session variable, instead of reporting an error.

Error Logs:

The Client Fetch Error I was getting looks like this

```
[next-auth][error][CLIENT_FETCH_ERROR] [
  'http://localhost:3000/api/auth/session',
  FetchError: invalid json response body at http://localhost:3000/api/auth/session reason: Unexpected token E in JSON at position 0
      at /Users/jereyi/Downloads/next-auth-app/node_modules/next/dist/compiled/node-fetch/index.js:1:52179
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5) {
    type: 'invalid-json'
  }
] 
```

Additional Context:

After doing some debugging in the dist folder, it seems like the underlying reason for this CLIENT_FETCH_ERROR is that I'm getting a 504 Gateway Timeout error whenever I try to access the route 'api/auth/session'. I tried to build my own getSession() function, just hitting 'api/auth/session' using the 'fetch' api, but I still got the 504 Gateway Timeout Error.

All of the routes are simple that I'm trying to get the session in, for example:

```
//I've tried this both with and without setOptions, because it seems like it's no longer necessary in //v3, and neither works.
import { getSession, setOptions } from "next-auth/client";

setOptions({ site: process.env.SITE });

export default async (req, res) => {
  const session = await getSession({ req });
  console.log("sesssion in api is", JSON.stringify(session, null, 4));

  if (session) {
    res.send({
      content:
        "This is protected content. You can access this content because you are signed in.",
    });
  } else {
    res.send({
      error: "You must be sign in to view the protected content on this page.",
    });
  }
};
```

This is the getSession function I tried to write:

```
export const getSession = async () => {
  const session = await fetch(`${process.env.SITE}/api/auth/session`);
  if (session === {}) {
    return null;
  }
  return session;
};
```

**Comment by balazsorban44** [comment]
Hi there! Could you please provide a reproduction repository with a link, so we can help you more easily?

Also, which versions of Next.js and next-auth are you using exactly?
