### ISSUE TITLE
Okta Provider expected 200 got 401

### ISSUE THREAD

**Issue by ppetitto1** [nextauthjs/next-auth#7656]
### Question 💬

Hey guys, thanks for reviewing my question. In short, when I use an Okta developer account, NextAuth works fine. When I switch to my production org, however, I am getting this error back.
`[next-auth][error][SIGNIN_OAUTH_ERROR] 
https://next-auth.js.org/errors#signin_oauth_error expected 200 OK, got: 401 Unauthorized {
  error: {
    message: 'expected 200 OK, got: 401 Unauthorized',
    stack: 'OPError: expected 200 OK, got: 401 Unauthorized\n' +
      '    at processResponse (/var/task/node_modules/openid-client/lib/helpers/process_response.js:41:11)\n' +
      '    at Issuer.discover (/var/task/node_modules/openid-client/lib/issuer.js:152:20)\n' +
      '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
      '    at async openidClient (/var/task/node_modules/next-auth/core/lib/oauth/client.js:16:14)\n' +
      '    at async getAuthorizationUrl (/var/task/node_modules/next-auth/core/lib/oauth/authorization-url.js:70:18)\n' +
      '    at async Object.signin (/var/task/node_modules/next-auth/core/routes/signin.js:38:24)\n' +
      '    at async AuthHandler (/var/task/node_modules/next-auth/core/index.js:260:26)\n' +
      '    at async NextAuthApiHandler (/var/task/node_modules/next-auth/next/index.js:22:19)\n' +
      '    at async NextAuth._args$ (/var/task/node_modules/next-auth/next/index.js:106:14)',
    name: 'OPError'
  },
  providerId: 'okta',
  message: 'expected 200 OK, got: 401 Unauthorized'
}`

About the code:
I used the create t3 app to initialize the code. I modified it for Okta and tested using a developer org. All of that was gravy baby, yet I'm having issues when using a production org's credentials. I'm thinking some kind of access issue but not sure what could cause this.

I had a lengthy discussion with ChatGPT in which i double checked my Client Id, Client Secret, Okta Domain, scopes, trusted origin, and CORS settings. Things appear to be configured correctly, however I am still getting this error. I consulted the docs and saw that this error is usually a misconfiguration (https://next-auth.js.org/errors).

Are there any considerations for Production Okta orgs compared to developer instances? Is any additional configuration needed within NextAuth in order to work with a production Okta Provider?

Thanks,
Paul

### How to reproduce ☕️

Here is my auth.ts file

```import { type GetServerSidePropsContext } from "next";
import {
  getServerSession,
  type NextAuthOptions,
  type DefaultSession,
} from "next-auth";
import Okta from "next-auth/providers/okta";
import { env } from "~/env.mjs";

/**
 * Module augmentation for `next-auth` types. Allows us to add custom properties to the `session`
 * object and keep type safety.
 *
 * @see https://next-auth.js.org/getting-started/typescript#module-augmentation
 */
declare module "next-auth" {
  interface Session extends DefaultSession {
    user: {
      id: string;
      // ...other properties
      // role: UserRole;
    } & DefaultSession["user"];
  }

  // interface User {
  //   // ...other properties
  //   // role: UserRole;
  // }
}

/**
 * Options for NextAuth.js used to configure adapters, providers, callbacks, etc.
 *
 * @see https://next-auth.js.org/configuration/options
 */
export const authOptions: NextAuthOptions = {
  debug: true,
  callbacks: {
    session: ({ session, token }) => ({
      ...session,
      user: {
        ...session.user,
        id: token.sub,
      },
    }),
  },
  providers: [
    Okta({
      clientId: env.OKTA_CLIENT_ID,
      clientSecret: env.OKTA_CLIENT_SECRET,
      issuer: env.OKTA_DOMAIN,
    }),
    /**
     * @see https://next-auth.js.org/providers/okta
     */
  ],
};

/**
 * Wrapper for `getServerSession` so that you don't need to import the `authOptions` in every file.
 *
 * @see https://next-auth.js.org/configuration/nextjs
 */
export const getServerAuthSession = (ctx: {
  req: GetServerSidePropsContext["req"];
  res: GetServerSidePropsContext["res"];
}) => {
  return getServerSession(ctx.req, ctx.res, authOptions);
};
```

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by ppetitto1** [comment]
Issue was i had OKTA_DOMAIN = myDomain.okta.com/oauth/default

when i changed it to OKTA_DOMAIN = myDomain.okta.com it worked
