### ISSUE TITLE
Custom login failure

### ISSUE THREAD

**Issue by overdev-l** [nextauthjs/next-auth#7797]
### Adapter type

@auth/prisma-adapter

### Environment

System:
    OS: macOS 13.4
    CPU: (8) arm64 Apple M1
    Memory: 75.09 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.3.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.6.7 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 114.0.5735.106
    Safari: 16.5

  npmPackages:
    @next-auth/prisma-adapter: ^1.0.5 => 1.0.5 

### Reproduction URL

https://github.com/overdev-l/tbaotu.git

### Describe the issue

I'm using nextAuth with Prisma to verify that the user login email and password are correct, but I just visit my /login page terminal and it throws an exception, I checked my code and looked at some Issues and I asked chatGPT😂, so far I didn't find a solution, I created the project using T3 and you can reproduce the problem by just visiting login

`[next-auth][error][adapter_error_getSessionAndUser] 
https://next-auth.js.org/errors#adapter_error_getsessionanduser Cannot read properties of undefined (reading 'findUnique') {
  message: "Cannot read properties of undefined (reading 'findUnique')",
  stack: "TypeError: Cannot read properties of undefined (reading 'findUnique')\n" +
    '    at getSessionAndUser (/Users/liuyongzhi/Desktop/workspace/tbauto/node_modules/.pnpm/@next-auth+prisma-adapter@1.0.5_@prisma+client@4.14.0_next-auth@4.22.1/node_modules/@next-auth/prisma-adapter/dist/index.js:24:52)\n' +
    '    at _callee2$ (/Users/liuyongzhi/Desktop/workspace/tbauto/node_modules/.pnpm/next-auth@4.22.1_next@13.4.2_react-dom@18.2.0_react@18.2.0/node_modules/next-auth/core/errors.js:365:29)\n' +
    '    at tryCatch (/Users/liuyongzhi/Desktop/workspace/tbauto/node_modules/.pnpm/@babel+runtime@7.22.5/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:44:17)\n' +
    '    at Generator.<anonymous> (/Users/liuyongzhi/Desktop/workspace/tbauto/node_modules/.pnpm/@babel+runtime@7.22.5/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:125:22)\n' +
    '    at Generator.next (/Users/liuyongzhi/Desktop/workspace/tbauto/node_modules/.pnpm/@babel+runtime@7.22.5/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:69:21)\n' +
    '    at asyncGeneratorStep (/Users/liuyongzhi/Desktop/workspace/tbauto/node_modules/.pnpm/@babel+runtime@7.22.5/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)\n' +
    '    at _next (/Users/liuyongzhi/Desktop/workspace/tbauto/node_modules/.pnpm/@babel+runtime@7.22.5/node_modules/@babel/runtime/helpers/asyncToGenerator.js:22:9)\n' +
    '    at /Users/liuyongzhi/Desktop/workspace/tbauto/node_modules/.pnpm/@babel+runtime@7.22.5/node_modules/@babel/runtime/helpers/asyncToGenerator.js:27:7\n' +
    '    at new Promise (<anonymous>)\n' +
    '    at /Users/liuyongzhi/Desktop/workspace/tbauto/node_modules/.pnpm/@babel+runtime@7.22.5/node_modules/@babel/runtime/helpers/asyncToGenerator.js:19:12\n' +
    '    at Object.session (/Users/liuyongzhi/Desktop/workspace/tbauto/node_modules/.pnpm/next-auth@4.22.1_next@13.4.2_react-dom@18.2.0_react@18.2.0/node_modules/next-auth/core/routes/session.js:92:34)\n' +
    '    at AuthHandler (/Users/liuyongzhi/Desktop/workspace/tbauto/node_modules/.pnpm/next-auth@4.22.1_next@13.4.2_react-dom@18.2.0_react@18.2.0/node_modules/next-auth/core/index.js:165:40)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async NextAuthApiHandler (/Users/liuyongzhi/Desktop/workspace/tbauto/node_modules/.pnpm/next-auth@4.22.1_next@13.4.2_react-dom@18.2.0_react@18.2.0/node_modules/next-auth/next/index.js:22:19)\n' +
    '    at async NextAuth._args$ (/Users/liuyongzhi/Desktop/workspace/tbauto/node_modules/.pnpm/next-auth@4.22.1_next@13.4.2_react-dom@18.2.0_react@18.2.0/node_modules/next-auth/next/index.js:106:14)',
  name: 'TypeError'
}
[next-auth][error][SESSION_ERROR] 
https://next-auth.js.org/errors#session_error Cannot read properties of undefined (reading 'findUnique') TypeError: Cannot read properties of undefined (reading 'findUnique')
    at getSessionAndUser (/Users/liuyongzhi/Desktop/workspace/tbauto/node_modules/.pnpm/@next-auth+prisma-adapter@1.0.5_@prisma+client@4.14.0_next-auth@4.22.1/node_modules/@next-auth/prisma-adapter/dist/index.js:24:52)
    at _callee2$ (/Users/liuyongzhi/Desktop/workspace/tbauto/node_modules/.pnpm/next-auth@4.22.1_next@13.4.2_react-dom@18.2.0_react@18.2.0/node_modules/next-auth/core/errors.js:365:29)
    at tryCatch (/Users/liuyongzhi/Desktop/workspace/tbauto/node_modules/.pnpm/@babel+runtime@7.22.5/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (/Users/liuyongzhi/Desktop/workspace/tbauto/node_modules/.pnpm/@babel+runtime@7.22.5/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:125:22)
    at Generator.next (/Users/liuyongzhi/Desktop/workspace/tbauto/node_modules/.pnpm/@babel+runtime@7.22.5/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (/Users/liuyongzhi/Desktop/workspace/tbauto/node_modules/.pnpm/@babel+runtime@7.22.5/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/Users/liuyongzhi/Desktop/workspace/tbauto/node_modules/.pnpm/@babel+runtime@7.22.5/node_modules/@babel/runtime/helpers/asyncToGenerator.js:22:9)
    at /Users/liuyongzhi/Desktop/workspace/tbauto/node_modules/.pnpm/@babel+runtime@7.22.5/node_modules/@babel/runtime/helpers/asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at /Users/liuyongzhi/Desktop/workspace/tbauto/node_modules/.pnpm/@babel+runtime@7.22.5/node_modules/@babel/runtime/helpers/asyncToGenerator.js:19:12
    at Object.session (/Users/liuyongzhi/Desktop/workspace/tbauto/node_modules/.pnpm/next-auth@4.22.1_next@13.4.2_react-dom@18.2.0_react@18.2.0/node_modules/next-auth/core/routes/session.js:92:34)
    at AuthHandler (/Users/liuyongzhi/Desktop/workspace/tbauto/node_modules/.pnpm/next-auth@4.22.1_next@13.4.2_react-dom@18.2.0_react@18.2.0/node_modules/next-auth/core/index.js:165:40)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async NextAuthApiHandler (/Users/liuyongzhi/Desktop/workspace/tbauto/node_modules/.pnpm/next-auth@4.22.1_next@13.4.2_react-dom@18.2.0_react@18.2.0/node_modules/next-auth/next/index.js:22:19)
    at async NextAuth._args$ (/Users/liuyongzhi/Desktop/workspace/tbauto/node_modules/.pnpm/next-auth@4.22.1_next@13.4.2_react-dom@18.2.0_react@18.2.0/node_modules/next-auth/next/index.js:106:14) {
  name: 'GetSessionAndUserError',
  code: undefined
}`

### How to reproduce

I created the project using T3 and you can reproduce the problem by simply accessing the login

### Expected behavior

The message should be returned correctly after the client calls signIn

**Comment by balazsorban44** [comment]
https://github.com/overdev-l/tbaotu/blob/8f9284b656228fd6f715ab7131f64c5cb55c28d2/src/server/auth.ts#L38

This line receives user input from the browser, so you should validate/handle it accordingly. Check if the values are present, conform to your security standards, etc.

**Comment by overdev-l** [comment]
> https://github.com/overdev-l/tbaotu/blob/8f9284b656228fd6f715ab7131f64c5cb55c28d2/src/server/auth.ts#L38
> 
> This line receives user input from the browser, so you should validate/handle it accordingly. Check if the values are present, conform to your security standards, etc.

Thank you very much for getting back to me!
I have used Prisma to query my database to compare data, if it exists return null and vice versa, I don't quite understand what you mean by checksum.

**Comment by amirakbulut** [comment]
Did you manage to solve this?
