### ISSUE TITLE
Opening login page in 2 separate tabs results in RPError: state mismatch

### ISSUE THREAD

**Issue by benitazhang** [nextauthjs/next-auth#7894]
### Environment

System:
    OS: macOS 11.7.2
    CPU: (8) x64 Intel(R) Core(TM) i7-8569U CPU @ 2.80GHz
    Memory: 292.34 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 18.15.0 - ~/.nvm/versions/node/v18.15.0/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.5.0 - ~/.nvm/versions/node/v18.15.0/bin/npm
  Browsers:
    Chrome: 114.0.5735.198
    Safari: 16.2

### Reproduction URL

https://github.com/benitazhang/next-auth-example

### Describe the issue

Here's a simplified version of the code I'm using: 
```javascript
export default function App({
  Component,
  pageProps: { session, ...pageProps },
}: AppProps) {
  return (
    <SessionProvider session={session}>
      <Auth>
        <Component {...pageProps} />
      </Auth>
    </SessionProvider>
  )
}

function Auth({ children }: { children: JSX.Element }) {
  const { data, status } = useSession();
  const isUser = !!data?.user;

  useEffect(() => {
    if (status !== "loading" && !isUser) {
      signIn("auth0");
    }
  }, [isUser, status]);

  if (isUser) {
    const user = data.user;
    return children;
  }

  return <div></div>;
}
```
It's similar to the suggestions from [this conversation](https://github.com/nextauthjs/next-auth/discussions/4078#discussioncomment-5441997)

I'm calling `signIn` in the useEffect so that I can bypass the NextAuth login page and automatically redirect to the Auth0 login widget. This works perfectly when just using a single tab. However, If I open 2 separate tabs that both redirect to the login widget. Attempting to login on the 1st tab results in an error that looks like 
```
https://next-auth.js.org/errors#oauth_callback_error state mismatch, expected N8V3aJhJiGJmNg39DaTUPpHEIw4-K4QN8zmHu53Q, got: xTEKk8YUiz1IzGiCFMav2fswzsV {
  error: RPError: state mismatch, expected N8V3aJhJiGJmNg39DaTUPpHEIw4-K4QN8zmHu53Q, got: xTEKk8YUiz1IzGiCFMav2fswzsV
```

### How to reproduce

the example uses auth0, so you'll need to configure the appropriate env var 

1) start up the app with `npm run dev`
2) open 2 separate tabs and navigate to localhost:3000. you should be redirected to the auth0 login widget
3) attempt to signin on the first tab you opened, it should fail with a state mismatch error
4) attempt to signin on the second tab, it should succeed

### Expected behavior

I should be able to login to both tabs

**Comment by paul-vd** [comment]
It might be better to do this with a middleware? for example

```ts
export { default } from 'next-auth/middleware';

export const config = { matcher: ['/dashboard'] }; // all the routes that require auth
```

I'm not sure but I think the issue you are having is that each tab is generating their own instance for the login token which communicates with auth0 so then 1 of them will no longer be valid (probably the first one which triggered)

But i'm just assuming here, I'm not certain.

**Comment by mrviniciux** [comment]
This is currently hapenning to me as well using:

node v18.17.1
next: "13.3.0",
next-auth: "4.20.1"


@paul-vd I tried to use middleware but the problem still persists

**Comment by mrviniciux** [comment]
Here's a detailed log of issue


## Opened login window 1

```
[next-auth][debug][CREATE_STATE] { value: 'xSWq_6Aus3I6S-v60W65HuDvqLEbMlx-4nb2F2pSYdA', maxAge: 900 }
[next-auth][debug][CREATE_PKCECODEVERIFIER] { value: 'n_Z4rdneU9v2G0V7tEWHCUlkSFZ96MVMg2DKYsDzpp0', maxAge: 900 }
[next-auth][debug][GET_AUTHORIZATION_URL] {
  url: 'https://mykeycloakdomain.com/auth/realms/my-app/protocol/openid-connect/auth?client_id=my-app-front-local&scope=openid&response_type=code&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Fapi%2Fauth%2Fcallback%2Fkeycloak&state=xSWq_6Aus3I6S-v60W65HuDvqLEbMlx-4nb2F2pSYdA&code_challenge=3ifudhCUd5GrZl09nQZd4VBsZw0KI7iU8Gxr1h-4wKY&code_challenge_method=S256',
  cookies: [
    {
      name: 'next-auth.state',
      value: 'eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..MnD2KLorZF_-pgRc.jhhR5_z4SqFAUJirGkt8KrMLZ10iGi_59s01BYOSaSudJ730wAJwqzOAgythnJtchhGN2RjcgpgKvO8n-Sp2taWLG9WLA48ETABRiRY61WuOTjtPEVwnWtrkTl1MhEoD8FWkjmK6lFZJ4RVF4hnhcNJkJ_0aEYE8wVhbSGZ10qWFHNHvLX0.tIPIimvkuHpA6tOHWi-krQ',
      options: [Object]
    },
    {
      name: 'next-auth.pkce.code_verifier',
      value: 'eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..BrAha9DPEUX4VXt0.dl_jXCoT7hlc2L4kHp445KrN0oN8DLU7cDyCnGohs6BeffRJcTGj6viBNsW5AJLjvDAUuGnQJoJyjDigjXKhCNb45oUBJ7OT-tHvX9dMDwE8sl3y_Pk3FBMKJbjpt9uBrGONE4cslzpSPmJqskLLqd9RtN0JleB8_IJM9bYmDRgjYs244uc.8NU8br68xlaG_GJz6xzYsA',
      options: [Object]
    }
  ],
  provider: {
    id: 'keycloak',
    name: 'Keycloak',
    wellKnown: 'https://mykeycloakdomain.com/auth/realms/my-app/.well-known/openid-configuration',
    type: 'oauth',
    authorization: { params: [Object] },
    checks: [ 'pkce', 'state' ],
    idToken: true,
    profile: [Function: profile],
    style: {
      logo: '/keycloak.svg',
      logoDark: '/keycloak.svg',
      bg: '#fff',
      text: '#000',
      bgDark: '#fff',
      textDark: '#000'
    },
    clientId: 'my-app-front-local',
    clientSecret: 'sY40FqoWSZc1fQKOKXJ9/T2P+VyXMXqSkfPffS/yGS8s=',
    issuer: 'https://mykeycloakdomain.com/auth/realms/my-app',
    signinUrl: 'http://localhost:3000/api/auth/signin/keycloak',
    callbackUrl: 'http://localhost:3000/api/auth/callback/keycloak'
  }
}
```

## Then, I opened another window (not a tab). Login window 2:

```

[next-auth][debug][CREATE_STATE] { value: 'yOxao7slDobEiuE6RB6DmnsIFIgF8wKmyBlbaJH2bmA', maxAge: 900 }
[next-auth][debug][CREATE_PKCECODEVERIFIER] { value: '_wuF74vwU2zzdqvCM4a8qf5CyjmB51bBsFr0Q3wkxHk', maxAge: 900 }
[next-auth][debug][GET_AUTHORIZATION_URL] {
  url: 'https://mykeycloakdomain.com/auth/realms/my-app/protocol/openid-connect/auth?client_id=my-app-front-local&scope=openid&response_type=code&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Fapi%2Fauth%2Fcallback%2Fkeycloak&state=yOxao7slDobEiuE6RB6DmnsIFIgF8wKmyBlbaJH2bmA&code_challenge=f9xWVhs_a2P2URlDVREj2jLLGlj-nuk63RaLnGcSWr4&code_challenge_method=S256',
  cookies: [
    {
      name: 'next-auth.state',
      value: 'eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..elwCd5tBzJnPeO-5.qsvfa4udYlLxRbh1eMABQi41o6zSqOX6ybCWk24vOC8TsJQ4yi4uj7a9D1LNYdA4__n0ymvklJng5zCGiMIqCMNuC0MGwG3cB6UH21kfGfU1YKNsIIElgq3Dw8dE22NsIbJC8HYxDdEw8jHaS7-gcSZM1VHqxPwdloTgYwbXPioorRvTsv0.ZoIJva1qcURAXm-CS0Dhjw',
      options: [Object]
    },
    {
      name: 'next-auth.pkce.code_verifier',
      value: 'eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..wK54vyG80yMRqj5P.MX7ycF55dZbCIe8W6mtnvJGG85ZXZ0AUQG6NQvtQklpnOsPW6RvFJAL2wuUfsBVBn2TnAGYFzNMjBxlG6PpwDihdB13erBCaAUERQHvw3zLpQLL_TRsETvkufgCRtlOCs81tOKaA_LRfhUazUeBFaCzQU3svyEfXRf4ZnnV5CXMllzJeDEs.hTO119nDH3RoLMWcD78x9w',
      options: [Object]
    }
  ],
  provider: {
    id: 'keycloak',
    name: 'Keycloak',
    wellKnown: 'https://mykeycloakdomain.com/auth/realms/my-app/.well-known/openid-configuration',
    type: 'oauth',
    authorization: { params: [Object] },
    checks: [ 'pkce', 'state' ],
    idToken: true,
    profile: [Function: profile],
    style: {
      logo: '/keycloak.svg',
      logoDark: '/keycloak.svg',
      bg: '#fff',
      text: '#000',
      bgDark: '#fff',
      textDark: '#000'
    },
    clientId: 'my-app-front-local',
    clientSecret: 'sY40FqoWSZc1fQKOKXJ9/T2P+VyXMXqSkfPffS/yGS8s=',
    issuer: 'https://mykeycloakdomain.com/auth/realms/my-app',
    signinUrl: 'http://localhost:3000/api/auth/signin/keycloak',
    callbackUrl: 'http://localhost:3000/api/auth/callback/keycloak'
  }
}
```

## Now I went to window number 1 and tried to login:

```
[next-auth][error][OAUTH_CALLBACK_ERROR] 
https://next-auth.js.org/errors#oauth_callback_error state mismatch, expected yOxao7slDobEiuE6RB6DmnsIFIgF8wKmyBlbaJH2bmA, got: xSWq_6Aus3I6S-v60W65HuDvqLEbMlx-4nb2F2pSYdA {
  error: RPError: state mismatch, expected yOxao7slDobEiuE6RB6DmnsIFIgF8wKmyBlbaJH2bmA, got: xSWq_6Aus3I6S-v60W65HuDvqLEbMlx-4nb2F2pSYdA
      at Client.callback (/Users/99765/Software/my-app-front/node_modules/openid-client/lib/client.js:399:13)
      at oAuthCallback (/Users/99765/Software/my-app-front/node_modules/next-auth/core/lib/oauth/callback.js:109:29)
      at async Object.callback (/Users/99765/Software/my-app-front/node_modules/next-auth/core/routes/callback.js:58:11)
      at async AuthHandler (/Users/99765/Software/my-app-front/node_modules/next-auth/core/index.js:201:28)
      at async NextAuthHandler (/Users/99765/Software/my-app-front/node_modules/next-auth/next/index.js:24:19)
      at async auth (webpack-internal:///(api)/./src/pages/api/auth/[...nextauth].ts:29:20) {
    name: 'OAuthCallbackError',
    code: undefined
  },
  providerId: 'keycloak',
  message: 'state mismatch, expected yOxao7slDobEiuE6RB6DmnsIFIgF8wKmyBlbaJH2bmA, got: xSWq_6Aus3I6S-v60W65HuDvqLEbMlx-4nb2F2pSYdA'
}
```

Client side error:

![Captura de Tela 2023-11-09 às 18 16 47](https://github.com/nextauthjs/next-auth/assets/50468019/95616d1a-3ce4-4286-a5fb-93c98ba9ac71)

**Comment by dmunch** [comment]
I assume this discussion went stale since there's no real solution for this?

**Comment by piltie** [comment]
### TL;DR

I believe this is how Auth.js was set up to be and it's not worth it to bypass its login page. Instead, just use it, and make a custom error page with a user-friendly auth error message. If you don't want this behavior to happens, your best options are to not use Auth.js and do something else instead. In sum, based in my conclusions, here're your best options:

- Use Auth.js and accept it as it is with a custom login error page, assuming this login issue has a low chance to happen in real life and won't be a real hassle;
- Use the recommended lib for keycloak (keycloak-js), but it doesn't work with server files so you won't be able to access session info in middleware.ts and such.
- Use pure React instead of Next.js and the recommended lib for keycloak (keycloak-js) without any issues;
- Use another open-source auth lib like better-auth or lucia-auth, but beware since those libs all require database-stored sessions and aren't like Auth.js which uses stateless sessions and only needs JWT and cookies;
- Use a paid option like clerk or supabase, but given you're already hosting or paying for a Keycloak server I'm not sure this is worth it;
- Roll your own auth mechanism in front-end, which I think it's ideal only if you have the time and resources to always make sure your solution is safe against the most popular attacks ,and up to date to most recent auth protocols and good practices so it won't have any vulnerabilities as time goes on.
 
If someone has another alternative or a correction for something wrong I may have said, please feel free to add a new suggestion or to correct me.

### Issue

I'm having this exact same situation and issue (using Microsoft Entra ID as my IDP instead of Keycloak), and at this point I think this is (unfortunately?) just how Auth.js works and there's no workaround. Auth.js doesn't treat each signIn firing as a single thing, and always uses the same cookies for every try, even on different tabs, and no synchronization between them. We can't even make the login page be a pop-up window instead of a redirect, so really, I don't think the effort to change this is worth the pain.

### Honest Answer: We can't change this

Instead of bypassing Auth.js's login page, use it and style it with your website's branding, and when the user clicks on the login button make it disabled so it won't be fired multiple times by the user.

I believe that's only way we can try to mitigate this behavior, by not starting the OAuth proccess immediately when the user opens the website. If they happen to still open two or more tabs and click the login button in them and tries to sign in the first tabs, no matter what we do the user will be redirect to Auth.js's error page, so just create a custom one with your branding to show to the user and that's it. Maybe write a user-friendly message like "Authentication error, close all tabs and try again".

### If you really don't want this to happen...

If you don't want that behaviour, I believe the most pausible option is to just not use Auth.js, as it doesn't fit your needs.

Since you're using keycloak, I would suggest you to use keycloak-js, but if I recall correctly, keycloak-js has the same problem as msal-js for Entra ID, which is it only works on the client so you won't be able to access the session info on middleware.ts and such server files without a workaround (if there even is a workaround for that, in their docs it's specified they do not support Next.js).

So, you either would need to use pure React instead of Next.js if you wanna use keycloak-js without hassle. But if you want to keep using Next.js you can go for another open-source lib that indeed has real Next.js support, but I have yet to find a reliable open-source lib that doesn't require us setting another database only for auth. Auth.js is the only one open-source lib I found that uses stateless auth sessions by only using JWT tokens, and doesn't require us storing tokens in database like better-auth and lucia-auth or so, and as I said keyclok and msal js also are stateless but they don't work in the server). So, carefully consider if that's what you want, since you may be setting up another headache for yourself if you already have a database set up.

You can also go to a paid option supabase or clerk auth, but since you're already paying/hosting Keycloak (just like me paying for Entra ID) idk if it's worth it in this situation, so as a last resource, rolling your own auth in front-end maybe is the option that makes more sense, but only if you have the knowledge and maybe even resources to handle it and make sure it's always secure as time goes on. I wouldn't recommend doing it if you're a solo dev.

Personally, for now I wanna keep using Next.js and will be using Auth.js since I'm doing it for a MVP, and I don't think this login issue will be a hassle. As time goes on and I have more people in my team, time and resources, I will roll my own solution in front-end.
