### ISSUE TITLE
No access token provided 

### ISSUE THREAD

**Issue by Rahuletto** [nextauthjs/next-auth#7995]
### Environment

```json
{
  "next": "^13.4.7",
  "next-auth": "^4.22.1",
  "react": "18.2.0"
}
```

### Reproduction URL

https://github.com/Rahuletto/CodeBoard/tree/dev

### Describe the issue

No access token provided error.
Double checked my GITHUB_SECRET, GITHUB_ID and it's correct.

https://codeboard-git-dev-rahuletto.vercel.app
When logging in, it will give `504 GATEWAY TIMEOUT` and when looking into logs, this is what I got.

```sh
[next-auth][error][OAUTH_CALLBACK_ERROR] 
https://next-auth.js.org/errors#oauth_callback_error no access token provided {
  error: TypeError: no access token provided
      at Client.requestResource (/Users/felixhaberle/Desktop/git/backstage/node_modules/openid-client/lib/client.js:1123:13)
      at Client.userinfo (/Users/felixhaberle/Desktop/git/backstage/node_modules/openid-client/lib/client.js:1235:33)
      at Object.request (/Users/felixhaberle/Desktop/git/backstage/node_modules/next-auth/providers/github.js:27:38)
      at oAuthCallback (/Users/felixhaberle/Desktop/git/backstage/node_modules/next-auth/core/lib/oauth/callback.js:141:41)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async Object.callback (/Users/felixhaberle/Desktop/git/backstage/node_modules/next-auth/core/routes/callback.js:52:11)
      at async AuthHandler (/Users/felixhaberle/Desktop/git/backstage/node_modules/next-auth/core/index.js:201:28)
      at async NextAuthHandler (/Users/felixhaberle/Desktop/git/backstage/node_modules/next-auth/next/index.js:24:19)
      at async Object.apiResolver (/Users/felixhaberle/Desktop/git/backstage/node_modules/next/dist/server/api-utils/node.js:366:9) {
    name: 'OAuthCallbackError',
    code: undefined
  },
  providerId: 'github',
  message: 'no access token provided'
}
```

Hosted on Vercel.

### How to reproduce

- Login
- Click Sign in with GitHub
- Receives GATEWAY TIMEOUT in website
- In logs, received this error.

`NOTE:` The auth worked when I use local host on my machine. But when deployed for preview in Vercel, it got broken apart and errors this instead. So you cannot reproduce it in local host.

### Expected behavior

Should authorize with GitHub and login successfully

**Comment by Rahuletto** [comment]
Ad said earlier. This cannot be reproduced in localhost. I can successfully login when it have `without pages option`. But when having pages option like `signIn` I rather get fetch error. Even tho I have NEXTAUTH_URL in .env.local file. when I host on deploy that `fetch error` gets fixed. But rather this `no access token provided` error. This no access token provided can also be seen without the pages option `aka. Default page next auth provides`

**Comment by Rahuletto** [comment]
Repository url if you need to check. `NEXT-AUTH ONLY ON DEV BRANCH`
https://github.com/Rahuletto/CodeBoard/tree/dev
