### ISSUE TITLE
OAUTH Authorization Grant Access Token

### ISSUE THREAD

**Issue by calebanderson526** [nextauthjs/next-auth#8019]
### Question 💬

Hello,

I am using google OAUTH with quik and auth.js.

A part of my app is reading data from the user's google drive, and I need the access token generated by google for this. It appears this token is stored as a cookie, however I can't find an API in auth.js that allows me to do this.

My question is: is there a standard practice for something like this? Or do I need to write code to read and parse the cookie to then send it to google? Shouldn't the access token just be in the session object?

### How to reproduce ☕️

n/a

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by calebanderson526** [comment]
UPDATE:

I figured out that I need to configure scope within the authorization: {params: any} object such as:
```typescript
export const {
  onRequest,
  useAuthSession,
  useAuthSignin,
  useAuthSignout,
} = serverAuth$(({ env }) => ({
  secret: env.get("AUTH_SECRET"),
  trustHost: true,
  providers: [
    Google({
      clientId: env.get("GOOGLE_ID")!,
      clientSecret: env.get("GOOGLE_SECRET")!,
      authorization: {
        params: {
          scope:
            "https://www.googleapis.com/auth/drive.readonly",
        },
      },
    }),
  ] as Provider[],
}));
```

However I get an error while signing in:

```[auth][error][CallbackRouteError]: Read more at https://errors.authjs.dev#callbackrouteerror
[auth][cause]: OperationProcessingError: "response" body "id_token" property must be a non-empty string
    at Module.processAuthorizationCodeOpenIDResponse (file:///C:/Users/caleb/Documents/doc-assistant/node_modules/oauth4webapi/build/index.js:1016:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async handleOAuth (file:///C:/Users/caleb/Documents/doc-assistant/node_modules/@auth/core/lib/oauth/callback.js:77:24)
    at async Module.callback (file:///C:/Users/caleb/Documents/doc-assistant/node_modules/@auth/core/lib/routes/callback.js:20:41)
    at async AuthInternal (file:///C:/Users/caleb/Documents/doc-assistant/node_modules/@auth/core/lib/index.js:65:38)
    at async Proxy.Auth (file:///C:/Users/caleb/Documents/doc-assistant/node_modules/@auth/core/index.js:100:30)
    at async onRequest (C:/Users/caleb/Documents/doc-assistant/node_modules/@builder.io/qwik-auth/lib/index.qwik.mjs:273:29)
    at async Object.next (C:\Users\caleb\Documents\doc-assistant\node_modules\@builder.io\qwik-city\vite\index.cjs:24359:9)
    at async runNext (C:\Users\caleb\Documents\doc-assistant\node_modules\@builder.io\qwik-city\vite\index.cjs:24610:5)
    at async C:\Users\caleb\Documents\doc-assistant\node_modules\@builder.io\qwik-city\vite\index.cjs:25054:26
[auth][details]: {
  "provider": "google"
}
```

**Comment by balazsorban44** [comment]
Google adheres to the OIDC spec, so you'll need to pass at least the `openid` scope too.

See the defaults here https://github.com/nextauthjs/next-auth/blob/1e886b97bcd76b0679a00d6d03e9cc0a68ca9407/packages/next-auth/src/providers/google.ts#L29

**Comment by DeepakDonde-GWL** [comment]
> Google adheres to the OIDC spec, so you'll need to pass at least the `openid` scope too.
> 
> See the defaults here
> 
> [next-auth/packages/next-auth/src/providers/google.ts](https://github.com/nextauthjs/next-auth/blob/1e886b97bcd76b0679a00d6d03e9cc0a68ca9407/packages/next-auth/src/providers/google.ts#L29)
> 
> Line 29 in [1e886b9](/nextauthjs/next-auth/commit/1e886b97bcd76b0679a00d6d03e9cc0a68ca9407)
> 
>  authorization: { params: { scope: "openid email profile" } },

This worked for Saleforce too
