### ISSUE TITLE
jwt error

### ISSUE THREAD

**Issue by avnav88** [nextauthjs/next-auth#8325]
### Environment

```
  System:
    OS: Linux 5.10 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (8) x64 Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
    Memory: 10.69 GB / 12.42 GB
    Container: Yes
    Shell: 5.1.4 - /bin/bash
  Binaries:
    Node: 20.5.0 - /usr/bin/node
    npm: 9.8.1 - /usr/bin/npm
```

### Reproduction URL

not possible

### Describe the issue

```
jakey@mnymkr:~/itys$ npm run push

> itys@0.0.1 push
> drizzle-kit push:sqlite

No config path provided, using default 'drizzle.config.ts'
Reading config file '/home/jakey/itys/drizzle.config.ts'
drizzle-kit: v0.19.12
drizzle-orm: v0.27.2

/home/jakey/itys/node_modules/drizzle-kit/index.cjs:48352
    return new LibsqlError(e.message, code, e);
           ^

LibsqlError: AUTH_JWT_INVALID: Authentication failed: The JWT is invalid
    at mapHranaError (/home/jakey/itys/node_modules/drizzle-kit/index.cjs:48352:12)
    at HranaClient.execute (/home/jakey/itys/node_modules/drizzle-kit/index.cjs:48392:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async TursoSqlite.query (/home/jakey/itys/node_modules/drizzle-kit/index.cjs:42851:21)
    at async fromDatabase3 (/home/jakey/itys/node_modules/drizzle-kit/index.cjs:12875:23)
    at async sqlitePushIntrospect (/home/jakey/itys/node_modules/drizzle-kit/index.cjs:51860:19)
    at async Command.<anonymous> (/home/jakey/itys/node_modules/drizzle-kit/index.cjs:53318:31) {
  code: 'AUTH_JWT_INVALID',
  [cause]: [ResponseError: Authentication failed: The JWT is invalid] {
    code: 'AUTH_JWT_INVALID',
    proto: {
      message: 'Authentication failed: The JWT is invalid',
      code: 'AUTH_JWT_INVALID'
    }
  }
}


```

### How to reproduce

trying to push the generated schema, but have a jwt issue.

### Expected behavior

to be able to push to the turso db.

**Comment by sahilshahane** [comment]
I'm getting similar error, it should automatically clear your cookies and redirect to signin but it's not doing that

![image](https://github.com/nextauthjs/next-auth/assets/57249267/3a0590b5-c1e9-4c55-8e9a-630098e6c78f)

**Comment by avnav88** [comment]
i created a new db token and it took care of it
