### ISSUE TITLE
Integration with Duende Identity Provider 6 and Qwik

### ISSUE THREAD

**Issue by FranciscoJavierMartin** [nextauthjs/next-auth#8390]
### Provider type

Identity Server 4

### Environment

  System:
    OS: macOS 13.4.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 48.42 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.12.1/bin/yarn
    npm: 9.8.1 - ~/.nvm/versions/node/v18.12.1/bin/npm
    pnpm: 7.28.0 - /opt/homebrew/bin/pnpm
  Browsers:
    Brave Browser: 115.1.56.20
    Safari: 16.5.2

### Reproduction URL

https://github.com/FranciscoJavierMartin/Carsties/tree/auth

### Describe the issue

When I try to login, I am redirected to an error page instead of the Identity provider login page. On the console, the following message appear
```sh
[auth][error][SignInError]: Read more at https://errors.authjs.dev#signinerror
[auth][cause]: TypeError [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:393:5)
    at URL.onParseError (node:internal/url:565:9)
    at new URL (node:internal/url:645:5)
    at Module.processDiscoveryResponse (file:///Users/francisco/Developer/Dotnet/Carsties/frontend/qwik-app/node_modules/.pnpm/oauth4webapi@2.3.0/node_modules/oauth4webapi/build/index.js:231:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getAuthorizationUrl (file:///Users/francisco/Developer/Dotnet/Carsties/frontend/qwik-app/node_modules/.pnpm/@auth+core@0.7.1/node_modules/@auth/core/lib/oauth/authorization-url.js:19:20)
    at async Module.signin (file:///Users/francisco/Developer/Dotnet/Carsties/frontend/qwik-app/node_modules/.pnpm/@auth+core@0.7.1/node_modules/@auth/core/lib/routes/signin.js:14:20)
    at async AuthInternal (file:///Users/francisco/Developer/Dotnet/Carsties/frontend/qwik-app/node_modules/.pnpm/@auth+core@0.7.1/node_modules/@auth/core/lib/index.js:116:36)
    at async Proxy.Auth (file:///Users/francisco/Developer/Dotnet/Carsties/frontend/qwik-app/node_modules/.pnpm/@auth+core@0.7.1/node_modules/@auth/core/index.js:100:30)
    at async authAction (/Users/francisco/Developer/Dotnet/Carsties/frontend/qwik-app/node_modules/.pnpm/@builder.io+qwik-auth@0.1.0_v3rqwd5hc5kd5pslqhdnxxzoye/node_modules/@builder.io/qwik-auth/lib/index.qwik.mjs:165:17)
[auth][details]: {
  "provider": "id-server"
}
```

The environment variables for the Qwik app are these
```
BACKEND_URL=http://localhost:6001/
AUTH_SECRET=something
AUTH_DIS6_ID=id-server
AUTH_DIS6_CLIENT_SECRET=secret
AUTH_DIS6_CLIENT_ID=qwikApp
AUTH_DIS6_ISSUER=http://localhost:5001
NEXTAUTH_SECRET=something
NEXTAUTH_URL=http://localhost:3001
AUTH_URL=http://localhost:3001
```

I am using @auth/core@0.7.1 and @builder.io/qwik-auth@0.1.0. I use the same config for a Next.js project using next-auth@4.23.1. Not sure if it is a bug from auth-core, the Qwik integration or I am missing something.

### How to reproduce

Download the code from the repo provided on the auth branch. Build and run the backend solution using docker
```sh
docker-compose build
docker-compose up -d
```
This build, populate and run the entire backend solution. Go to frontend/qwik-app and run these commands
```sh
pnpm i
pnpm dev
```
or
```sh
npm i
npm run dev
```

Open the browser, navigate to (http://localhost:3001), click on the login button on the top right corner of the browser, then check the console for the logs.

The most interesting files are:
- frontend/qwik-app/src/routes/plugin@auth.ts (config for Qwik app)
- src/IdentityService/Config.cs
- frontent/web-app/app/api/auth/[...nextauth]/route.ts (config for Next.js app that works fine).

### Expected behavior

When click on the login button, then redirect to Duende Identity Server login page.

**Comment by balazsorban44** [comment]
Currently `@builder.io/qwik-auth` is a community package and so this issue should be opened at https://github.com/BuilderIO/qwik/issues
