### ISSUE TITLE
SyntaxError: Invalid regular expression

### ISSUE THREAD

**Issue by plamen5rov** [nextauthjs/next-auth#8439]
### Question 💬

When I run `npm run dev` command I get the following error:

`SyntaxError: Invalid regular expression: /^/_next/data/development/api/auth/[...nextauth}.json$/: Unterminated character class
    at new RegExp (<anonymous>)
    at buildDataRoute (/home/plamen/Code/promptopia/node_modules/next/dist/server/lib/router-utils/build-data-route.js:34:69)
    at Watchpack.<anonymous> (/home/plamen/Code/promptopia/node_modules/next/dist/server/lib/router-utils/setup-dev.js:875:70)`

The full code repo is here: [](https://github.com/plamen5rov/promptopia/)

### How to reproduce ☕️

[https://github.com/plamen5rov/promptopia/tree/master](https://github.com/plamen5rov/promptopia/tree/master)

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by plamen5rov** [comment]
Sorry for the botther! Found the ahswer myself:

the directory was named `[...naxtauth} `instead of `[...naxtauth]`
