### ISSUE TITLE
KyselyAdapter isSqlite check fails for D1Dialect

### ISSUE THREAD

**Issue by JanThiel** [nextauthjs/next-auth#8453]
### Adapter type

@auth/kysely-adapter

### Environment

  System:
    OS: Windows 10 10.0.22621
    CPU: (24) x64 AMD Ryzen 9 7900X 12-Core Processor
    Memory: 7.49 GB / 31.12 GB
  Binaries:
    Node: 18.14.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 9.6.7 - C:\Program Files\nodejs\npm.CMD
    pnpm: 7.18.0 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Chrome: 116.0.5845.111
    Edge: Spartan (44.22621.2134.0), Chromium (116.0.1938.62)

### Reproduction URL

https://github.com/JanThiel/next-auth-kyselyadapter-d1-bug

### Describe the issue

The `@auth/kysely-adapter` `KyselyAdapter` performs a check against `instanceof SqliteAdapter`

https://github.com/nextauthjs/next-auth/blob/35977bf13276072887b554b15b49f782cf15c35a/packages/adapter-kysely/src/index.ts#L283

This check fails for the D1Dialect which adapter is most obviously an Instance of the Sqliteadapter:

https://github.com/aidenwallis/kysely-d1/blob/ba48112890fd91035fb51b93dc1301e9f8e4329d/src/index.ts#L43-L45
```
  createAdapter() {
    return new SqliteAdapter();
  }
```

Due to this calling `createSession` fails on Cloudflare D1 which seems to be a bit more strict than other local Sqlite databases. 

```
"Error: D1_TYPE_ERROR: Type 'object' not supported for value 'Tue Sep 26 2023 12:48:07 GMT+0000 (Coordinated Universal Time)'
    at D1PreparedStatement.bind (bundledWorker-0.17018918700489616.mjs:898:17)
    at s.executeQuery (__next-on-pages-dist__/webpack/9b3bdf9eee839442fe37ed586efaff1d.js:12:44988)
    at __next-on-pages-dist__/webpack/9b3bdf9eee839442fe37ed586efaff1d.js:1:48052
    at Ii.provideConnection (__next-on-pages-dist__/webpack/9b3bdf9eee839442fe37ed586efaff1d.js:1:83082)
    at async at.executeQuery (__next-on-pages-dist__/webpack/9b3bdf9eee839442fe37ed586efaff1d.js:1:47999)
    at async _e.execute (__next-on-pages-dist__/webpack/9b3bdf9eee839442fe37ed586efaff1d.js:1:19677)
    at async _e.executeTakeFirst (__next-on-pages-dist__/webpack/9b3bdf9eee839442fe37ed586efaff1d.js:1:19900)
    at async _e.executeTakeFirstOrThrow (__next-on-pages-dist__/webpack/9b3bdf9eee839442fe37ed586efaff1d.js:1:19972)
    at async createSession (__next-on-pages-dist__/webpack/9b3bdf9eee839442fe37ed586efaff1d.js:1:91101)
    at async Ue.<computed> (__next-on-pages-dist__/webpack/71992532242772f20ff0087800cdd46e.js:56:78937)"
```
Forcing the check to `true` / "Sqlite Mode" fixes the issues for us.

### How to reproduce

Checkout the repo, install, run dev.
Check the console for: 
```
is D1Dialect KyseAuth Adapter instanceof SqliteAdapter false
```

We simply added this debug code to `[...nextauth].ts`:

```typescript
const kyselyDb = new KyselyAuth<Database>({
  dialect: new D1Dialect({
    database: binding<D1Database>("DB"),
  })
});

const executor = kyselyDb.getExecutor();
const adapter = executor.adapter;

console.log("is D1Dialect KyseAuth Adapter instanceof SqliteAdapter", adapter instanceof SqliteAdapter ? "true" : "false");
```

### Expected behavior

The Adapter should run in the "SQlite Mode" and convert the Date object to an ISO String.
The instanceOf Check should return `true` as well.

**Comment by JanThiel** [comment]
For reference: We simply copied the `KyselyAdapter` to our local project and hardcoded `true` for `isSqlite`.

**Comment by JanThiel** [comment]
To be more precise, the actual issue that type conversions from `Date` to `string` - as ISOString - only happen if the `KyselyAdapter` recognizes a `SqliteAdapter`. This fails and as such the conversion does not happen.
Within D1 this then leads to the mentioned error while creating a session.

This are the relevant code parts:

https://github.com/nextauthjs/next-auth/blob/35977bf13276072887b554b15b49f782cf15c35a/packages/adapter-kysely/src/index.ts#L361

https://github.com/nextauthjs/next-auth/blob/35977bf13276072887b554b15b49f782cf15c35a/packages/adapter-kysely/src/index.ts#L58-L75

**Comment by JanThiel** [comment]
@balazsorban44 Could you please be so kind to re-open this issue?
