### ISSUE TITLE
How to send custom nonce from OktaProvider?

### ISSUE THREAD

**Issue by AdenierOsorto** [nextauthjs/next-auth#8498]
Is there a way to add a custom nonce? I have tried this:

```
OktaProvider({
	clientId: xxxxx,
	clientSecret: xxxxx,
	issuer: xxxx,
	idToken: true,
	checks: ["none", "state"],
	authorization: {
		params: {
			grant_type: "implicit",
			token_endpoint_auth_method: "none",
			response_types: ["token", "id_token"],
			scope: "openid email profile",
			nonce: "aa-ss-dd-ff-ggg",
		},
	},
}),
```
But I get this error:

## Error in console
```
[next-auth][error][OAUTH_CALLBACK_ERROR] 
https://next-auth.js.org/errors#oauth_callback_error nonce mismatch, expected undefined, got: aa-ss-dd-ff-ggg {
  error: RPError: nonce mismatch, expected undefined, got: aa-ss-dd-ff-ggg
      at Client.validateIdToken (/Applications/repositories/nextjs/rate-plan-builder/node_modules/openid-client/lib/client.js:785:13)
      at async Client.callback (/Applications/repositories/nextjs/rate-plan-builder/node_modules/openid-client/lib/client.js:488:7)
      at async oAuthCallback (/Applications/repositories/nextjs/rate-plan-builder/node_modules/next-auth/core/lib/oauth/callback.js:109:16)
      at async Object.callback (/Applications/repositories/nextjs/rate-plan-builder/node_modules/next-auth/core/routes/callback.js:52:11)
      at async AuthHandler (/Applications/repositories/nextjs/rate-plan-builder/node_modules/next-auth/core/index.js:208:28)
      at async NextAuthApiHandler (/Applications/repositories/nextjs/rate-plan-builder/node_modules/next-auth/next/index.js:22:19)
      at async NextAuth._args$ (/Applications/repositories/nextjs/rate-plan-builder/node_modules/next-auth/next/index.js:107:14) {
    name: 'OAuthCallbackError',
    code: undefined
  },
  providerId: 'okta',
  message: 'nonce mismatch, expected undefined, got: aa-ss-dd-ff-ggg

```

Any suggestions?

**Comment by balazsorban44** [comment]
Currently the nonce value generation is automatic and cannot be configured, when you add the `nonce` string to checks. Note, you had a typo.

Code https://github.com/nextauthjs/next-auth/blob/64a190e549c52ca436cbd58884725bccd37dbd10/packages/next-auth/src/core/lib/oauth/checks.ts#L146

**Comment by 0x73696d616f** [comment]
Is setting custom nonces a planned feature?
It would be really useful for me

**Comment by 0x73696d616f** [comment]
@AdenierOsorto I managed to tweak the code to make it work, check it out
https://github.com/nextauthjs/next-auth/discussions/8893
