### ISSUE TITLE
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in @auth\sequelize-adapter\package.json

### ISSUE THREAD

**Issue by UncleBu1728** [nextauthjs/next-auth#8597]
### Adapter type

@auth/sequelize-adapter

### Environment

  System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 Intel(R) Core(TM) i7-6800K CPU @ 3.40GHz
  Binaries:
    Node: 18.17.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.6.7 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 116.0.5845.188
    Edge: Spartan (44.19041.1266.0), Chromium (116.0.1938.81)
    Internet Explorer: 11.0.19041.1566

```javascript
"@auth/sequelize-adapter": "^1.0.1",
"next-auth": "^4.23.1",
"sequelize": "^6.28.0",
"sequelize-typescript": "^2.1.5",
"ts-node": "^10.9.1",
nodejs: v18.17.1
```

### Reproduction URL

Add later if needed

### Describe the issue

The project I am on recently changed from another authentication to nextAuth.js.
I have experienced the Error shown below when using unit tests or customized tools to call Server-side API

```javascript
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in C:\src\app\node_modules\@auth\sequelize-adapter\package.json
    at new NodeError (node:internal/errors:405:5)
    at exportsNotFound (node:internal/modules/esm/resolve:359:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:639:13)
    at resolveExports (node:internal/modules/cjs/loader:567:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:636:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1063:27)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (C:\src\app\node_modules\@cspotcode\source-map-support\source-map-support.js:811:30)
    at Function.Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at Object.<anonymous> (C:\src\app\src\pages\api\auth\[...nextauth].ts:2:1)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module.m._compile (C:\src\app\node_modules\ts-node\src\index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Object.require.extensions.<computed> [as .ts] (C:\src\app\node_modules\ts-node\src\index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Function.Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at Object.<anonymous> (C:\src\app\src\api\auth.ts:9:1)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    ...
```
### Solutions tried
I have tried downgrading/upgrading the packages using "yarn" or "npm", customizing the export directly in sequelize-adapter package.json, along with trying different nodejs versions such as 16,18, and 20 but this problem persists. 

### How to reproduce

execute package.json scripts that call server-side API

### Expected behavior

Before changing to nextAuth,js and using the Sequelize adapter to manage models, the unit tests and tools function normally when running package.json scripts

### Actual behavior
I have found that whenever a script is imported and executed a server-side API, the error above will show.
However, the web app and APIs work normally when under development or production.

**Comment by masonbrothers** [comment]
I am having the same issue, but for the Drizzle adapter.

**Comment by UncleBu1728** [comment]
So for now, we have a workaround which is just copying the code we needed from the sequelize-adapter library and pasting it to a customized file, then importing from there

**Comment by balazsorban44** [comment]
Our `exports` look correct: https://github.com/nextauthjs/next-auth/blob/a767456e36e2a48f82909c4214065f8b308dad12/packages/adapter-sequelize/package.json#L18-L23

Would need a reproduction.

> Add later if needed

Please **always** assume that this is needed. That's why it's part of the template. :pray:
