### ISSUE TITLE
https://next-auth.js.org/errors#oauth_callback_handler_error No metadata for "AccountEntity"

### ISSUE THREAD

**Issue by gkorland** [nextauthjs/next-auth#8777]
### Summary

After I update the package to the latest version I started to get this error, any ideas what has changed?

"next": "^13.4.19" -> "next": "^13.5.3"
"next-auth": "^4.23.0" ->  "next-auth": "^4.23.1"

```
https://next-auth.js.org/errors#oauth_callback_handler_error No metadata for "AccountEntity" was found. s: No metadata for "AccountEntity" was found.
    at t.DataSource.getMetadata (/var/task/.next/server/chunks/982.js:52:42515)
    at t.EntityManager.findOne (/var/task/.next/server/chunks/982.js:149:25680)
    at getUserByAccount (/var/task/.next/server/chunks/982.js:150:427302)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  name: 'GetUserByAccountError',
  code: undefined
}
```

_Originally posted by @gkorland in https://github.com/nextauthjs/next-auth/discussions/8770_

**Comment by balazsorban44** [comment]
Please use the bug report template.
