### ISSUE TITLE
prisma-adapter mysql Invalid prisma.account.create() invocation

### ISSUE THREAD

**Issue by sao-coding** [nextauthjs/next-auth#8922]
### Adapter type

@auth/prisma-adapter

### Environment

```
  System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 11th Gen Intel(R) Core(TM) i5-11400 @ 2.60GHz
    Memory: 18.32 GB / 31.77 GB
  Binaries:
    Node: 18.17.0 - D:\nodejs\node.EXE
    npm: 9.6.7 - D:\nodejs\npm.CMD
    pnpm: 8.9.2 - ~\AppData\Local\pnpm\pnpm.CMD
  Browsers:
    Edge: Spartan (44.19041.3570.0), Chromium (118.0.2088.46)
    
```
### Reproduction URL

https://github.com/sao-coding/iot

### Describe the issue

If I try to manually add user information to the Account table in mysql, it will login successfully.
```
Server has closed the connection. {
  message: '\n' +
    'Invalid `prisma.account.create()` invocation:\n' +
    '\n' +
    '\n' +
    'Server has closed the connection.',
  stack: 'PrismaClientKnownRequestError: \n' +
    'Invalid `prisma.account.create()` invocation:\n' +
    '\n' +
    '\n' +
    'Server has closed the connection.\n' +
    '    at Cn.handleRequestError (D:\\code\\Next.js\\iot\\node_modules\\.pnpm\\@prisma+client@5.4.2_prisma@5.4.2\\node_modules\\@prisma\\client\\runtime\\library.js:123:6817)\n' +
    '    at Cn.handleAndLogRequestError (D:\\code\\Next.js\\iot\\node_modules\\.pnpm\\@prisma+client@5.4.2_prisma@5.4.2\\node_modules\\@prisma\\client\\runtime\\library.js:123:6206)\n' +
    '    at Cn.request (D:\\code\\Next.js\\iot\\node_modules\\.pnpm\\@prisma+client@5.4.2_prisma@5.4.2\\node_modules\\@prisma\\client\\runtime\\library.js:123:5926)\n' +
    '    at async l (D:\\code\\Next.js\\iot\\node_modules\\.pnpm\\@prisma+client@5.4.2_prisma@5.4.2\\node_modules\\@prisma\\client\\runtime\\library.js:128:9968)',
  name: 'PrismaClientKnownRequestError'
}
[next-auth][error][OAUTH_CALLBACK_HANDLER_ERROR] 
https://next-auth.js.org/errors#oauth_callback_handler_error
Invalid `prisma.account.create()` invocation:


Server has closed the connection. PrismaClientKnownRequestError:
Invalid `prisma.account.create()` invocation:
```

### How to reproduce

Login to the login page

### Expected behavior

Successfully wrote data in the database and logged in successfully

**Comment by deltasierra96** [comment]
Facing the same issue. Appears to happen with any provider I use.

**Comment by fuegonju** [comment]
Having similar issue with 'create':

`[next-auth][error][SIGNIN_EMAIL_ERROR] 
https://next-auth.js.org/errors#signin_email_error Cannot read properties of undefined (reading 'create') {
  error: TypeError: Cannot read properties of undefined (reading 'create')
      at createVerificationToken (webpack-internal:///(rsc)/./node_modules/.pnpm/@auth+prisma-adapter@1.0.5_@prisma+client@5.5.0_nodemailer@6.9.7/node_modules/@auth/prisma-adapter/index.js:280:65)
      at _callee2$ (webpack-internal:///(rsc)/./node_modules/.pnpm/next-auth@4.24.3_next@13.5.6_nodemailer@6.9.7_react-dom@18.2.0_react@18.2.0/node_modules/next-auth/core/errors.js:301:43)
      at tryCatch (webpack-internal:///(rsc)/./node_modules/.pnpm/@babel+runtime@7.23.2/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:36:24)
      at Generator.eval (webpack-internal:///(rsc)/./node_modules/.pnpm/@babel+runtime@7.23.2/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:123:25)
      at Generator.eval [as next] (webpack-internal:///(rsc)/./node_modules/.pnpm/@babel+runtime@7.23.2/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:64:29)
      at asyncGeneratorStep (webpack-internal:///(rsc)/./node_modules/.pnpm/@babel+runtime@7.23.2/node_modules/@babel/runtime/helpers/asyncToGenerator.js:4:28)
      at _next (webpack-internal:///(rsc)/./node_modules/.pnpm/@babel+runtime@7.23.2/node_modules/@babel/runtime/helpers/asyncToGenerator.js:22:17)
      at eval (webpack-internal:///(rsc)/./node_modules/.pnpm/@babel+runtime@7.23.2/node_modules/@babel/runtime/helpers/asyncToGenerator.js:27:13)
      at new Promise (<anonymous>)
      at Object.eval [as createVerificationToken] (webpack-internal:///(rsc)/./node_modules/.pnpm/@babel+runtime@7.23.2/node_modules/@babel/runtime/helpers/asyncToGenerator.js:19:16)
      at email (webpack-internal:///(rsc)/./node_modules/.pnpm/next-auth@4.24.3_next@13.5.6_nodemailer@6.9.7_react-dom@18.2.0_react@18.2.0/node_modules/next-auth/core/lib/email/signin.js:29:145)
      at async Object.signin (webpack-internal:///(rsc)/./node_modules/.pnpm/next-auth@4.24.3_next@13.5.6_nodemailer@6.9.7_react-dom@18.2.0_react@18.2.0/node_modules/next-auth/core/routes/signin.js:92:30)
      at async AuthHandler (webpack-internal:///(rsc)/./node_modules/.pnpm/next-auth@4.24.3_next@13.5.6_nodemailer@6.9.7_react-dom@18.2.0_react@18.2.0/node_modules/next-auth/core/index.js:259:36)
      at async NextAuthRouteHandler (webpack-internal:///(rsc)/./node_modules/.pnpm/next-auth@4.24.3_next@13.5.6_nodemailer@6.9.7_react-dom@18.2.0_react@18.2.0/node_modules/next-auth/next/index.js:50:30)
      at async NextAuth._args$ (webpack-internal:///(rsc)/./node_modules/.pnpm/next-auth@4.24.3_next@13.5.6_nodemailer@6.9.7_react-dom@18.2.0_react@18.2.0/node_modules/next-auth/next/index.js:85:24)
      at async /home/fuegonju/my-app/node_modules/.pnpm/next@13.5.6_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:62499 {
    name: 'CreateVerificationTokenError',
    code: undefined
  },
  providerId: 'email',
  message: "Cannot read properties of undefined (reading 'create')"`

**Comment by sao-coding** [comment]
The latest version solves current problems

**Comment by balazsorban44** [comment]
closing based on comment above
