### ISSUE TITLE
SvelteKit Auth, (Google), TypeError ("response" must be an instance of Response)

### ISSUE THREAD

**Issue by notarib-catcher** [nextauthjs/next-auth#8943]
### Provider type

Google

### Environment

Environment

System:
- OS: Windows 10 10.0.22621
- CPU: (16) x64 AMD Ryzen 7 5800H with Radeon Graphics
- Memory: 4.44 GB / 15.35 GB
Binaries:
- Node: 18.12.1 - C:\Program Files\nodejs\node.EXE
- Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
- npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
- pnpm: 7.17.1 - C:\Program Files\nodejs\pnpm.CMD
Browsers:
- Edge: Chromium (118.0.2088.61)
- Internet Explorer: 11.0.22621.1

### Reproduction URL

https://github.com/notarib-catcher/fest-msite-sveltk

### Describe the issue

I am hosting my sveltekit site on Vercel's Hobby plan, we're using authjs for sveltekit with google as the provider to authenticate users.
The version of Authjs I'm using in live is @auth/sveltekit 0.3.10, the error is occuring even when I update to 0.3.11 (latest)
The error seems to be a TypeError that occurs when attempting to login.
So far, I have only attempted this with the google auth provider.

To be completely honest, I am at a loss for why this error is occuring.
 - The error only occurs on live production and not on dev deployments - Login works fine on dev
 - I am unable to reproduce it on the local dev server (vite dev)
 - The error came up without intervention: We made a new deployment with CSS and some text changes that triggered it
 - The error seems to have come up after the vercel incident last night (Degraded performance: Assigning domains) **_however, this may also be coincidence._**

### How to reproduce

Since this error is rather specific to my deployment, I cannot provide a proper steps-to-reproduce, however here is the error log from vercel's runtime logs
```
[POST] /auth/signin/google

[auth][cause]: TypeError: "response" must be an instance of Response
    at Module.processDiscoveryResponse (file:///var/task/node_modules/oauth4webapi/build/index.js:212:15)
    at getAuthorizationUrl (file:///var/task/node_modules/@auth/core/lib/oauth/authorization-url.js:19:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Module.signin (file:///var/task/node_modules/@auth/core/lib/routes/signin.js:15:20)
    at async AuthInternal (file:///var/task/node_modules/@auth/core/lib/index.js:112:36)
    at async Auth (file:///var/task/node_modules/@auth/core/index.js:100:30)
    at async respond (file:///var/task/.svelte-kit/output/server/index.js:2523:22)
    at async Server.default (file:///var/task/.svelte-kit/vercel-tmp/index.js:47:3)
    at async Server.<anonymous> (/var/task/___vc/__launcher/__launcher.js:14:11367)

[auth][details]: {
  "provider": "google"
}

[auth][error][SignInError]: Read more at https://errors.authjs.dev#signinerror
```

### Expected behavior

The user should be signed in with google

**Comment by Penca53** [comment]
I also have the same issue.

**Comment by notarib-catcher** [comment]
Update: It seems to be fixed for my project, and the cause was the node version being used, (16 vs 18)

**Comment by nasso** [comment]
Had the same problem, with Node.js 18 being used on Vercel, but Node 20 locally.

We downgraded to Node.js 18 locally (and most importantly, in CI) before building and deploying the app. Fixed it!
