### ISSUE TITLE
The "listener" argument must be of type function. Received an instance of Object - Google oAuth Error

### ISSUE THREAD

**Issue by mikeacre** [nextauthjs/next-auth#9078]
I am also receiving this issue but only on certain devices, and randomly. It appears on certain devices, after a successful login, after about a day or so they will no longer be able to login. I am running this as production on an AWS server. ~10-15 users for internal use app using google oAuth for login only. 

I know it must have something to do with the tokens not refreshing for certain users. Is there a way to force this refresh? Or maybe I  missed something?

Full Error:

```
[next-auth][error][SIGNIN_OAUTH_ERROR] 
 https://next-auth.js.org/errors#signin_oauth_error The "listener" argument must be of type function. Received an instance of Object {
   error: {
     message: 'The "listener" argument must be of type function. Received an instance of Object',
     stack: 'TypeError [ERR_INVALID_ARG_TYPE]: The "listener" argument must be of type function. Received an instance of Object\n' +
       '    at checkListener (node:events:266:3)\n' +
       '    at ClientRequest.once (node:events:647:3)\n' +
       '    at new ClientRequest (node:_http_client:237:10)\n' +
       '    at Object.request (node:https:357:10)\n' +
       '    at Object.<anonymous> (/home/ubuntu/git_dirs/lmsign-full/next-display/node_modules/proxy-agent/node_modules/agent-base/patch-core.js:25:22)\n' +
       '    at /home/ubuntu/git_dirs/lmsign-full/next-display/node_modules/socks-proxy-agent/node_modules/agent-base/patch-core.js:23:20\n' +
       '    at Function.request (/home/ubuntu/git_dirs/lmsign-full/next-display/node_modules/openid-client/lib/helpers/request.js:120:73)\n' +
       '    at Function.discover (/home/ubuntu/git_dirs/lmsign-full/next-display/node_modules/openid-client/lib/issuer.js:144:38)\n' +
       '    at openidClient (/home/ubuntu/git_dirs/lmsign-full/next-display/node_modules/next-auth/core/lib/oauth/client.js:16:41)\n' +
       '    at getAuthorizationUrl (/home/ubuntu/git_dirs/lmsign-full/next-display/node_modules/next-auth/core/lib/oauth/authorization-url.js:70:49)',
     name: 'TypeError'
   },
   providerId: 'google',
   message: 'The "listener" argument must be of type function. Received an instance of Object'
 }

```

Next Auth:
```
`GoogleProvider({
            clientId: process.env.GOOGLE.CLIENT_ID,
            clientSecret: process.env.GOOGLE.SECRET,
            callbackUrl: "HIDDEN",
            authorization: {
                params: {
                    prompt: "consent",
                    access_type: "offline",
                    response_type: "code"
                }
            }

        }),
`
```

_Originally posted by @mikeacre in https://github.com/nextauthjs/next-auth/discussions/6090#discussioncomment-7456763_

**Comment by balazsorban44** [comment]
Please use the [bug report template](https://github.com/nextauthjs/next-auth/issues/new?assignees=&labels=triage%2Cbug&projects=&template=1_bug_framework.yml)

**Comment by kwu-soundhound** [comment]
@mikeacre  Did you find solution for this issue?  Thanks.
