### ISSUE TITLE
Auth.js SvelteKit GoogleProvider: Not Found error

### ISSUE THREAD

**Issue by WhyAsh5114** [nextauthjs/next-auth#9146]
### Provider type

Google

### Environment

  System:
    OS: Windows 11 10.0.22621
    CPU: (12) x64 AMD Ryzen 5 3600 6-Core Processor
    Memory: 6.25 GB / 15.91 GB
  Binaries:
    Node: 18.18.2 - C:\Program Files\nodejs\node.EXE
    npm: 10.2.3 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (119.0.2151.58)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @auth/core: ^0.18.1 => 0.18.1
    @auth/sveltekit: ^0.3.12 => 0.3.12

### Reproduction URL

https://github.com/WhyAsh5114/authjs-sveltekit-googleProvider-bug

### Describe the issue

Sign in with Google provider causes a Not found error

Console error
```
GET http://localhost:4173/auth/callback/google?code=4%2F0AfJohXmkelJp2aynEXiSAV2O0bDO8jedJbZ8ebpnawK_M3D9jY7j2bDiFOVabnGkkI6hdA&scope=email+profile+openid+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email&authuser=2&prompt=consent 404 (Not Found)
```

I can see this in the terminal after using build and preview
```
UnknownAction: Cannot handle action: callback
    at AuthInternal (file:///D:/Programming/Web/my-app/node_modules/@auth/core/lib/index.js:167:11)
    at async Auth (file:///D:/Programming/Web/my-app/node_modules/@auth/core/index.js:100:30)
    at async respond (file:///D:/Programming/Web/my-app/.svelte-kit/output/server/index.js:2676:22)
    at async file:///D:/Programming/Web/my-app/node_modules/@sveltejs/kit/src/exports/vite/preview/index.js:171:5
```

After choosing Google account in signIn
![image](https://github.com/nextauthjs/next-auth/assets/71895020/02e4a5f8-d0fa-4243-be2e-c1e6455d972a)

### How to reproduce

npm create svelte@latest my-app
cd my-app
npm install
npm install @auth/core @auth/sveltekit

Create a google provider hooks.server.ts, add .env with id and secret, basic session loading in +layout.server.ts, and a page with signIn and signOut

### Expected behavior

Just normal signIn and redirect to callbackURL

**Comment by WhyAsh5114** [comment]
My bad, it was actually my service worker trying to cache the auth requests causing this bug.
Ignoring any requests including `'/auth/'` fixed it

**Comment by Neo-Ciber94** [comment]
I have the same issue, tried changed the path to keep the service worker there but there is also issues when changing the `basePath`: https://github.com/nextauthjs/next-auth/discussions/13326
