### ISSUE TITLE
Custom error page not working in SvelteKit

### ISSUE THREAD

**Issue by socketopp** [nextauthjs/next-auth#9416]
### Environment

```
$ npx envinfo --system --binaries --browsers --npmPackages "{next,react,next-auth,@auth/*}"

  System:
    OS: Windows 10 10.0.19045
    CPU: (6) x64 Intel(R) Core(TM) i5-8600K CPU @ 3.60GHz
    Memory: 3.65 GB / 15.95 GB
  Binaries:
    Node: 18.17.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.6.7 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (120.0.2210.77)
    Internet Explorer: 11.0.19041.3636
  npmPackages:
    @auth/sveltekit: ^0.4.0 => 0.4.0

```

### Reproduction URL

https://github.com/socketopp/cf-worker-sveltekit-bug/tree/authjs-error-page

### Describe the issue

I am using the `signIn` callback and tried returning false which should raise the [AuthorizedCallbackError](https://authjs.dev/reference/core/errors#authorizedcallbackerror) because I want to handle my errors gracefully. 

What I expected was the `auth/error/+page.svelte` to be rendered.
In the project provided in the replication URL, not even the default error route is found.
In my own project, the default was found however. 

We get the following log when the error is thrown
```js
[auth][error] AuthorizedCallbackError: AccessDenied .Read more at https://errors.authjs.dev#authorizedcallbackerror
    at handleAuthorized (file:/svelte/cf-worker-sveltekit-bug/node_modules/@auth/core/lib/actions/callback/index.js:257:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Module.callback (file:/svelte/cf-worker-sveltekit-bug/node_modules/@auth/core/lib/actions/callback/index.js:47:13)
    at async AuthInternal (file:/svelte/cf-worker-sveltekit-bug/node_modules/@auth/core/lib/index.js:27:24)
    at async Proxy.Auth (file:/svelte/cf-worker-sveltekit-bug/node_modules/@auth/core/index.js:104:29)
    at async routing (/coding/svelte/cf-worker-sveltekit-bug/src/hooks.server.ts:12:20)
    at async Module.respond (/coding/svelte/cf-worker-sveltekit-bug/node_modules/@sveltejs/kit/src/runtime/server/respond.js:282:20)
    at async file:/svelte/cf-worker-sveltekit-bug/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:510:22

```

### How to reproduce

1. Copy the repository. 
2. Add your github configs to the .env file.
3. Run with npm run dev.
4. Navigate to http://localhost:5173/ and click the login button.

### Expected behavior

We should render our `auth/error/+page.svelte` because we specified to in the `SvelteKitAuth` Handler. 

```js
export const authProviders = SvelteKitAuth(async (event) => {
	const authOptions = {
		providers: [
			GitHub({ clientId: GITHUB_ID, clientSecret: GITHUB_SECRET }),
		],
    pages: {
      error: '/auth/error',
       
		},
		trustHost: true,
    secret:'abc123',
		callbacks: {
			async signIn() {
				return false;
			}
		}
	};
	return authOptions;
}) satisfies Handle;

export const handle: Handle = sequence(authProviders, routing);
```

**Comment by socketopp** [comment]
Easy fix, don't use ` error: '/auth/error',`, but have a route that is not currently occupied. I thought you could override this. But by setting it to `/signin`, I was managed to have custom error page
