### ISSUE TITLE
Error: NEXT_REDIRECT at signOut in a Server Action.

### ISSUE THREAD

**Issue by AmphibianDev** [nextauthjs/next-auth#9959]
### Environment

  System:
    OS: Windows 11 10.0.22631
    CPU: (24) x64 AMD Ryzen 9 3900X 12-Core Processor
    Memory: 26.00 GB / 47.93 GB
  Binaries:
    Node: 20.11.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.2.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (121.0.2277.106)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @auth/prisma-adapter: ^1.2.1 => 1.2.1
    next: 14.1.0 => 14.1.0
    next-auth: ^5.0.0-beta.5 => 5.0.0-beta.5
    react: ^18 => 18.2.0

### Reproduction URL

https://github.com/AmphibianDev/todo-app

### Describe the issue

The user is logout successfully, but the redirect doesn't work and throws an error:
```javascript
 ⨯ unhandledRejection: Error: NEXT_REDIRECT
    at getRedirectError (C:\Users\Work\Desktop\todo-app\.next\server\chunks\node_modules_next_626524._.js:4635:19)
    at Module.redirect (C:\Users\Work\Desktop\todo-app\.next\server\chunks\node_modules_next_626524._.js:4646:11)
    at Module.signOut (C:\Users\Work\Desktop\todo-app\.next\server\chunks\node_modules_f8950b._.js:378:185) {
  digest: 'NEXT_REDIRECT;replace;http://localhost:3000/;303;',
  mutableCookies: p {
    _parsed: Map(3) {
      'authjs.csrf-token' => [Object],
      'authjs.callback-url' => [Object],
      'authjs.session-token' => [Object]
    },
    _headers: HeadersList {
      cookies: [Array],
      [Symbol(headers map)]: [Map],
      [Symbol(headers map sorted)]: null
    }
  }
}
```

### How to reproduce

```typescript
import Link from "next/link";
import { Button } from "./ui/button";
import { auth, signOut } from "@/auth";

export default async function Navbar() {
  const session = await auth();

  const serverAction = async () => {
    "use server";

    signOut({ redirectTo: "/", redirect: true });
  };

  return (
    <header className="shadow-sm">
      <nav className="m-auto flex max-w-5xl items-center justify-between px-3 py-5">
        <Link href="/" className="text-xl font-bold tracking-tight">
          Todo App
        </Link>
        <div className="flex gap-6">
          {session?.user ? (
            <form action={serverAction}>
              <Button variant="ghost">Log Out</Button>
            </form>
          ) : (
            <Button asChild variant="outline">
              <Link href="/auth/login">Log In</Link>
            </Button>
          )}
          <Button asChild>
            <Link href="/todo/new">Make a ToDo</Link>
          </Button>
        </div>
      </nav>
    </header>
  );
}
```

### Expected behavior

A working redirect to the root "/", without any errors.

**Comment by AmphibianDev** [comment]
I forgot to await `await signOut({ redirectTo: "/", redirect: true });` ...
