### ISSUE TITLE
[Auth0] OAuthAccountNotLinked: Another account already exists with the same e-mail address

### ISSUE THREAD

**Issue by pippinmole** [nextauthjs/next-auth#9992]
### Provider type

Auth0

### Environment

  System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 AMD Ryzen 7 5700X 8-Core Processor
    Memory: 9.76 GB / 31.93 GB
  Binaries:
    Node: 20.9.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 10.2.4 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.11.0 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Chromium (121.0.2277.112)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @auth/prisma-adapter: ^1.3.3 => 1.3.3 
    next: latest => 14.1.0 
    next-auth: beta => 5.0.0-beta.9 
    react: ^18.2.0 => 18.2.0

### Reproduction URL

https://github.com/pippinmole/auth0-authjs-bug

### Describe the issue

I haev a default setup with a prisma schema [defined here](https://github.com/pippinmole/auth0-authjs-bug/blob/main/prisma/schema.prisma), authjs config [defined here](https://github.com/pippinmole/auth0-authjs-bug/blob/main/auth.ts),

1. Log in using some custom credentials (this will insert a user into the database)
2. Log out
3. Log back in using the same credentials
4. Observe server logs

Please see attached video

https://github.com/nextauthjs/next-auth/assets/40035529/4ea89b4f-e502-4fee-b6ed-233625b8a369

As the error message says, I've taken a look at [this](https://errors.authjs.dev#oauthaccountnotlinked), and this is what it suggests:
> If you trust the OAuth provider to have verified the user's email address, you can enable automatic account linking by setting [allowDangerousEmailAccountLinking: true](https://authjs.dev/reference/core/providers#allowdangerousemailaccountlinking) in the provider configuration.

I shouldn't have to enable a dangerous flag just so a user can log in twice

### How to reproduce

1. Clone repo
2. Copy .env.example to .env
3. Enter relevant .env file variables for auth0
4. yarn run dev
5. Log in as the video above shows

### Expected behavior

It should let you log in the second time with no issues

**Comment by AdytZZa22** [comment]
Same issue here with Github & Google provider. If I delete the session manually from the browser & try to login back, I get the same error: **OAuthAccountNotLinked: Another account already exists with the same e-mail address**

**Comment by jbultez** [comment]
Hello,

Same issue here on `"next-auth": "^5.0.0-beta.9"` with the google provider.

```
[auth][error] OAuthAccountNotLinked: Another account already exists with the same e-mail address .Read more at https://errors.authjs.dev#oauthaccountnotlinked
```

**Comment by Dailton-Bastos** [comment]
Same issue here  with "^5.0.0-beta.9", but "^5.0.0-beta.4" was working.

**Comment by nnad3N** [comment]
I did some quick tests on vercel and versions beta.7 and beta.8 gave the same error as beta.9. The error occurs with the google provider, github one is working. Works fine with beta.5.

**Comment by ThangHuuVu** [comment]
we're tracking this issue, thanks for reporting!
@ndom91 it looks like #9932 didn't fix the issue entirely - seems like OIDC providers still have some issue.

**Comment by ndom91** [comment]
@pippinmole  Just thought of something too, that database of users in your demo app. When was the Github user created, that yuo're trying to login with but triggers the error? Do you happen to remember which version of `next-auth` you were using?

**Comment by pippinmole** [comment]
@ndom91 So in the first video it shows a bug where you can log in the first time with Auth0, then logging in the second time with the SAME PROVIDER causes that error, and the recent video I sent shows me logging in first time with Auth0, then trying to log in via GitHub (THROUGH AUTH0) and getting the error.

**Comment by pippinmole** [comment]
> Where it would previously throw the "oauth account already exists" error, I was now able to successfully login.

I think I've confused myself here. Here's a video (doing exactly the same thing as the first video), but it working successfully on the latest version (beta 11):


https://github.com/nextauthjs/next-auth/assets/40035529/96e24ee8-b6d6-45f5-b741-466f411ca4d0

So it looks like the original issue is fixed.

**Comment by ndom91** [comment]
@pippinmole okay I'm pretty sure I know what the issue is.. This will be an error for anyone if they created the users during `beta.6,7,8,9` that were available for the last 3-4 days.

The issue boils down to the fact that your `account.providerAccountId` field for your GitHub user wasn't correctly set during those versions. 

The easiest thing to do is to just drop the account + user rows from your DB, next time you login with them they will be recreated with the correct values. However, I know that might not be possible in a production environment. If that's not an option for you, you can manually modify the `account.providerAccountId` to match the (correct) one that's used to match now. 

For Github, yuor `providerAccountId` can easily be found by visiting https://github.com/pippinmole.png and grabbing the ID in the URL that it redirects you to. So in your case, it redirects to `https://avatars.githubusercontent.com/u/40035529?v=4` making your Github `providerAccountId=40035529`. 

So what you want to do is set the `account.providerAccountId = 40035529` for your Github user in your DB. With prisma you can run `pnpm exec prisma studio` to open a nice little DB editing UI.

Some general notes on your repository:

- You don't need to explicitly install / import anything from `@auth/core`. If you've got `next-auth`, you can import all of the provdiers from there as well, i.e. `import GitHub from "next-auth/providers/github"`.
- Also the providers now auto-detect environment variables if they're named in the expected fashion, as you're seemingly doing (i.e. `AUTH_GITHUB_ID`/`AUTH_GITHUB_SECRET`). So you can just do `provider: [Auth0, Github]`.

**Comment by ndom91** [comment]
Ah okay, good to hear. Did you create a new DB / users?

**Comment by pippinmole** [comment]
Yes, at the start I ran `npx prisma migrate reset` which clears the database.

**Comment by pippinmole** [comment]
So just to confirm the intended behaviour: if I do the following:
1. Clear the database via `npx prisma migrate reset`
2. Log in with GitHub (which creates a user entry with email `test@acme.com`
3. Log out
4. Log in with Auth0 using the same email (`test@acme.com`)

Should this:
- Link my Auth0 account as if I logged in via GitHub
- Give me the following error message: `OAuthAccountNotLinked: Another account already exists with the same e-mail address .Read more at https://errors.authjs.dev#oauthaccountnotlinked`

**Comment by ndom91** [comment]
Yeah so this logging in with one provider and then another provider with the same email is a whole other issue. You can read more about it [here](https://authjs.dev/reference/core/providers#allowdangerousemailaccountlinking) and [here](https://authjs.dev/concepts/faq#security) (see second item under "Security").

But long story short, you can enable this with the provider config option `allowDangerousEmailAccountLinking: true`

**Comment by pippinmole** [comment]
Perfect, thank you for your help with all of this

**Comment by jbultez** [comment]
Hello,

@ndom91 I tried your fix on version 5.0.11 and it solved the problem concerning authentication with Google. (thanks for it)

However I don't know if it has anything to do with this update but now the redirect after a connection with credentials doesn't work anymore.

It may be my fault for changing the configuration, but here are the logs


```
Error: NEXT_REDIRECT
    at getRedirectError (webpack-internal:///(action-browser)/./node_modules/next/dist/client/components/redirect.js:49:19)
    at redirect (webpack-internal:///(action-browser)/./node_modules/next/dist/client/components/redirect.js:60:11)
    at signIn (webpack-internal:///(action-browser)/./node_modules/next-auth/lib/actions.js:63:89)
    at async login (webpack-internal:///(action-browser)/./actions/users/login.ts:28:9)
    at async /my-app/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:39:406
    at async t0 (/my-app/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:38:5773)
    at async rh (/my-app/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:39:23636)
    at async doRender (/my-app/node_modules/next/dist/server/base-server.js:1391:30)
    at async cacheEntry.responseCache.get.routeKind (/my-app/node_modules/next/dist/server/base-server.js:1552:28)
    at async DevServer.renderToResponseWithComponentsImpl (/my-app/node_modules/next/dist/server/base-server.js:1460:28)
    at async DevServer.renderPageComponent (/my-app/node_modules/next/dist/server/base-server.js:1843:24)
    at async DevServer.renderToResponseImpl (/my-app/node_modules/next/dist/server/base-server.js:1881:32)
    at async DevServer.pipeImpl (/my-app/node_modules/next/dist/server/base-server.js:909:25)
    at async NextNodeServer.handleCatchallRenderRequest (/my-app/node_modules/next/dist/server/next-server.js:266:17)
    at async DevServer.handleRequestImpl (/my-app/node_modules/next/dist/server/base-server.js:805:17) {
  digest: 'NEXT_REDIRECT;replace;http://localhost:3000/settings;303;',
  mutableCookies: p {
    _parsed: Map(6) {
      'next-auth.csrf-token' => [Object],
      'next-auth.callback-url' => [Object],
      'next-auth.session-token' => [Object],
      'authjs.csrf-token' => [Object],
      'authjs.callback-url' => [Object],
      'authjs.session-token' => [Object]
    },
    _headers: HeadersList {
      cookies: [Array],
      [Symbol(headers map)]: [Map],
      [Symbol(headers map sorted)]: null
    }
  }
}
```

**Comment by jbultez** [comment]
Hello @ndom91 

I've managed to correct my problem, but I still don't understand how this error could occur.

I have a server action where I use the next-auth signIn. Here is the code

```ts
"use server";
import * as z from "zod";
import { userLoginSchema } from "@/schemas/user.schema";
import { signIn } from "@/auth";
import { DEFAULT_LOGIN_REDIRECT } from "@/routes";
import { AuthError } from "next-auth";

export const login = async (values: z.infer<typeof userLoginSchema>) => {
  const validateFields = userLoginSchema.safeParse(values);

  if (!validateFields.success) {
    return { error: "Invalid data provided" };
  }

  const { email, password } = validateFields.data;

  try {
    await signIn("credentials", {
      email,
      password,
      redirectTo: DEFAULT_LOGIN_REDIRECT,
    });
  } catch (error) {
    // I see in my server console the error message
    console.log(error);
    if (error instanceof AuthError) {
      switch (error.type) {
        case "CredentialsSignin":
          return { error: "Invalid email or password" };
        default:
          return { error: "Something went wrong" };
      }
    }
    // If I let the return error The NEXTREDIRECT error is there
    return { error: "Something went wrong" };
    // If I put `throw error` the NEXTREDIRECT error is gone and my user is logged in and redirected nicely
    // throw error;
  }
  return { success: "You are now logged in" };
};
```
If I use `throw error` until `return {error: "Something went wrong"}` all is fine.

**Comment by vehktaur** [comment]
# **Problem: NextAuth.js Creates New Accounts on Every Login (GitHub and Google)**

## **Root Cause: Missing `providerAccountId` in Profile Callback**

The issue arises from how **NextAuth.js** generates the `providerAccountId`. This value is used to match users with existing accounts. By default, it is derived from the `id` returned in the `profile` callback of the OAuth provider (e.g., GitHub, Google). However, since the `profile` callback wasn't returning an `id`, **NextAuth.js** generated a new `providerAccountId` with each sign-in, causing it to treat the sign-in as a new account.

## **Solution: Ensure `id` is Returned in Profile Callback**

I was already modifying the `profile` callback for customizing user creation in the database. However, I wasn't including the `id` property, assuming MongoDB would generate it automatically. But the `profile` callback needs to return an `id`, which **NextAuth.js** uses to correctly match the user to an existing account.

To fix this, I updated the `profile` callback for both **GitHub** and **Google** to return a consistent `id`. Now, **NextAuth.js** uses this `id` as the `providerAccountId`, ensuring the user is matched correctly with their existing account on subsequent sign-ins.

Here’s how I customized the `profile` callbacks for both providers:

### **GitHub Provider**:

```javascript
const githubProvider = GitHub({
  profile: (profile: GitHubProfile) => {
    const name = profile.name?.split(' ');
    return {
      id: profile.id.toString(),  // Ensure the 'id' is returned
      firstName: name?.[0] ?? 'unknown',
      lastName: name?.[1],
      email: profile.email,
      image: profile.avatar_url,
      username: profile.login,
    };
  },
});

export default githubProvider;
```

### **Google Provider**:

```javascript
const googleProvider = Google({
  profile: (profile: GoogleProfile) => {
      id: profile.sub,  // Ensure the 'id' (sub) is returned
      firstName: profile.given_name,
      lastName: profile.family_name,
      email: profile.email,
      image: profile.picture,
      username: `${profile.given_name}${profile.family_name}`.toLowerCase() ?? 'unknown',
  },
});

export default googleProvider;
```

## **Explanation**:

- **GitHub** returns the user’s `id` in the OAuth response, so I made sure to include it in the `profile` callback as `id: profile.id.toString()`.
- **Google** returns a `sub` (subject) field, which I used as the `id` in the `profile` callback (`id: profile.sub`).

## **Outcome:**

With these changes, the `providerAccountId` is consistently returned and properly stored, ensuring that NextAuth.js can now correctly match users with their accounts on subsequent logins. No more duplicate accounts are created, and everything works as expected.

## **Conclusion:**

Make sure the `profile` callback in your OAuth providers returns an `id`. This ensures that the `providerAccountId` used by NextAuth.js is consistent and unique, solving issues with duplicate accounts and incorrect sign-ins.
